#!/bin/sh 

# fsx options: 
# -W disables mapped writes (which pvfs2 does not support)
# -R disables mapped reads.  In FSX, mmap reads are MAP_SHARED, which pvfs2
#    does not support.
# good catch, sam!

gcc ${USERLIB_SCRIPTS}/fsx.c -o ${PVFS2_DEST}/fsx && export ${PRELOAD} && ${PVFS2_DEST}/fsx -N 1000 -W -R ${PVFS2_MOUNTPOINT}/fsx_testfile
