#!/bin/sh 

PATH=${PVFS2_DEST}/INSTALL-pvfs2-${CVS_TAG}/bin:${PATH}
echo $PATH
export PATH
export ${PRELOAD} && ${PVFS2_DEST}/INSTALL-pvfs2-${CVS_TAG}/test/test-mkdir --directory ${PVFS2_MOUNTPOINT} 
