#!/bin/sh

export ${PRELOAD} && cp ${PVFS2_DEST}/INSTALL-pvfs2-${CVS_TAG}/bin/pvfs2-cp ${PVFS2_MOUNTPOINT}
export ${PRELOAD} && cp ${PVFS2_MOUNTPOINT}/pvfs2-cp ${PVFS2_DEST}

export ${PRELOAD} && cmp ${PVFS2_DEST}/pvfs2-cp ${PVFS2_DEST}/INSTALL-pvfs2-${CVS_TAG}/bin/pvfs2-cp
