#!/bin/sh
pushd .
cd ${EXTRA_TESTS}/iozone3_239/src/current  || return 1
make linux  || return 1
# -y min record size
# -q max record size
# -n min file size
# -g max file size
./iozone -a -y 4096 -q $((1024*16)) -n 4096 -g $((1024*16*2)) \
        -f ${PVFS2_MOUNTPOINT}/test_iozone_file
popd
