#!/bin/sh

cd ${EXTRA_TESTS}/iozone3_239/src/current  || exit 1

#do we need to rebuild iozone
if [ ! -f ./iozone ] 
then
patch -p5 < ${USERLIB_SCRIPTS}/iozone.patch
	#if [ $? != 0 ]
	#then
   	#	echo "Attemp to patch iozone software failed."
   	#	exit 1
	#fi
	make linux  || exit 1
fi
# -y min record size
# -q max record size
# -n min file size
# -g max file size
export ${PRELOAD} && ./iozone -a -y 4096 -q $((1024*16)) -n 4096 -g $((1024*16*2)) \
        -f ${PVFS2_MOUNTPOINT}/test_iozone_file
