#!/usr/bin/python -u

#from OFSTest import *

from OFSTest import OFSTestMain
from OFSTest import OFSTestConfigMenu
from OFSTest import OFSTestConfigFile
import sys
import getopt
import os, errno


def mkdir_p(path):
    try:
        os.makedirs(path)
    except OSError as exc: # Python >2.5
        if exc.errno == errno.EEXIST and os.path.isdir(path):
            pass
        else: raise

# defaults
config_file = None
output_dir = "."
#print sys.argv
optlist, args = getopt.getopt(sys.argv[1:], 'hf:d:c:')
#print optlist
#print args

for o, a  in optlist:

    if o == "-d":
        output_dir = a
    if o == "-f":
        config_file = a
	if o == "-h":
		print "start_test -f <path to config file> -d <output directory> config1=value1 config2=value2...configN=valueN"
		exit()

# Convert arguments to a dictionary
#argd = dict([my_arg.split('=') for my_arg in args])

#print "Output dir is %s, config file is %s" % (output_dir,config_file)
print "==================================================================="
print "Welcome to the OrangeFS Setup and Testing System"


if config_file != None:
    try:
        #print "Using configuration from "+ config_file
        test_driver = OFSTestMain.OFSTestMain(OFSTestConfigFile.OFSTestConfigFile())
        #print "setting config"
        #ugly python hack
        test_driver.setConfig(kwargs={"filename":config_file})
        
        #test_driver.printConfig()
        #print "done"
    except ValueError:
        print "File %s could not be read or invalid format." % config_file
        #test_driver = OFSTestMain.OFSTestMain(OFSTestConfigMenu.OFSTestConfigMenu())
        #test_driver.setConfig()
        exit(-1)
else:
    test_driver = OFSTestMain.OFSTestMain(OFSTestConfig.OFSTestConfig())

#Add additional configuration options from command line
test_driver.config.addConfig(args)
test_driver.printConfig()

#exit()
mkdir_p(output_dir)
os.chdir(output_dir)

# if nodes exist, then check to see if OrangeFS is already installed
rc = test_driver.checkOFS()

# if orangefs is not installed, set it up
if rc != 0:
    rc = test_driver.setupOFS()
    
# Ok, now we have a good OrangeFS installation. Let's test it!    
if rc == 0:
    test_driver.runTest()
