#!/bin/bash

# first test open

MPICH2_INSTALL=/home/slang/INSTALL-mpich2
PVFS2_TOPDIR=/home/slang/pvfs2-pos-ext
PVFS2_MNT=$PVFS2_TOPDIR/mnt

levels=8

base="$PVFS2_MNT"
for i in `seq 1 $levels`; do 

	mkdir -p $base/$i 
	base="$base/$i" 
done

openg_deepfile=$base/openg-test
openg_shallowfile=$PVFS2_MNT/openg-test
open_deepfile=$base/open-test
open_shallowfile=$PVFS2_MNT/open-test

clients="1 10 20 30 40 50 60"

for c in $clients; do

	echo "Running openg-mpi with $c clients"
	echo "    openg file (create): ${openg_shallowfile}-$c-clients"
	${MPICH2_INSTALL}/bin/mpiexec -n $c ${PVFS2_TOPDIR}/test/posix/openg-mpi \
		-f ${openg_shallowfile}-$c-clients -c
	
	echo "    openg file (reopen): ${openg_shallowfile}-$c-clients"
	${MPICH2_INSTALL}/bin/mpiexec -n $c $PVFS2_TOPDIR/test/posix/openg-mpi \
		-f ${openg_shallowfile}-$c-clients

	echo "    openg file (create); ${openg_deepfile}-$c-clients"
	${MPICH2_INSTALL}/bin/mpiexec -n $c ${PVFS2_TOPDIR}/test/posix/openg-mpi \
		-f ${openg_deepfile}-$c-clients -c

	echo "    openg file (reopen): ${openg_deepfile}-$c-clients"
	${MPICH2_INSTALL}/bin/mpiexec -n $c ${PVFS2_TOPDIR}/test/posix/openg-mpi \
		-f ${openg_deepfile}-$c-clients

	echo "Running open with $c clients"
	echo "    open file (create): ${open_shallowfile}-$c-clients"
	${MPICH2_INSTALL}/bin/mpiexec -n $c ${PVFS2_TOPDIR}/test/posix/open \
		-f ${open_shallowfile}-$c-clients -c
	
	echo "    open file (reopen): ${open_shallowfile}-$c-clients"
	${MPICH2_INSTALL}/bin/mpiexec -n $c $PVFS2_TOPDIR/test/posix/open \
		-f ${open_shallowfile}-$c-clients

	echo "    open file (create); ${open_deepfile}-$c-clients"
	${MPICH2_INSTALL}/bin/mpiexec -n $c ${PVFS2_TOPDIR}/test/posix/open \
		-f ${open_deepfile}-$c-clients -c

	echo "    open file (reopen): ${open_deepfile}-$c-clients"
	${MPICH2_INSTALL}/bin/mpiexec -n $c ${PVFS2_TOPDIR}/test/posix/open \
		-f ${open_deepfile}-$c-clients
done
