#!/bin/sh

cd ${EXTRA_TESTS}/fsx
# fsx options: 
# -W disables mapped writes (which pvfs2 does not support)
# -R disables mapped reads.  In FSX, mmap reads are MAP_SHARED, which pvfs2
#    does not support.
# good catch, sam!

gcc ${VFS_SCRIPTS}/fsx.c -o fsx && ./fsx -N 1000 -W -R ${PVFS2_MOUNTPOINT}/fsx_testfile
