#!/bin/sh
[ -d ${EXTRA_TESTS}/fsx ] || exit 1

cd ${EXTRA_TESTS}/fsx
# fsx options: -W disables mapped writes (which pvfs2 does not support)
# good catch, sam!
gcc fsx.c -o fsx && ./fsx -N 1000 -W ${PVFS2_MOUNTPOINT}/fsx_testfile
