#!/bin/bash

LTPVER="20081130"
THISDATE=`date +%F-%R`
DOWNLOAD="http://www-unix.mcs.anl.gov/~carns/nightly-download/ltp-full-${LTPVER}.tgz"

cd ${EXTRA_TESTS}

# get rid of any old copies
sudo rm -rf ltp-full-${LTPVER} ltp-full-${LTPVER}.tgz 

# download
echo Downloading LTP...
wget -q ${DOWNLOAD} > /dev/null
if [ "${?}" != 0 ]
then
    echo "Error: failed to download ${DOWNLOAD}."
    exit 1;
fi

tar -xvzf ltp-full-${LTPVER}.tgz > /dev/null
if [ "${?}" != 0 ]
then
    echo "Error: failed to untar ${DOWNLOAD}."
    exit 1;
fi

# fix some pvfs specific problems
cd ltp-full-${LTPVER}
for patch in \
	${VFS_SCRIPTS}/ltp-20080630-zoo-path.patch \
        ${VFS_SCRIPTS}/ltp-20080630-accept4-wrapper.patch; do
		patch -p1 < $patch
done
if [ "${?}" != 0 ]
then
    echo "Error: failed to apply patches to LTP."
    exit 1;
fi

echo Compiling LTP...
export CFLAGS="-g"
make >& /dev/null 
if [ "${?}" != 0 ]
then
    echo "Error: failed to build LTP."
    exit 1;
fi

# NOTE: this does not install anything outside of the ltp directory.  It
# just configures the test programs so that they can be executed.  We
# deliberately avoid running make install at the top level because that
# _would_ install files in /opt/ltp unecessarily.
cd testcases
sudo make install > /dev/null
if [ "${?}" != 0 ]
then
    echo "Error: failed to make install LTP testcases."
    exit 1;
fi
cd ../

# copy pvfs friendly test cases; we should pass all of these
cp ${VFS_SCRIPTS}/ltp-pvfs-testcases runtest/
mkdir -p ${PVFS2_MOUNTPOINT}/ltp-tmp 
chmod 777 ${PVFS2_MOUNTPOINT}/ltp-tmp
umask 0

# run ltp
echo Running LTP...
sudo ./runltp -p -l `pwd`/../ltp-pvfs-testcases-${THISDATE}.log -d ${PVFS2_MOUNTPOINT}/ltp-tmp -f ltp-pvfs-testcases -z ${EXTRA_TESTS}/zoo.tmp >& `pwd`/../ltp-pvfs-testcases-$THISDATE.output
LTPRET=${?}
if [ "${LTPRET}" != 0 ]
then
    echo "Error: either failed to invoke LTP, or at least one test failed"
fi

cd ..

FAILCOUNT=`grep FAIL ltp-pvfs-testcases-$THISDATE.log | wc -l`

if [ "${FAILCOUNT}" != 0 -o "${LTPRET}" != 0 ]
then 
    echo "Error: failed the following LTP test cases:"
    grep FAIL ltp-pvfs-testcases-$THISDATE.log
    echo "log file:                    ${EXTRA_TESTS}/ltp-pvfs-testcases-$THISDATE.log"
    echo "record of stdout and stderr: ${EXTRA_TESTS}/ltp-pvfs-testcases-$THISDATE.output"
    exit 1
fi

echo "Completed LTP tests."

exit 0
