#!/bin/sh

#Path to our PVFS prefix
PVFS2_TOP_PREFIX=~/trunk

#Remove Old Stuff
rm -f libPVFS2JNI.so *.class *.h

#Path to JAVA
JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:bin/javac::")

#Add current directory to LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:.

#Compile Java Classes
javac *.java

#Generate JNI header file
javah PVFS2JNI 

#Store our build string so we can view it before it's run.
#NOTE: for this build to work correctly, the environment variable CFLAGS
# must have contained '-fPIC' during the 'configure' step of OrangeFS
# installation.
BUILD_STRING="gcc -fPIC -shared -D_FILE_OFFSET_BITS=64 \
-I${JAVA_HOME}include -I${JAVA_HOME}include/linux \
-I$PVFS2_TOP_PREFIX/include -L$PVFS2_TOP_PREFIX/lib \
-o libPVFS2JNI.so \
libPVFS2JNI.c \
-lofs -rdynamic -lpvfs2  -ldl  -lpthread  -lssl -lcrypto"

#Display the BUILD_STRING
echo "BUILD_STRING=$BUILD_STRING"

#Execute the BUILD_STRING
$BUILD_STRING
