#define _LARGEFILE64_SOURCE

/* Headers required by native routines. */
#include <features.h>
#include <pvfs2-types.h>
#include <stdlib.h>
#include <unistd.h>
#include <stdio.h>
#include <string.h>
#include <sys/uio.h>
#include <sys/types.h>
#include <sys/resource.h>
#include <stdint.h>
#include <sys/vfs.h>
#include <sys/statfs.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/mount.h>
#include <features.h>
#include <dirent.h>

#include <pvfs2.h>
#include <pvfs2-usrint.h>

/* Header for JNI */
#include "jni.h"
/* Our header generated by "javah" */
#include "org_orangefs_usrint_PVFS2JNI.h"

#define JNI_DBG 0

#if 0
void disp(struct stat *abc)
{
    printf("=======DISPLAY========\n");
    printf("The st_dev is: %d\n", (int) abc->st_dev);
    printf("The ino is: %ld\n", (long int)abc->st_ino);
    printf("The st_mode is: %d\n", (int) abc->st_mode);
    printf("The st_nlink is: %d\n", (int)abc->st_nlink);
    printf("The st_uid is: %ld\n", (long int) abc->st_uid);
    printf("The st_gid is: %ld\n", (long int) abc->st_gid);
    printf("The st_rdev is: %ld\n", (long int) abc->st_rdev);
    printf("The st_size is: %ld\n", (long int) abc->st_size);
    printf("The st_blksize is: %d\n", (int)abc->st_blksize);
    printf("The st_blocks is: %ld\n", (long int) abc->st_blocks);
    printf("The st_atime is: %ld\n", (long int) abc->st_atime);
    printf("The st_mtime is: %ld\n", (long int) abc->st_mtime);
    printf("The st_ctime is: %ld\n", (long int) abc->st_ctime);
    printf("=======DISPLAY========\n");
    fflush(stdout);
}

void disp64(struct stat64 *abc)
{
    printf("=======DISPLAY========\n");
    printf("The st_dev is: %d\n", (int) abc->st_dev);
    printf("The ino is: %ld\n", (long int) abc->st_ino);
    printf("The st_mode is: %d\n", (int) abc->st_mode);
    printf("The st_nlink is: %d\n", (int) abc->st_nlink);
    printf("The st_uid is: %ld\n", (long int) abc->st_uid);
    printf("The st_gid is: %ld\n", (long int) abc->st_gid);
    printf("The st_rdev is: %ld\n", (long int) abc->st_rdev);
    printf("The st_size is: %ld\n", (long int) abc->st_size);
    printf("The st_blksize is: %d\n", (int) abc->st_blksize);
    printf("The st_blocks is: %ld\n", (long int) abc->st_blocks);
    printf("The st_atime is: %ld\n", (long int) abc->st_atime);
    printf("The st_mtime is: %ld\n", (long int) abc->st_mtime);
    printf("The st_ctime is: %ld\n", (long int) abc->st_ctime);
    printf("=======DISPLAY========\n");
    fflush(stdout);
}
#endif

/* pvfs_open */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsOpen(
    JNIEnv *env,
    jobject obj,
    jstring path,
    int flags,
    int mode
)
{
    if(JNI_DBG) printf("pvfsOpen\n");
    int rc = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    if((flags & O_CREAT) == O_CREAT)
    {
        if(JNI_DBG) printf("\tO_CREAT detected!\n");
        rc = pvfs_open(cpath, flags, mode);
    }
    else
    {
        if(JNI_DBG) printf("\tNo O_CREAT detected\n");
        rc = pvfs_open(cpath, flags);
    }
    if(rc < 0)
    {
        perror("pvfs_open error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_open64 06/08/2012 */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsOpen64 (JNIEnv *env, jobject obj, jstring path, int flags)
{
    if(JNI_DBG) printf("pvfsOpen64\n");
    int rc = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    rc = pvfs_open64(cpath, flags);
    if(rc < 0)
    {
        perror("pvfs_open64 error");
        rc -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_openat */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsOpenat (JNIEnv *env, jobject obj, int dirfd, jstring path, int flags)
{
    if(JNI_DBG) printf("pvfsOpenat\n");
    int rc = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    rc = pvfs_openat(dirfd, cpath, flags);
    if(rc < 0)
    {
        perror("pvfs_openat error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_openat64 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsOpenat64 (JNIEnv *env, jobject obj, int dirfd, jstring path, int flags)
{
    if(JNI_DBG) printf("pvfsOpenat64\n");
    int rc = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    rc = pvfs_openat(dirfd, cpath, flags);
    if(rc < 0)
    {
        perror("pvfs_openat64 error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_creat */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsCreat(JNIEnv *env, jobject obj, jstring path, int mode)
{
    if(JNI_DBG) printf("pvfsCreat\n");
    int rc = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    rc = pvfs_creat(cpath, mode);
    if(rc < 0)
    {
        perror("pvfs_creat error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_creat64 */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsCreat64(JNIEnv *env, jobject obj, jstring path, int mode)
{
    if(JNI_DBG) printf("pvfsCreat64\n");
    int rc = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    rc = pvfs_creat64(cpath, mode);
    if(rc < 0)
    {
        perror("pvfs_creat error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_unlink */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsUnlink(JNIEnv *env, jobject obj, jstring path)
{
    if(JNI_DBG) printf("pvfsUnlink\n");
    int rc = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    rc = pvfs_unlink(cpath);
    if(rc < 0)
    {
        perror("pvfs_unlink error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_unlinkat */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsUnlinkat (JNIEnv *env, jobject obj, int dirfd, jstring path, int flags)
{
    if(JNI_DBG) printf("pvfsUnlinkat\n");
    int rc = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    rc = pvfs_unlinkat(dirfd, cpath, flags);
    if(rc < 0)
    {
        perror("pvfs_unlinkat error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_rename */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsRename(JNIEnv *env,
    jobject obj,
    jstring oldpath,
    jstring newpath
)
{
    if(JNI_DBG) printf("pvfsRename\n");
    int rc = 0;
    char coldpath[PVFS_PATH_MAX];
    int coldpath_len = (*env)->GetStringLength(env, oldpath);
    (*env)->GetStringUTFRegion(env, oldpath, 0, coldpath_len, coldpath);
    char cnewpath[PVFS_PATH_MAX];
    int cnewpath_len = (*env)->GetStringLength(env, newpath);
    (*env)->GetStringUTFRegion(env, newpath, 0, cnewpath_len, cnewpath);
    rc = pvfs_rename(coldpath, cnewpath);
    if(rc < 0)
    {
        perror("pvfs_rename error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_RenameAt */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsRenameAt(JNIEnv *env,
    jobject obj,
    int olddirfd,
    jstring oldpath,
    int newdirfd,
    jstring newpath
)
{
    if(JNI_DBG) printf("pvfsRenameAt\n");
    int rc = 0;
    char coldpath[PVFS_PATH_MAX];
    int coldpath_len = (*env)->GetStringLength(env, oldpath);
    (*env)->GetStringUTFRegion(env, oldpath, 0, coldpath_len, coldpath);
    char cnewpath[PVFS_PATH_MAX];
    int cnewpath_len = (*env)->GetStringLength(env, newpath);
    (*env)->GetStringUTFRegion(env, newpath, 0, cnewpath_len, cnewpath);
    rc = pvfs_renameat(olddirfd, coldpath, newdirfd, cnewpath);
    if(rc < 0)
    {
        perror("pvfs_renameat error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_close */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsClose(JNIEnv *env, jobject obj, int fd)
{
    if(JNI_DBG) printf("pvfsClose\n");
    int rc = 0;
    rc = pvfs_close(fd);
    if(rc < 0)
    {
        perror("pvfs_close error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_flush */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFlush(JNIEnv *env, jobject obj, int fd)
{
    if(JNI_DBG) printf("pvfsFlush\n");
    int rc = 0;
    rc = pvfs_flush(fd);
    if(rc < 0)
    {
        perror("pvfs_close error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_prdwr64  (INCOMPLETE) */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsPrdwr64(JNIEnv *env, jobject obj, int fd, jlong buf, jlong count, jlong offset, int which)
{
    printf("pvfsPrdwr64\n");
    fflush(stdout);
    size_t countc = (size_t) count;
    off64_t offsetc = (off64_t) offset;
    void* bufc = (void*) buf;
    int rc = 0;
    rc = pvfs_prdwr64(fd, bufc, countc, offsetc, which);
    if(rc < 0)
    {
        perror("pvfs_prdwr64 error");
        fflush(stdout);
        return -1;
    }
    return rc;
}

/* pvfs_lseek */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsLseek(JNIEnv *env, jobject obj, int fd, jlong offset, int whence)
{
    if(JNI_DBG) printf("pvfsLseek\n");
    off_t offsetc = (off_t) offset;
    off_t rc = pvfs_lseek(fd, offsetc, whence);
    jlong op = (jlong)rc;
    if(op < 0)
    {
        perror("pvfs_lseek error");
        op = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return op;
}

/* pvfs_lseek64 */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsLseek64(JNIEnv *env, jobject obj, int fd, jlong offset, int whence)
{
    if(JNI_DBG) printf("pvfsLseek64\n");
    off_t offsetc = (off_t) offset;
    off_t rc = pvfs_lseek(fd, offsetc, whence);
    jlong op = (jlong)rc;
    if(op < 0)
    {
        perror("pvfs_lseek64 error");
        op = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return op;
}

/* pvfs_truncate */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsTruncate(JNIEnv *env, jobject obj, jstring path, jlong length)
{
    if(JNI_DBG) printf("pvfsTruncate\n");
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    off_t clength = (off_t) length;
    int rc = pvfs_truncate(cpath, clength);
    if(rc < 0)
    {
        perror("pvfs_truncate error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_truncate64 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsTruncate64(JNIEnv *env, jobject obj, jstring path, jlong length)
{
    if(JNI_DBG) printf("pvfsTruncate64\n");
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    off64_t clength = (off64_t) length;
    int rc = 0;
    rc = pvfs_truncate64(cpath, clength);
    if(rc < 0)
    {
        perror("pvfs_truncate64 error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_fallocate */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFallocate(JNIEnv *env, jobject obj, int fd, jlong offset, jlong length)
{
    if(JNI_DBG) printf("pvfsFallocate\n");
    off_t coffset = (off_t) offset;
    off_t clength = (off_t) length;
    int rc = 0;
    rc = pvfs_fallocate(fd, coffset, clength);
    if(rc < 0)
    {
        perror("pvfs_fallocate error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_ftruncate */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFtruncate(JNIEnv *env, jobject obj, int fd, jlong length)
{
    if(JNI_DBG) printf("pvfsFtruncate\n");
    off_t clength = (off_t) length;
    int rc = 0;
    rc = pvfs_ftruncate(fd, clength);
    if(rc < 0)
    {
        perror("pvfs_ftruncate error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_ftruncate64 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFtruncate64(JNIEnv *env, jobject obj, int fd, jlong length)
{
    if(JNI_DBG) printf("pvfsFtruncate64\n");
    off64_t clength = (off64_t) length;
    int rc = 0;
    rc = pvfs_ftruncate(fd, clength);
    if(rc < 0)
    {
        perror("pvfs_ftruncate64 error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_dup */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsDup(JNIEnv *env, jobject obj, int oldfd)
{
    if(JNI_DBG) printf("pvfsDup\n");
    int rc = 0;
    rc = pvfs_dup(oldfd);
    if(rc < 0)
    {
        perror("pvfs_dup error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_dup2 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsDup2(JNIEnv *env, jobject obj, int oldfd, int newfd)
{
    if(JNI_DBG) printf("pvfsDup2\n");
    int rc = 0;
    rc = pvfs_dup_descriptor(oldfd, newfd);
    if(rc < 0)
    {
        perror("pvfs_dup2 error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_chown */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsChown(JNIEnv *env, jobject obj, jstring path, jlong owner, jlong group)
{
    if(JNI_DBG) printf("pvfsChown\n");
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    uid_t cowner = (uid_t) owner;
    gid_t cgroup = (gid_t) group;
    int rc = pvfs_chown(cpath, cowner, cgroup);
    if(rc < 0)
    {
        perror("pvfs_chown error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_fchown */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFchown(JNIEnv *env, jobject obj, int fd, jlong owner, jlong group)
{
    if(JNI_DBG) printf("pvfsFchown\n");
    uid_t cowner = (uid_t) owner;
    gid_t cgroup = (gid_t) group;
    int rc = pvfs_fchown(fd, cowner, cgroup);
    if(rc < 0)
    {
        perror("pvfs_fchown error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_fchownat */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFchownat(JNIEnv *env, jobject obj, int fd, jstring path, jlong owner, jlong group, int flag)
{
    if(JNI_DBG) printf("pvfsFchownat\n");
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    uid_t cowner = (uid_t) owner;
    gid_t cgroup = (gid_t) group;
    int rc = pvfs_fchownat(fd, cpath, cowner, cgroup, flag);
    if(rc < 0)
    {
        perror("pvfs_fchownat error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_chmod */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsChmod(JNIEnv *env, jobject obj, jstring path, int mode)
{
    if(JNI_DBG) printf("pvfsChmod\n");
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    mode_t cmode = (mode_t) mode;
    int rc = pvfs_chmod(cpath, cmode);
    if(rc < 0)
    {
        perror("pvfs_chmod error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_fchmod */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFchmod(JNIEnv *env, jobject obj, int fd, int mode)
{
    if(JNI_DBG) printf("pvfsFchmod\n");
    mode_t cmode = (mode_t) mode;
    int rc = pvfs_fchmod(fd, cmode);
    if(rc < 0)
    {
        perror("pvfs_fchmod error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_fchmodat */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFchmodat (JNIEnv *env, jobject obj, int fd, jstring path, int mode, int flag)
{
    if(JNI_DBG) printf("pvfsFchmodat\n");
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    mode_t cmode = (mode_t) mode;
    int rc = pvfs_fchmodat(fd, cpath, cmode, flag);
    if(rc < 0)
    {
        perror("pvfs_fchmodat error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_mkdir */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsMkdir (JNIEnv *env, jobject obj, jstring path, jint mode)
{
    if(JNI_DBG) printf("pvfsMkdir\n");
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    int rc = 0;
    mode_t cmode = (mode_t) mode;
    rc = pvfs_mkdir(cpath, cmode);
    if(rc < 0)
    {
        perror("pvfs_mkdir error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_mkdirat */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsMkdirat (JNIEnv *env, jobject obj, int dirfd, jstring path, jint mode)
{
    if(JNI_DBG) printf("pvfsMkdirat\n");
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    int rc = 0;
    mode_t cmode = (mode_t) mode;
    rc = pvfs_mkdirat(dirfd, cpath, cmode);
    if(rc < 0)
    {
        perror("pvfs_mkdirat error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_rmdir */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsRmdir (JNIEnv *env, jobject obj, jstring path)
{
    if(JNI_DBG) printf("pvfsRmdir\n");
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    int rc = 0;
    rc = pvfs_rmdir(cpath);
    if(rc < 0)
    {
        perror("pvfs_rmdir error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_readlink */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsReadlink (JNIEnv *env, jobject obj, jstring path, jstring buf, jlong bufsiz)
{
    if(JNI_DBG) printf("pvfsReadlink\n");
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    long cbufsiz = (long) bufsiz;
    char cbuf[cbufsiz];
    int cbuf_len = (*env)->GetStringLength(env, buf);
    (*env)->GetStringUTFRegion(env, path, 0, cbuf_len, cbuf);
    size_t bufsize = (size_t) bufsiz;
    ssize_t rc = pvfs_readlink(cpath, cbuf, bufsize);
    jlong op = (jlong) rc;
    if(op < 0)
    {
        perror("pvfs_readlink error");
        op = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return op;
}

/* pvfs_readlinkat */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsReadlinkat (JNIEnv *env, jobject obj, int fd, jstring path, jstring buf, jlong bufsiz)
{
    if(JNI_DBG) printf("pvfsReadlinkat\n");
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    long cbufsiz = (long) bufsiz;
    char cbuf[cbufsiz];
    int cbuf_len = (*env)->GetStringLength(env, buf);
    (*env)->GetStringUTFRegion(env, path, 0, cbuf_len, cbuf);
    size_t bufsize = (size_t) bufsiz;
    ssize_t rc = pvfs_readlinkat(fd, cpath, cbuf, bufsize);
    jlong op = (jlong) rc;
    if(op < 0)
    {
        perror("pvfs_readlinkat error");
        op = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return op;
}

/* pvfs_symlink */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsSymlink(JNIEnv *env, jobject obj, jstring oldpath, jstring newpath)
{
    if(JNI_DBG) printf("pvfsSymlink\n");
    int rc = 0;
    char coldpath[PVFS_PATH_MAX];
    int coldpath_len = (*env)->GetStringLength(env, oldpath);
    (*env)->GetStringUTFRegion(env, oldpath, 0, coldpath_len, coldpath);
    char cnewpath[PVFS_PATH_MAX];
    int cnewpath_len = (*env)->GetStringLength(env, newpath);
    (*env)->GetStringUTFRegion(env, newpath, 0, cnewpath_len, cnewpath);
    rc = pvfs_symlink(coldpath, cnewpath);
    if(rc < 0)
    {
        perror("pvfs_symlink error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_symlinkat */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsSymlinkat(JNIEnv *env, jobject obj, jstring oldpath, int newdirfd, jstring newpath)
{
    if(JNI_DBG) printf("pvfsSymlinkat\n");
    int rc = 0;
    char coldpath[PVFS_PATH_MAX];
    int coldpath_len = (*env)->GetStringLength(env, oldpath);
    (*env)->GetStringUTFRegion(env, oldpath, 0, coldpath_len, coldpath);
    char cnewpath[PVFS_PATH_MAX];
    int cnewpath_len = (*env)->GetStringLength(env, newpath);
    (*env)->GetStringUTFRegion(env, newpath, 0, cnewpath_len, cnewpath);
    rc = pvfs_symlinkat(coldpath, newdirfd, cnewpath);
    if(rc < 0)
    {
        perror("pvfs_symlinkat error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_link */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsLink(JNIEnv *env, jobject obj, jstring oldpath, jstring newpath)
{
    if(JNI_DBG) printf("pvfsLink\n");
    int rc = 0;
    char coldpath[PVFS_PATH_MAX];
    int coldpath_len = (*env)->GetStringLength(env, oldpath);
    (*env)->GetStringUTFRegion(env, oldpath, 0, coldpath_len, coldpath);
    char cnewpath[PVFS_PATH_MAX];
    int cnewpath_len = (*env)->GetStringLength(env, newpath);
    (*env)->GetStringUTFRegion(env, newpath, 0, cnewpath_len, cnewpath);
    rc = pvfs_link(coldpath, cnewpath);
    if(rc < 0)
    {
        perror("pvfs_link error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_linkat */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsLinkat(JNIEnv *env, jobject obj, int olddirfd, jstring oldpath, int newdirfd, jstring newpath, int flags)
{
    if(JNI_DBG) printf("pvfsLinkat\n");
    int rc = 0;
    char coldpath[PVFS_PATH_MAX];
    int coldpath_len = (*env)->GetStringLength(env, oldpath);
    (*env)->GetStringUTFRegion(env, oldpath, 0, coldpath_len, coldpath);
    char cnewpath[PVFS_PATH_MAX];
    int cnewpath_len = (*env)->GetStringLength(env, newpath);
    (*env)->GetStringUTFRegion(env, newpath, 0, cnewpath_len, cnewpath);
    rc = pvfs_linkat(olddirfd, coldpath, newdirfd, cnewpath, flags);
    if(rc < 0)
    {
        perror("pvfs_linkat error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_access */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsAccess (JNIEnv *env, jobject obj, jstring path, int mode)
{
    if(JNI_DBG) printf("pvfsAccess\n");
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    int rc = pvfs_access(cpath, mode);
    if(rc < 0)
    {
        perror("pvfs_access error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_faccessat */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFaccessat (JNIEnv *env, jobject obj, int fd, jstring path, int mode, int flags)
{
    if(JNI_DBG) printf("pvfsAccess\n");
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    int rc = pvfs_faccessat(fd, cpath, mode, flags);
    if(rc < 0)
    {
        perror("pvfs_faccessat error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_flock */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFlock (JNIEnv *env, jobject obj, int fd, int op)
{
    if(JNI_DBG) printf("pvfsFlock\n");
    int rc = pvfs_flock(fd, op);
    if(rc < 0)
    {
        perror("pvfs_flock error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_fcntl */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFcntl  (JNIEnv *env, jobject obj, int fd, int cmd)
{
    if(JNI_DBG) printf("pvfsFcntl\n");
    int rc = pvfs_fcntl(fd, cmd);
    if(rc < 0)
    {
        perror("pvfs_fcntl error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_fsync */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFsync  (JNIEnv *env, jobject obj, int fd)
{
    if(JNI_DBG) printf("pvfsFsync\n");
    int rc = pvfs_fsync(fd);
    if(rc < 0)
    {
        perror("pvfs_fsync error");
        fflush(stdout);
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_fdatasync */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFdatasync  (JNIEnv *env, jobject obj, int fd)
{
    if(JNI_DBG) printf("pvfsFdatasync\n");
    int rc = pvfs_fdatasync(fd);
    if(rc < 0)
    {
        perror("pvfs_fdatasync error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_fadvise */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFadvise  (JNIEnv *env, jobject obj, int fd, jlong offset, jlong len, int advice)
{
    if(JNI_DBG) printf("pvfsFadvise\n");
    off_t coffset = (off_t) offset;
    off_t clen = (off_t) clen;
    int rc = pvfs_fadvise(fd, coffset, clen, advice);
    if(rc < 0)
    {
        perror("pvfs_fadvise error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_fadvise64 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFadvise64  (JNIEnv *env, jobject obj, int fd, jlong offset, jlong len, int advice)
{
    if(JNI_DBG) printf("pvfsFadvise64\n");
    off_t coffset = (off64_t) offset;
    off_t clen = (off64_t) clen;
    int rc = pvfs_fadvise64(fd, coffset, clen, advice);
    if(rc < 0)
    {
        perror("pvfs_fadvise64 error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_mknod */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsMknod  (JNIEnv *env, jobject obj, jstring path, int mode, int dev)
{
    if(JNI_DBG) printf("pvfsMknod\n");
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    mode_t cmode = (mode_t) mode;
    dev_t cdev = (dev_t) dev;
    int rc = pvfs_mknod(cpath, cmode, cdev);
    if(rc < 0)
    {
        perror("pvfs_mknod error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_mknodat */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsMknodat (JNIEnv *env, jobject obj, int dirfd, jstring path, int mode, int dev)
{
    if(JNI_DBG) printf("pvfsMknodat\n");
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    mode_t cmode = (mode_t) mode;
    dev_t cdev = (dev_t) dev;
    int rc = pvfs_mknodat(dirfd, cpath, cmode, cdev);
    if(rc < 0)
    {
        perror("pvfs_mknodat error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_chdir */ 
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsChdir  (JNIEnv *env, jobject obj, jstring path)
{
    if(JNI_DBG) printf("pvfsChdir\n");
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    int rc = pvfs_chdir(cpath);
    if(rc < 0)
    {
        perror("pvfs_chdir error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_fchdir */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFchdir  (JNIEnv *env, jobject obj, int fd)
{
    if(JNI_DBG) printf("pvfsFchdir\n");
    int rc = pvfs_fchdir(fd);
    if(rc < 0)
    {
        perror("pvfs_fchdir error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_umask */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsUmask  (JNIEnv *env, jobject obj, int mask)
{
    if(JNI_DBG) printf("pvfsUmask\n");
    mode_t cmask = (mode_t) mask;
    mode_t rc = pvfs_umask(mask);
    if(rc < 0)
    {
        perror("pvfs_umask error");
        rc = -1;
    }
    if(JNI_DBG) fflush(stdout);
    return (int) rc;
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsRead(JNIEnv *env, jobject obj, int fd, jbyteArray buf, jlong count)
{
    ssize_t rc = 0;
    jboolean is_copy;
    jbyte * buffer = (*env)->GetByteArrayElements(env, buf, &is_copy);
    if(JNI_DBG)
    {
        printf("\tfd = %d\n", fd);
        printf("\tcount = %lu\n", (uint64_t) count);
        is_copy == JNI_TRUE ? printf("\tbuf is_copy\n") : printf("\tbuf !is_copy\n");
    }
    if(!buffer)
    {
        perror("GetByteArrayElements");
        errno = EFAULT;
        rc = -1;
        goto done;
    }
    rc = pvfs_read(fd, (void *) buffer, (size_t) count);
    if(rc < 0)
    {
        perror("jni pvfs_read");
        rc = -1;
        goto done;
    }
    if(rc > 0)
    {
        if(JNI_DBG) printf("\tread %lld bytes\n", (long long int) rc);
    }
done:
    /* copy back and free the buffer using 0 */
    (*env)->ReleaseByteArrayElements(env, buf, buffer, 0);
    if(JNI_DBG) fflush(stdout);
    fflush(stderr);
    return (jlong) rc;
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsPread(JNIEnv *env, jobject obj, int fd, jbyteArray buf, jlong count, jlong offset)
{
    ssize_t rc = 0;
    jboolean is_copy;
    jbyte * buffer = (*env)->GetByteArrayElements(env, buf, &is_copy);
    if(JNI_DBG)
    {
        printf("pvfsPread\n");
        printf("\tfd = %d\n", fd);
        printf("\tcount = %lu\n", (uint64_t) count);
        printf("\toffset = %lu\n", (uint64_t) offset);
        is_copy == JNI_TRUE ? printf("\tbuf is_copy\n") : printf("\tbuf !is_copy\n");
    }
    if(!buffer)
    {
        perror("GetByteArrayElements");
        errno = EFAULT;
        rc = -1;
        goto done;
    }
    rc = pvfs_pread(fd, (void *) buffer, (size_t) count, (off_t) offset);
    if(rc < 0)
    {
        perror("jni pvfs_pread");
    }
    else
    {
        if(JNI_DBG) printf("\tread %lld bytes\n", (long long int) rc);
    }
done:
    /* copy back and free the buffer using 0 */
    (*env)->ReleaseByteArrayElements(env, buf, buffer, 0);
    if(JNI_DBG) fflush(stdout);
    fflush(stderr);
    return (jlong) rc;
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsPread64(JNIEnv *env, jobject obj, int fd, jbyteArray buf, jlong count, jlong offset)
{
    ssize_t rc = 0;
    jboolean is_copy;
    jbyte * buffer = (*env)->GetByteArrayElements(env, buf, &is_copy);
    if(JNI_DBG)
    {
        printf("pvfsPread64\n");
        printf("\tfd = %d\n", fd);
        printf("\tcount = %lu\n", (uint64_t) count);
        printf("\toffset = %lu\n", (uint64_t) offset);
        is_copy == JNI_TRUE ? printf("\tbuf is_copy\n") : printf("\tbuf !is_copy\n");
    }
    if(!buffer)
    {
        perror("GetByteArrayElements");
        errno = EFAULT;
        rc = -1;
        goto done;
    }
    rc = pvfs_pread64(fd, (void *) buffer, (size_t) count, (off64_t) offset);
    if(rc < 0)
    {
        perror("jni pvfs_pread64");
    }
    else
    {
        printf("\tread %lld bytes\n", (long long int) rc);
    }
done:
    /* copy back and free the buffer using 0 */
    (*env)->ReleaseByteArrayElements(env, buf, buffer, 0);
    if(JNI_DBG) fflush(stdout);
    fflush(stderr);
    return (jlong) rc;
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsWrite(JNIEnv *env, jobject obj, int fd, jbyteArray buf, jlong count)
{
    ssize_t rc = 0;
    jboolean is_copy;
    jbyte * buffer = (*env)->GetByteArrayElements(env, buf, &is_copy);
    if(JNI_DBG)
    {
        printf("pvfsWrite\n");
        printf("\tfd = %d\n", fd);
        printf("\tcount = %lu\n", (uint64_t) count);
        is_copy == JNI_TRUE ? printf("\tbuf is_copy\n") : 
            printf("\tbuf !is_copy\n");
    }
    if(!buffer)
    {
        perror("GetByteArrayElements");
        errno = EFAULT;
        rc = -1;
        goto done;
    }
    rc = pvfs_write(fd, (void *) buffer, (size_t) count);
    if(rc < 0)
    {
        perror("jni pvfs_write");
    }
    if(rc > 0)
    {
        printf("\twrote %lld bytes\n", (long long int) rc);
    }
done:
    /* free the buffer without copying back the possible changes in buffer 
     * using JNI_ABORT 
     */
    (*env)->ReleaseByteArrayElements(env, buf, buffer, JNI_ABORT);
    if(JNI_DBG) fflush(stdout);
    fflush(stderr);
    return (jlong) rc;
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsPwrite(JNIEnv *env, jobject obj, int fd, jbyteArray buf, jlong count, jlong offset)
{
    ssize_t rc = 0;
    jboolean is_copy;
    jbyte * buffer = (*env)->GetByteArrayElements(env, buf, &is_copy);
    if(JNI_DBG)
    {
        printf("pvfsPwrite\n");
        printf("\tfd = %d\n", fd);
        printf("\tcount = %lu\n", (uint64_t) count);
        printf("\toffset = %lu\n", (uint64_t) offset);
        is_copy == JNI_TRUE ? printf("\tbuf is_copy\n") : 
            printf("\tbuf !is_copy\n");
    }
    if(!buffer)
    {
        perror("GetByteArrayElements");
        errno = EFAULT;
        rc = -1;
    }
    rc = pvfs_pwrite(fd, (void *) buffer, (size_t) count, (off_t) offset);
    if(rc < 0)
    {
        perror("jni pvfs_pwrite");
    }
    else
    {
        if(JNI_DBG) printf("\twrote %lld bytes\n", (long long int) rc);
    }
done:
    /** free the buffer without copying back the possible changes in buffer
      * using JNI_ABORT 
      */
    (*env)->ReleaseByteArrayElements(env, buf, buffer, JNI_ABORT);
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return (jlong) rc;
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsPwrite64(JNIEnv *env, jobject obj, int fd, jbyteArray buf, jlong count, jlong offset)
{
    ssize_t rc = 0;
    jboolean is_copy;
    jbyte * buffer = (*env)->GetByteArrayElements(env, buf, &is_copy);
    if(JNI_DBG)
    {
        printf("pvfsPwrite64\n");
        printf("\tfd = %d\n", fd);
        printf("\tcount = %lu\n", (uint64_t) count);
        printf("\toffset = %lu\n", (uint64_t) offset);
        is_copy == JNI_TRUE ? printf("\tbuf is_copy\n") : 
            printf("\tbuf !is_copy\n");
    }
    if(!buffer)
    {
        perror("GetByteArrayElements");
        errno = EFAULT;
        rc = -1;
        goto done;
    }
    rc = pvfs_pwrite64(fd, (void *) buffer, (size_t) count, (off_t) offset);
    if(rc < 0)
    {
        perror("jni pvfs_pwrite64");
    }
    else
    {
        if(JNI_DBG) printf("\twrote %lld bytes\n", (long long int) rc);
    }
done:
    /** Free the buffer without copying back the possible changes in buffer 
     * using JNI_ABORT 
     */
    (*env)->ReleaseByteArrayElements(env, buf, buffer, JNI_ABORT);
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return (jlong) rc;
}

/*
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsReadv(JNIEnv *env, jobject obj, int fd, jObject vector, jlong count)
{

}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsWritev(JNIEnv *env, jobject obj, int fd, jObject vector, jlong count)
{

}
*/

/* pvfs_stat */
JNIEXPORT jobject JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsStat  (JNIEnv *env, jobject obj, jstring path)
{
    printf("pvfsStat\n");
    #if 0
    struct stat *ptr = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    fprintf(stdout, "provided path = %s\n", cpath);
    ptr = (struct stat *) malloc(sizeof(struct stat));
    if(!ptr)
    {
        fprintf(stderr, "couldn't allocate memory for struct stat!\n");
        goto ret;
    }
    int rc = pvfs_stat(cpath, ptr);
    if(rc < 0)
    {
        perror("pvfs_stat error");
        goto free;
    }
    /* Convert C Struct to Java Class and Return */
    jfieldID fid1;
    jfieldID fid2;
    jfieldID fid3;
    jfieldID fid4;
    jfieldID fid5;
    jfieldID fid6;
    jfieldID fid7;
    jfieldID fid8;
    jfieldID fid9;
    jfieldID fid10;
    jfieldID fid11;
    jfieldID fid12;
    jfieldID fid13;
    jclass cls = (*env)->FindClass(env, "PVFS2JNI$Stat");
    if(!cls)
    {
        goto free;
    }
    jmethodID cid = (*env)->GetMethodID(env, cls, 
        "<init>", "(Lorg/orangefs/usrint/PVFS2JNI;)V");
    if(!cid)
    {
        goto free;
    }
    jobject stat_object = (*env)->NewObject(env, cls, cid);

free:
    free(ptr);
ret:
    fflush(stdout); fflush(stderr);
    return stat_object;
    #endif
    fflush(stdout); fflush(stderr);
    return (jobject) 0;
}



/* pvfs_stat_mask */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsStatMask  (JNIEnv *env, jobject obj, jlong jarg, jstring path, jlong mask)
{
    if(JNI_DBG) printf("pvfsStatMask\n");
    struct stat *arg;
    arg = (struct stat *)jarg;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    uint32_t cmask = (uint32_t) mask;
    int rc = pvfs_stat_mask(cpath, arg, cmask);
    if(rc < 0)
    {
        perror("pvfs_stat_mask error");
        rc = -1;
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_fstat */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFstat  (JNIEnv *env, jobject obj, jlong jarg, int fd)
{
    if(JNI_DBG) printf("pvfsFstat\n");
    struct stat *arg;
    arg = (struct stat *)jarg;
    int rc = pvfs_fstat(fd, arg);
    if(rc < 0)
    {
        perror("pvfs_fstat error");
        rc = -1;
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return rc;
}


/* pvfs_fstat_mask */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFstatMask  (JNIEnv *env, jobject obj, jlong jarg, int fd, jlong mask)
{
    if(JNI_DBG) printf("pvfsFstatMask\n");
    struct stat *arg;
    arg = (struct stat *)jarg;
    uint32_t cmask = (uint32_t) mask;
    int rc = pvfs_fstat_mask(fd, arg, cmask);
    if(rc < 0)
    {
        perror("pvfs_fstat_mask error");
        rc = -1;
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_Fstatat */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFstatat  (JNIEnv *env, jobject obj, jlong jarg, int fd, jstring path, int flag)
{
    if(JNI_DBG) printf("pvfFstatat\n");
    struct stat *arg;
    arg = (struct stat *)jarg;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    int rc = pvfs_fstatat(fd, cpath, arg, flag);
    if(rc < 0)
    {
        perror("pvfs_fstatat error");
        rc = -1;
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_lstat */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsLstat  (JNIEnv *env, jobject obj, jlong jarg, jstring path)
{
    if(JNI_DBG) printf("pvfsLstat\n");
    struct stat *arg;
    arg = (struct stat *)jarg;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    int rc = pvfs_lstat(cpath, arg);
    if(rc < 0)
    {
        perror("pvfs_lstat error");
        rc = -1;
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return rc;
}


/* pvfs_lstat_mask */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsLstatMask  (JNIEnv *env, jobject obj, jlong jarg, jstring path, jlong mask)
{
    if(JNI_DBG) printf("pvfsLstatMask\n");
    struct stat *arg;
    arg = (struct stat *)jarg;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    uint32_t cmask = (uint32_t) mask;
    int rc = pvfs_lstat_mask(cpath, arg, cmask);
    if(rc < 0)
    {
        perror("pvfs_lstat_mask error");
        rc = -1;
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_stat64 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsStat64  (JNIEnv *env, jobject obj, jlong jarg, jstring path)
{
    if(JNI_DBG) printf("pvfsStat64\n");
    struct stat64 *arg;
    arg = (struct stat64 *)jarg;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    int rc = pvfs_stat64(cpath, arg);
    if(rc < 0)
    {
        perror("pvfs_stat64 error");
        rc = -1;
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_Fstat64 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFstat64  (JNIEnv *env, jobject obj, jlong jarg, int fd)
{
    if(JNI_DBG) printf("pvfsFstat64\n");
    struct stat64 *arg;
    arg = (struct stat64 *)jarg;
    int rc = pvfs_fstat64(fd, arg);
    if(rc < 0)
    {
        perror("pvfs_fstat64 error");
        rc = -1;
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_Fstatat64 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFstatat64  (JNIEnv *env, jobject obj, jlong jarg, int fd, jstring path, int flag)
{
    if(JNI_DBG) printf("pvfsFstatat64\n");
    struct stat64 *arg;
    arg = (struct stat64 *)jarg;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    int rc = pvfs_fstatat64(fd, cpath, arg, flag);
    if(rc < 0)
    {
        perror("pvfs_fstatat64 error");
        rc = -1;
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_lstat64 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsLstat64  (JNIEnv *env, jobject obj, jlong jarg, jstring path)
{
    if(JNI_DBG) printf("pvfsLstat64\n");
    struct stat64 *arg;
    arg = (struct stat64 *)jarg;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    int rc = pvfs_lstat64(cpath, arg);
    if(rc < 0)
    {
        perror("pvfs_lstat64 error");
        rc = -1;
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return rc;
}

#if 0
/* FILLSTAT64 */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_FillStat64  (JNIEnv *env, jobject obj, jobject x)
{
    if(JNI_DBG) printf("FillStat64\n");
    jlong rc = 0;
    jfieldID fid1;
    jfieldID fid2;
    jfieldID fid3;
    jfieldID fid4;
    jfieldID fid5;
    jfieldID fid6;
    jfieldID fid7;
    jfieldID fid8;
    jfieldID fid9;
    jfieldID fid10;
    jfieldID fid11;
    jfieldID fid12;
    jfieldID fid13;
    jlong st_dev;
    jlong st_ino;
    jint st_mode;
    jint st_nlink;
    jlong st_uid;
    jlong st_gid;
    jlong st_rdev;
    jlong st_size;
    jint st_blksize;
    jlong st_blocks;
    jlong st_atim;
    jlong st_mtim;
    jlong st_ctim;
    jclass cls1 = (*env)->FindClass(env, "PVFS2JNI$Stat64");
    fid1 = (*env)->GetFieldID(env, cls1, "st_dev", "J");
    if (fid1 == NULL)
    {
        return;
    }
    fid2 = (*env)->GetFieldID(env, cls1, "st_ino", "J");
    if (fid2 == NULL)
    {
        return;
    }
    fid3 = (*env)->GetFieldID(env, cls1, "st_mode", "I");
    if (fid3 == NULL)
    {
        return;
    }
    fid4 = (*env)->GetFieldID(env, cls1, "st_nlink", "I");
    if (fid4 == NULL)
    {
        return;
    }
    fid5 = (*env)->GetFieldID(env, cls1, "st_uid", "J");
    if (fid5 == NULL)
    {
        return;
    }
    fid6 = (*env)->GetFieldID(env, cls1, "st_gid", "J");
    if (fid6 == NULL)
    {
        return;
    }
    fid7 = (*env)->GetFieldID(env, cls1, "st_rdev", "J");
    if (fid7 == NULL)
    {
        return;
    }
    fid8 = (*env)->GetFieldID(env, cls1, "st_size", "J");
    if (fid8 == NULL)
    {
        return;
    }
    fid9 = (*env)->GetFieldID(env, cls1, "st_blksize", "I");
    if (fid9 == NULL)
    {
        return;
    }
    fid10 = (*env)->GetFieldID(env, cls1, "st_blocks", "J");
    if (fid10 == NULL)
    {
        return;
    }
    fid11 = (*env)->GetFieldID(env, cls1, "st_atime", "J");
    if (fid11 == NULL)
    {
        return;
    }
    fid12 = (*env)->GetFieldID(env, cls1, "st_mtime", "J");
    if (fid12 == NULL)
    {
        return;
    }
    fid13 = (*env)->GetFieldID(env, cls1, "st_ctime", "J");
    if (fid13 == NULL)
    {
        return;
    }
    struct stat64 *cstat64 = (struct stat64 *) malloc(sizeof(struct stat64));
    if(!cstat64)
    {
        return -1;
    }
    st_dev = (*env)->GetLongField(env, x, fid1);
    dev_t cst_dev = (dev_t) st_dev;
    cstat64->st_dev = cst_dev;
    st_ino = (*env)->GetLongField(env, x, fid2);
    ino64_t cst_ino = (ino64_t) st_ino;
    cstat64->st_ino = cst_ino;
    st_mode = (*env)->GetIntField(env, x, fid3);
    mode_t cst_mode = (mode_t) st_mode;
    cstat64->st_mode = cst_mode;
    st_nlink = (*env)->GetIntField(env, x, fid4);
    nlink_t cst_nlink = (nlink_t) st_nlink;
    cstat64->st_nlink = cst_nlink;
    st_uid = (*env)->GetLongField(env, x, fid5);
    uid_t cst_uid = (uid_t) st_uid;
    cstat64->st_uid = cst_uid;
    st_gid = (*env)->GetLongField(env, x, fid6);
    gid_t cst_gid = (gid_t) st_gid;
    cstat64->st_gid = cst_gid;
    st_rdev = (*env)->GetLongField(env, x, fid7);
    dev_t cst_rdev = (dev_t) st_rdev;
    cstat64->st_rdev = cst_rdev;
    st_size = (*env)->GetLongField(env, x, fid8);
    off64_t cst_size = (off64_t) st_size;
    cstat64->st_size = cst_size;
    st_blksize = (*env)->GetIntField(env, x, fid9);
    blksize_t cst_blksize = (blksize_t) st_blksize;
    cstat64->st_blksize = cst_blksize;
    st_blocks = (*env)->GetLongField(env, x, fid10);
    blkcnt64_t cst_blocks = (blkcnt64_t) st_blocks;
    cstat64->st_blocks = cst_blocks;
    st_atim = (*env)->GetLongField(env, x, fid11);
    time_t cst_atime = (time_t) st_atim;
    cstat64->st_atime = cst_atime;
    st_mtim = (*env)->GetLongField(env, x, fid12);
    time_t cst_mtime = (time_t) st_mtim;
    cstat64->st_mtime = cst_mtime;
    st_ctim = (*env)->GetLongField(env, x, fid13);
    time_t cst_ctime = (time_t) st_ctim;
    cstat64->st_ctime = cst_ctime;
    /* TODO: this looks incorrect */
    long lp = (long)cstat64;
    free(cstat64);
    if(JNI_DBG) fflush(stdout);
    return lp;
}

/* FILLSTAT */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_FillStat  (JNIEnv *env, jobject obj, jobject x)
{
    if(JNI_DBG) printf("FillStat\n");
    jfieldID fid1;
    jfieldID fid2;
    jfieldID fid3;
    jfieldID fid4;
    jfieldID fid5;
    jfieldID fid6;
    jfieldID fid7;
    jfieldID fid8;
    jfieldID fid9;
    jfieldID fid10;
    jfieldID fid11;
    jfieldID fid12;
    jfieldID fid13;
    jlong st_dev;
    jlong st_ino;
    jint st_mode;
    jint st_nlink;
    jlong st_uid;
    jlong st_gid;
    jlong st_rdev;
    jlong st_size;
    jint st_blksize;
    jlong st_blocks;
    jlong st_atim;
    jlong st_mtim;
    jlong st_ctim;
    jclass cls1 = (*env)->FindClass(env, "PVFS2JNI$Stat");
    fid1 = (*env)->GetFieldID(env, cls1, "st_dev", "J");
    if (fid1 == NULL)
    {
        return;
    }
    fid2 = (*env)->GetFieldID(env, cls1, "st_ino", "J");
    if (fid2 == NULL)
    {
        return;
    }
    fid3 = (*env)->GetFieldID(env, cls1, "st_mode", "I");
    if (fid3 == NULL)
    {
        return;
    }
    fid4 = (*env)->GetFieldID(env, cls1, "st_nlink", "I");
    if (fid4 == NULL)
    {
        return;
    }
    fid5 = (*env)->GetFieldID(env, cls1, "st_uid", "J");
    if (fid5 == NULL)
    {
        return;
    }
    fid6 = (*env)->GetFieldID(env, cls1, "st_gid", "J");
    if (fid6 == NULL)
    {
        return;
    }
    fid7 = (*env)->GetFieldID(env, cls1, "st_rdev", "J");
    if (fid7 == NULL)
    {
        return;
    }
    fid8 = (*env)->GetFieldID(env, cls1, "st_size", "J");
    if (fid8 == NULL)
    {
        return;
    }
    fid9 = (*env)->GetFieldID(env, cls1, "st_blksize", "I");
    if (fid9 == NULL)
    {
        return;
    }
    fid10 = (*env)->GetFieldID(env, cls1, "st_blocks", "J");
    if (fid10 == NULL)
    {
        return;
    }
    fid11 = (*env)->GetFieldID(env, cls1, "st_atime", "J");
    if (fid11 == NULL)
    {
        return;
    }
    fid12 = (*env)->GetFieldID(env, cls1, "st_mtime", "J");
    if (fid12 == NULL)
    {
        return;
    }
    fid13 = (*env)->GetFieldID(env, cls1, "st_ctime", "J");
    if (fid13 == NULL)
    {
        return;
    }
    struct stat *cstat = (struct stat *)malloc(sizeof(struct stat));
    if(!cstat)
    {
        perror("malloc failure");
        goto done;
    }
    st_dev = (*env)->GetLongField(env, x, fid1);
    dev_t cst_dev = (dev_t) st_dev;
    cstat->st_dev = cst_dev;
    st_ino = (*env)->GetLongField(env, x, fid2);
    ino64_t cst_ino = (ino64_t) st_ino;
    cstat->st_ino = cst_ino;
    st_mode = (*env)->GetIntField(env, x, fid3);
    mode_t cst_mode = (mode_t) st_mode;
    cstat->st_mode = cst_mode;
    st_nlink = (*env)->GetIntField(env, x, fid4);
    nlink_t cst_nlink = (nlink_t) st_nlink;
    cstat->st_nlink = cst_nlink;
    st_uid = (*env)->GetLongField(env, x, fid5);
    uid_t cst_uid = (uid_t) st_uid;
    cstat->st_uid = cst_uid;
    st_gid = (*env)->GetLongField(env, x, fid6);
    gid_t cst_gid = (gid_t) st_gid;
    cstat->st_gid = cst_gid;
    st_rdev = (*env)->GetLongField(env, x, fid7);
    dev_t cst_rdev = (dev_t) st_rdev;
    cstat->st_rdev = cst_rdev;
    st_size = (*env)->GetLongField(env, x, fid8);
    off64_t cst_size = (off64_t) st_size;
    cstat->st_size = cst_size;
    st_blksize = (*env)->GetIntField(env, x, fid9);
    blksize_t cst_blksize = (blksize_t) st_blksize;
    cstat->st_blksize = cst_blksize;
    st_blocks = (*env)->GetLongField(env, x, fid10);
    blkcnt64_t cst_blocks = (blkcnt64_t) st_blocks;
    cstat->st_blocks = cst_blocks;
    st_atim = (*env)->GetLongField(env, x, fid11);
    time_t cst_atime = (time_t) st_atim;
    cstat->st_atime = cst_atime;
    st_mtim = (*env)->GetLongField(env, x, fid12);
    time_t cst_mtime = (time_t) st_mtim;
    cstat->st_mtime = cst_mtime;
    st_ctim = (*env)->GetLongField(env, x, fid13);
    time_t cst_ctime = (time_t) st_ctim;
    cstat->st_ctime = cst_ctime;
    /* TODO: this looks incorrect */
    long lp = (long)cstat;
done:
    if(cstat)
    {
        free(cstat);
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return lp;
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_UseStat64  (JNIEnv *env, jobject obj, jlong jarg)
{
    struct stat64 *arg;
    arg = (struct stat64 *)jarg;
    disp64(arg);
    /*
    printf("=======DISPLAY========\n");
    printf("The st_dev is: %ld\n", arg->st_dev);
    */
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_UseStat  (JNIEnv *env, jobject obj, jlong jarg)
{
    struct stat *arg;
    arg = (struct stat *)jarg;
    disp(arg);
    /*
    printf("=======DISPLAY========\n");
    printf("The st_dev is: %ld\n", arg->st_dev);
    */
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_FillDirent  (JNIEnv *env, jobject obj, jobject x)
{
    if(JNI_DBG) printf("FillDirent\n");
    long lp = 0;
    struct dirent *cdirent = 0;
    jfieldID fid1;
    jfieldID fid2;
    jfieldID fid3;
    jfieldID fid4;
    jfieldID fid5;
    jlong d_ino;
    jlong d_off;
    jint d_reclen;
    jstring d_type;
    jstring d_name;
    jclass cls1 = (*env)->FindClass(env, "PVFS2JNI$Dirent");
    fid1 = (*env)->GetFieldID(env, cls1, "d_ino", "J");
    if (fid1 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid2 = (*env)->GetFieldID(env, cls1, "d_off", "J");
    if (fid2 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid3 = (*env)->GetFieldID(env, cls1, "d_reclen", "I");
    if (fid3 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid4 = (*env)->GetFieldID(env, cls1, "d_type", "Ljava/lang/String;");
    if (fid4 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid5 = (*env)->GetFieldID(env, cls1, "d_name", "Ljava/lang/String;");
    if (fid5 == NULL)
    {
        lp = -1;
        goto done;
    }
    const char* strdtype;
    const char* strdname;
    cdirent = (struct dirent *) malloc(sizeof(struct dirent));
    if(!cdirent)
    {
        lp = -1;
        perror("malloc failed");
        goto done;
    }
    d_ino = (*env)->GetLongField(env, x, fid1);
    __ino_t cd_ino = (__ino_t) d_ino;
    cdirent->d_ino = cd_ino;
    d_off = (*env)->GetLongField(env, x, fid2);
    __off_t cd_off = (__off_t) d_off;
    cdirent->d_off = cd_off;
    d_reclen = (*env)->GetIntField(env, x, fid3);
    unsigned short int cd_reclen = (unsigned short int) d_reclen;
    cdirent->d_reclen = cd_reclen;
    d_type = (*env)->GetObjectField(env, x, fid4);
    strdtype = (*env)->GetStringUTFChars(env, d_type, NULL);
    if (!strdtype)
    {
        lp = -1; /* out of memory */
        perror("GetStringUTFChars failed");
        goto done;
    }
    if(strlen(strdtype) != 1)
    {
        lp = -1;
        perror("d_type is of type char, hence length cannot exceed 1\n");
        goto done;
    }
    else
    {
        char dtypearr[10];
        strcpy(dtypearr, strdtype);
        char cd_type = dtypearr[0];
        if(JNI_DBG) printf("The d_type is: %c \n", cd_type);
        cdirent->d_type = cd_type;
    }
    /*
    char cstrdtype = &(strdtype);
    printf("The d_type is: %s \n", chartest);
    */
    (*env)->ReleaseStringUTFChars(env, d_type, strdtype);
    d_name = (*env)->GetObjectField(env, x, fid5);
    strdname = (*env)->GetStringUTFChars(env, d_name, NULL);
    if (strdname == NULL)
    {
        lp = -1;
        perror("GetStringUTFChars failed");
        goto done;
    }
    if((strlen(strdname)) > 256)
    {
        lp = -1;
        perror("Length of strdname cannot exceed 250\n");
        goto done;
    }
    else
    {
        char cd_name[256];
        strcpy(cd_name, strdname);
        strcpy(cdirent->d_name, cd_name);
    }
    (*env)->ReleaseStringUTFChars(env, d_name, strdname);
    lp = (long)cdirent;
done:
    if(cdirent)
    {
        free(cdirent);
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return lp;
}

void dispdirent(struct dirent *abc)
{
    if(JNI_DBG)
    {
        printf("=======DISPLAY========\n");
        printf("The d_ino is: %d\n", (int) abc->d_ino);
        printf("The d_off is: %d\n", (int) abc->d_off);
        printf("The d_reclen is: %d\n", abc->d_reclen);
        printf("The d_type is: %c \n", abc->d_type);
        printf("The d_name is: %s \n", abc->d_name);
        fflush(stdout);
    }
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_UseDirent  (JNIEnv *env, jobject obj, jlong jarg)
{
    struct dirent *arg;
    arg = (struct dirent *)jarg;
    dispdirent(arg);
    /*
    printf("=======DISPLAY========\n");
    printf("The st_dev is: %ld\n", arg->st_dev);
    */
}

/*  FILL DIRENT */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_FillDirent64(JNIEnv *env, jobject obj, jobject x)
{
    if(JNI_DBG) printf("FillDirent64\n");
    long lp = 0;
    struct dirent64 *cdirent64 = NULL;
    const char* strdtype = NULL;
    const char* strdname = NULL;
    jfieldID fid1;
    jfieldID fid2;
    jfieldID fid3;
    jfieldID fid4;
    jfieldID fid5;
    jlong d_ino;
    jlong d_off;
    jint d_reclen;
    jstring d_type;
    jstring d_name;
    jclass cls1 = (*env)->FindClass(env, "PVFS2JNI$Dirent64");
    fid1 = (*env)->GetFieldID(env, cls1, "d_ino", "J");
    if (fid1 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid2 = (*env)->GetFieldID(env, cls1, "d_off", "J");
    if (fid2 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid3 = (*env)->GetFieldID(env, cls1, "d_reclen", "I");
    if (fid3 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid4 = (*env)->GetFieldID(env, cls1, "d_type", "Ljava/lang/String;");
    if (fid4 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid5 = (*env)->GetFieldID(env, cls1, "d_name", "Ljava/lang/String;");
    if (fid5 == NULL)
    {
        lp = -1;
        goto done;
    }
    cdirent64 = (struct dirent64 *) malloc(sizeof(struct dirent64));
    d_ino = (*env)->GetLongField(env, x, fid1);
    __ino64_t cd_ino = (__ino64_t) d_ino;
    cdirent64->d_ino = cd_ino;
    d_off = (*env)->GetLongField(env, x, fid2);
    __off64_t cd_off = (__off64_t) d_off;
    cdirent64->d_off = cd_off;
    d_reclen = (*env)->GetIntField(env, x, fid3);
    unsigned short int cd_reclen = (unsigned short int) d_reclen;
    cdirent64->d_reclen = cd_reclen;
    d_type = (*env)->GetObjectField(env, x, fid4);
    strdtype = (*env)->GetStringUTFChars(env, d_type, NULL);
    if (strdtype == NULL)
    {
        lp = -1;
        perror("GetStringUTFChars failed");
        goto done;
    }
    if(strlen(strdtype) != 1)
    {
        lp = -1;
        perror("d_type is of type char, hence length cannot exceed 1\n");
        goto done;
    }
    else
    {
        char dtypearr[10];
        strcpy(dtypearr, strdtype);
        char cd_type = dtypearr[0];
        /*
        printf("The d_type is: %c \n", cd_type);
        fflush(stdout);
        */
        cdirent64->d_type = cd_type;
    }
    /*
    char cstrdtype = &(strdtype);
    printf("The d_type is: %s \n", chartest);
    */
    (*env)->ReleaseStringUTFChars(env, d_type, strdtype);
    d_name = (*env)->GetObjectField(env, x, fid5);
    strdname = (*env)->GetStringUTFChars(env, d_name, NULL);
    if (strdname == NULL)
    {
        lp = -1;
        perror("GetStringUTFChars failed");
        goto done;
    }
    if(strlen(strdname) > 257)
    {
        lp = -1;
        perror("Length of strdname cannot exceed 250\n");
        goto done;
    }
    else
    {
        char cd_name[256];
        strcpy(cd_name, strdname);
        strcpy(cdirent64->d_name, cd_name);
    }
    (*env)->ReleaseStringUTFChars(env, d_name, strdname);
    lp = (long)cdirent64;
done:
    if(cdirent64)
    {
        free(cdirent64);
    }
    if(JNI_DBG) fflush(stdout);
    return lp;
}

void dispdirent64(struct dirent64 *abc)
{
    if(JNI_DBG)
    {
        printf("=======DISPLAY========\n");
        printf("The d_ino is: %d\n", (int) abc->d_ino);
        printf("The d_off is: %d\n", (int) abc->d_off);
        printf("The d_reclen is: %d\n", abc->d_reclen);
        printf("The d_type is: %c \n", abc->d_type);
        printf("The d_name is: %s \n", abc->d_name);
        fflush(stdout);
    }
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_UseDirent64  (JNIEnv *env, jobject obj, jlong jarg)
{
    struct dirent64 *arg;
    arg = (struct dirent64 *)jarg;
    dispdirent64(arg);
    /*
    printf("=======DISPLAY========\n");
    printf("The st_dev is: %ld\n", arg->st_dev);
    */
}

/* FILL STATFS */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_FillStatfs  (JNIEnv *env, jobject obj, jobject x, jlong jarg)
{
    if(JNI_DBG) printf("FillStatfs\n");
    long lp = 0;
    struct statfs *cstatfs = NULL;
    jfieldID fid1;
    jfieldID fid2;
    jfieldID fid3;
    jfieldID fid4;
    jfieldID fid5;
    jfieldID fid6;
    jfieldID fid7;
    jfieldID fid8;
    jfieldID fid9;
    jfieldID fid10;
    jfieldID fid11;
    jfieldID fid12;
    jlong f_type;
    jlong f_bsize;
    jlong f_blocks;
    jlong f_bfree;
    jlong f_bavail;
    jlong f_files;
    jlong f_ffree;
    jlong f_fsid;
    jlong f_namelen;
    jlong f_frsize;
    jlong f_flags;
    jclass cls1 = (*env)->FindClass(env, "PVFS2JNI$Statfs");
    fid1 = (*env)->GetFieldID(env, cls1, "f_type", "J");
    if (fid1 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid2 = (*env)->GetFieldID(env, cls1, "f_bsize", "J");
    if (fid2 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid3 = (*env)->GetFieldID(env, cls1, "f_blocks", "J");
    if (fid3 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid4 = (*env)->GetFieldID(env, cls1, "f_bfree", "J");
    if (fid4 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid5 = (*env)->GetFieldID(env, cls1, "f_bavail", "J");
    if (fid5 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid6 = (*env)->GetFieldID(env, cls1, "f_files", "J");
    if (fid6 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid7 = (*env)->GetFieldID(env, cls1, "f_ffree", "J");
    if (fid7 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid9 = (*env)->GetFieldID(env, cls1, "f_namelen", "J");
    if (fid9 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid10 = (*env)->GetFieldID(env, cls1, "f_frsize", "J");
    if (fid10 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid11 = (*env)->GetFieldID(env, cls1, "f_spare", "[J");
    if (fid11 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid12 = (*env)->GetFieldID(env, cls1, "f_flags", "J");
    if (fid12 == NULL)
    {
        lp = -1;
        goto done;
    }
    /*
    __SWORD_TYPE* tmp;
    tmp = (__SWORD_TYPE *) malloc( 5 * sizeof(__SWORD_TYPE) );
    tmp[0]=10;
    tmp[1]=20;
    printf("tmp=%ld\n",tmp[0]);
    */
    cstatfs = (struct statfs *)malloc(sizeof(struct statfs) + 1);
    /*
    long int i= 10;
    long int *(cstatfs->f_spare[0]) = tmp[0];
    cstatfs->f_spare[4]=10;
    printf("f_spare[4]=%d\n",cstatfs->f_spare[4]);
    */
    f_type = (*env)->GetLongField(env, x, fid1);
    __SWORD_TYPE cf_type = (__SWORD_TYPE) f_type;
    cstatfs->f_type = cf_type;
    f_bsize = (*env)->GetLongField(env, x, fid2);
    __SWORD_TYPE cf_bsize = (__SWORD_TYPE) f_bsize;
    cstatfs->f_bsize = cf_bsize;
    f_blocks = (*env)->GetLongField(env, x, fid3);
    fsblkcnt_t cf_blocks = (fsblkcnt_t) f_blocks;
    cstatfs->f_blocks = cf_blocks;
    f_bfree = (*env)->GetLongField(env, x, fid4);
    fsblkcnt_t cf_bfree = (fsblkcnt_t) f_bfree;
    cstatfs->f_bfree = cf_bfree;
    f_bavail = (*env)->GetLongField(env, x, fid5);
    fsblkcnt_t cf_bavail = (fsblkcnt_t) f_bavail;
    cstatfs->f_bavail = cf_bavail;
    f_files = (*env)->GetLongField(env, x, fid6);
    fsfilcnt_t cf_files = (fsfilcnt_t) f_files;
    cstatfs->f_files = cf_files;
    f_ffree = (*env)->GetLongField(env, x, fid7);
    fsfilcnt_t cf_ffree = (fsfilcnt_t) f_ffree;
    cstatfs->f_ffree = cf_ffree;
    f_namelen = (*env)->GetLongField(env, x, fid9);
    __SWORD_TYPE cf_namelen = (__SWORD_TYPE) f_namelen;
    cstatfs->f_namelen = cf_namelen;
    f_frsize = (*env)->GetLongField(env, x, fid10);
    __SWORD_TYPE cf_frsize = (__SWORD_TYPE) f_frsize;
    cstatfs->f_frsize = cf_frsize;
    f_flags = (*env)->GetLongField(env, x, fid12);
    __SWORD_TYPE cf_flags = (__SWORD_TYPE) f_flags;
    cstatfs->f_flags = cf_flags;
    /*
    buf=(*env)->GetLongArrayElements(env,x,fid11);
    printf("ARRAY:%ld",buf[0];
    */
    jlong buf[5];
    jlongArray ar;
    ar = (*env)->GetObjectField(env, x, fid11);
    (*env)->GetLongArrayRegion(env, ar, 0, 5, buf);
    __SWORD_TYPE cbuf[5];
    int ival;
    int jval;
    for(ival = 0; ival <= 4; ival++)
    {
        cbuf[ival] = buf[ival];
    }
    /* printf("cbuf=%ld",cbuf[4]); */
    for(jval = 0; jval <= 4; jval++)
    {
        cstatfs->f_spare[jval] = cbuf[jval];
    }
    /* cstatfs->f_spare[4] = 10; */
    fsid_t *arg;
    arg = (fsid_t *)jarg;
    cstatfs->f_fsid.__val[0] = arg->__val[0];
    cstatfs->f_fsid.__val[1] = arg->__val[1];
    /*
    printf("cstatfs.fsid1=%d\n",cstatfs->f_fsid.__val[0]);
    printf("cstatfs.fsid2=%d\n",cstatfs->f_fsid.__val[1]);
    */
    /* TODO: this looks incorrect */
    lp = (long)cstatfs;
done:
    free(cstatfs);
    fflush(stdout);
    return lp;

}

void dispstatfs(struct statfs *abc)
{
    if(JNI_DBG)
    {
        printf("=======DISPLAY========\n");
        printf("The f_type is: %ld\n", abc->f_type);
        printf("The f_bsize is: %ld\n", abc->f_bsize);
        printf("The f_blocks is: %lu\n", (long unsigned int) abc->f_blocks);
        printf("The f_bfree is: %lu \n", (long unsigned int) abc->f_bfree);
        printf("The f_bavail is: %lu \n", (long unsigned int) abc->f_bavail);
        printf("The f_files is: %lu \n", (long unsigned int) abc->f_files);
        printf("The f_ffree is: %lu \n", (long unsigned int) abc->f_ffree);
        /* printf("The f_fsid is: %d \n", abc->f_fsid); */
        printf("The f_namelen is: %ld \n", abc->f_namelen);
        printf("The f_frsize is: %ld \n", abc->f_frsize);
        printf("The f_flags is: %ld \n", abc->f_flags);
        int i;
        for(i = 0; i <= 4; i++)
        {
            printf("F_SPARE %d = %ld\n", i, abc->f_spare[i]);
        }
        for(i = 0; i <= 1; i++)
        {
            printf("F_FSID %d = %d\n", i, abc->f_fsid.__val[i]);
        }
        printf("=======DISPLAY========\n");
        fflush(stdout);
    }
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_UseStatfs  (JNIEnv *env, jobject obj, jlong jarg)
{
    struct statfs *arg;
    arg = (struct statfs *)jarg;
    dispstatfs(arg);
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_FillFsid  (JNIEnv *env, jobject obj, jobject x)
{
    if(JNI_DBG) printf("FillFsid\n");
    long lp = 0;
    fsid_t *cfsid_t = 0;
    jfieldID fid1;
    jclass cls1 = (*env)->FindClass(env, "PVFS2JNI$Fsid");
    fid1 = (*env)->GetFieldID(env, cls1, "val", "[I");
    if (fid1 == NULL)
    {
        lp = -1;
        goto done;
    }
    cfsid_t = (fsid_t *) malloc(sizeof(fsid_t));
    if(!cfsid_t)
    {
        perror("malloc failed");
        lp = -1;
        goto done;
    }
    jint buf[2];
    jintArray ar;
    ar = (*env)->GetObjectField(env, x, fid1);
    (*env)->GetIntArrayRegion(env, ar, 0, 2, buf);
    int cbuf[2];
    int ival;
    int jval;
    for(ival = 0; ival <= 1; ival++)
    {
        cbuf[ival] = buf[ival];
    }
    /* printf("cbuf=%ld",cbuf[4]); */
    for(jval = 0; jval <= 1; jval++)
    {
        cfsid_t->__val[jval] = cbuf[jval];
    }
    for(jval = 0; jval <= 1; jval++)
    {
        if(JNI_DBG) printf("arr[%d]=%d\n", jval, cfsid_t->__val[jval]);
    }
    lp = (long)cfsid_t;
done:
    if(cfsid_t)
    {
        free(cfsid_t);
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return lp;
}

void dispfsid(fsid_t *abc)
{
    if(JNI_DBG)
    {
        printf("=======DISPLAY========\n");
        int i;
        for(i = 0; i <= 1; i++)
        {
            printf("Array element %d = %d\n", i, abc->__val[i]);
        }
        printf("=======DISPLAY========\n");
        fflush(stdout);
    }
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_UseFsid  (JNIEnv *env, jobject obj, jlong jarg)
{
    fsid_t *arg;
    arg = (fsid_t *)jarg;
    dispfsid(arg);
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_FillUtimbuf  (JNIEnv *env, jobject obj, jobject x)
{
    if(JNI_DBG) printf("FillUtimbuf\n");
    struct utimbuf *cutimbuf = 0;
    long lp = 0;
    jfieldID fid1;
    jfieldID fid2;
    jlong actime;
    jlong modtime;
    jclass cls1 = (*env)->FindClass(env, "PVFS2JNI$Utimbuf");
    fid1 = (*env)->GetFieldID(env, cls1, "actime", "J");
    if (fid1 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid2 = (*env)->GetFieldID(env, cls1, "modtime", "J");
    if (fid2 == NULL)
    {
        lp = -1;
        goto done;
    }
    cutimbuf = (struct utimbuf *)malloc(sizeof(struct utimbuf));
    if(!cutimbuf)
    {
        perror("malloc failed");
        lp = -1;
        goto done;
    }
    actime = (*env)->GetLongField(env, x, fid1);
    long cactime = (long) actime;
    cutimbuf->actime = cactime;
    modtime = (*env)->GetLongField(env, x, fid2);
    long cmodtime = (long) modtime;
    cutimbuf->modtime = cmodtime;
    if(JNI_DBG)
    {
        printf("ACTIME=:%ld\n", cutimbuf->actime);
        printf("MODTIME=:%ld\n", cutimbuf->modtime);
    }
    lp = (long)cutimbuf;
done:
    if(cutimbuf)
    {
        free(cutimbuf);
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return lp;
}

void disputimbuf(struct utimbuf *abc)
{
    if(JNI_DBG)
    {
        printf("=======DISPLAY========\n");
        printf("ACTIME=:%ld\n", abc->actime);
        printf("MODTIME=:%ld\n", abc->modtime);
        printf("=======DISPLAY========\n");
        fflush(stdout);
    }
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_UseUtimbuf  (JNIEnv *env, jobject obj, jlong jarg)
{
    struct utimbuf *arg;
    arg = (struct utimbuf *)jarg;
    disputimbuf(arg);
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_FillTimeval  (JNIEnv *env, jobject obj, jobject x)
{
    if(JNI_DBG) printf("FillTimeval\n");
    struct timeval *ctimeval = NULL;
    long lp = 0;
    jfieldID fid1;
    jfieldID fid2;
    jlong tv_sec;
    jlong tv_usec;
    jclass cls1 = (*env)->FindClass(env, "PVFS2JNI$Timeval");
    fid1 = (*env)->GetFieldID(env, cls1, "tv_sec", "J");
    if (fid1 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid2 = (*env)->GetFieldID(env, cls1, "tv_usec", "J");
    if (fid2 == NULL)
    {
        lp = -1;
        goto done;
    }
    ctimeval = (struct timeval *)malloc(sizeof(struct timeval));
    if(!ctimeval)
    {
        perror("malloc failed");
        lp = -1;
        goto done;
    }
    tv_sec = (*env)->GetLongField(env, x, fid1);
    __time_t ctv_sec = (__time_t) tv_sec;
    ctimeval->tv_sec = ctv_sec;
    tv_usec = (*env)->GetLongField(env, x, fid2);
    __suseconds_t ctv_usec = (__suseconds_t) tv_usec;
    ctimeval->tv_usec = ctv_usec;
    if(JNI_DBG)
    {
        printf("TV_SEC=:%ld\n", ctimeval->tv_sec);
        printf("TV_USEC=:%ld\n", ctimeval->tv_usec);
    }
    lp = (long) ctimeval;
done:
    if(ctimeval)
    {
        free(ctimeval);
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return lp;
}

void disptimeval(struct timeval abc[2])
{
    if(JNI_DBG)
    {
        printf("=======DISPLAY========\n");
        printf("++STRUCT  1++\n");
        printf("ACTIME=:%ld\n", abc[0].tv_sec);
        printf("MODTIME=:%ld\n", abc[0].tv_usec);
        printf("++STRUCT  2++\n");
        printf("ACTIME=:%ld\n", abc[1].tv_sec);
        printf("MODTIME=:%ld\n", abc[1].tv_usec);
        printf("=======DISPLAY========\n");
        fflush(stdout);
    }
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_UseTimeval  (JNIEnv *env, jobject obj, jlong jarg1, jlong jarg2)
{
    struct timeval *arg1;
    struct timeval *arg2;
    arg1 = (struct timeval *)jarg1;
    arg2 = (struct timeval *)jarg2;
    struct timeval abc[2];
    abc[0].tv_sec = arg1->tv_sec;
    abc[0].tv_usec = arg1->tv_usec;
    abc[1].tv_sec = arg2->tv_sec;
    abc[1].tv_usec = arg2->tv_usec;
    disptimeval(abc);
    /*
    printf("++STRUCT  1++\n");
    printf("ACTIME=:%ld\n", abc[0].tv_sec);
    printf("MODTIME=:%ld\n", abc[0].tv_usec);
    printf("++STRUCT  2++\n");
    printf("ACTIME=:%ld\n", abc[1].tv_sec);
    printf("MODTIME=:%ld\n", abc[1].tv_usec);
    */
}
#endif 

/* pvfs_readdir */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsReaddir  (JNIEnv *env, jobject obj, jlong jarg, int fd, int count)
{
    if(JNI_DBG) printf("pvfsReaddir\n");
    int rc = 0;
    struct dirent *arg;
    arg = (struct dirent *)jarg;
    unsigned int cfd = (unsigned int) fd;
    unsigned int ccount = (unsigned int) count;
    rc = pvfs_readdir(cfd, arg, ccount);
    if(rc < 0)
    {
        perror("pvfs_readdir error");
        rc = -1;
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return rc;
}


/* pvfs_getdents */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsGetdents  (JNIEnv *env, jobject obj, jlong jarg, int fd, int size)
{
    if(JNI_DBG) printf("pvfsGetdents\n");
    int rc = 0;
    struct dirent *arg;
    arg = (struct dirent *)jarg;
    unsigned int cfd = (unsigned int) fd;
    unsigned int csize = (unsigned int) size;
    rc = pvfs_getdents(cfd, arg, csize);
    if(rc < 0)
    {
        perror("pvfs_getdents error");
        rc = -1;
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_getdents64 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsGetdents64  (JNIEnv *env, jobject obj, jlong jarg, int fd, int size)
{
    if(JNI_DBG) printf("pvfsGetdents64\n");
    int rc = 0;
    struct dirent64 *arg;
    arg = (struct dirent64 *)jarg;
    unsigned int cfd = (unsigned int) fd;
    unsigned int csize = (unsigned int) size;
    rc = pvfs_getdents64(cfd, arg, csize);
    if(rc < 0)
    {
        perror("pvfs_getdents64 error");
        rc = -1;
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_futimesat */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_Futimesat  (JNIEnv *env, jobject obj, jlong jarg1, jlong jarg2, int dirfd, jstring path)
{
    if(JNI_DBG) printf("pvfsFutimesat\n");
    int rc = 0;
    struct timeval *arg1;
    struct timeval *arg2;
    arg1 = (struct timeval *)jarg1;
    arg2 = (struct timeval *)jarg2;
    struct timeval abc[2];
    abc[0].tv_sec = arg1->tv_sec;
    abc[0].tv_usec = arg1->tv_usec;
    abc[1].tv_sec = arg2->tv_sec;
    abc[1].tv_usec = arg2->tv_usec;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    rc = pvfs_futimesat(dirfd, cpath, abc);
    if(rc < 0)
    {
        perror("pvfs_futimesat error");
        rc = -1;
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_utimes */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_Utimes  (JNIEnv *env, jobject obj, jlong jarg1, jlong jarg2, jstring path)
{
    if(JNI_DBG) printf("pvfs_Utimes\n");
    int rc = 0;
    struct timeval *arg1;
    struct timeval *arg2;
    arg1 = (struct timeval *)jarg1;
    arg2 = (struct timeval *)jarg2;
    struct timeval abc[2];
    abc[0].tv_sec = arg1->tv_sec;
    abc[0].tv_usec = arg1->tv_usec;
    abc[1].tv_sec = arg2->tv_sec;
    abc[1].tv_usec = arg2->tv_usec;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    rc = pvfs_utimes(cpath, abc);
    if(rc < 0)
    {
        perror("pvfs_utimes error");
        rc = -1;
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_futimes */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_Futimes  (JNIEnv *env, jobject obj, jlong jarg1, jlong jarg2, int fd)
{
    if(JNI_DBG) printf("pvfs_futimes\n");
    int rc = 0;
    struct timeval *arg1;
    struct timeval *arg2;
    arg1 = (struct timeval *)jarg1;
    arg2 = (struct timeval *)jarg2;
    struct timeval abc[2];
    abc[0].tv_sec = arg1->tv_sec;
    abc[0].tv_usec = arg1->tv_usec;
    abc[1].tv_sec = arg2->tv_sec;
    abc[1].tv_usec = arg2->tv_usec;
    rc = pvfs_futimes(fd, abc);
    if(rc < 0)
    {
        perror("pvfs_futimes error");
        rc = -1;
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_utime */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsUtime  (JNIEnv *env, jobject obj, jlong jarg, jstring path)
{
    if(JNI_DBG) printf("pvfsUtime\n");
    int rc = 0;
    struct utimbuf *arg;
    arg = (struct utimbuf *)jarg;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    rc = pvfs_utime(cpath, arg);
    if(rc < 0)
    {
        perror("pvfs_utime error");
        rc = -1;
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_listxattr */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsListxattr (JNIEnv *env, jobject obj, jstring path, jstring list, jlong size)
{
    if(JNI_DBG) printf("pvfsListxattr\n");
    long rc = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    char clist[PVFS_MAX_XATTR_LISTLEN];
    int clist_len = (*env)->GetStringLength(env, list);
    (*env)->GetStringUTFRegion(env, list, 0, clist_len, clist);
    size_t csize = (size_t) size;
    rc = pvfs_listxattr(cpath, clist, csize);
    if(rc < 0)
    {
        perror("pvfs_listxattr error");
        rc = -1;
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_llistxattr */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsLlistxattr (JNIEnv *env, jobject obj, jstring path, jstring list, jlong size)
{
    if(JNI_DBG) printf("pvfsLlistxattr\n");
    long rc = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    char clist[PVFS_MAX_XATTR_LISTLEN];
    int clist_len = (*env)->GetStringLength(env, list);
    (*env)->GetStringUTFRegion(env, list, 0, clist_len, clist);
    size_t csize = (size_t) size;
    rc = pvfs_llistxattr(cpath, clist, csize);
    if(rc < 0)
    {
        perror("pvfs_llistxattr error");
        rc = -1;
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_flistxattr */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFlistxattr (JNIEnv *env, jobject obj, int fd, jstring list, jlong size)
{
    if(JNI_DBG) printf("pvfsFlistxattr\n");
    long rc = 0;
    char clist[PVFS_MAX_XATTR_LISTLEN];
    int clist_len = (*env)->GetStringLength(env, list);
    (*env)->GetStringUTFRegion(env, list, 0, clist_len, clist);
    size_t csize = (size_t) size;
    rc = pvfs_flistxattr(fd, clist, csize);
    if(rc < 0)
    {
        perror("pvfs_flistxattr error");
        rc = -1;
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_removexattr */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsRemovexattr(JNIEnv *env, jobject obj, jstring path, jstring name)
{
    if(JNI_DBG) printf("pvfsRemovexattr\n");
    int rc = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    char cname[PVFS_NAME_MAX];
    int cname_len = (*env)->GetStringLength(env, name);
    (*env)->GetStringUTFRegion(env, name, 0, cname_len, cname);
    rc = pvfs_removexattr(cpath, cname);
    if(rc < 0)
    {
        perror("pvfs_removexattr error");
        rc = -1;
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stderr);
    return rc;
}

/* pvfs_lremovexattr */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsLremovexattr(JNIEnv *env, jobject obj, jstring path, jstring name)
{
    if(JNI_DBG) printf("pvfsLremovexattr\n");
    int rc = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    char cname[PVFS_NAME_MAX];
    int cname_len = (*env)->GetStringLength(env, name);
    (*env)->GetStringUTFRegion(env, name, 0, cname_len, cname);
    rc = pvfs_lremovexattr(cpath, cname);
    if(rc < 0)
    {
        perror("pvfs_Lremovexattr error");
        rc = -1;
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_fremovexattr */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFremovexattr(JNIEnv *env, jobject obj, int fd, jstring name)
{
    if(JNI_DBG) printf("pvfsFremovexattr\n");
    int rc = 0;
    char cname[PVFS_NAME_MAX];
    int cname_len = (*env)->GetStringLength(env, name);
    (*env)->GetStringUTFRegion(env, name, 0, cname_len, cname);
    rc = pvfs_fremovexattr(fd, cname);
    if(rc < 0)
    {
        perror("pvfs_fremovexattr error");
        rc = -1;
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_getumask */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsGetumask(JNIEnv *env, jobject obj)
{
    if(JNI_DBG)
    {
         printf("pvfsGetumask\n");
         fflush(stdout);
    }
    mode_t rc = pvfs_getumask();
    long ret = (long) rc;
    return ret;
}

/* pvfs_getdtablesize */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsGetdtablesize(JNIEnv *env, jobject obj)
{
    if(JNI_DBG)
    {
        printf("pvfsGetdtablesize\n");
        fflush(stdout);
    }
    int rc = pvfs_getdtablesize();
    return rc;
}

/* pvfs_sync */
JNIEXPORT void JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsSync(JNIEnv *env, jobject obj)
{
    if(JNI_DBG)
    {
        printf("pvfsSync\n");
        fflush(stdout);
    }
    pvfs_sync();
    return;
}

#if 0
/* FILL STATFS64 */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_FillStatfs64  (JNIEnv *env, jobject obj, jobject x, jlong jarg)
{
    if(JNI_DBG) printf("FillStatfs64\n");
    long lp = 0;
    struct statfs64 *cstatfs64 = 0;
    jfieldID fid1;
    jfieldID fid2;
    jfieldID fid3;
    jfieldID fid4;
    jfieldID fid5;
    jfieldID fid6;
    jfieldID fid7;
    jfieldID fid8;
    jfieldID fid9;
    jfieldID fid10;
    jfieldID fid11;
    jfieldID fid12;
    jlong f_type;
    jlong f_bsize;
    jlong f_blocks;
    jlong f_bfree;
    jlong f_bavail;
    jlong f_files;
    jlong f_ffree;
    jlong f_fsid;
    jlong f_namelen;
    jlong f_frsize;
    jlong f_flags;
    jclass cls1 = (*env)->FindClass(env, "PVFS2JNI$Statfs64");
    fid1 = (*env)->GetFieldID(env, cls1, "f_type", "J");
    if (fid1 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid2 = (*env)->GetFieldID(env, cls1, "f_bsize", "J");
    if (fid2 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid3 = (*env)->GetFieldID(env, cls1, "f_blocks", "J");
    if (fid3 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid4 = (*env)->GetFieldID(env, cls1, "f_bfree", "J");
    if (fid4 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid5 = (*env)->GetFieldID(env, cls1, "f_bavail", "J");
    if (fid5 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid6 = (*env)->GetFieldID(env, cls1, "f_files", "J");
    if (fid6 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid7 = (*env)->GetFieldID(env, cls1, "f_ffree", "J");
    if (fid7 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid9 = (*env)->GetFieldID(env, cls1, "f_namelen", "J");
    if (fid9 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid10 = (*env)->GetFieldID(env, cls1, "f_frsize", "J");
    if (fid10 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid11 = (*env)->GetFieldID(env, cls1, "f_spare", "[J");
    if (fid11 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid12 = (*env)->GetFieldID(env, cls1, "f_flags", "J");
    if (fid12 == NULL)
    {
        lp = -1;
        goto done;
    }
    /*
     __SWORD_TYPE* tmp;
    tmp = (__SWORD_TYPE *) malloc( 5 * sizeof(__SWORD_TYPE) );
    tmp[0]=10;
    tmp[1]=20;
    printf("tmp=%ld\n",tmp[0]);
    */
    cstatfs64 = (struct statfs64 *) malloc(sizeof(struct statfs64) + 1);
    if(!cstatfs64)
    {
        perror("malloc failed");
        lp = -1;
        goto done;
    }
    /*
    long int *(cstatfs->f_spare[0]) = tmp[0];
    long int i= 10;
    cstatfs->f_spare[4]=10;
    printf("f_spare[4]=%d\n",cstatfs->f_spare[4]);
    */
    f_type = (*env)->GetLongField(env, x, fid1);
    __SWORD_TYPE cf_type = (__SWORD_TYPE) f_type;
    cstatfs64->f_type = cf_type;
    f_bsize = (*env)->GetLongField(env, x, fid2);
    __SWORD_TYPE cf_bsize = (__SWORD_TYPE) f_bsize;
    cstatfs64->f_bsize = cf_bsize;
    f_blocks = (*env)->GetLongField(env, x, fid3);
    fsblkcnt64_t cf_blocks = (fsblkcnt64_t) f_blocks;
    cstatfs64->f_blocks = cf_blocks;
    f_bfree = (*env)->GetLongField(env, x, fid4);
    fsblkcnt64_t cf_bfree = (fsblkcnt64_t) f_bfree;
    cstatfs64->f_bfree = cf_bfree;
    f_bavail = (*env)->GetLongField(env, x, fid5);
    fsblkcnt64_t cf_bavail = (fsblkcnt64_t) f_bavail;
    cstatfs64->f_bavail = cf_bavail;
    f_files = (*env)->GetLongField(env, x, fid6);
    fsfilcnt64_t cf_files = (fsfilcnt64_t) f_files;
    cstatfs64->f_files = cf_files;
    f_ffree = (*env)->GetLongField(env, x, fid7);
    fsfilcnt64_t cf_ffree = (fsfilcnt64_t) f_ffree;
    cstatfs64->f_ffree = cf_ffree;
    f_namelen = (*env)->GetLongField(env, x, fid9);
    __SWORD_TYPE cf_namelen = (__SWORD_TYPE) f_namelen;
    cstatfs64->f_namelen = cf_namelen;
    f_frsize = (*env)->GetLongField(env, x, fid10);
    __SWORD_TYPE cf_frsize = (__SWORD_TYPE) f_frsize;
    cstatfs64->f_frsize = cf_frsize;
    f_flags = (*env)->GetLongField(env, x, fid12);
    __SWORD_TYPE cf_flags = (__SWORD_TYPE) f_flags;
    cstatfs64->f_flags = cf_flags;
    /*
    buf=(*env)->GetLongArrayElements(env,x,fid11);
    printf("ARRAY:%ld",buf[0];
    */
    jlong buf[5];
    jlongArray ar;
    ar = (*env)->GetObjectField(env, x, fid11);
    (*env)->GetLongArrayRegion(env, ar, 0, 5, buf);
    __SWORD_TYPE cbuf[5];
    int ival;
    int jval;
    for(ival = 0; ival <= 4; ival++)
    {
        cbuf[ival] = buf[ival];
    }
    /*i printf("cbuf=%ld",cbuf[4]); */
    for(jval = 0; jval <= 4; jval++)
    {
        cstatfs64->f_spare[jval] = cbuf[jval];
    }
    /* cstatfs->f_spare[4] = 10; */
    fsid_t *arg;
    arg = (fsid_t *)jarg;
    cstatfs64->f_fsid.__val[0] = arg->__val[0];
    cstatfs64->f_fsid.__val[1] = arg->__val[1];
    /*
    printf("cstatfs.fsid1=%d\n",cstatfs->f_fsid.__val[0]);
    printf("cstatfs.fsid2=%d\n",cstatfs->f_fsid.__val[1]);
    */
    lp = (long)cstatfs64;
done:
    if(cstatfs64)
    {
        free(cstatfs64);
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return lp;
}

/* DISPSTATFS64 */
void dispstatfs64(struct statfs64 *abc)
{
    if(JNI_DBG)
    {
        printf("=======DISPLAY========\n");
        printf("The f_type is: %ld\n", (long int) abc->f_type);
        printf("The f_bsize is: %ld\n", (long int) abc->f_bsize);
        printf("The f_blocks is: %lu\n", abc->f_blocks);
        printf("The f_bfree is: %lu\n", abc->f_bfree);
        printf("The f_bavail is: %lu\n", abc->f_bavail);
        printf("The f_files is: %lu\n", abc->f_files);
        printf("The f_ffree is: %lu\n", abc->f_ffree);
        /* printf("The f_fsid is: %lu\n", abc->f_fsid); */
        printf("The f_namelen is: %lu\n", abc->f_namelen);
        printf("The f_frsize is: %lu\n", abc->f_frsize);
        printf("The f_flags is: %ld \n", abc->f_flags);
        int i;
        for(i = 0; i <= 4; i++)
        {
            printf("F_SPARE %d = %ld\n", i, abc->f_spare[i]);
        }
        for(i = 0; i <= 1; i++)
        {
            printf("F_FSID %d = %d\n", i, abc->f_fsid.__val[i]);
        }
        printf("=======DISPLAY========\n");
        fflush(stdout);
    }
}

/* UseStatfs64 */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_UseStatfs64  (JNIEnv *env, jobject obj, jlong jarg)
{
    struct statfs64 *arg;
    arg = (struct statfs64 *)jarg;
    dispstatfs64(arg);
}

/* FILL STATVFS */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_FillStatvfs  (JNIEnv *env, jobject obj, jobject x)
{
    if(JNI_DBG) printf("FillStatvfs\n");
    long lp = 0;
    struct statvfs *cstatvfs = 0;
    jfieldID fid2;
    jfieldID fid3;
    jfieldID fid4;
    jfieldID fid5;
    jfieldID fid6;
    jfieldID fid7;
    jfieldID fid12;
    jfieldID fid9;
    jfieldID fid10;
    jfieldID fid13;
    jfieldID fid14;
    jlong f_bsize;
    jlong f_frsize;
    jlong f_blocks;
    jlong f_bfree;
    jlong f_bavail;
    jlong f_files;
    jlong f_ffree;
    jlong f_favail;
    jlong f_fsid;
    jlong f_flag;
    jlong f_namemax;
    jclass cls1 = (*env)->FindClass(env, "PVFS2JNI$Statvfs");
    fid2 = (*env)->GetFieldID(env, cls1, "f_bsize", "J");
    if (fid2 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid3 = (*env)->GetFieldID(env, cls1, "f_blocks", "J");
    if (fid3 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid4 = (*env)->GetFieldID(env, cls1, "f_bfree", "J");
    if (fid4 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid5 = (*env)->GetFieldID(env, cls1, "f_bavail", "J");
    if (fid5 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid6 = (*env)->GetFieldID(env, cls1, "f_files", "J");
    if (fid6 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid7 = (*env)->GetFieldID(env, cls1, "f_ffree", "J");
    if (fid7 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid9 = (*env)->GetFieldID(env, cls1, "f_namemax", "J");
    if (fid9 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid10 = (*env)->GetFieldID(env, cls1, "f_frsize", "J");
    if (fid10 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid12 = (*env)->GetFieldID(env, cls1, "f_flag", "J");
    if (fid12 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid13 = (*env)->GetFieldID(env, cls1, "f_favail", "J");
    if (fid13 == NULL)
    {
        lp = -1;
        goto done;
    }
    fid14 = (*env)->GetFieldID(env, cls1, "f_fsid", "J");
    if (fid14 == NULL)
    {
        lp = -1;
        goto done;
    }
    /*
    __SWORD_TYPE* tmp;
    tmp = (__SWORD_TYPE *) malloc( 5 * sizeof(__SWORD_TYPE) );
    tmp[0]=10;
    tmp[1]=20;
    printf("tmp=%ld\n",tmp[0]);
    */
    cstatvfs = (struct statvfs *)malloc(sizeof(struct statvfs));
    if(!cstatvfs)
    {
        perror("malloc failed");
        lp = -1;
        goto done;
    }
    /*
    long int i= 10;
    long int *(cstatfs->f_spare[0]) = tmp[0];
    cstatfs->f_spare[4]=10;
    printf("f_spare[4]=%d\n",cstatfs->f_spare[4]);
    */
    f_bsize = (*env)->GetLongField(env, x, fid2);
    unsigned long cf_bsize = (unsigned long) f_bsize;
    cstatvfs->f_bsize = cf_bsize;
    f_blocks = (*env)->GetLongField(env, x, fid3);
    fsblkcnt_t cf_blocks = (fsblkcnt_t) f_blocks;
    cstatvfs->f_blocks = cf_blocks;
    f_bfree = (*env)->GetLongField(env, x, fid4);
    fsblkcnt_t cf_bfree = (fsblkcnt_t) f_bfree;
    cstatvfs->f_bfree = cf_bfree;
    f_bavail = (*env)->GetLongField(env, x, fid5);
    fsblkcnt_t cf_bavail = (fsblkcnt_t) f_bavail;
    cstatvfs->f_bavail = cf_bavail;
    f_files = (*env)->GetLongField(env, x, fid6);
    fsfilcnt_t cf_files = (fsfilcnt_t) f_files;
    cstatvfs->f_files = cf_files;
    f_ffree = (*env)->GetLongField(env, x, fid7);
    fsfilcnt_t cf_ffree = (fsfilcnt_t) f_ffree;
    cstatvfs->f_ffree = cf_ffree;
    f_namemax = (*env)->GetLongField(env, x, fid9);
    unsigned long cf_namemax = (unsigned long) f_namemax;
    cstatvfs->f_namemax = cf_namemax;
    f_frsize = (*env)->GetLongField(env, x, fid10);
    unsigned long cf_frsize = (unsigned long) f_frsize;
    cstatvfs->f_frsize = cf_frsize;
    f_flag = (*env)->GetLongField(env, x, fid12);
    unsigned long cf_flag = (unsigned long) f_flag;
    cstatvfs->f_flag = cf_flag;
    f_favail = (*env)->GetLongField(env, x, fid13);
    unsigned long cf_favail = (unsigned long) f_favail;
    cstatvfs->f_favail = cf_favail;
    f_fsid = (*env)->GetLongField(env, x, fid14);
    unsigned long cf_fsid = (unsigned long) f_fsid;
    cstatvfs->f_fsid = cf_fsid;
    lp = (long)cstatvfs;
done:
    if(cstatvfs)
    {
        free(cstatvfs);
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return lp;
}

void dispstatvfs(struct statvfs *abc)
{
    if(JNI_DBG)
    {
        printf("=======DISPLAY========\n");
        printf("The f_bsize is: %lu\n", abc->f_bsize);
        printf("The f_blocks is: %lu\n", abc->f_blocks);
        printf("The f_bfree is: %lu\n", abc->f_bfree);
        printf("The f_bavail is: %lu\n", abc->f_bavail);
        printf("The f_files is: %lu\n", abc->f_files);
        printf("The f_ffree is: %lu\n", abc->f_ffree);
        printf("The f_fsid is: %lu\n", abc->f_fsid);
        printf("The f_namemax is: %lu\n", abc->f_namemax);
        printf("The f_frsize is: %lu\n", abc->f_frsize);
        printf("The f_flag is: %lu\n", abc->f_flag);
        printf("The f_favail is: %lu\n", abc->f_favail);
        printf("=======DISPLAY========\n");
        fflush(stdout);
    }
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_UseStatvfs  (JNIEnv *env, jobject obj, jlong jarg)
{
    struct statvfs *arg;
    arg = (struct statvfs *)jarg;
    dispstatvfs(arg);
}
#endif

/* pvfs_statfs */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsStatfs  (JNIEnv *env, jobject obj, jlong jarg, jstring path)
{
    if(JNI_DBG) printf("pvfsStatfs\n");
    int rc = 0;
    struct statfs *arg;
    arg = (struct statfs *)jarg;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    rc = pvfs_statfs(cpath, arg);
    if(rc < 0)
    {
        perror("pvfs_statfs error");
        rc = -1;
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_fstatfs */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFstatfs(JNIEnv *env, jobject obj, jlong jarg, int fd)
{
    if(JNI_DBG) printf("pvfsFstatfs\n");
    int rc = 0;
    struct statfs *arg;
    arg = (struct statfs *)jarg;
    rc = pvfs_fstatfs(fd, arg);
    if(rc < 0)
    {
        perror("pvfs_fstatfs error");
        rc = -1;
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_statfs64 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsStatfs64  (JNIEnv *env, jobject obj, jlong jarg, jstring path)
{
    if(JNI_DBG) printf("pvfsStatfs64\n");
    int rc = 0;
    struct statfs64 *arg;
    arg = (struct statfs64 *)jarg;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    rc = pvfs_statfs64(cpath, arg);
    if(rc < 0)
    {
        perror("pvfs_statfs64 error");
        rc = -1;
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_fstatfs64 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFstatfs64(JNIEnv *env, jobject obj, jlong jarg, int fd)
{
    if(JNI_DBG) printf("pvfsFstatfs64\n");
    int rc = 0;
    struct statfs64 *arg;
    arg = (struct statfs64 *)jarg;
    rc = pvfs_fstatfs64(fd, arg);
    if(rc < 0)
    {
        perror("pvfs_fstatfs64 error");
        rc = -1;
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_statvfs */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsStatvfs  (JNIEnv *env, jobject obj, jlong jarg, jstring path)
{
    if(JNI_DBG) printf("pvfsStatvfs\n");
    int rc = 0;
    struct statvfs *arg;
    arg = (struct statvfs *)jarg;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    rc = pvfs_statvfs(cpath, arg);
    if(rc < 0)
    {
        perror("pvfs_statvfs error");
        rc = -1;
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return rc;
}

/* pvfs_fstatvfs */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFstatvfs(JNIEnv *env, jobject obj, jlong jarg, int fd)
{
    if(JNI_DBG) printf("pvfsFstatvfs\n");
    int rc = 0;
    struct statvfs *arg;
    arg = (struct statvfs *)jarg;
    rc = pvfs_fstatvfs(fd, arg);
    if(rc < 0)
    {
        perror("pvfs_fstatvfs error");
        rc = -1;
    }
    fflush(stderr);
    if(JNI_DBG) fflush(stdout);
    return rc;
}
