#define _LARGEFILE64_SOURCE

/* Headers required by native routines. */
#include <features.h>
#include <pvfs2-types.h>
#include <stdlib.h>
#include <unistd.h>
#include <stdio.h>
#include <string.h>
#include <sys/uio.h>
#include <sys/types.h>
#include <sys/resource.h>
#include <stdint.h>
#include <sys/vfs.h>
#include <sys/statfs.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/mount.h>
#include <features.h>
#include <dirent.h>
#include <errno.h>

#include <pvfs2.h>
#include <pvfs2-usrint.h>

/* Header for JNI */
#include "jni.h"
/* Our header generated by "javah" */
#include "org_orangefs_usrint_PVFS2JNI.h"

#define JNI_DBG 1
#define NULL_OBJ ((jobject) 0)

/* Macro that helps print function info */
#define PFI if(JNI_DBG){printf("function={%s}\n", __func__);}

/* Macro that flushes stderr. stdout if JNI_DBG is enabled */
#define JNI_FLUSH if(JNI_DBG){fflush(stdout);} fflush(stderr);

#define GET_FIELD_ID(ENV, CLASS, FIELD_NAME, FIELD_TYPE)                       \
    ( (*(ENV))->GetFieldID((ENV), (CLASS), (FIELD_NAME), (FIELD_TYPE)) )

#define SET_LONG_FIELD(ENV, OBJ, FIELD_ID, VAL)                                \
    ( (*(ENV))->SetLongField((ENV), (OBJ), (FIELD_ID), (VAL)) )

#define SET_INT_FIELD(ENV, OBJ, FIELD_ID, VAL)                                 \
    ( (*(ENV))->SetIntField((ENV), (OBJ), (FIELD_ID), (VAL)) )

/* Forward Declarations */
void fill_error(void *ptr);
int fill_stat(JNIEnv *env, struct stat *ptr, jobject *inst);
int fill_statfs(JNIEnv *env, struct statfs *ptr, jobject *inst);
int fill_timeval(JNIEnv *env, struct timeval *ptr, jobject *inst);
int fill_utimbuf(JNIEnv *env, struct utimbuf *ptr, jobject *inst);

void fill_error(void *ptr)
{
    if(ptr)
    {
        free(ptr);
    }
    JNI_FLUSH
}

/* pvfs_open */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsOpen(
    JNIEnv *env,
    jobject obj,
    jstring path,
    int flags,
    int mode
)
{
    PFI
    int rc = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    if((flags & O_CREAT) == O_CREAT)
    {
        if(JNI_DBG) printf("\tO_CREAT detected!\n");
        rc = pvfs_open(cpath, flags, mode);
    }
    else
    {
        if(JNI_DBG) printf("\tNo O_CREAT detected\n");
        rc = pvfs_open(cpath, flags);
    }
    if(rc < 0)
    {
        perror("pvfs_open error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_open64 06/08/2012 */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsOpen64 (JNIEnv *env, jobject obj, jstring path, int flags)
{
    PFI
    int rc = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    rc = pvfs_open64(cpath, flags);
    if(rc < 0)
    {
        perror("pvfs_open64 error");
        rc -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_openat */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsOpenat (JNIEnv *env, jobject obj, int dirfd, jstring path, int flags)
{
    PFI
    int rc = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    rc = pvfs_openat(dirfd, cpath, flags);
    if(rc < 0)
    {
        perror("pvfs_openat error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_openat64 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsOpenat64 (JNIEnv *env, jobject obj, int dirfd, jstring path, int flags)
{
    PFI
    int rc = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    rc = pvfs_openat(dirfd, cpath, flags);
    if(rc < 0)
    {
        perror("pvfs_openat64 error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_creat */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsCreat(JNIEnv *env, jobject obj, jstring path, int mode)
{
    PFI
    int rc = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    rc = pvfs_creat(cpath, mode);
    if(rc < 0)
    {
        perror("pvfs_creat error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_creat64 */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsCreat64(JNIEnv *env, jobject obj, jstring path, int mode)
{
    PFI
    int rc = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    rc = pvfs_creat64(cpath, mode);
    if(rc < 0)
    {
        perror("pvfs_creat error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_unlink */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsUnlink(JNIEnv *env, jobject obj, jstring path)
{
    PFI
    int rc = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    errno = 0;
    rc = pvfs_unlink(cpath);
    if(rc == -1)
    {
        perror("pvfs_unlink error");
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_unlinkat */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsUnlinkat (JNIEnv *env, jobject obj, int dirfd, jstring path, int flags)
{
    PFI
    int rc = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    rc = pvfs_unlinkat(dirfd, cpath, flags);
    if(rc < 0)
    {
        perror("pvfs_unlinkat error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_rename */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsRename(JNIEnv *env,
    jobject obj,
    jstring oldpath,
    jstring newpath
)
{
    PFI
    int rc = 0;
    char coldpath[PVFS_PATH_MAX];
    int coldpath_len = (*env)->GetStringLength(env, oldpath);
    (*env)->GetStringUTFRegion(env, oldpath, 0, coldpath_len, coldpath);
    char cnewpath[PVFS_PATH_MAX];
    int cnewpath_len = (*env)->GetStringLength(env, newpath);
    (*env)->GetStringUTFRegion(env, newpath, 0, cnewpath_len, cnewpath);
    rc = pvfs_rename(coldpath, cnewpath);
    if(rc < 0)
    {
        perror("pvfs_rename error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_RenameAt */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsRenameAt(JNIEnv *env,
    jobject obj,
    int olddirfd,
    jstring oldpath,
    int newdirfd,
    jstring newpath
)
{
    PFI
    int rc = 0;
    char coldpath[PVFS_PATH_MAX];
    int coldpath_len = (*env)->GetStringLength(env, oldpath);
    (*env)->GetStringUTFRegion(env, oldpath, 0, coldpath_len, coldpath);
    char cnewpath[PVFS_PATH_MAX];
    int cnewpath_len = (*env)->GetStringLength(env, newpath);
    (*env)->GetStringUTFRegion(env, newpath, 0, cnewpath_len, cnewpath);
    rc = pvfs_renameat(olddirfd, coldpath, newdirfd, cnewpath);
    if(rc < 0)
    {
        perror("pvfs_renameat error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_close */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsClose(JNIEnv *env, jobject obj, int fd)
{
    PFI
    int rc = 0;
    rc = pvfs_close(fd);
    if(rc < 0)
    {
        perror("pvfs_close error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_flush */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFlush(JNIEnv *env, jobject obj, int fd)
{
    PFI
    int rc = 0;
    rc = pvfs_flush(fd);
    if(rc < 0)
    {
        perror("pvfs_close error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_prdwr64  (INCOMPLETE) */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsPrdwr64(JNIEnv *env, jobject obj, int fd, jlong buf, jlong count, jlong offset, int which)
{
    PFI
    size_t countc = (size_t) count;
    off64_t offsetc = (off64_t) offset;
    void* bufc = (void*) buf;
    int rc = 0;
    rc = pvfs_prdwr64(fd, bufc, countc, offsetc, which);
    if(rc < 0)
    {
        perror("pvfs_prdwr64 error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_lseek */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsLseek(JNIEnv *env, jobject obj, int fd, jlong offset, int whence)
{
    PFI
    off_t offsetc = (off_t) offset;
    off_t rc = pvfs_lseek(fd, offsetc, whence);
    jlong op = (jlong)rc;
    if(op < 0)
    {
        perror("pvfs_lseek error");
        op = -1;
    }
    JNI_FLUSH
    return op;
}

/* pvfs_lseek64 */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsLseek64(JNIEnv *env, jobject obj, int fd, jlong offset, int whence)
{
    PFI
    off_t offsetc = (off_t) offset;
    off_t rc = pvfs_lseek(fd, offsetc, whence);
    jlong op = (jlong)rc;
    if(op < 0)
    {
        perror("pvfs_lseek64 error");
        op = -1;
    }
    JNI_FLUSH
    return op;
}

/* pvfs_truncate */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsTruncate(JNIEnv *env, jobject obj, jstring path, jlong length)
{
    PFI
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    off_t clength = (off_t) length;
    int rc = pvfs_truncate(cpath, clength);
    if(rc < 0)
    {
        perror("pvfs_truncate error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_truncate64 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsTruncate64(JNIEnv *env, jobject obj, jstring path, jlong length)
{
    PFI
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    off64_t clength = (off64_t) length;
    int rc = 0;
    rc = pvfs_truncate64(cpath, clength);
    if(rc < 0)
    {
        perror("pvfs_truncate64 error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_fallocate */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFallocate(JNIEnv *env, jobject obj, int fd, jlong offset, jlong length)
{
    PFI
    off_t coffset = (off_t) offset;
    off_t clength = (off_t) length;
    int rc = 0;
    rc = pvfs_fallocate(fd, coffset, clength);
    if(rc < 0)
    {
        perror("pvfs_fallocate error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_ftruncate */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFtruncate(JNIEnv *env, jobject obj, int fd, jlong length)
{
    PFI
    off_t clength = (off_t) length;
    int rc = 0;
    rc = pvfs_ftruncate(fd, clength);
    if(rc < 0)
    {
        perror("pvfs_ftruncate error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_ftruncate64 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFtruncate64(JNIEnv *env, jobject obj, int fd, jlong length)
{
    PFI
    off64_t clength = (off64_t) length;
    int rc = 0;
    rc = pvfs_ftruncate(fd, clength);
    if(rc < 0)
    {
        perror("pvfs_ftruncate64 error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_dup */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsDup(JNIEnv *env, jobject obj, int oldfd)
{
    PFI
    int rc = 0;
    rc = pvfs_dup(oldfd);
    if(rc < 0)
    {
        perror("pvfs_dup error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_dup2 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsDup2(JNIEnv *env, jobject obj, int oldfd, int newfd)
{
    PFI
    int rc = 0;
    rc = pvfs_dup_descriptor(oldfd, newfd);
    if(rc < 0)
    {
        perror("pvfs_dup2 error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_chown */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsChown(JNIEnv *env, jobject obj, jstring path, jlong owner, jlong group)
{
    PFI
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    uid_t cowner = (uid_t) owner;
    gid_t cgroup = (gid_t) group;
    int rc = pvfs_chown(cpath, cowner, cgroup);
    if(rc < 0)
    {
        perror("pvfs_chown error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_fchown */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFchown(JNIEnv *env, jobject obj, int fd, jlong owner, jlong group)
{
    PFI
    uid_t cowner = (uid_t) owner;
    gid_t cgroup = (gid_t) group;
    int rc = pvfs_fchown(fd, cowner, cgroup);
    if(rc < 0)
    {
        perror("pvfs_fchown error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_fchownat */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFchownat(JNIEnv *env, jobject obj, int fd, jstring path, jlong owner, jlong group, int flag)
{
    PFI
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    uid_t cowner = (uid_t) owner;
    gid_t cgroup = (gid_t) group;
    int rc = pvfs_fchownat(fd, cpath, cowner, cgroup, flag);
    if(rc < 0)
    {
        perror("pvfs_fchownat error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_chmod */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsChmod(JNIEnv *env, jobject obj, jstring path, int mode)
{
    PFI
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    mode_t cmode = (mode_t) mode;
    int rc = pvfs_chmod(cpath, cmode);
    if(rc < 0)
    {
        perror("pvfs_chmod error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_fchmod */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFchmod(JNIEnv *env, jobject obj, int fd, int mode)
{
    PFI
    mode_t cmode = (mode_t) mode;
    int rc = pvfs_fchmod(fd, cmode);
    if(rc < 0)
    {
        perror("pvfs_fchmod error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_fchmodat */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFchmodat (JNIEnv *env, jobject obj, int fd, jstring path, int mode, int flag)
{
    PFI
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    mode_t cmode = (mode_t) mode;
    int rc = pvfs_fchmodat(fd, cpath, cmode, flag);
    if(rc < 0)
    {
        perror("pvfs_fchmodat error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_mkdir */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsMkdir (JNIEnv *env, jobject obj, jstring path, jint mode)
{
    PFI
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    int rc = 0;
    mode_t cmode = (mode_t) mode;
    rc = pvfs_mkdir(cpath, cmode);
    if(rc < 0)
    {
        perror("pvfs_mkdir error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_mkdirat */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsMkdirat (JNIEnv *env, jobject obj, int dirfd, jstring path, jint mode)
{
    PFI
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    int rc = 0;
    mode_t cmode = (mode_t) mode;
    rc = pvfs_mkdirat(dirfd, cpath, cmode);
    if(rc < 0)
    {
        perror("pvfs_mkdirat error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_rmdir */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsRmdir(JNIEnv *env, jobject obj, jstring path)
{
    PFI
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    int rc = 0;
    rc = pvfs_rmdir(cpath);
    if(rc < 0)
    {
        perror("pvfs_rmdir error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_readlink */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsReadlink (JNIEnv *env, jobject obj, jstring path, jstring buf, jlong bufsiz)
{
    PFI
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    long cbufsiz = (long) bufsiz;
    char cbuf[cbufsiz];
    int cbuf_len = (*env)->GetStringLength(env, buf);
    (*env)->GetStringUTFRegion(env, path, 0, cbuf_len, cbuf);
    size_t bufsize = (size_t) bufsiz;
    ssize_t rc = pvfs_readlink(cpath, cbuf, bufsize);
    jlong op = (jlong) rc;
    if(op < 0)
    {
        perror("pvfs_readlink error");
        op = -1;
    }
    JNI_FLUSH
    return op;
}

/* pvfs_readlinkat */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsReadlinkat (JNIEnv *env, jobject obj, int fd, jstring path, jstring buf, jlong bufsiz)
{
    PFI
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    long cbufsiz = (long) bufsiz;
    char cbuf[cbufsiz];
    int cbuf_len = (*env)->GetStringLength(env, buf);
    (*env)->GetStringUTFRegion(env, path, 0, cbuf_len, cbuf);
    size_t bufsize = (size_t) bufsiz;
    ssize_t rc = pvfs_readlinkat(fd, cpath, cbuf, bufsize);
    jlong op = (jlong) rc;
    if(op < 0)
    {
        perror("pvfs_readlinkat error");
        op = -1;
    }
    JNI_FLUSH
    return op;
}

/* pvfs_symlink */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsSymlink(JNIEnv *env, jobject obj, jstring oldpath, jstring newpath)
{
    PFI
    int rc = 0;
    char coldpath[PVFS_PATH_MAX];
    int coldpath_len = (*env)->GetStringLength(env, oldpath);
    (*env)->GetStringUTFRegion(env, oldpath, 0, coldpath_len, coldpath);
    char cnewpath[PVFS_PATH_MAX];
    int cnewpath_len = (*env)->GetStringLength(env, newpath);
    (*env)->GetStringUTFRegion(env, newpath, 0, cnewpath_len, cnewpath);
    rc = pvfs_symlink(coldpath, cnewpath);
    if(rc < 0)
    {
        perror("pvfs_symlink error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_symlinkat */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsSymlinkat(JNIEnv *env, jobject obj, jstring oldpath, int newdirfd, jstring newpath)
{
    PFI
    int rc = 0;
    char coldpath[PVFS_PATH_MAX];
    int coldpath_len = (*env)->GetStringLength(env, oldpath);
    (*env)->GetStringUTFRegion(env, oldpath, 0, coldpath_len, coldpath);
    char cnewpath[PVFS_PATH_MAX];
    int cnewpath_len = (*env)->GetStringLength(env, newpath);
    (*env)->GetStringUTFRegion(env, newpath, 0, cnewpath_len, cnewpath);
    rc = pvfs_symlinkat(coldpath, newdirfd, cnewpath);
    if(rc < 0)
    {
        perror("pvfs_symlinkat error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_link */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsLink(JNIEnv *env, jobject obj, jstring oldpath, jstring newpath)
{
    PFI
    int rc = 0;
    char coldpath[PVFS_PATH_MAX];
    int coldpath_len = (*env)->GetStringLength(env, oldpath);
    (*env)->GetStringUTFRegion(env, oldpath, 0, coldpath_len, coldpath);
    char cnewpath[PVFS_PATH_MAX];
    int cnewpath_len = (*env)->GetStringLength(env, newpath);
    (*env)->GetStringUTFRegion(env, newpath, 0, cnewpath_len, cnewpath);
    rc = pvfs_link(coldpath, cnewpath);
    if(rc < 0)
    {
        perror("pvfs_link error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_linkat */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsLinkat(JNIEnv *env, jobject obj, int olddirfd, jstring oldpath, int newdirfd, jstring newpath, int flags)
{
    PFI
    int rc = 0;
    char coldpath[PVFS_PATH_MAX];
    int coldpath_len = (*env)->GetStringLength(env, oldpath);
    (*env)->GetStringUTFRegion(env, oldpath, 0, coldpath_len, coldpath);
    char cnewpath[PVFS_PATH_MAX];
    int cnewpath_len = (*env)->GetStringLength(env, newpath);
    (*env)->GetStringUTFRegion(env, newpath, 0, cnewpath_len, cnewpath);
    rc = pvfs_linkat(olddirfd, coldpath, newdirfd, cnewpath, flags);
    if(rc < 0)
    {
        perror("pvfs_linkat error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_access */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsAccess (JNIEnv *env, jobject obj, jstring path, int mode)
{
    PFI
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    int rc = pvfs_access(cpath, mode);
    if(rc < 0)
    {
        perror("pvfs_access error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_faccessat */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFaccessat (JNIEnv *env, jobject obj, int fd, jstring path, int mode, int flags)
{
    PFI
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    int rc = pvfs_faccessat(fd, cpath, mode, flags);
    if(rc < 0)
    {
        perror("pvfs_faccessat error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_flock */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFlock (JNIEnv *env, jobject obj, int fd, int op)
{
    PFI
    int rc = pvfs_flock(fd, op);
    if(rc < 0)
    {
        perror("pvfs_flock error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_fcntl */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFcntl  (JNIEnv *env, jobject obj, int fd, int cmd)
{
    PFI
    int rc = pvfs_fcntl(fd, cmd);
    if(rc < 0)
    {
        perror("pvfs_fcntl error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_fsync */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFsync  (JNIEnv *env, jobject obj, int fd)
{
    PFI
    int rc = pvfs_fsync(fd);
    if(rc < 0)
    {
        perror("pvfs_fsync error");
        fflush(stdout);
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_fdatasync */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFdatasync  (JNIEnv *env, jobject obj, int fd)
{
    PFI
    int rc = pvfs_fdatasync(fd);
    if(rc < 0)
    {
        perror("pvfs_fdatasync error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_fadvise */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFadvise  (JNIEnv *env, jobject obj, int fd, jlong offset, jlong len, int advice)
{
    PFI
    off_t coffset = (off_t) offset;
    off_t clen = (off_t) clen;
    int rc = pvfs_fadvise(fd, coffset, clen, advice);
    if(rc < 0)
    {
        perror("pvfs_fadvise error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_fadvise64 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFadvise64  (JNIEnv *env, jobject obj, int fd, jlong offset, jlong len, int advice)
{
    PFI
    off_t coffset = (off64_t) offset;
    off_t clen = (off64_t) clen;
    int rc = pvfs_fadvise64(fd, coffset, clen, advice);
    if(rc < 0)
    {
        perror("pvfs_fadvise64 error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_mknod */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsMknod  (JNIEnv *env, jobject obj, jstring path, int mode, int dev)
{
    PFI
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    mode_t cmode = (mode_t) mode;
    dev_t cdev = (dev_t) dev;
    int rc = pvfs_mknod(cpath, cmode, cdev);
    if(rc < 0)
    {
        perror("pvfs_mknod error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_mknodat */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsMknodat (JNIEnv *env, jobject obj, int dirfd, jstring path, int mode, int dev)
{
    PFI
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    mode_t cmode = (mode_t) mode;
    dev_t cdev = (dev_t) dev;
    int rc = pvfs_mknodat(dirfd, cpath, cmode, cdev);
    if(rc < 0)
    {
        perror("pvfs_mknodat error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_chdir */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsChdir  (JNIEnv *env, jobject obj, jstring path)
{
    PFI
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    int rc = pvfs_chdir(cpath);
    if(rc < 0)
    {
        perror("pvfs_chdir error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_fchdir */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFchdir  (JNIEnv *env, jobject obj, int fd)
{
    PFI
    int rc = pvfs_fchdir(fd);
    if(rc < 0)
    {
        perror("pvfs_fchdir error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_umask */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsUmask  (JNIEnv *env, jobject obj, int mask)
{
    PFI
    mode_t cmask = (mode_t) mask;
    mode_t rc = pvfs_umask(mask);
    if(rc < 0)
    {
        perror("pvfs_umask error");
        rc = -1;
    }
    JNI_FLUSH
    return (int) rc;
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsRead(JNIEnv *env, jobject obj, int fd, jbyteArray buf, jlong count)
{
    PFI
    ssize_t rc = 0;
    jboolean is_copy;
    jbyte * buffer = (*env)->GetByteArrayElements(env, buf, &is_copy);
    if(JNI_DBG)
    {
        printf("\tfd = %d\n", fd);
        printf("\tcount = %lu\n", (uint64_t) count);
        is_copy == JNI_TRUE ? printf("\tbuf is_copy\n") : printf("\tbuf !is_copy\n");
    }
    if(!buffer)
    {
        perror("GetByteArrayElements");
        errno = EFAULT;
        rc = -1;
        goto done;
    }
    rc = pvfs_read(fd, (void *) buffer, (size_t) count);
    if(rc < 0)
    {
        perror("jni pvfs_read");
        rc = -1;
        goto done;
    }
    if(rc > 0)
    {
        if(JNI_DBG) printf("\tread %lld bytes\n", (long long int) rc);
    }
done:
    /* copy back and free the buffer using 0 */
    (*env)->ReleaseByteArrayElements(env, buf, buffer, 0);
    JNI_FLUSH
    return (jlong) rc;
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsPread(JNIEnv *env, jobject obj, int fd, jbyteArray buf, jlong count, jlong offset)
{
    PFI
    ssize_t rc = 0;
    jboolean is_copy;
    jbyte * buffer = (*env)->GetByteArrayElements(env, buf, &is_copy);
    if(JNI_DBG)
    {
        printf("pvfsPread\n");
        printf("\tfd = %d\n", fd);
        printf("\tcount = %lu\n", (uint64_t) count);
        printf("\toffset = %lu\n", (uint64_t) offset);
        is_copy == JNI_TRUE ? printf("\tbuf is_copy\n") : printf("\tbuf !is_copy\n");
    }
    if(!buffer)
    {
        perror("GetByteArrayElements");
        errno = EFAULT;
        rc = -1;
        goto done;
    }
    rc = pvfs_pread(fd, (void *) buffer, (size_t) count, (off_t) offset);
    if(rc < 0)
    {
        perror("jni pvfs_pread");
    }
    else
    {
        if(JNI_DBG) printf("\tread %lld bytes\n", (long long int) rc);
    }
done:
    /* copy back and free the buffer using 0 */
    (*env)->ReleaseByteArrayElements(env, buf, buffer, 0);
    JNI_FLUSH
    return (jlong) rc;
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsPread64(JNIEnv *env, jobject obj, int fd, jbyteArray buf, jlong count, jlong offset)
{
    PFI
    ssize_t rc = 0;
    jboolean is_copy;
    jbyte * buffer = (*env)->GetByteArrayElements(env, buf, &is_copy);
    if(JNI_DBG)
    {
        printf("pvfsPread64\n");
        printf("\tfd = %d\n", fd);
        printf("\tcount = %lu\n", (uint64_t) count);
        printf("\toffset = %lu\n", (uint64_t) offset);
        is_copy == JNI_TRUE ? printf("\tbuf is_copy\n") : printf("\tbuf !is_copy\n");
    }
    if(!buffer)
    {
        perror("GetByteArrayElements");
        errno = EFAULT;
        rc = -1;
        goto done;
    }
    rc = pvfs_pread64(fd, (void *) buffer, (size_t) count, (off64_t) offset);
    if(rc < 0)
    {
        perror("jni pvfs_pread64");
    }
    else
    {
        printf("\tread %lld bytes\n", (long long int) rc);
    }
done:
    /* copy back and free the buffer using 0 */
    (*env)->ReleaseByteArrayElements(env, buf, buffer, 0);
    JNI_FLUSH
    return (jlong) rc;
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsWrite(JNIEnv *env, jobject obj, int fd, jbyteArray buf, jlong count)
{
    PFI
    ssize_t rc = 0;
    jboolean is_copy;
    jbyte * buffer = (*env)->GetByteArrayElements(env, buf, &is_copy);
    if(JNI_DBG)
    {
        printf("pvfsWrite\n");
        printf("\tfd = %d\n", fd);
        printf("\tcount = %lu\n", (uint64_t) count);
        is_copy == JNI_TRUE ? printf("\tbuf is_copy\n") :
            printf("\tbuf !is_copy\n");
    }
    if(!buffer)
    {
        perror("GetByteArrayElements");
        errno = EFAULT;
        rc = -1;
        goto done;
    }
    rc = pvfs_write(fd, (void *) buffer, (size_t) count);
    if(rc < 0)
    {
        perror("jni pvfs_write");
    }
    if(rc > 0)
    {
        printf("\twrote %lld bytes\n", (long long int) rc);
    }
done:
    /* free the buffer without copying back the possible changes in buffer
     * using JNI_ABORT
     */
    (*env)->ReleaseByteArrayElements(env, buf, buffer, JNI_ABORT);
    JNI_FLUSH
    return (jlong) rc;
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsPwrite(JNIEnv *env, jobject obj, int fd, jbyteArray buf, jlong count, jlong offset)
{
    PFI
    ssize_t rc = 0;
    jboolean is_copy;
    jbyte * buffer = (*env)->GetByteArrayElements(env, buf, &is_copy);
    if(JNI_DBG)
    {
        printf("pvfsPwrite\n");
        printf("\tfd = %d\n", fd);
        printf("\tcount = %lu\n", (uint64_t) count);
        printf("\toffset = %lu\n", (uint64_t) offset);
        is_copy == JNI_TRUE ? printf("\tbuf is_copy\n") :
            printf("\tbuf !is_copy\n");
    }
    if(!buffer)
    {
        perror("GetByteArrayElements");
        errno = EFAULT;
        rc = -1;
    }
    rc = pvfs_pwrite(fd, (void *) buffer, (size_t) count, (off_t) offset);
    if(rc < 0)
    {
        perror("jni pvfs_pwrite");
    }
    else
    {
        if(JNI_DBG) printf("\twrote %lld bytes\n", (long long int) rc);
    }
done:
    /** free the buffer without copying back the possible changes in buffer
      * using JNI_ABORT
      */
    (*env)->ReleaseByteArrayElements(env, buf, buffer, JNI_ABORT);
    JNI_FLUSH
    return (jlong) rc;
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsPwrite64(JNIEnv *env, jobject obj, int fd, jbyteArray buf, jlong count, jlong offset)
{
    PFI
    ssize_t rc = 0;
    jboolean is_copy;
    jbyte * buffer = (*env)->GetByteArrayElements(env, buf, &is_copy);
    if(JNI_DBG)
    {
        printf("\tfd = %d\n", fd);
        printf("\tcount = %lu\n", (uint64_t) count);
        printf("\toffset = %lu\n", (uint64_t) offset);
        is_copy == JNI_TRUE ? printf("\tbuf is_copy\n") :
            printf("\tbuf !is_copy\n");
    }
    if(!buffer)
    {
        perror("GetByteArrayElements");
        errno = EFAULT;
        rc = -1;
        goto done;
    }
    rc = pvfs_pwrite64(fd, (void *) buffer, (size_t) count, (off_t) offset);
    if(rc < 0)
    {
        perror("jni pvfs_pwrite64");
    }
    else
    {
        if(JNI_DBG) printf("\twrote %lld bytes\n", (long long int) rc);
    }
done:
    /** Free the buffer without copying back the possible changes in buffer
     * using JNI_ABORT
     */
    (*env)->ReleaseByteArrayElements(env, buf, buffer, JNI_ABORT);
    JNI_FLUSH
    return (jlong) rc;
}

/* Note: Removed readv and writev ... */

/* Returns non-zero (true) if the supplied mode corresponds to a directory. */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2JNI_isDir(JNIEnv *env, jobject obj, int mode)
{
    PFI
    if(JNI_DBG) printf("mode = %d\n", mode);
    fflush(stdout);
    return S_ISDIR(mode);
}

/* Convert allocated struct to an instance of our PVFS2JNI$Stat Class */
int fill_stat(JNIEnv *env, struct stat *ptr, jobject *inst)
{
    int num_fields = 13;
    char *field_names[] = {
        "st_dev", "st_ino", "st_mode",
        "st_nlink", "st_uid", "st_gid",
        "st_rdev", "st_size", "st_blksize",
        "st_blocks", "st_atime", "st_mtime", "st_ctime"};
    char *field_types[] = {
        "J", "J", "I",
        "I", "J", "J",
        "J", "J", "I",
        "J", "J", "J", "J"};
    jfieldID fids[num_fields];
    char *cls_name = "org/orangefs/usrint/PVFS2JNI$Stat";
    jclass cls = (*env)->FindClass(env, cls_name);
    if(!cls)
    {
        fprintf(stderr, "invalid class: %s\n", cls_name);
        fill_error((void *) ptr);
        return -1;
    }
    int fid_index = 0;
    for(; fid_index < num_fields; fid_index++)
    {
        fids[fid_index] = GET_FIELD_ID(env, cls, 
            field_names[fid_index], field_types[fid_index]);
        if(!fids[fid_index])
        {
            fprintf(stderr, "invalid field requested: %s\n", field_names[fid_index]);
            fill_error((void *) ptr);
            return -1;
        }
    }
    *inst = (*env)->AllocObject(env, cls);
    /* Load object with data from structure using
     * constructor or set methods.
     */
    SET_LONG_FIELD(env, *inst, fids[0],ptr->st_dev);
    SET_LONG_FIELD(env, *inst, fids[1],ptr->st_ino);
    SET_INT_FIELD(env, *inst, fids[2],ptr->st_mode);
    SET_INT_FIELD(env, *inst, fids[3],ptr->st_nlink);
    SET_LONG_FIELD(env, *inst, fids[4],ptr->st_uid);
    SET_LONG_FIELD(env, *inst, fids[5],ptr->st_gid);
    SET_LONG_FIELD(env, *inst, fids[6],ptr->st_rdev);
    SET_LONG_FIELD(env, *inst, fids[7],ptr->st_size);
    SET_INT_FIELD(env, *inst, fids[8],ptr->st_blksize);
    SET_LONG_FIELD(env, *inst, fids[9],ptr->st_blocks);
    SET_LONG_FIELD(env, *inst, fids[10],ptr->st_atime);
    SET_LONG_FIELD(env, *inst, fids[11],ptr->st_mtime);
    SET_LONG_FIELD(env, *inst, fids[12],ptr->st_ctime);
    /* Free the space allocated for the stat struct and
     * return an instance of PVFS2JNI$Stat.
     */
    JNI_FLUSH
    free(ptr);
    return 0;
}

/* pvfs_stat */
JNIEXPORT jobject JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsStat(JNIEnv *env, jobject obj, jstring path)
{
    PFI
    struct stat *ptr = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    ptr = (struct stat *) calloc(1, sizeof(struct stat));
    if(!ptr)
    {
        fprintf(stderr, "calloc couldn't allocate memory for struct stat!\n");
        fill_error((void *) ptr);
        goto err;
    }
    int rc = pvfs_stat(cpath, ptr);
    if(rc != 0)
    {
        perror("pvfs_stat error");
        fill_error((void *) ptr);
        goto err;
    }
    //TODO remove later
    else 
    {
        printf("pvfs_stat successful on %s\n", cpath);
    }

    jobject stat_obj;
    if(fill_stat(env, ptr, &stat_obj) == 0)
    {
        JNI_FLUSH
        return stat_obj;
    }
err:
    return (jobject) 0;
}

/* pvfs_fstat */
JNIEXPORT jobject JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFstat(JNIEnv *env, jobject obj, int fd)
{
    PFI
    struct stat *ptr = 0;
    ptr = (struct stat *) calloc(1, sizeof(struct stat));
    if(!ptr)
    {
        fprintf(stderr, "couldn't allocate memory for struct stat!\n");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    int rc = pvfs_fstat(fd, ptr);
    if(rc != 0)
    {
        perror("pvfs_fstat error");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    jobject stat_obj;
    if(fill_stat(env, ptr, &stat_obj) == 0)
    {
        JNI_FLUSH;
        return stat_obj;
    }
    JNI_FLUSH
    return NULL_OBJ;
}

/* pvfs_Fstatat */
JNIEXPORT jobject JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFstatat(JNIEnv *env, jobject obj, int fd, jstring path, int flag)
{
    PFI
    struct stat *ptr = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    ptr = (struct stat *) calloc(1, sizeof(struct stat));
    if(!ptr)
    {
        fprintf(stderr, "couldn't allocate memory for struct stat!\n");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    int rc = pvfs_fstatat(fd,cpath, ptr,flag);
    if(rc < 0)
    {
        perror("pvfs_fstatat error");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    jobject stat_obj;
    if(fill_stat(env, ptr, &stat_obj) == 0)
    {
        JNI_FLUSH;
        return stat_obj;
    }
    JNI_FLUSH
    return NULL_OBJ;
}

/* pvfs_lstat */
JNIEXPORT jobject JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsLstat(JNIEnv *env, jobject obj, jstring path)
{
    PFI
    struct stat *ptr = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    ptr = (struct stat *) calloc(1, sizeof(struct stat));
    if(!ptr)
    {
        fprintf(stderr, "couldn't allocate memory for struct stat!\n");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    int rc = pvfs_lstat(cpath, ptr);
    if(rc < 0)
    {
        perror("pvfs_lstat error");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    jobject stat_obj;
    if(fill_stat(env, ptr, &stat_obj) == 0)
    {
        JNI_FLUSH;
        return stat_obj;
    }
    JNI_FLUSH
    return NULL_OBJ;
}

/* TODO */
#if 0
/* pvfs_stat64 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsStat64  (JNIEnv *env, jobject obj, jlong jarg, jstring path)
{
    PFI
    struct stat64 *arg;
    arg = (struct stat64 *)jarg;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    int rc = pvfs_stat64(cpath, arg);
    if(rc < 0)
    {
        perror("pvfs_stat64 error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_Fstat64 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFstat64  (JNIEnv *env, jobject obj, jlong jarg, int fd)
{
    PFI
    struct stat64 *arg;
    arg = (struct stat64 *)jarg;
    int rc = pvfs_fstat64(fd, arg);
    if(rc < 0)
    {
        perror("pvfs_fstat64 error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_Fstatat64 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFstatat64  (JNIEnv *env, jobject obj, jlong jarg, int fd, jstring path, int flag)
{
    PFI
    struct stat64 *arg;
    arg = (struct stat64 *)jarg;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    int rc = pvfs_fstatat64(fd, cpath, arg, flag);
    if(rc < 0)
    {
        perror("pvfs_fstatat64 error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_lstat64 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsLstat64  (JNIEnv *env, jobject obj, jlong jarg, jstring path)
{
    PFI
    struct stat64 *arg;
    arg = (struct stat64 *)jarg;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    int rc = pvfs_lstat64(cpath, arg);
    if(rc < 0)
    {
        perror("pvfs_lstat64 error");
        rc = -1;
    }
    return rc;
}


/* pvfs_readdir */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsReaddir  (JNIEnv *env, jobject obj, jlong jarg, int fd, int count)
{
    PFI
    int rc = 0;
    struct dirent *arg;
    arg = (struct dirent *)jarg;
    unsigned int cfd = (unsigned int) fd;
    unsigned int ccount = (unsigned int) count;
    rc = pvfs_readdir(cfd, arg, ccount);
    if(rc < 0)
    {
        perror("pvfs_readdir error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}


/* pvfs_getdents */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsGetdents  (JNIEnv *env, jobject obj, jlong jarg, int fd, int size)
{
    PFI
    int rc = 0;
    struct dirent *arg;
    arg = (struct dirent *)jarg;
    unsigned int cfd = (unsigned int) fd;
    unsigned int csize = (unsigned int) size;
    rc = pvfs_getdents(cfd, arg, csize);
    if(rc < 0)
    {
        perror("pvfs_getdents error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_getdents64 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsGetdents64  (JNIEnv *env, jobject obj, jlong jarg, int fd, int size)
{
    PFI
    int rc = 0;
    struct dirent64 *arg;
    arg = (struct dirent64 *)jarg;
    unsigned int cfd = (unsigned int) fd;
    unsigned int csize = (unsigned int) size;
    rc = pvfs_getdents64(cfd, arg, csize);
    if(rc < 0)
    {
        perror("pvfs_getdents64 error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}
#endif

/* fill_timeval */
int fill_timeval(JNIEnv *env, struct timeval *ptr, jobject *inst)
{
    int num_fields = 2;
    char *field_names[] = {
        "tv_sec", "tv_usec"};
    char *field_types[] = {
        "[J","[J"};
    jfieldID fids[num_fields];
    char *cls_name = "org/orangefs/usrint/PVFS2JNI$Timeval";
    jclass cls = (*env)->FindClass(env, cls_name);
    if(!cls)
    {
        fprintf(stderr, "invalid class: %s\n", cls_name);
        fill_error((void *) ptr);
        return -1;
    }
    int fid_index = 0;
    for(; fid_index < num_fields; fid_index++)
    {
        fids[fid_index] = GET_FIELD_ID(env, cls, 
            field_names[fid_index], field_types[fid_index]);
        if(!fids[fid_index])
        {
            fprintf(stderr, "invalid field requested: %s\n", field_names[fid_index]);
            fill_error((void *) ptr);
            return -1;
        }
    }
    jmethodID mid = (*env)->GetMethodID(env,cls, "<init>", "()V");
    *inst = (*env)->NewObject(env,cls,mid);
    jlongArray ar;
    jlongArray ar1;
    int jval;
    jlong cbuf[2];
    jlong cbuf1[2];
    for(jval = 0; jval < 2; jval++)
    {
        cbuf[jval]=ptr[jval].tv_sec;
    }
    for(jval = 0; jval < 2; jval++)
    {
        cbuf1[jval]=ptr[jval].tv_usec;
    }
    //printf("cbuf[0]=%ld",cbuf[0]);
    //printf("cbuf[0]=%ld",cbuf[]);
    ar = (*env)->GetObjectField(env, *inst , fids[0]);
    (*env)->SetLongArrayRegion(env, ar, 0, 2, cbuf);
    ar1 = (*env)->GetObjectField(env, *inst , fids[1]);
    (*env)->SetLongArrayRegion(env, ar1, 0, 2, cbuf1);
    /* Free the space allocated for the stat struct and
     return an instance of PVFS2JNI$Timeval. */
    JNI_FLUSH
    free(ptr);
    return 0;
}

/* pvfs_utimes */
JNIEXPORT jobject JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsUtimes (JNIEnv *env, jobject obj, jstring path)
{
    PFI
    struct timeval *ptr = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    ptr = (struct timeval *) calloc(1, 2 * sizeof(struct timeval));
    if(!ptr)
    {
        fprintf(stderr, "couldn't allocate memory for struct timeval!\n");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    int rc = pvfs_utimes(cpath, ptr);
    if(rc < 0)
    {
        perror("pvfs_utimes error");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    jobject timeval_obj;
    if(fill_timeval(env, ptr, &timeval_obj) == 0)
    {
        JNI_FLUSH;
        return timeval_obj;
    }
    JNI_FLUSH
    return NULL_OBJ; 
}

/* pvfs_futimes */
JNIEXPORT jobject JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFutimes (JNIEnv *env, jobject obj, int fd)
{
    PFI
    struct timeval *ptr = 0;
    ptr = (struct timeval *) calloc(1, 2 * sizeof(struct timeval));
    if(!ptr)
    {
        fprintf(stderr, "couldn't allocate memory for struct timeval!\n");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    int rc = pvfs_futimes(fd, ptr);
    if(rc < 0)
    {
        perror("pvfs_futimes error");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    jobject timeval_obj;
    if(fill_timeval(env, ptr, &timeval_obj) == 0)
    {
        JNI_FLUSH;
        return timeval_obj;
    }
    JNI_FLUSH
    return NULL_OBJ; 
}

/* pvfs_futimesat */
JNIEXPORT jobject JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFutimesat (JNIEnv *env, jobject obj, int dirfd, jstring path)
{
    PFI
    struct timeval *ptr = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    ptr = (struct timeval *) calloc(1, 2 * sizeof(struct timeval));
    if(!ptr)
    {
        fprintf(stderr, "couldn't allocate memory for struct timeval!\n");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    int rc = pvfs_futimesat(dirfd,cpath, ptr);
    if(rc < 0)
    {
        perror("pvfs_futimesat error");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    jobject timeval_obj;
    if(fill_timeval(env, ptr, &timeval_obj) == 0)
    {
        JNI_FLUSH;
        return timeval_obj;
    }
    JNI_FLUSH
    return NULL_OBJ;  
}

/* fill_utimbuf */
int fill_utimbuf(JNIEnv *env, struct utimbuf *ptr, jobject *inst)
{
    int num_fields = 2;
    char *field_names[] = {
        "actime", "modtime"};
    char *field_types[] = {
        "J", "J"};
    jfieldID fids[num_fields];
    char *cls_name = "org/orangefs/usrint/PVFS2JNI$Utimbuf";
    jclass cls = (*env)->FindClass(env, cls_name);
    if(!cls)
    {
        fprintf(stderr, "invalid class: %s\n", cls_name);
        fill_error((void *) ptr);
        return -1;
    }
    int fid_index = 0;
    for(; fid_index < num_fields; fid_index++)
    {
        fids[fid_index] = GET_FIELD_ID(env, cls, 
            field_names[fid_index], field_types[fid_index]);
        if(!fids[fid_index])
        {
            fprintf(stderr, "invalid field requested: %s\n", field_names[fid_index]);
            fill_error((void *) ptr);
            return -1;
        }
    }
    *inst = (*env)->AllocObject(env, cls);
    /* Load object with data from structure using
     * constructor or set methods.
     */
    SET_LONG_FIELD(env, *inst, fids[0],ptr->actime);
    SET_LONG_FIELD(env, *inst, fids[1],ptr->modtime);
    /* Free the space allocated for the stat struct and
     * return an instance of PVFS2JNI$Stat.
     */
    JNI_FLUSH
    free(ptr);
    return 0;
}

/* pvfs_utime */
JNIEXPORT jobject JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsUtime(JNIEnv *env, jobject obj, jstring path)
{
    PFI
    struct utimbuf *ptr = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    ptr = (struct utimbuf *) calloc(1, sizeof(struct utimbuf));
    if(!ptr)
    {
        fprintf(stderr, "couldn't allocate memory for struct utimbuf!\n");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    int rc = pvfs_utime(cpath, ptr);
    if(rc < 0)
    {
        perror("pvfs_utime error");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    jobject utimbuf_obj;
    if(fill_utimbuf(env, ptr, &utimbuf_obj) == 0)
    {
        JNI_FLUSH;
        return utimbuf_obj;
    }
    JNI_FLUSH
    return NULL_OBJ;
}

/* pvfs_listxattr */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsListxattr (JNIEnv *env, jobject obj, jstring path, jstring list, jlong size)
{
    PFI
    long rc = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    char clist[PVFS_MAX_XATTR_LISTLEN];
    int clist_len = (*env)->GetStringLength(env, list);
    (*env)->GetStringUTFRegion(env, list, 0, clist_len, clist);
    size_t csize = (size_t) size;
    rc = pvfs_listxattr(cpath, clist, csize);
    if(rc < 0)
    {
        perror("pvfs_listxattr error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_llistxattr */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsLlistxattr (JNIEnv *env, jobject obj, jstring path, jstring list, jlong size)
{
    PFI
    long rc = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    char clist[PVFS_MAX_XATTR_LISTLEN];
    int clist_len = (*env)->GetStringLength(env, list);
    (*env)->GetStringUTFRegion(env, list, 0, clist_len, clist);
    size_t csize = (size_t) size;
    rc = pvfs_llistxattr(cpath, clist, csize);
    if(rc < 0)
    {
        perror("pvfs_llistxattr error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_flistxattr */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFlistxattr (JNIEnv *env, jobject obj, int fd, jstring list, jlong size)
{
    PFI
    long rc = 0;
    char clist[PVFS_MAX_XATTR_LISTLEN];
    int clist_len = (*env)->GetStringLength(env, list);
    (*env)->GetStringUTFRegion(env, list, 0, clist_len, clist);
    size_t csize = (size_t) size;
    rc = pvfs_flistxattr(fd, clist, csize);
    if(rc < 0)
    {
        perror("pvfs_flistxattr error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_removexattr */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsRemovexattr(JNIEnv *env, jobject obj, jstring path, jstring name)
{
    PFI
    int rc = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    char cname[PVFS_NAME_MAX];
    int cname_len = (*env)->GetStringLength(env, name);
    (*env)->GetStringUTFRegion(env, name, 0, cname_len, cname);
    rc = pvfs_removexattr(cpath, cname);
    if(rc < 0)
    {
        perror("pvfs_removexattr error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_lremovexattr */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsLremovexattr(JNIEnv *env, jobject obj, jstring path, jstring name)
{
    PFI
    int rc = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    char cname[PVFS_NAME_MAX];
    int cname_len = (*env)->GetStringLength(env, name);
    (*env)->GetStringUTFRegion(env, name, 0, cname_len, cname);
    rc = pvfs_lremovexattr(cpath, cname);
    if(rc < 0)
    {
        perror("pvfs_Lremovexattr error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_fremovexattr */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFremovexattr(JNIEnv *env, jobject obj, int fd, jstring name)
{
    PFI
    int rc = 0;
    char cname[PVFS_NAME_MAX];
    int cname_len = (*env)->GetStringLength(env, name);
    (*env)->GetStringUTFRegion(env, name, 0, cname_len, cname);
    rc = pvfs_fremovexattr(fd, cname);
    if(rc < 0)
    {
        perror("pvfs_fremovexattr error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_getumask */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsGetumask(JNIEnv *env, jobject obj)
{
    PFI
    mode_t rc = pvfs_getumask();
    long ret = (long) rc;
    JNI_FLUSH
    return ret;
}

/* pvfs_getdtablesize */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsGetdtablesize(JNIEnv *env, jobject obj)
{
    PFI
    int rc = pvfs_getdtablesize();
    JNI_FLUSH
    return rc;
}

/* pvfs_sync */
JNIEXPORT void JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsSync(JNIEnv *env, jobject obj)
{
    PFI
    pvfs_sync();
    JNI_FLUSH
    return;
}

/* Convert allocated struct to an instance of our PVFS2JNI$Statfs Class */
int fill_statfs(JNIEnv *env, struct statfs *ptr, jobject *inst)
{
    int num_fields = 12;
    char *field_names[] = {
        "f_type", "f_bsize", "f_blocks",
        "f_bfree", "f_bavail", "f_files",
        "f_ffree", "f_flags", "f_namelen",
        "f_frsize","f_spare","f_fsid"};
    char *field_types[] = {
        "J", "J", "J",
        "J", "J", "J",
        "J", "J", "J",
        "J","[J","[I"};
    jfieldID fids[num_fields];
    char *cls_name = "org/orangefs/usrint/PVFS2JNI$Statfs";
    jclass cls = (*env)->FindClass(env, cls_name);
    if(!cls)
    {
        fprintf(stderr, "invalid class: %s\n", cls_name);
        fill_error((void *) ptr);
        return -1;
    }
    int fid_index = 0;
    for(; fid_index < num_fields; fid_index++)
    {
        fids[fid_index] = GET_FIELD_ID(env, cls, 
            field_names[fid_index], field_types[fid_index]);
        if(!fids[fid_index])
        {
            fprintf(stderr, "invalid field requested: %s\n", field_names[fid_index]);
            fill_error((void *) ptr);
            return -1;
        }
    }
    
    jmethodID mid = (*env)->GetMethodID(env,cls, "<init>", "()V");
    *inst = (*env)->NewObject(env,cls,mid);
    jlongArray ar;
    jlongArray ar1;
    int jval;
    jlong cbuf[5];
    jlong cbuf1[2];
    for(jval = 0; jval < 5; jval++)
    {
        cbuf[jval]=ptr->f_spare[jval];
        
    }
    for(jval = 0; jval < 2; jval++)
    {
        cbuf1[jval]=ptr->f_fsid.__val[jval];
        
    }
    /* Load object with data from structure using
     * constructor or set methods.
     */
    SET_LONG_FIELD(env, *inst, fids[0],ptr->f_type);
    SET_LONG_FIELD(env, *inst, fids[1],ptr->f_bsize);
    SET_LONG_FIELD(env, *inst, fids[2],ptr->f_blocks);
    SET_LONG_FIELD(env, *inst, fids[3],ptr->f_bfree);
    SET_LONG_FIELD(env, *inst, fids[4],ptr->f_bavail);
    SET_LONG_FIELD(env, *inst, fids[5],ptr->f_files);
    SET_LONG_FIELD(env, *inst, fids[6],ptr->f_ffree);
    SET_LONG_FIELD(env, *inst, fids[7],ptr->f_flags);
    SET_LONG_FIELD(env, *inst, fids[8],ptr->f_namelen);
    SET_LONG_FIELD(env, *inst, fids[9],ptr->f_frsize);

    ar = (*env)->GetObjectField(env, *inst , fids[10]);
    (*env)->SetLongArrayRegion(env, ar, 0, 5, cbuf);
    
    ar1 = (*env)->GetObjectField(env, *inst , fids[11]);
    (*env)->SetLongArrayRegion(env, ar1, 0, 2, cbuf1);

    /* Free the space allocated for the stat struct and
     return an instance of PVFS2JNI$Statfs. */
    JNI_FLUSH
    free(ptr);
    return 0;
}

/* pvfs_statfs */
JNIEXPORT jobject JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsStatfs(JNIEnv *env, jobject obj, jstring path)
{
    PFI
    struct statfs *ptr = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    ptr = (struct statfs *) calloc(1, sizeof(struct statfs));
    if(!ptr)
    {
        fprintf(stderr, "couldn't allocate memory for struct statfs!\n");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    int rc = pvfs_statfs(cpath, ptr);
    
    if(rc < 0)
    {
        perror("pvfs_statfs error");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }

    jobject statfs_obj;
    if(fill_statfs(env, ptr, &statfs_obj) == 0)
    {
        JNI_FLUSH;
        return statfs_obj;
    }
    JNI_FLUSH
    return NULL_OBJ;
}

/* pvfs_fstatfs */
JNIEXPORT jobject JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFstatfs(JNIEnv *env, jobject obj, int fd)
{
    PFI
    struct statfs *ptr = 0;
    ptr = (struct statfs *) calloc(1, sizeof(struct statfs));
    if(!ptr)
    {
        fprintf(stderr, "couldn't allocate memory for struct statfs!\n");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    int rc = pvfs_fstatfs(fd, ptr);
    if(rc < 0)
    {
        perror("pvfs_fstatfs error");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    jobject statfs_obj;
    if(fill_statfs(env, ptr, &statfs_obj) == 0)
    {
        JNI_FLUSH;
        return statfs_obj;
    }
    JNI_FLUSH
    return NULL_OBJ;
}

/* TODO */
#if 0
/* pvfs_statfs64 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsStatfs64  (JNIEnv *env, jobject obj, jlong jarg, jstring path)
{
    PFI
    int rc = 0;
    struct statfs64 *arg;
    arg = (struct statfs64 *)jarg;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    rc = pvfs_statfs64(cpath, arg);
    if(rc < 0)
    {
        perror("pvfs_statfs64 error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_fstatfs64 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFstatfs64(JNIEnv *env, jobject obj, jlong jarg, int fd)
{
    PFI
    int rc = 0;
    struct statfs64 *arg;
    arg = (struct statfs64 *)jarg;
    rc = pvfs_fstatfs64(fd, arg);
    if(rc < 0)
    {
        perror("pvfs_fstatfs64 error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}
#endif

/* TODO */
/* pvfs_statvfs */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsStatvfs  (JNIEnv *env, jobject obj, jlong jarg, jstring path)
{
    PFI
    int rc = 0;
    struct statvfs *arg;
    arg = (struct statvfs *)jarg;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    rc = pvfs_statvfs(cpath, arg);
    if(rc < 0)
    {
        perror("pvfs_statvfs error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* pvfs_fstatvfs */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2JNI_pvfsFstatvfs(JNIEnv *env, jobject obj, jlong jarg, int fd)
{
    PFI
    int rc = 0;
    struct statvfs *arg;
    arg = (struct statvfs *)jarg;
    rc = pvfs_fstatvfs(fd, arg);
    if(rc < 0)
    {
        perror("pvfs_fstatvfs error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}
