/* 
 * (C) 2011 Clemson University
 *
 * See COPYING in top-level directory.
 */

#define _GNU_SOURCE
/* #define OPEN_SOURCE >= 700 || _POSIX_C_SOURCE >= 200809L */ 

/* Include our headers that wrap calls present in stdio.c */
#include <jni_stdio.h>

/* Header for JNI */
#include "jni.h"

/* Include other headers */
#include <stdlib.h>
#include <dirent.h>
#include <sys/types.h>
#include <pvfs2-types.h>
#include <errno.h>
#include <malloc.h>

/* Our header generated by "javah" */
#include "PVFS2STDIOJNI.h"

/* Debug Ouput On/OFF */
#define JNI_DBG 1

/* malloc */
JNIEXPORT long JNICALL
Java_PVFS2STDIOJNI_Malloc(JNIEnv *env, jobject obj, jlong size)
{
    if(JNI_DBG) printf("malloc\n");
    void *ptr = malloc((size_t) size);
    if(!ptr)
    {
        perror("malloc failed");
    }
    return (long unsigned int) ptr;
}

/* free */
JNIEXPORT void JNICALL
Java_PVFS2STDIOJNI_Free(JNIEnv *env, jobject obj, jlong ptr)
{
    if(JNI_DBG) printf("free\n");
    free((void *) ptr);
}

/* fopen */
JNIEXPORT long JNICALL
Java_PVFS2STDIOJNI_Fopen(JNIEnv *env, jobject obj, jstring path, jstring mode)
{
    if(JNI_DBG) printf("fopen\n");
    char cpath[256];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    char cmode[10];
    int cmode_len = (*env)->GetStringLength(env, mode);
    (*env)->GetStringUTFRegion(env, mode, 0, cmode_len, cmode);
    if(JNI_DBG) printf("%s\n",cpath);
    if(JNI_DBG) printf("%s\n",cmode);
    FILE *fp = jni_fopen(cpath, cmode);
    if(JNI_DBG) printf("FILE *fp = %llu\n", (long long unsigned int) fp);
    if(fp == 0)
    {
        perror("fopen failed");
    }
    return (long) fp;
}

/* fdopen */
JNIEXPORT jlong JNICALL
Java_PVFS2STDIOJNI_Fdopen(JNIEnv *env, jobject obj, int fd, jstring mode)
{    
    if(JNI_DBG) printf("fdopen\n");
    char cmode[10];
    int cmode_len = (*env)->GetStringLength(env, mode);
    (*env)->GetStringUTFRegion(env, mode, 0, cmode_len, cmode);
    FILE * fptr;
    fptr = jni_fdopen(fd, cmode);
    if(fptr == NULL)
    {
        perror("fdopen failed!");
    }
    return (jlong) fptr;
}

/* fileno */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_Fileno(JNIEnv *env, jobject obj, jlong stream)
{    
    if(JNI_DBG) printf("fileno\n");
    int fd = jni_fileno((FILE *) stream);
    if(fd == -1)
    {
        perror("fileno failed!");
    }
    return (jint) fd;
}

/* remove */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_Remove(JNIEnv *env, jobject obj, jstring path)
{    
    if(JNI_DBG) printf("remove\n");
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    int val = jni_remove(cpath);
    if (val != 0)
    {
        perror("remove failed!");
    }
    return (jint) val;
}

/* fread */
JNIEXPORT jlong JNICALL
Java_PVFS2STDIOJNI_Fread(JNIEnv *env, jobject obj, jbyteArray ptr, jlong size, jlong nmemb, jlong stream)
{
    if(JNI_DBG) printf("fread\n");
    ssize_t rc = 0;
    jboolean is_copy;
    jbyte * cptr = (*env)->GetByteArrayElements(env, ptr, &is_copy);
    if(!ptr)
    {
        perror("GetByteArrayElements");
        errno = EFAULT;
        rc = -1;
        goto err;
    }
    rc = jni_fread((void *) cptr, (size_t) size, (size_t) nmemb, (FILE *) stream);
    if(rc < 0)
    {
        perror("jni fread");
    }
    else
    {
        if(JNI_DBG) printf("\tread %llu \n", ((long long unsigned int) rc * (long long unsigned int) size));
    }
err:
    /* copy back and free the ptr using 0 */
    (*env)->ReleaseByteArrayElements(env, ptr, cptr, 0);
    return (jlong) rc;
}

/* fwrite */
JNIEXPORT jlong JNICALL
Java_PVFS2STDIOJNI_Fwrite(JNIEnv *env, jobject obj, jbyteArray ptr, jlong size, jlong nmemb, jlong stream)   
{
    if(JNI_DBG) printf("fwrite\n");
    ssize_t rc = 0;
    jboolean is_copy;
    jbyte * cptr = (*env)->GetByteArrayElements(env, ptr, &is_copy);
    if(!ptr)
    {
        perror("GetByteArrayElements");
        errno = EFAULT;
        rc = -1;
        goto err;
    }
    rc = jni_fwrite((void *) cptr, (size_t) size, (size_t) nmemb, (FILE *) stream);
    if(rc < 0)
    {
        perror("jni fwrite");
    }
    else
    {
        if(JNI_DBG) printf("\twrote %llu bytes\n", ((long long unsigned int) rc * (long long unsigned int) size));
    }
err:
    /* copy back and free the ptr using 0 */
    (*env)->ReleaseByteArrayElements(env, ptr, cptr, 0);
    return (jlong) rc;
}

/* fdopendir */
JNIEXPORT jlong JNICALL
Java_PVFS2STDIOJNI_Fdopendir(JNIEnv *env, jobject obj, int fd)   
{
    DIR *dstr;
    if(JNI_DBG) printf("fdopendir\n");
    dstr = jni_fdopendir(fd);
    if(dstr == NULL)
    {
        perror("jni fdopendir");
    }
    return (jlong) dstr;
}

/* flockfile */
JNIEXPORT void JNICALL
Java_PVFS2STDIOJNI_Flockfile(JNIEnv *env, jobject obj, jlong stream)   
{
    if(JNI_DBG) printf("flockfile\n");
    jni_flockfile((FILE *) stream);
    return;
}

/* ftrylockfile */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_Ftrylockfile(JNIEnv *env, jobject obj, jlong stream)
{
    if(JNI_DBG) printf("ftrylockfile\n");
    int rc = jni_ftrylockfile((FILE *) stream);
    if(rc == 0)
    {
        perror("jni ftrylockfile");
    }
    return (jint) rc;
}

/* funlockfile */
JNIEXPORT void JNICALL
Java_PVFS2STDIOJNI_Funlockfile(JNIEnv *env, jobject obj, jlong stream)   
{
    if(JNI_DBG) printf("funlockfile\n");
    jni_funlockfile((FILE *) stream);
    return;
}

/* fopen64 */
JNIEXPORT jlong JNICALL
Java_PVFS2STDIOJNI_Fopen64(JNIEnv *env, jobject obj, jstring path, jstring modes)
{    
    if(JNI_DBG) printf("fopen64\n");
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    char cmodes[10];
    int cmodes_len = (*env)->GetStringLength(env, modes);
    (*env)->GetStringUTFRegion(env, modes, 0, cmodes_len, cmodes);
    FILE * fptr = jni_fopen64(cpath, cmodes);
    if(fptr == NULL)
    {
        perror("fopen failed");
    }
    else
    {
        if(JNI_DBG) printf("Fptr = %llu \n",(long long unsigned int) fptr);
    }
    return (jlong) fptr;
}

/* freopen */
JNIEXPORT jlong JNICALL
Java_PVFS2STDIOJNI_Freopen(JNIEnv *env, jobject obj, jstring path, jstring modes, jlong stream)
{    
    if(JNI_DBG) printf("freopen\n");
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    char cmodes[10];
    int cmodes_len = (*env)->GetStringLength(env, modes);
    (*env)->GetStringUTFRegion(env, modes, 0, cmodes_len, cmodes);
    FILE * fptr = jni_freopen(cpath, cmodes, (FILE *) stream);
    if (fptr == NULL)
    {
        perror("freopen failed");
    }
    else
    {
        if(JNI_DBG) printf("fptr = %llu \n", (long long unsigned int) fptr);
    }
    return (jlong) fptr;
}

/* freopen64 */
JNIEXPORT jlong JNICALL
Java_PVFS2STDIOJNI_Freopen64(JNIEnv *env, jobject obj, jstring path, jstring modes, jlong stream)
{    
    if(JNI_DBG) printf("freopen64\n");
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    char cmodes[10];
    int cmodes_len = (*env)->GetStringLength(env, modes);
    (*env)->GetStringUTFRegion(env, modes, 0, cmodes_len, cmodes);
    FILE * fptr = jni_freopen64(cpath, cmodes, (FILE *) stream);
    if(fptr == NULL)
    {
        perror("freopen64 failed");
    }
    else
    {
        if(JNI_DBG) printf("fptr = %llu \n", (long long unsigned int) fptr);
    }
    return (jlong) fptr;
}   

/* fwrite_unlocked */

JNIEXPORT jlong JNICALL
Java_PVFS2STDIOJNI_FwriteUnlocked(JNIEnv *env, jobject obj, jbyteArray ptr, jlong size, jlong nmemb, jlong stream)   
{
ssize_t rc = 0;
    if(JNI_DBG) printf("fwrite_unlocked\n"); 
    jboolean is_copy;
    jbyte * cptr = (*env)->GetByteArrayElements(env, ptr, &is_copy);
    if(!ptr)
    {
        perror("GetByteArrayElements");
        errno = EFAULT;
        rc = -1;
        goto err;
    }
    rc = fwrite_unlocked((void *) cptr, (size_t) size, (size_t) nmemb, (FILE *) stream);
    if(rc < 0)
    {
        fprintf(stderr, "jni fwrite_unlocked\n");
    }
    else
    {
        if(JNI_DBG) printf("\twrote %llu bytes\n", (long long unsigned int) rc);
    }
err:
    /* copy back and free the ptr using 0 */
    (*env)->ReleaseByteArrayElements(env, ptr, cptr, 0);
    return (jlong) rc;
}

/* fread_unlocked */
JNIEXPORT jlong JNICALL
Java_PVFS2STDIOJNI_FreadUnlocked(JNIEnv *env, jobject obj, jbyteArray ptr, jlong size, jlong nmemb, jlong stream)
{
    if(JNI_DBG) printf("fread_unlocked\n"); 
    ssize_t rc = 0;
    jboolean is_copy;
    jbyte * cptr = (*env)->GetByteArrayElements(env, ptr, &is_copy);
    if(!ptr)
    {
        perror("GetByteArrayElements");
        errno = EFAULT;
        rc = -1;
        goto err;
    }
    rc = fread_unlocked((void *) cptr, (size_t) size, (size_t) nmemb, (FILE *) stream);
    if(rc < 0)
    {
        fprintf(stderr, "jni fread_unlocked\n");
    }
    else
    {
        if(JNI_DBG) printf("\tread %llu bytes\n", (long long unsigned int) rc);
    }
err:
    /* copy back and free the ptr using 0 */
    (*env)->ReleaseByteArrayElements(env, ptr, cptr, 0);
    return (jlong) rc;
}

/* fclose */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_Fclose(JNIEnv *env, jobject obj, long fp)
{
    int rc = 0;
    if(JNI_DBG) printf("fclose\n");
    if(JNI_DBG) printf("jni_fclose fp = %llu\n", (long long unsigned int) fp);
    rc = jni_fclose((FILE *) fp);
    if(rc == EOF)
    {
        perror("fclose");
		return EOF;
    }
    return (jint) 0;
}

/* fcloseall */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_Fcloseall(JNIEnv *env, jobject obj)   
{
    if(JNI_DBG) printf("fcloseall\n");
    int rc = jni_fcloseall();
    if(rc == EOF)
    {
        fprintf(stderr, "fcloseall failed\n");
    }
    return rc;
}

/* fseek */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_Fseek(JNIEnv *env, jobject obj, jlong stream, jlong offset, int whence)
{
    if(JNI_DBG) printf("fseek\n");
    int rc = jni_fseek((FILE *) stream, (long) offset, whence);
    if(rc != 0)
    {
        perror("Fseek failed!");
    }
    return (jint) rc;
}

/* fseeko */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_Fseeko(JNIEnv *env, jobject obj, jlong stream, jlong offset, int whence)
{
    if(JNI_DBG) printf("fseeko\n");
    int rc = jni_fseeko((FILE *) stream, (off_t) offset, whence);
    if(rc != 0)
    {
        perror("Fseeko failed!");
    }
    return (jint) rc;
}

/* fseek64 */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_Fseek64(JNIEnv *env, jobject obj, jlong stream, jlong offset, int whence)
{
    if(JNI_DBG) printf("fseek64\n");
    int rc = jni_fseek64((FILE *) stream, (off64_t) offset, whence);
    if(rc != 0)
    {
        perror("Fseek64 failed!");
    }
    return (jint) rc;
}

/* setvbuf*/
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_Setvbuf(JNIEnv *env, jobject obj, jlong stream, jlong buf, jint mode, jlong size)
{
    if(JNI_DBG) printf("setvbuf\n");
    int rc = jni_setvbuf((FILE *) stream, (char *) buf, (int) mode, (size_t) size);
    if(rc != 0)
    {
        perror("setvbuf failed!");
    }
    return (jint) rc;
}

#if 0
/*
JNIEXPORT jlong JNICALL
Java_PVFS2STDIOJNI_FillFpost(JNIEnv *env, jobject obj, jobject x)
{
    printf("FillStatvfs\n");
    
    jfieldID fid1;
    jfieldID fid2;
    
    
    jlong pos;
    jlong state;
    
    jclass cls1 = (*env)->FindClass(env, "PVFS2STDIOJNI$Fpost");
    
    fid1 = (*env)->GetFieldID(env, cls1, "__pos", "J");
    if (fid1 == NULL)
    {
        return;
    }
    fid2 = (*env)->GetFieldID(env, cls1, "__state", "J");
    if (fid2 == NULL)
    {
        return;
    }
    
    fpos_t *cfpos_t = (fpos_t *)malloc(sizeof(fpos_t));
    
    pos = (*env)->GetLongField(env, x, fid1);
    __off_t cpos = (__off_t) pos;
    cfpos_t->__pos = cpos;
    
    state = (*env)->GetLongField(env, x, fid2);
    __mbstate_t cstate = (__mbstate_t) state;
    cfpos_t->__state = cstate;
    
    
    long lp = (long)cfpos_t;
    return lp;
}

void dispfpost(fpos_t *abc)
{
    printf("=======DISPLAY========\n");
    printf("The pos is: %lu\n", abc->__pos);
    printf("The state is: %lu\n", abc->__state);
    free(abc);
}

JNIEXPORT jlong JNICALL
Java_PVFS2STDIOJNI_UseFpost(JNIEnv *env, jobject obj, jlong jarg)
{
    fpos_t *arg;
    arg = (fpos_t *)jarg;
    dispfpost(arg);
}*/

/* fflush */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_Fflush(JNIEnv *env, jobject obj, jlong stream)
{
    printf("Fflush\n");
    int rc = 0;
    rc = fflush((FILE *) stream);
    if(rc == -1)
    {
        perror("Fflush failed!");
        
    }
    else
    {
        printf("Fflush successful.\n");
    }
    return (jint) rc;
}

/*fflush_unlocked*/

JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_FflushUnlocked(JNIEnv *env, jobject obj, jlong stream)
{
    printf("FflushUnlocked\n");
    int rc = 0;
    rc = fflush_unlocked((FILE *) stream);
    if(rc < 0)
    {
        perror("FflushUnlocked failed!");
        
    }
    else
    {
        printf("FflushUnlocked successful.\n");
    }
    return (jint) rc;
}

/*fputc*/
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_Fputc(JNIEnv *env, jobject obj, int c, jlong stream)
{
    printf("Fputc\n");
    int rc = 0;
    rc = fputc(c, (FILE *) stream);
    if(rc == -1)
    {
        perror("Fputc failed!");
        
    }
    else
    {
        printf("Fputc successful.\n");
    }
    return (jint) rc;
}

/*fputc_unlocked*/
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_FputcUnlocked(JNIEnv *env, jobject obj, int c, jlong stream)
{
    printf("FputcUnlocked\n");
    int rc;
    rc = fputc_unlocked(c, (FILE *) stream);
    if(rc == -1)
    {
        perror("FputcUnlocked failed!");
    }
    else
    {
        printf("FputcUnlocked successful.\n");
    }
    return (jint) rc;
}

/* fputs */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_Fputs(JNIEnv *env, jobject obj, jstring s, jlong stream)
{
    printf("Fputs\n");
    int rc = 0;
    char cs[1024];
    int cs_len = (*env)->GetStringLength(env, s);
    (*env)->GetStringUTFRegion(env, s, 0, cs_len, cs);
    rc = fputs(cs, (FILE *) stream);
    if(rc == -1)
    {
        perror("Fputs failed!");
        
    }
    else
    {
        printf("Fputs successful.\n");
    }
    return (jint) rc;
}

/* fputs_unlocked */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_FputsUnlocked(JNIEnv *env, jobject obj, jstring s, jlong stream)
{
    printf("FputsUnlocked\n");
    int rc ;
    char cs[1024];
    int cs_len = (*env)->GetStringLength(env, s);
    (*env)->GetStringUTFRegion(env, s, 0, cs_len, cs);
    rc = fputs_unlocked(cs, (FILE *) stream);
    if(rc == -1)
    {
        perror("FputsUnlocked failed!");
        
    }
    else
    {
        printf("FputsUnlocked successful.\n");
    }
    return (jint) rc;
} 

/* putc */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_Putc(JNIEnv *env, jobject obj, int c, jlong stream)
{
    printf("Putc\n");
    int rc = 0;
    rc = putc(c, (FILE *) stream);
    if(rc == -1)
    {
        perror("Putc failed!");
        
    }
    else
    {
        printf("Putc successful.\n");
    }
    return (jint) rc;
}

/* putc_unlocked */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_PutcUnlocked(JNIEnv *env, jobject obj, int c, jlong stream)
{
    printf("PutcUnlocked\n");
    int rc;
    rc = putc_unlocked(c, (FILE *) stream);
    if(rc == -1)
    {
        perror("PutcUnlocked failed!");
        
    }
    else
    {
        printf("PutcUnlocked successful.\n");
    }
    return (jint) rc;
}


/* putchar */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_Putchar(JNIEnv *env, jobject obj, int c)
{
    printf("Putchar\n");
    int rc = 0;
    rc = putchar(c);
    if(rc == -1)
    {
        perror("Putchar failed!");
        
    }
    else
    {
        printf("Putchar successful.\n");
    }
    return (jint) rc;
}

/*putchar_unlocked*/
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_PutcharUnlocked(JNIEnv *env, jobject obj, int c)
{
    printf("PutcharUnlocked\n");
    int rc;
    rc = putchar_unlocked(c);
    if(rc == -1)
    {
        perror("PutcharUnlocked failed!");
        
    }
    else
    {
        printf("PutcharUnlocked successful.\n");
    }
    return (jint) rc;
}

/* puts */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_Puts(JNIEnv *env, jobject obj, jstring s)
{
    printf("Puts\n");
    int rc = 0;
    char cs[1024];
    int cs_len = (*env)->GetStringLength(env, s);
    (*env)->GetStringUTFRegion(env, s, 0, cs_len, cs);
    rc = puts(cs);
    if(rc == -1)
    {
        perror("Puts failed!");
        
    }
    else
    {
        printf("Puts successful.\n");
    }

/*fputc*/
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_Fputc(JNIEnv *env, jobject obj, int c, jlong stream)
{
    printf("Fputc\n");
    int rc = 0;
    rc = fputc(c, (FILE *) stream);
    if(rc == -1)
    {
        perror("Fputc failed!");
        
    }
    else
    {
        printf("Fputc successful.\n");
    }
    return (jint) rc;
}

/* putw */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_Putw(JNIEnv *env, jobject obj, int wd, jlong stream)
{
    printf("Putw\n");
    int rc;
    char cs[1024];
    rc = putw(wd, (FILE *) stream);
    if(rc <= 0)
    {
        perror("Putw failed!");
        
    }
    else
    {
        printf("Putw successful.\n");
    }
    return (jint) rc;
}

/* fgets */
JNIEXPORT jstring JNICALL
Java_PVFS2STDIOJNI_Fgets(JNIEnv *env, jobject obj, jstring s, int size, jlong stream)
{
    printf("Fgets\n");
    char *rc = NULL;
    char cs[size];
    int cs_len = (*env)->GetStringLength(env, s);
    (*env)->GetStringUTFRegion(env, s, 0, cs_len, cs);
    rc = fgets(cs, size, (FILE *) stream);
    if(rc == NULL)
    {
        perror("Fgets failed!");
        
    }
    else
    {
        printf("Fgets successful.\n");
    }
    return (*env)->NewStringUTF(env, rc);
}

/* fgets_unlocked 
JNIEXPORT jstring JNICALL
Java_PVFS2STDIOJNI_FgetsUnlocked(JNIEnv *env, jobject obj, jstring s, int size, jlong stream)
{
    printf("FgetsUnlocked\n");
    char *rc = NULL;
    char cs[size];
    int cs_len = (*env)->GetStringLength(env, s);
    (*env)->GetStringUTFRegion(env, s, 0, cs_len, cs);
    rc = fgets_unlocked(cs, size, (FILE *) stream);
    if(rc == NULL)
    {
        perror("FgetsUnlocked failed!");
    }
    else
    {
        printf("FgetsUnlocked successful.\n");
    }
    return (*env)->NewStringUTF(env, rc);
    
}
*/
/* fgetc */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_Fgetc(JNIEnv *env, jobject obj, jlong stream)
{
    printf("Fgetc\n");
    int rc;
    rc = fgetc((FILE *) stream);
    if(rc == -1)
    {
        perror("Fgetc failed!");
        
    }
    else
    {
        printf("Fgetc successful.\n");
    }
    return (jint) rc;
}

/* fgetc_unlocked */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_FgetcUnlocked(JNIEnv *env, jobject obj, jlong stream)
{
    printf("FgetcUnlocked\n");
    int rc;
    rc = fgetc_unlocked((FILE *) stream);
    if(rc == -1)
    {
        perror("FgetcUnlocked failed!");
        
    }
    else
    {
        printf("FgetcUnlocked successful.\n");
    }
    return (jint) rc;
}


/* getc */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_Getc(JNIEnv *env, jobject obj, jlong stream)
{
    printf("Getc\n");
    int rc;
    rc = getc((FILE *) stream);
    if(rc == -1)
    {
        perror("Getc failed!");
        
    }
    else
    {
        printf("Getc successful.\n");
    }
    return (jint) rc;
}

/* getc_unlocked */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_GetcUnlocked(JNIEnv *env, jobject obj, jlong stream)
{
    printf("GetcUnlocked\n");
    int rc;
    rc = getc_unlocked((FILE *) stream);
    if(rc == -1)
    {
        perror("GetcUnlocked failed!");
        
    }
    else
    {
        printf("GetcUnlocked successful.\n");
    }
    return (jint) rc;
}

/* getchar */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_Getchar(JNIEnv *env, jobject obj)
{
    printf("Getchar\n");
    int rc;
    rc = jni_getchar();
    if(rc == -1)
    {
        perror("Getchar failed!");
        
    }
    else
    {
        printf("Getchar successful.\n");
    }
    return (jint) rc;
}

/* getchar_unlocked */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_GetcharUnlocked(JNIEnv *env, jobject obj)
{
    printf("GetcharUnlocked\n");
    int rc;
    rc = jni_getchar_unlocked();
    if(rc == -1)
    {
        perror("GetcharUnlocked failed!");
        
    }
    else
    {
        printf("GetcharUnlocked successful.\n");
    }
    return (jint) rc;
}

/* getw */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_Getw(JNIEnv *env, jobject obj, jlong stream)
{
    printf("Getw\n");
    int rc;
    rc = getw((FILE *) stream);
    if(rc == -1)
    {
        perror("Getw failed!");
        
    }
    else
    {
        printf("Getw successful.\n");
    }
    return (jint) rc;
}

/* gets */
JNIEXPORT jstring JNICALL
Java_PVFS2STDIOJNI_Gets(JNIEnv *env, jobject obj, jstring s)
{
    printf("Gets\n");
    char *rc = NULL;
    char cs[1024];
    int cs_len = (*env)->GetStringLength(env, s);
    (*env)->GetStringUTFRegion(env, s, 0, cs_len, cs);
    rc = gets(cs);
    if(rc == NULL)
    {
        perror("Gets failed!");
        
    }
    else
    {
        printf("Gets successful.\n");
    }
    return (*env)->NewStringUTF(env, rc);
    
}

/* ungetc */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_Ungetc(JNIEnv *env, jobject obj, int c, jlong stream)
{
    printf("Ungetc\n");
    int rc;
    rc = ungetc(c, (FILE *) stream);
    if(rc < 0)
    {
        perror("Ungetc failed!");
        
    }
    else
    {
        printf("Ungetc successful.\n");
    }
    return (jint) rc;
}

/* perror */

JNIEXPORT void JNICALL
Java_PVFS2STDIOJNI_Perror(JNIEnv *env, jobject obj, jstring s)
{
    printf("Perror\n");
    
    char cs[1024];
    int cs_len = (*env)->GetStringLength(env, s);
    (*env)->GetStringUTFRegion(env, s, 0, cs_len, cs);
    perror(cs);
}

/* clearerr */

JNIEXPORT void JNICALL
Java_PVFS2STDIOJNI_Clearerr(JNIEnv *env, jobject obj, jlong stream)
{
    printf("Clearerr\n");
    clearerr((FILE *) stream);
}

/* clearerr_unlocked */

JNIEXPORT void JNICALL
Java_PVFS2STDIOJNI_ClearerrUnlocked(JNIEnv *env, jobject obj, jlong stream)
{
    printf("ClearerrUnlocked\n");
    clearerr_unlocked((FILE *) stream);
}

/* feof */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_Feof(JNIEnv *env, jobject obj, jlong stream)
{
    printf("Feof\n");
    int rc = 0;
    rc = feof((FILE *) stream);
    if(rc == -1)
    {
        perror("Feof failed!");
        
    }
    else
    {
        printf("Feof successful.\n");
        
    }
    return (jint) rc;
}

/* feof_unlocked  */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_FeofUnlocked(JNIEnv *env, jobject obj, jlong stream)
{
    printf("FeofUnlocked\n");
    int rc = 0;
    rc = feof_unlocked((FILE *) stream);
    if(rc == -1)
    {
        perror("FeofUnlocked failed!");
        
    }
    else
    {
        printf("FeofUnlocked successful.\n");
        
    }
    return (jint) rc;
}

/* ferror */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_Ferror(JNIEnv *env, jobject obj, jlong stream)
{
    printf("Ferror\n");
    int rc = 0;
    rc = ferror((FILE *) stream);
    if(rc == -1)
    {
        perror("Ferror failed!");
        
    }
    else
    {
        printf("Ferror successful.\n");
        
    }
    return (jint) rc;
}

/* ferror_unlocked */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_FerrorUnlocked(JNIEnv *env, jobject obj, jlong stream)
{
    printf("FerrorUnlocked\n");
    int rc = 0;
    rc = ferror_unlocked((FILE *) stream);
    if(rc == -1)
    {
        perror("FerrorUnlocked failed!");
        
    }
    else
    {
        printf("FerrorUnlocked successful.\n");
        
    }
    return (jint) rc;
}

/* fileno_unlocked */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_FilenoUnlocked(JNIEnv *env, jobject obj, jlong stream)
{
    printf("FilenoUnlocked\n");
    int rc = 0;
    rc = fileno_unlocked((FILE *) stream);
    if(rc == -1)
    {
        perror("FilenoUnlocked failed!");
        
    }
    else
    {
        printf("FilenoUnlocked successful.\n");
        
    }
    return (jint) rc;
}

/* setbuf */
JNIEXPORT void JNICALL
Java_PVFS2STDIOJNI_Setbuf(JNIEnv *env, jobject obj, jlong stream, jstring buf)
{    
    printf("Setbuf\n");
    
    char cbuf[1024];
    int cbuf_len = (*env)->GetStringLength(env, buf);
    (*env)->GetStringUTFRegion(env, buf, 0, cbuf_len, cbuf);
    setbuf((FILE *) stream, cbuf);
    
}

/* setbuffer */
JNIEXPORT void JNICALL
Java_PVFS2STDIOJNI_Setbuffer(JNIEnv *env, jobject obj, jlong stream, jstring buf, jlong size)
{    
    printf("Setbuffer\n");
    
    char cbuf[size];
    int cbuf_len = (*env)->GetStringLength(env, buf);
    (*env)->GetStringUTFRegion(env, buf, 0, cbuf_len, cbuf);
    
    setbuffer((FILE *) stream, cbuf, (size_t) size);
}

/* setlinebuf */
JNIEXPORT void JNICALL
Java_PVFS2STDIOJNI_Setlinebuf(JNIEnv *env, jobject obj, jlong stream)
{    
    printf("Setlinebuf\n");
    setlinebuf((FILE *) stream);
}

/* setvbuf*/
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_Setvbuf(JNIEnv *env, jobject obj)
/*
Java_PVFS2STDIOJNI_Setvbuf(JNIEnv *env, jobject obj, jlong stream, jlong buf, jint mode, jlong size)
*/
{
    /*
    if(JNI_DBG) printf("setvbuf\n");
    int rc = jni_setvbuf((FILE *) stream, (char *) buf, (int) mode, (size_t) size);
    if(rc != 0)
    {
        perror("setvbuf failed!");
    }
    return (jint) rc;
    */
    return 1;
}

/* mkdtemp */
JNIEXPORT jstring JNICALL
Java_PVFS2STDIOJNI_Mkdtemp(JNIEnv *env, jobject obj, jstring tmplate)
{    
    printf("Mkdtemp\n");
    char * rc;
    char ctmplate[1024];
    int ctmplate_len = (*env)->GetStringLength(env, tmplate);
    (*env)->GetStringUTFRegion(env, tmplate, 0, ctmplate_len, ctmplate);
    rc = mkdtemp(ctmplate);
    if(rc == NULL)
    {
        perror("Mkdtemp failed!");
        
    }
    else
    {
        printf("Mkdtemp successful.\n");
    }
    return (*env)->NewStringUTF(env, rc);
}

/* mkstemp */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_Mkstemp(JNIEnv *env, jobject obj, jstring tmplate)
{    
    printf("Mkstemp\n");
    int rc;
    char ctmplate[1024];
    int ctmplate_len = (*env)->GetStringLength(env, tmplate);
    (*env)->GetStringUTFRegion(env, tmplate, 0, ctmplate_len, ctmplate);
    rc = mkstemp(ctmplate);
    if(rc == -1)
    {
        perror("Mkstemp failed!");
        
    }
    else
    {
        printf("Mkstemp successful.\n");
        
    }
    return (jint) rc;
}

/* tmpfile */
JNIEXPORT jlong JNICALL
Java_PVFS2STDIOJNI_Tmpfile(JNIEnv *env, jobject obj)
{    
    printf("Tmpfile\n");
    FILE * fd;
    
    fd = tmpfile();
    if(fd == NULL)
    {
        perror("Tmpfile failed!");
        
    }
    else
    {
        printf("Tmpfile successful.\n");
        
    }
    return (jlong) fd;
}

/* opendir */
JNIEXPORT jlong JNICALL
Java_PVFS2STDIOJNI_Opendir(JNIEnv *env, jobject obj, jstring name)
{    
    printf("Opendir\n");
    DIR * d;
    char cname[PVFS_NAME_MAX];
    int cname_len = (*env)->GetStringLength(env, name);
    (*env)->GetStringUTFRegion(env, name, 0, cname_len, cname);
    d = opendir(cname);
    if(d == NULL)
    {
        perror("Opendir failed!");
        
    }
    else
    {
        printf("Opendir successful.\n");
        
    }
    return (jlong) d;
}

/* dirfd */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_Dirfd(JNIEnv *env, jobject obj, jlong dir)
{
    printf("Dirfd\n");
    int rc;
    rc = dirfd((DIR *) dir);
    if(rc == -1)
    {
        perror("Dirfd failed!");
        
    }
    else
    {
        printf("Dirfd successful.\n");
    }
    return (jint) rc;
}

/* rewinddir */
JNIEXPORT void JNICALL
Java_PVFS2STDIOJNI_Rewinddir(JNIEnv *env, jobject obj, jlong dir)
{
    printf("Rewinddir\n");
    rewinddir((DIR *) dir);
}

/* seekdir */
JNIEXPORT void JNICALL
Java_PVFS2STDIOJNI_Seekdir(JNIEnv *env, jobject obj, jlong dir, jlong offset)
{
    printf("Seekdir\n");
    seekdir((DIR *) dir, (off_t) offset);
}

/* telldir */
JNIEXPORT jlong JNICALL
Java_PVFS2STDIOJNI_Telldir(JNIEnv *env, jobject obj, jlong dir)
{
    printf("Telldir\n");
    off_t rc;
    rc = telldir((DIR *) dir);
    if(rc == -1)
    {
        perror("Telldir failed!");
        
    }
    else
    {
        printf("Telldir successful.\n");
    }
    return (jlong) rc;
}

/* closedir */
JNIEXPORT jint JNICALL
Java_PVFS2STDIOJNI_Closedir(JNIEnv *env, jobject obj, jlong dir)
{
    printf("Closedir\n");
    int rc;
    rc = closedir((DIR *) dir);
    if(rc == 0)
    {
        printf("Closedir successful.\n");
    }
    else
    {
        perror("Closedir failed!");
    }
    return (jint) rc;
}
#endif
