/* 
 * (C) 2011 Clemson University
 *
 * See COPYING in top-level directory.
 */

#define _GNU_SOURCE

/* Headers required by native routines. */
#include <features.h>
#include <pvfs2-types.h>
#include <stdlib.h>
#include <unistd.h>
#include <stdio.h>
#include <string.h>
#include <sys/uio.h>
#include <sys/types.h>
#include <sys/resource.h>
#include <stdint.h>
#include <sys/vfs.h>
#include <sys/statfs.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/mount.h>
#include <features.h>
#include <dirent.h>
#include <errno.h>

#include <pvfs2.h>
#include <pvfs2-usrint.h>

/* Our header generated by "javah" */
#include "org_orangefs_usrint_PVFS2POSIXJNI.h"

/* Header file that includes definitions and macros used by both POSIX and
 * STDIO libs */
#include "libPVFS2JNI_common.h"

/* Forward Declarations */
void fill_error(void *ptr);
int fill_stat(JNIEnv *env, struct stat *ptr, jobject *inst);
int fill_statfs(JNIEnv *env, struct statfs *ptr, jobject *inst);
int fill_timeval(JNIEnv *env, struct timeval *ptr, jobject *inst);
int fill_utimbuf(JNIEnv *env, struct utimbuf *ptr, jobject *inst);

/* Fill PVFS2POSIXJNIFlags object */
JNIEXPORT jobject JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_fillPVFS2POSIXJNIFlags(
    JNIEnv *env, 
    jobject obj
)
{
    int num_fields = 52;
    jfieldID fids[num_fields];
    char *field_names[] = 
    {
        "O_WRONLY", //0 
        "O_RDONLY", 
        "PVFS_IO_READ", 
        "PVFS_IO_WRITE", 
        "O_ACCMODE", 
        "O_HINTS", 
        "PVFS_HINT_NULL", 
        "O_LARGEFILE", 
        "AT_FDCWD",
        "O_EXCL",
        
        "AT_REMOVEDIR", //10
        "O_APPEND",
        "PVFS_FD_FAILURE", 
        "PVFS_ATTR_DEFAULT_MASK", 
        "AT_SYMLINK_NOFOLLOW",
        "O_NOFOLLOW", 
        "PVFS_ATTR_SYS_ATIME", 
        "PVFS_ATTR_SYS_MTIME",
        "O_CLOEXEC", 
        "O_ASYNC",
        
        "O_CREAT", //20
        "O_DIRECT", 
        "O_DIRECTORY", 
        "O_NOATIME", 
        "O_NOCTTY", 
        "O_NONBLOCK", 
        "FD_CLOEXEC", 
        "ST_RDONLY", 
        "ST_NOSUID", 
        "S_IRWXU",
        
        "S_IRUSR", //30
        "S_IWUSR", 
        "S_IXUSR", 
        "S_IRWXG", 
        "S_IRGRP", 
        "S_IWGRP", 
        "S_IXGRP", 
        "S_IRWXO", 
        "S_IROTH", 
        "S_IWOTH",
        
        "S_IXOTH", //40
        "S_IFMT", 
        "S_IFSOCK", 
        "S_IFLNK", 
        "S_IFREG", 
        "S_IFBLK", 
        "S_IFDIR", 
        "S_IFCHR", 
        "S_IFIFO", 
        "S_ISUID",
        
        "S_ISGID", //50
        "S_ISVTX"
    };

    char *field_types[] = 
    {
        "J", "J", "J",
        "J", "J", "J",
        "J", "J", "J",
        "J", "J", "J",
        "J", "J", "J",
        "J", "J", "J",
        "J", "J", "J",
        "J", "J", "J",
        "J", "J", "J",
        "J", "J", "J",
        "J", "J", "J",
        "J", "J", "J",
        "J", "J", "J",
        "J", "J", "J",
        "J", "J", "J",
        "J", "J", "J",
        "J", "J", "J",
        "J"
    };

    char *cls_name = "org/orangefs/usrint/PVFS2POSIXJNIFlags";
    jclass cls = (*env)->FindClass(env, cls_name);
    if(!cls)
    {
        fprintf(stderr, "invalid class: %s\n", cls_name);
        return;
    }
    /* Allocates Memory for the Object specified by cls w/o calling its 
     * constructor. 
     */
    jobject inst = (*env)->AllocObject(env, cls);
    /* Get the field ids */
    int fid_index = 0;
    for(; fid_index < num_fields; fid_index++)
    {
        fids[fid_index] = GET_FIELD_ID(env, cls, 
            field_names[fid_index], field_types[fid_index]);
        if(!fids[fid_index])
        {
            fprintf(stderr, "invalid field requested: %s\n", field_names[fid_index]);
            return;
        }
        
    }

    /* Load PVFS2POSIXJNIFlags object with data replaced by C-Preprocessor 
     * using set methods.
     */
    /* TODO: why are these commented out? */
    //SET_LONG_FIELD(env, inst, fids[],O_HINTS);
    //SET_LONG_FIELD(env, inst, fids[],PVFS_HINTS_NULL);
    //SET_LONG_FIELD(env, inst, fids[],PVFS_FD_FAILURE);
    //SET_LONG_FIELD(env, inst, fids[],PVFS_ATTR_DEFAULT_MASK);
    
    SET_LONG_FIELD(env, inst, fids[0], O_WRONLY);
    SET_LONG_FIELD(env, inst, fids[1], O_RDONLY);
    SET_LONG_FIELD(env, inst, fids[2], PVFS_IO_READ);
    SET_LONG_FIELD(env, inst, fids[3], PVFS_IO_WRITE);
    SET_LONG_FIELD(env, inst, fids[4], O_ACCMODE);
    SET_LONG_FIELD(env, inst, fids[7], O_LARGEFILE);
    SET_LONG_FIELD(env, inst, fids[8], AT_FDCWD);
    SET_LONG_FIELD(env, inst, fids[9], O_EXCL);
    
    SET_LONG_FIELD(env, inst, fids[10], AT_REMOVEDIR);
    SET_LONG_FIELD(env, inst, fids[11], O_APPEND);
    //SET_LONG_FIELD(env, inst, fids[12], PVFS_FD_FAILURE);
    //SET_LONG_FIELD(env, inst, fids[13], PVFS_ATTR_DEFAULT_MASK);
    SET_LONG_FIELD(env, inst, fids[14], AT_SYMLINK_NOFOLLOW);
    SET_LONG_FIELD(env, inst, fids[15], O_NOFOLLOW);
    SET_LONG_FIELD(env, inst, fids[16], PVFS_ATTR_SYS_ATIME);
    SET_LONG_FIELD(env, inst, fids[17], PVFS_ATTR_SYS_MTIME);
    SET_LONG_FIELD(env, inst, fids[18], O_CLOEXEC);
    SET_LONG_FIELD(env, inst, fids[19], O_ASYNC);
        
    SET_LONG_FIELD(env, inst, fids[20], O_CREAT);
    SET_LONG_FIELD(env, inst, fids[21], O_DIRECT);
    SET_LONG_FIELD(env, inst, fids[22], O_DIRECTORY);
    SET_LONG_FIELD(env, inst, fids[23], O_NOATIME);
    SET_LONG_FIELD(env, inst, fids[24], O_NOCTTY);
    SET_LONG_FIELD(env, inst, fids[25], O_NONBLOCK);
    SET_LONG_FIELD(env, inst, fids[26], FD_CLOEXEC);
    SET_LONG_FIELD(env, inst, fids[27], ST_RDONLY);
    SET_LONG_FIELD(env, inst, fids[28], ST_NOSUID);
    SET_LONG_FIELD(env, inst, fids[29], S_IRWXU);
        
    SET_LONG_FIELD(env, inst, fids[30], S_IRUSR);
    SET_LONG_FIELD(env, inst, fids[31], S_IWUSR);
    SET_LONG_FIELD(env, inst, fids[32], S_IXUSR);
    SET_LONG_FIELD(env, inst, fids[33], S_IRWXG);
    SET_LONG_FIELD(env, inst, fids[34], S_IRGRP);
    SET_LONG_FIELD(env, inst, fids[35], S_IWGRP);
    SET_LONG_FIELD(env, inst, fids[36], S_IXGRP);
    SET_LONG_FIELD(env, inst, fids[37], S_IRWXO);
    SET_LONG_FIELD(env, inst, fids[38], S_IROTH);
    SET_LONG_FIELD(env, inst, fids[39], S_IWOTH);
        
    SET_LONG_FIELD(env, inst, fids[40], S_IXOTH);
    SET_LONG_FIELD(env, inst, fids[41],S_IFMT);
    SET_LONG_FIELD(env, inst, fids[42],S_IFSOCK);
    SET_LONG_FIELD(env, inst, fids[43],S_IFLNK);
    SET_LONG_FIELD(env, inst, fids[44],S_IFREG);
    SET_LONG_FIELD(env, inst, fids[45],S_IFBLK);
    SET_LONG_FIELD(env, inst, fids[46],S_IFDIR);
    SET_LONG_FIELD(env, inst, fids[47],S_IFCHR);
    SET_LONG_FIELD(env, inst, fids[48],S_IFIFO);
    SET_LONG_FIELD(env, inst, fids[49],S_ISUID);
    
    SET_LONG_FIELD(env, inst, fids[50],S_ISGID);
    SET_LONG_FIELD(env, inst, fids[51],S_ISVTX);
        
    JNI_FLUSH
    return inst;
}

void fill_error(void *ptr)
{
    if(ptr)
    {
        free(ptr);
    }
    JNI_FLUSH
}

/* jni_open */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_open(
    JNIEnv *env,
    jobject obj,
    jstring path,
    jlong flags,
    jlong mode
)
{
    PFI
    int rc = 0;

    int cpath_len = (*env)->GetStringLength(env, path);
    char cpath[cpath_len + 1];
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    
    if(((int) flags & O_CREAT) == O_CREAT)
    {
        if(JNI_DBG) printf("\tO_CREAT detected!\n");
        rc = jni_open(cpath, (int) flags, (mode_t) mode);
    }
    else
    {
        if(JNI_DBG) printf("\tNo O_CREAT detected\n");
        rc = jni_open(cpath, (int) flags);
    }
    if(rc < 0)
    {
        perror("jni_open error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_open64 06/08/2012 */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_open64 (JNIEnv *env, jobject obj, jstring path, jlong flags, jlong mode)
{
    PFI
    int rc = 0;

    int cpath_len = (*env)->GetStringLength(env, path);
    char cpath[cpath_len + 1];
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);

    if(((int) flags & O_CREAT) == O_CREAT)
    {
        if(JNI_DBG) printf("\tO_CREAT detected!\n");
        rc = jni_open64(cpath, (int) flags, (mode_t) mode);
    }
    else
    {
        if(JNI_DBG) printf("\tNo O_CREAT detected\n");
        rc = jni_open64(cpath, (int) flags);
    }

    if(rc < 0)
    {
        perror("jni_open64 error");
        rc -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_openat */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_openat (
    JNIEnv *env, 
    jobject obj, 
    int dirfd, 
    jstring path, 
    jlong flags, 
    jlong mode)
{
    PFI
    int rc = 0;

    int cpath_len = (*env)->GetStringLength(env, path);
    char cpath[cpath_len + 1];
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);

    if(((int) flags & O_CREAT) == O_CREAT)
    {
        if(JNI_DBG) printf("\tO_CREAT detected!\n");
        rc = jni_openat(dirfd, cpath, (int) flags, (mode_t) mode);
    }
    else
    {
        if(JNI_DBG) printf("\tNo O_CREAT detected\n");
        rc = jni_openat(dirfd, cpath, (int) flags);
    }
    
    if(rc < 0)
    {
        perror("jni_openat error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_openat64 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_openat64 (JNIEnv *env, 
    jobject obj, 
    int dirfd, 
    jstring path, 
    jlong flags,
    jlong mode)
{
    PFI
    int rc = 0;

    int cpath_len = (*env)->GetStringLength(env, path);
    char cpath[cpath_len + 1];
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);

    if(((int) flags & O_CREAT) == O_CREAT)
    {
        if(JNI_DBG) printf("\tO_CREAT detected!\n");
        rc = jni_openat64(dirfd, cpath, (int) flags, (mode_t) mode);
    }
    else
    {
        if(JNI_DBG) printf("\tNo O_CREAT detected\n");
        rc = jni_openat64(dirfd, cpath, (int) flags);
    }

    if(rc < 0)
    {
        perror("jni_openat64 error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_creat */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_creat(JNIEnv *env, jobject obj, jstring path, jlong mode)
{
    PFI
    int rc = 0;

    int cpath_len = (*env)->GetStringLength(env, path);
    char cpath[cpath_len + 1];
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);

    rc = jni_creat(cpath, (mode_t) mode);
    if(rc < 0)
    {
        perror("jni_creat error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_creat64 */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_creat64(JNIEnv *env, jobject obj, jstring path, jlong mode)
{
    PFI
    int rc = 0;

    int cpath_len = (*env)->GetStringLength(env, path);
    char cpath[cpath_len + 1];
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);

    rc = jni_creat64(cpath, (mode_t) mode);
    if(rc < 0)
    {
        perror("jni_creat error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_unlink */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_unlink(JNIEnv *env, jobject obj, jstring path)
{
    PFI
    int rc = 0;

    int cpath_len = (*env)->GetStringLength(env, path);
    char cpath[cpath_len + 1];
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);

    errno = 0;
    rc = jni_unlink(cpath);
    if(rc == -1)
    {
        perror("jni_unlink error");
    }
    JNI_FLUSH
    return rc;
}

/* jni_unlinkat */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_unlinkat (JNIEnv *env, jobject obj, int dirfd, jstring path, jlong flags)
{
    PFI
    int rc = 0;

    int cpath_len = (*env)->GetStringLength(env, path);
    char cpath[cpath_len + 1];
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);

    rc = jni_unlinkat(dirfd, cpath, (int) flags);
    if(rc < 0)
    {
        perror("jni_unlinkat error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_rename */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_rename(JNIEnv *env,
    jobject obj,
    jstring oldpath,
    jstring newpath
)
{
    PFI
    int rc = 0;
    char coldpath[PVFS_PATH_MAX];
    int coldpath_len = (*env)->GetStringLength(env, oldpath);
    (*env)->GetStringUTFRegion(env, oldpath, 0, coldpath_len, coldpath);
    char cnewpath[PVFS_PATH_MAX];
    int cnewpath_len = (*env)->GetStringLength(env, newpath);
    (*env)->GetStringUTFRegion(env, newpath, 0, cnewpath_len, cnewpath);
    rc = jni_rename(coldpath, cnewpath);
    if(rc < 0)
    {
        perror("jni_rename error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_RenameAt */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_renameAt(JNIEnv *env,
    jobject obj,
    int olddirfd,
    jstring oldpath,
    int newdirfd,
    jstring newpath
)
{
    PFI
    int rc = 0;
    char coldpath[PVFS_PATH_MAX];
    int coldpath_len = (*env)->GetStringLength(env, oldpath);
    (*env)->GetStringUTFRegion(env, oldpath, 0, coldpath_len, coldpath);
    char cnewpath[PVFS_PATH_MAX];
    int cnewpath_len = (*env)->GetStringLength(env, newpath);
    (*env)->GetStringUTFRegion(env, newpath, 0, cnewpath_len, cnewpath);
    rc = jni_renameat(olddirfd, coldpath, newdirfd, cnewpath);
    if(rc < 0)
    {
        perror("jni_renameat error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_close */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_close(JNIEnv *env, jobject obj, int fd)
{
    PFI
    int rc = 0;
    rc = jni_close(fd);
    if(rc < 0)
    {
        perror("jni_close error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_flush */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_flush(JNIEnv *env, jobject obj, int fd)
{
    PFI
    int rc = 0;
    rc = jni_flush(fd);
    if(rc < 0)
    {
        perror("jni_close error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_prdwr64  (INCOMPLETE) */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_prdwr64(JNIEnv *env, jobject obj, int fd, jlong buf, jlong count, jlong offset, jlong which)
{
    PFI
    size_t countc = (size_t) count;
    off64_t offsetc = (off64_t) offset;
    void* bufc = (void*) buf;
    int rc = 0;
    rc = jni_prdwr64(fd, bufc, countc, offsetc, (int) which);
    if(rc < 0)
    {
        perror("jni_prdwr64 error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_lseek */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_lseek(JNIEnv *env, jobject obj, int fd, jlong offset, jlong whence)
{
    PFI
    off_t offsetc = (off_t) offset;

    off_t rc = jni_lseek(fd, offsetc, (int) whence);
    jlong op = (jlong)rc;
    if(op < 0)
    {
        perror("jni_lseek error");
        op = -1;
    }
    JNI_FLUSH
    return op;
}

/* jni_lseek64 */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_lseek64(JNIEnv *env, jobject obj, int fd, jlong offset, jlong whence)
{
    PFI
    off_t offsetc = (off_t) offset;
    
    off_t rc = jni_lseek(fd, offsetc, (int) whence);
    jlong op = (jlong)rc;
    if(op < 0)
    {
        perror("jni_lseek64 error");
        op = -1;
    }
    JNI_FLUSH
    return op;
}

/* jni_truncate */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_truncate(JNIEnv *env, jobject obj, jstring path, jlong length)
{
    PFI
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    off_t clength = (off_t) length;
    int rc = jni_truncate(cpath, clength);
    if(rc < 0)
    {
        perror("jni_truncate error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_truncate64 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_truncate64(JNIEnv *env, jobject obj, jstring path, jlong length)
{
    PFI
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    off64_t clength = (off64_t) length;
    int rc = 0;
    rc = jni_truncate64(cpath, clength);
    if(rc < 0)
    {
        perror("jni_truncate64 error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_fallocate */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_fallocate(JNIEnv *env, jobject obj, int fd, jlong offset, jlong length)
{
    PFI
    off_t coffset = (off_t) offset;
    off_t clength = (off_t) length;
    int rc = 0;
    rc = jni_fallocate(fd, coffset, clength);
    if(rc < 0)
    {
        perror("jni_fallocate error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_ftruncate */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_ftruncate(JNIEnv *env, jobject obj, int fd, jlong length)
{
    PFI
    off_t clength = (off_t) length;
    int rc = 0;
    rc = jni_ftruncate(fd, clength);
    if(rc < 0)
    {
        perror("jni_ftruncate error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_ftruncate64 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_ftruncate64(JNIEnv *env, jobject obj, int fd, jlong length)
{
    PFI
    off64_t clength = (off64_t) length;
    int rc = 0;
    rc = jni_ftruncate(fd, clength);
    if(rc < 0)
    {
        perror("jni_ftruncate64 error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_dup */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_dup(JNIEnv *env, jobject obj, int oldfd)
{
    PFI
    int rc = 0;
    rc = jni_dup(oldfd);
    if(rc < 0)
    {
        perror("jni_dup error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_dup2 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_dup2(JNIEnv *env, jobject obj, int oldfd, int newfd)
{
    PFI
    int rc = 0;
    rc = jni_dup_descriptor(oldfd, newfd);
    if(rc < 0)
    {
        perror("jni_dup2 error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_chown */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_chown(JNIEnv *env, jobject obj, jstring path, jlong owner, jlong group)
{
    PFI
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    uid_t cowner = (uid_t) owner;
    gid_t cgroup = (gid_t) group;
    int rc = jni_chown(cpath, cowner, cgroup);
    if(rc < 0)
    {
        perror("jni_chown error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_fchown */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_fchown(JNIEnv *env, jobject obj, int fd, jlong owner, jlong group)
{
    PFI
    uid_t cowner = (uid_t) owner;
    gid_t cgroup = (gid_t) group;
    int rc = jni_fchown(fd, cowner, cgroup);
    if(rc < 0)
    {
        perror("jni_fchown error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_fchownat */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_fchownat(JNIEnv *env, jobject obj, int fd, jstring path, jlong owner, jlong group, jlong flag)
{
    PFI
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    uid_t cowner = (uid_t) owner;
    gid_t cgroup = (gid_t) group;

    int rc = jni_fchownat(fd, cpath, cowner, cgroup, (int) flag);
    if(rc < 0)
    {
        perror("jni_fchownat error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_chmod */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_chmod(JNIEnv *env, jobject obj, jstring path, jlong mode)
{
    PFI

    int cpath_len = (*env)->GetStringLength(env, path);
    char cpath[cpath_len + 1];
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);

    int rc = jni_chmod(cpath, (mode_t) mode);
    if(rc < 0)
    {
        perror("jni_chmod error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_fchmod */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_fchmod(JNIEnv *env, jobject obj, int fd, jlong mode)
{
    PFI
    int rc = jni_fchmod(fd, (mode_t) mode);
    if(rc < 0)
    {
        perror("jni_fchmod error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_fchmodat */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_fchmodat (JNIEnv *env, jobject obj, int fd, jstring path, jlong mode, jlong flag)
{
    PFI
    int cpath_len = (*env)->GetStringLength(env, path);
    char cpath[cpath_len + 1];
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    
    int rc = jni_fchmodat(fd, cpath, (mode_t) mode, (int) flag);
    if(rc < 0)
    {
        perror("jni_fchmodat error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_mkdir */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_mkdir (JNIEnv *env, jobject obj, jstring path, jlong mode)
{
    PFI
    int rc = 0;

    int cpath_len = (*env)->GetStringLength(env, path);
    char cpath[cpath_len + 1];
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);

    rc = jni_mkdir(cpath, (mode_t) mode);
    if(rc < 0)
    {
        perror("jni_mkdir error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_mkdirat */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_mkdirat (JNIEnv *env, jobject obj, int dirfd, jstring path, jlong mode)
{
    PFI
    int rc = 0;

    int cpath_len = (*env)->GetStringLength(env, path);
    char cpath[cpath_len + 1];
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);

    rc = jni_mkdirat(dirfd, cpath, (mode_t) mode);
    if(rc < 0)
    {
        perror("jni_mkdirat error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_rmdir */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_rmdir(JNIEnv *env, jobject obj, jstring path)
{
    PFI
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    int rc = 0;
    rc = jni_rmdir(cpath);
    if(rc < 0)
    {
        perror("jni_rmdir error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_readlink */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_readlink (JNIEnv *env, jobject obj, jstring path, jstring buf, jlong bufsiz)
{
    PFI
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    long cbufsiz = (long) bufsiz;
    char cbuf[cbufsiz];
    int cbuf_len = (*env)->GetStringLength(env, buf);
    (*env)->GetStringUTFRegion(env, path, 0, cbuf_len, cbuf);
    size_t bufsize = (size_t) bufsiz;
    ssize_t rc = jni_readlink(cpath, cbuf, bufsize);
    jlong op = (jlong) rc;
    if(op < 0)
    {
        perror("jni_readlink error");
        op = -1;
    }
    JNI_FLUSH
    return op;
}

/* jni_readlinkat */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_readlinkat (JNIEnv *env, jobject obj, int fd, jstring path, jstring buf, jlong bufsiz)
{
    PFI
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    long cbufsiz = (long) bufsiz;
    char cbuf[cbufsiz];
    int cbuf_len = (*env)->GetStringLength(env, buf);
    (*env)->GetStringUTFRegion(env, path, 0, cbuf_len, cbuf);
    size_t bufsize = (size_t) bufsiz;
    ssize_t rc = jni_readlinkat(fd, cpath, cbuf, bufsize);
    jlong op = (jlong) rc;
    if(op < 0)
    {
        perror("jni_readlinkat error");
        op = -1;
    }
    JNI_FLUSH
    return op;
}

/* jni_symlink */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_symlink(JNIEnv *env, jobject obj, jstring oldpath, jstring newpath)
{
    PFI
    int rc = 0;
    char coldpath[PVFS_PATH_MAX];
    int coldpath_len = (*env)->GetStringLength(env, oldpath);
    (*env)->GetStringUTFRegion(env, oldpath, 0, coldpath_len, coldpath);
    char cnewpath[PVFS_PATH_MAX];
    int cnewpath_len = (*env)->GetStringLength(env, newpath);
    (*env)->GetStringUTFRegion(env, newpath, 0, cnewpath_len, cnewpath);
    rc = jni_symlink(coldpath, cnewpath);
    if(rc < 0)
    {
        perror("jni_symlink error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_symlinkat */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_symlinkat(JNIEnv *env, jobject obj, jstring oldpath, int newdirfd, jstring newpath)
{
    PFI
    int rc = 0;
    char coldpath[PVFS_PATH_MAX];
    int coldpath_len = (*env)->GetStringLength(env, oldpath);
    (*env)->GetStringUTFRegion(env, oldpath, 0, coldpath_len, coldpath);
    char cnewpath[PVFS_PATH_MAX];
    int cnewpath_len = (*env)->GetStringLength(env, newpath);
    (*env)->GetStringUTFRegion(env, newpath, 0, cnewpath_len, cnewpath);
    rc = jni_symlinkat(coldpath, newdirfd, cnewpath);
    if(rc < 0)
    {
        perror("jni_symlinkat error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_link */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_link(JNIEnv *env, jobject obj, jstring oldpath, jstring newpath)
{
    PFI
    int rc = 0;
    char coldpath[PVFS_PATH_MAX];
    int coldpath_len = (*env)->GetStringLength(env, oldpath);
    (*env)->GetStringUTFRegion(env, oldpath, 0, coldpath_len, coldpath);
    char cnewpath[PVFS_PATH_MAX];
    int cnewpath_len = (*env)->GetStringLength(env, newpath);
    (*env)->GetStringUTFRegion(env, newpath, 0, cnewpath_len, cnewpath);
    rc = jni_link(coldpath, cnewpath);
    if(rc < 0)
    {
        perror("jni_link error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_linkat */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_linkat(
    JNIEnv *env, 
    jobject obj, 
    int olddirfd, 
    jstring oldpath, 
    int newdirfd, 
    jstring newpath, 
    jlong flags)
{
    PFI
    int rc = 0;
    char coldpath[PVFS_PATH_MAX];
    int coldpath_len = (*env)->GetStringLength(env, oldpath);
    (*env)->GetStringUTFRegion(env, oldpath, 0, coldpath_len, coldpath);
    char cnewpath[PVFS_PATH_MAX];
    int cnewpath_len = (*env)->GetStringLength(env, newpath);
    (*env)->GetStringUTFRegion(env, newpath, 0, cnewpath_len, cnewpath);

    rc = jni_linkat(olddirfd, coldpath, newdirfd, cnewpath, (int) flags);
    if(rc < 0)
    {
        perror("jni_linkat error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_access */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_access (JNIEnv *env, jobject obj, jstring path, jlong mode)
{
    PFI

    int cpath_len = (*env)->GetStringLength(env, path);
    char cpath[cpath_len + 1];
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    
    int rc = jni_access(cpath, (mode_t) mode);
    if(rc < 0)
    {
        perror("jni_access error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_faccessat */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_faccessat (JNIEnv *env, jobject obj, int fd, jstring path, jlong mode, jlong flags)
{
    PFI

    int cpath_len = (*env)->GetStringLength(env, path);
    char cpath[cpath_len + 1];
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);

    int rc = jni_faccessat(fd, cpath, (mode_t) mode, (int) flags);
    if(rc < 0)
    {
        perror("jni_faccessat error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_flock */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_flock (JNIEnv *env, jobject obj, int fd, jlong op)
{
    PFI

    int rc = jni_flock(fd, (int) op);
    if(rc < 0)
    {
        perror("jni_flock error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_fcntl */
/* TODO handle variadic args!!! */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_fcntl(JNIEnv *env, jobject obj, int fd, jlong cmd)
{
    PFI

    int rc = jni_fcntl(fd, (int) cmd);
    if(rc < 0)
    {
        perror("jni_fcntl error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_fsync */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_fsync  (JNIEnv *env, jobject obj, int fd)
{
    PFI
    int rc = jni_fsync(fd);
    if(rc < 0)
    {
        perror("jni_fsync error");
        fflush(stdout);
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_fdatasync */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_fdatasync  (JNIEnv *env, jobject obj, int fd)
{
    PFI
    int rc = jni_fdatasync(fd);
    if(rc < 0)
    {
        perror("jni_fdatasync error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_fadvise */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_fadvise  (JNIEnv *env, jobject obj, int fd, jlong offset, jlong len, jlong advice)
{
    PFI
    int rc = jni_fadvise(fd, (off_t) offset, (off_t) len, (int) advice);
    if(rc < 0)
    {
        perror("jni_fadvise error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_fadvise64 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_fadvise64  (JNIEnv *env, jobject obj, int fd, jlong offset, jlong len, jlong advice)
{
    PFI
    int rc = jni_fadvise64(fd, (off_t) offset, (off_t) len, (int) advice);
    if(rc < 0)
    {
        perror("jni_fadvise64 error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_mknod */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_mknod  (JNIEnv *env, jobject obj, jstring path, jlong mode, int dev)
{
    PFI

    int cpath_len = (*env)->GetStringLength(env, path);
    char cpath[cpath_len + 1];
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);

    dev_t cdev = (dev_t) dev;

    int rc = jni_mknod(cpath, (mode_t) mode, cdev);
    if(rc < 0)
    {
        perror("jni_mknod error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_mknodat */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_mknodat (JNIEnv *env, jobject obj, int dirfd, jstring path, jlong mode, int dev)
{
    PFI

    int cpath_len = (*env)->GetStringLength(env, path);
    char cpath[cpath_len + 1];
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);

    dev_t cdev = (dev_t) dev;
    int rc = jni_mknodat(dirfd, cpath, (mode_t) mode, cdev);
    if(rc < 0)
    {
        perror("jni_mknodat error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_chdir */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_chdir  (JNIEnv *env, jobject obj, jstring path)
{
    PFI
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    int rc = jni_chdir(cpath);
    if(rc < 0)
    {
        perror("jni_chdir error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_fchdir */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_fchdir  (JNIEnv *env, jobject obj, int fd)
{
    PFI
    int rc = jni_fchdir(fd);
    if(rc < 0)
    {
        perror("jni_fchdir error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_umask */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_umask  (JNIEnv *env, jobject obj, jlong mask)
{
    PFI
    mode_t rc = jni_umask((mode_t) mask);
    if(rc < 0)
    {
        perror("jni_umask error");
        rc = -1;
    }
    JNI_FLUSH
    return (int) rc;
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_read(JNIEnv *env, jobject obj, int fd, jbyteArray buf, jlong count)
{
    PFI
    ssize_t rc = 0;
    jboolean is_copy;
    jbyte * buffer = (*env)->GetByteArrayElements(env, buf, &is_copy);
    if(JNI_DBG)
    {
        printf("\tfd = %d\n", fd);
        printf("\tcount = %lu\n", (uint64_t) count);
        is_copy == JNI_TRUE ? printf("\tbuf is_copy\n") : printf("\tbuf !is_copy\n");
    }
    if(!buffer)
    {
        perror("GetByteArrayElements");
        errno = EFAULT;
        rc = -1;
        goto done;
    }
    rc = jni_read(fd, (void *) buffer, (size_t) count);
    if(rc < 0)
    {
        perror("jni jni_read");
        rc = -1;
        goto done;
    }
    if(rc > 0)
    {
        if(JNI_DBG) printf("\tread %lld bytes\n", (long long int) rc);
    }
done:
    /* copy back and free the buffer using 0 */
    (*env)->ReleaseByteArrayElements(env, buf, buffer, 0);
    JNI_FLUSH
    return (jlong) rc;
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_pread(JNIEnv *env, jobject obj, int fd, jbyteArray buf, jlong count, jlong offset)
{
    PFI
    ssize_t rc = 0;
    jboolean is_copy;
    jbyte * buffer = (*env)->GetByteArrayElements(env, buf, &is_copy);
    if(JNI_DBG)
    {
        printf("Pread\n");
        printf("\tfd = %d\n", fd);
        printf("\tcount = %lu\n", (uint64_t) count);
        printf("\toffset = %lu\n", (uint64_t) offset);
        is_copy == JNI_TRUE ? printf("\tbuf is_copy\n") : printf("\tbuf !is_copy\n");
    }
    if(!buffer)
    {
        perror("GetByteArrayElements");
        errno = EFAULT;
        rc = -1;
        goto done;
    }
    rc = jni_pread(fd, (void *) buffer, (size_t) count, (off_t) offset);
    if(rc < 0)
    {
        perror("jni jni_pread");
    }
    else
    {
        if(JNI_DBG) printf("\tread %lld bytes\n", (long long int) rc);
    }
done:
    /* copy back and free the buffer using 0 */
    (*env)->ReleaseByteArrayElements(env, buf, buffer, 0);
    JNI_FLUSH
    return (jlong) rc;
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_pread64(JNIEnv *env, jobject obj, int fd, jbyteArray buf, jlong count, jlong offset)
{
    PFI
    ssize_t rc = 0;
    jboolean is_copy;
    jbyte * buffer = (*env)->GetByteArrayElements(env, buf, &is_copy);
    if(JNI_DBG)
    {
        printf("Pread64\n");
        printf("\tfd = %d\n", fd);
        printf("\tcount = %lu\n", (uint64_t) count);
        printf("\toffset = %lu\n", (uint64_t) offset);
        is_copy == JNI_TRUE ? printf("\tbuf is_copy\n") : printf("\tbuf !is_copy\n");
    }
    if(!buffer)
    {
        perror("GetByteArrayElements");
        errno = EFAULT;
        rc = -1;
        goto done;
    }
    rc = jni_pread64(fd, (void *) buffer, (size_t) count, (off64_t) offset);
    if(rc < 0)
    {
        perror("jni jni_pread64");
    }
    else
    {
        printf("\tread %lld bytes\n", (long long int) rc);
    }
done:
    /* copy back and free the buffer using 0 */
    (*env)->ReleaseByteArrayElements(env, buf, buffer, 0);
    JNI_FLUSH
    return (jlong) rc;
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_write(JNIEnv *env, jobject obj, int fd, jbyteArray buf, jlong count)
{
    PFI
    ssize_t rc = 0;
    jboolean is_copy;
    jbyte * buffer = (*env)->GetByteArrayElements(env, buf, &is_copy);
    if(JNI_DBG)
    {
        printf("Write\n");
        printf("\tfd = %d\n", fd);
        printf("\tcount = %lu\n", (uint64_t) count);
        is_copy == JNI_TRUE ? printf("\tbuf is_copy\n") :
            printf("\tbuf !is_copy\n");
    }
    if(!buffer)
    {
        perror("GetByteArrayElements");
        errno = EFAULT;
        rc = -1;
        goto done;
    }
    rc = jni_write(fd, (void *) buffer, (size_t) count);
    if(rc < 0)
    {
        perror("jni jni_write");
    }
    if(rc > 0)
    {
        printf("\twrote %lld bytes\n", (long long int) rc);
    }
done:
    /* free the buffer without copying back the possible changes in buffer
     * using JNI_ABORT
     */
    (*env)->ReleaseByteArrayElements(env, buf, buffer, JNI_ABORT);
    JNI_FLUSH
    return (jlong) rc;
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_pwrite(JNIEnv *env, jobject obj, int fd, jbyteArray buf, jlong count, jlong offset)
{
    PFI
    ssize_t rc = 0;
    jboolean is_copy;
    jbyte * buffer = (*env)->GetByteArrayElements(env, buf, &is_copy);
    if(JNI_DBG)
    {
        printf("Pwrite\n");
        printf("\tfd = %d\n", fd);
        printf("\tcount = %lu\n", (uint64_t) count);
        printf("\toffset = %lu\n", (uint64_t) offset);
        is_copy == JNI_TRUE ? printf("\tbuf is_copy\n") :
            printf("\tbuf !is_copy\n");
    }
    if(!buffer)
    {
        perror("GetByteArrayElements");
        errno = EFAULT;
        rc = -1;
    }
    rc = jni_pwrite(fd, (void *) buffer, (size_t) count, (off_t) offset);
    if(rc < 0)
    {
        perror("jni jni_pwrite");
    }
    else
    {
        if(JNI_DBG) printf("\twrote %lld bytes\n", (long long int) rc);
    }
done:
    /** free the buffer without copying back the possible changes in buffer
      * using JNI_ABORT
      */
    (*env)->ReleaseByteArrayElements(env, buf, buffer, JNI_ABORT);
    JNI_FLUSH
    return (jlong) rc;
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_pwrite64(JNIEnv *env, jobject obj, int fd, jbyteArray buf, jlong count, jlong offset)
{
    PFI
    ssize_t rc = 0;
    jboolean is_copy;
    jbyte * buffer = (*env)->GetByteArrayElements(env, buf, &is_copy);
    if(JNI_DBG)
    {
        printf("\tfd = %d\n", fd);
        printf("\tcount = %lu\n", (uint64_t) count);
        printf("\toffset = %lu\n", (uint64_t) offset);
        is_copy == JNI_TRUE ? printf("\tbuf is_copy\n") :
            printf("\tbuf !is_copy\n");
    }
    if(!buffer)
    {
        perror("GetByteArrayElements");
        errno = EFAULT;
        rc = -1;
        goto done;
    }
    rc = jni_pwrite64(fd, (void *) buffer, (size_t) count, (off_t) offset);
    if(rc < 0)
    {
        perror("jni jni_pwrite64");
    }
    else
    {
        if(JNI_DBG) printf("\twrote %lld bytes\n", (long long int) rc);
    }
done:
    /** Free the buffer without copying back the possible changes in buffer
     * using JNI_ABORT
     */
    (*env)->ReleaseByteArrayElements(env, buf, buffer, JNI_ABORT);
    JNI_FLUSH
    return (jlong) rc;
}

/* Note: Removed readv and writev ... */

/* Returns non-zero (true) if the supplied mode corresponds to a directory. */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_isDir(JNIEnv *env, jobject obj, int mode)
{
    PFI
    if(JNI_DBG) printf("mode = %d\n", mode);
    fflush(stdout);
    return S_ISDIR(mode);
}

/* Convert allocated struct to an instance of our Stat Class */
int fill_stat(JNIEnv *env, struct stat *ptr, jobject *inst)
{
    int num_fields = 13;
    char *field_names[] = {
        "st_dev", "st_ino", "st_mode",
        "st_nlink", "st_uid", "st_gid",
        "st_rdev", "st_size", "st_blksize",
        "st_blocks", "st_atime", "st_mtime", "st_ctime"};
    char *field_types[] = {
        "J", "J", "I",
        "I", "J", "J",
        "J", "J", "I",
        "J", "J", "J", "J"};
    jfieldID fids[num_fields];
    char *cls_name = "org/orangefs/usrint/Stat";
    jclass cls = (*env)->FindClass(env, cls_name);
    if(!cls)
    {
        fprintf(stderr, "invalid class: %s\n", cls_name);
        fill_error((void *) ptr);
        return -1;
    }
    int fid_index = 0;
    for(; fid_index < num_fields; fid_index++)
    {
        fids[fid_index] = GET_FIELD_ID(env, cls, 
            field_names[fid_index], field_types[fid_index]);
        if(!fids[fid_index])
        {
            fprintf(stderr, "invalid field requested: %s\n", field_names[fid_index]);
            fill_error((void *) ptr);
            return -1;
        }
    }
    *inst = (*env)->AllocObject(env, cls);
    /* Load object with data from structure using
     * constructor or set methods.
     */
    SET_LONG_FIELD(env, *inst, fids[0],ptr->st_dev);
    SET_LONG_FIELD(env, *inst, fids[1],ptr->st_ino);
    SET_INT_FIELD(env, *inst, fids[2],ptr->st_mode);
    SET_INT_FIELD(env, *inst, fids[3],ptr->st_nlink);
    SET_LONG_FIELD(env, *inst, fids[4],ptr->st_uid);
    SET_LONG_FIELD(env, *inst, fids[5],ptr->st_gid);
    SET_LONG_FIELD(env, *inst, fids[6],ptr->st_rdev);
    SET_LONG_FIELD(env, *inst, fids[7],ptr->st_size);
    SET_INT_FIELD(env, *inst, fids[8],ptr->st_blksize);
    SET_LONG_FIELD(env, *inst, fids[9],ptr->st_blocks);
    SET_LONG_FIELD(env, *inst, fids[10],ptr->st_atime);
    SET_LONG_FIELD(env, *inst, fids[11],ptr->st_mtime);
    SET_LONG_FIELD(env, *inst, fids[12],ptr->st_ctime);
    /* Free the space allocated for the stat struct and
     * return an instance of Stat.
     */
    JNI_FLUSH
    free(ptr);
    return 0;
}

/* jni_stat */
JNIEXPORT jobject JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_stat(JNIEnv *env, jobject obj, jstring path)
{
    PFI
    struct stat *ptr = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    ptr = (struct stat *) calloc(1, sizeof(struct stat));
    if(!ptr)
    {
        fprintf(stderr, "calloc couldn't allocate memory for struct stat!\n");
        fill_error((void *) ptr);
        goto err;
    }
    int rc = jni_stat(cpath, ptr);
    if(rc != 0)
    {
        perror("jni_stat error");
        fill_error((void *) ptr);
        goto err;
    }
    //TODO remove later
    else 
    {
        printf("jni_stat successful on %s\n", cpath);
    }

    jobject stat_obj;
    if(fill_stat(env, ptr, &stat_obj) == 0)
    {
        JNI_FLUSH
        return stat_obj;
    }
err:
    return (jobject) 0;
}

/* jni_fstat */
JNIEXPORT jobject JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_fstat(JNIEnv *env, jobject obj, int fd)
{
    PFI
    struct stat *ptr = 0;
    ptr = (struct stat *) calloc(1, sizeof(struct stat));
    if(!ptr)
    {
        fprintf(stderr, "couldn't allocate memory for struct stat!\n");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    int rc = jni_fstat(fd, ptr);
    if(rc != 0)
    {
        perror("jni_fstat error");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    jobject stat_obj;
    if(fill_stat(env, ptr, &stat_obj) == 0)
    {
        JNI_FLUSH;
        return stat_obj;
    }
    JNI_FLUSH
    return NULL_OBJ;
}

/* jni_fstatat */
JNIEXPORT jobject JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_fstatat(JNIEnv *env, jobject obj, int fd, jstring path, jlong flag)
{
    PFI
    struct stat *ptr = 0;

    int cpath_len = (*env)->GetStringLength(env, path);
    char cpath[cpath_len + 1];
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);

    ptr = (struct stat *) calloc(1, sizeof(struct stat));
    if(!ptr)
    {
        fprintf(stderr, "couldn't allocate memory for struct stat!\n");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    
    int rc = jni_fstatat(fd, cpath, ptr, (int) flag);
    if(rc < 0)
    {
        perror("jni_fstatat error");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    jobject stat_obj;
    if(fill_stat(env, ptr, &stat_obj) == 0)
    {
        JNI_FLUSH;
        return stat_obj;
    }
    JNI_FLUSH
    return NULL_OBJ;
}

/* jni_lstat */
JNIEXPORT jobject JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_lstat(JNIEnv *env, jobject obj, jstring path)
{
    PFI
    struct stat *ptr = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    ptr = (struct stat *) calloc(1, sizeof(struct stat));
    if(!ptr)
    {
        fprintf(stderr, "couldn't allocate memory for struct stat!\n");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    int rc = jni_lstat(cpath, ptr);
    if(rc < 0)
    {
        perror("jni_lstat error");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    jobject stat_obj;
    if(fill_stat(env, ptr, &stat_obj) == 0)
    {
        JNI_FLUSH;
        return stat_obj;
    }
    JNI_FLUSH
    return NULL_OBJ;
}

/* Convert allocated struct to an instance of our Stat64 Class */
int fill_stat64(JNIEnv *env, struct stat64 *ptr, jobject *inst)
{
    int num_fields = 13;
    char *field_names[] = {
        "st_dev", "st_ino", "st_mode",
        "st_nlink", "st_uid", "st_gid",
        "st_rdev", "st_size", "st_blksize",
        "st_blocks", "st_atime", "st_mtime", "st_ctime"};
    char *field_types[] = {
        "J", "J", "I",
        "I", "J", "J",
        "J", "J", "I",
        "J", "J", "J", "J"};
    jfieldID fids[num_fields];
    char *cls_name = "org/orangefs/usrint/Stat64";
    jclass cls = (*env)->FindClass(env, cls_name);
    if(!cls)
    {
        fprintf(stderr, "invalid class: %s\n", cls_name);
        fill_error((void *)ptr);
        return -1;
    }
    int fid_index = 0;
    for(; fid_index < num_fields; fid_index++)
    {
        fids[fid_index] = GET_FIELD_ID(env, cls,
            field_names[fid_index], field_types[fid_index]);
        if(!fids[fid_index])
        {
            fprintf(stderr, "invalid field requested: %s\n", field_names[fid_index]);
            fill_error((void *) ptr);
            return -1;
        }
    }
    *inst = (*env)->AllocObject(env, cls);
    /* Load object with data from structure using
     * constructor or set methods.
     */
    SET_LONG_FIELD(env, *inst, fids[0],ptr->st_dev);
    SET_LONG_FIELD(env, *inst, fids[1],ptr->st_ino);
    SET_INT_FIELD(env, *inst, fids[2],ptr->st_mode);
    SET_INT_FIELD(env, *inst, fids[3],ptr->st_nlink);
    SET_LONG_FIELD(env, *inst, fids[4],ptr->st_uid);
    SET_LONG_FIELD(env, *inst, fids[5],ptr->st_gid);
    SET_LONG_FIELD(env, *inst, fids[6],ptr->st_rdev);
    SET_LONG_FIELD(env, *inst, fids[7],ptr->st_size);
    SET_INT_FIELD(env, *inst, fids[8],ptr->st_blksize);
    SET_LONG_FIELD(env, *inst, fids[9],ptr->st_blocks);
    SET_LONG_FIELD(env, *inst, fids[10],ptr->st_atime);
    SET_LONG_FIELD(env, *inst, fids[11],ptr->st_mtime);
    SET_LONG_FIELD(env, *inst, fids[12],ptr->st_ctime);
    /* Free the space allocated for the stat struct and
     * return an instance of Stat64.
     */
    JNI_FLUSH
    free(ptr);
    return 0;
}

/* jni_stat64 */
JNIEXPORT jobject JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_stat64(JNIEnv *env, jobject obj, jstring path)
{
    PFI
    struct stat64 *ptr = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    ptr = (struct stat64 *) calloc(1, sizeof(struct stat64));
    if(!ptr)
    {
        fprintf(stderr, "couldn't allocate memory for struct stat64!\n");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    int rc = jni_stat64(cpath, ptr);
    if(rc < 0)
    {
        perror("jni_stat64 error");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }

    jobject stat64_obj;
    if(fill_stat64(env, ptr, &stat64_obj) == 0)
    {
        JNI_FLUSH
        return stat64_obj;
    }
    JNI_FLUSH
    return NULL_OBJ;
}

/* jni_Fstat64 */
JNIEXPORT jobject JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_fstat64(JNIEnv *env, jobject obj, int fd)
{
    PFI
    struct stat64 *ptr = 0;
    ptr = (struct stat64 *) calloc(1, sizeof(struct stat64));
    if(!ptr)
    {
        fprintf(stderr, "couldn't allocate memory for struct stat64!\n");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    int rc = jni_fstat64(fd, ptr);
    if(rc < 0)
    {
        perror("jni_fstat64 error");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }

    jobject stat64_obj;
    if(fill_stat64(env, ptr, &stat64_obj) == 0)
    {
        return stat64_obj;
    }
    JNI_FLUSH
    return NULL_OBJ;
}

/* jni_Fstatat64 */
JNIEXPORT jobject JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_fstatat64(JNIEnv *env, jobject obj, int fd, jstring path, jlong flag)
{
    PFI
    struct stat64 *ptr = 0;

    int cpath_len = (*env)->GetStringLength(env, path);
    char cpath[cpath_len + 1];
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);

    ptr = (struct stat64 *) calloc(1, sizeof(struct stat64));
    if(!ptr)
    {
        fprintf(stderr, "couldn't allocate memory for struct stat64!\n");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }

    int rc = jni_fstatat64(fd, cpath, ptr, (int) flag);
    if(rc < 0)
    {
        perror("jni_fstatat64 error");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }

    jobject stat64_obj;
    if(fill_stat64(env, ptr, &stat64_obj) == 0)
    {
        return stat64_obj;
    }
    JNI_FLUSH
    return NULL_OBJ;
}

/* jni_lstat64 */
JNIEXPORT jobject JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_lstat64(JNIEnv *env, jobject obj, jstring path)
{
    PFI
    struct stat64 *ptr = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    ptr = (struct stat64 *) calloc(1, sizeof(struct stat64));
    if(!ptr)
    {
        fprintf(stderr, "couldn't allocate memory for struct stat64!\n");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    int rc = jni_lstat64(cpath, ptr);
    if(rc < 0)
    {
        perror("jni_lstat64 error");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }

    jobject stat64_obj;
    if(fill_stat64(env, ptr, &stat64_obj) == 0)
    {
        return stat64_obj;
    }
    JNI_FLUSH
    return NULL_OBJ;
}

/* TODO */
#if 0
/* jni_readdir */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_readdir  (JNIEnv *env, jobject obj, jlong jarg, int fd, int count)
{
    PFI
    int rc = 0;
    struct dirent *arg;
    arg = (struct dirent *)jarg;
    unsigned int cfd = (unsigned int) fd;
    unsigned int ccount = (unsigned int) count;
    rc = jni_readdir(cfd, arg, ccount);
    if(rc < 0)
    {
        perror("jni_readdir error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}


/* jni_getdents */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_getdents  (JNIEnv *env, jobject obj, jlong jarg, int fd, int size)
{
    PFI
    int rc = 0;
    struct dirent *arg;
    arg = (struct dirent *)jarg;
    unsigned int cfd = (unsigned int) fd;
    unsigned int csize = (unsigned int) size;
    rc = jni_getdents(cfd, arg, csize);
    if(rc < 0)
    {
        perror("jni_getdents error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_getdents64 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_getdents64  (JNIEnv *env, jobject obj, jlong jarg, int fd, int size)
{
    PFI
    int rc = 0;
    struct dirent64 *arg;
    arg = (struct dirent64 *)jarg;
    unsigned int cfd = (unsigned int) fd;
    unsigned int csize = (unsigned int) size;
    rc = jni_getdents64(cfd, arg, csize);
    if(rc < 0)
    {
        perror("jni_getdents64 error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}
#endif

/* fill_timeval */
int fill_timeval(JNIEnv *env, struct timeval *ptr, jobject *inst)
{
    int num_fields = 2;
    char *field_names[] = {
        "tv_sec", "tv_usec"};
    char *field_types[] = {
        "[J","[J"};
    jfieldID fids[num_fields];
    char *cls_name = "org/orangefs/usrint/Timeval";
    jclass cls = (*env)->FindClass(env, cls_name);
    if(!cls)
    {
        fprintf(stderr, "invalid class: %s\n", cls_name);
        fill_error((void *) ptr);
        return -1;
    }
    int fid_index = 0;
    for(; fid_index < num_fields; fid_index++)
    {
        fids[fid_index] = GET_FIELD_ID(env, cls, 
            field_names[fid_index], field_types[fid_index]);
        if(!fids[fid_index])
        {
            fprintf(stderr, "invalid field requested: %s\n", field_names[fid_index]);
            fill_error((void *) ptr);
            return -1;
        }
    }
    jmethodID mid = (*env)->GetMethodID(env,cls, "<init>", "()V");
    *inst = (*env)->NewObject(env,cls,mid);
    jlongArray ar;
    jlongArray ar1;
    int jval;
    jlong cbuf[2];
    jlong cbuf1[2];
    for(jval = 0; jval < 2; jval++)
    {
        cbuf[jval]=ptr[jval].tv_sec;
    }
    for(jval = 0; jval < 2; jval++)
    {
        cbuf1[jval]=ptr[jval].tv_usec;
    }
    //printf("cbuf[0]=%ld",cbuf[0]);
    //printf("cbuf[0]=%ld",cbuf[]);
    ar = (*env)->GetObjectField(env, *inst , fids[0]);
    (*env)->SetLongArrayRegion(env, ar, 0, 2, cbuf);
    ar1 = (*env)->GetObjectField(env, *inst , fids[1]);
    (*env)->SetLongArrayRegion(env, ar1, 0, 2, cbuf1);
    /* Free the space allocated for the stat struct and
     return an instance of Timeval. */
    JNI_FLUSH
    free(ptr);
    return 0;
}

/* jni_utimes */
JNIEXPORT jobject JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_utimes (JNIEnv *env, jobject obj, jstring path)
{
    PFI
    struct timeval *ptr = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    ptr = (struct timeval *) calloc(1, 2 * sizeof(struct timeval));
    if(!ptr)
    {
        fprintf(stderr, "couldn't allocate memory for struct timeval!\n");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    int rc = jni_utimes(cpath, ptr);
    if(rc < 0)
    {
        perror("jni_utimes error");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    jobject timeval_obj;
    if(fill_timeval(env, ptr, &timeval_obj) == 0)
    {
        JNI_FLUSH;
        return timeval_obj;
    }
    JNI_FLUSH
    return NULL_OBJ; 
}

/* jni_futimes */
JNIEXPORT jobject JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_futimes (JNIEnv *env, jobject obj, int fd)
{
    PFI
    struct timeval *ptr = 0;
    ptr = (struct timeval *) calloc(1, 2 * sizeof(struct timeval));
    if(!ptr)
    {
        fprintf(stderr, "couldn't allocate memory for struct timeval!\n");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    int rc = jni_futimes(fd, ptr);
    if(rc < 0)
    {
        perror("jni_futimes error");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    jobject timeval_obj;
    if(fill_timeval(env, ptr, &timeval_obj) == 0)
    {
        JNI_FLUSH;
        return timeval_obj;
    }
    JNI_FLUSH
    return NULL_OBJ; 
}

/* jni_futimesat */
JNIEXPORT jobject JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_futimesat (JNIEnv *env, jobject obj, int dirfd, jstring path)
{
    PFI
    struct timeval *ptr = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    ptr = (struct timeval *) calloc(1, 2 * sizeof(struct timeval));
    if(!ptr)
    {
        fprintf(stderr, "couldn't allocate memory for struct timeval!\n");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    int rc = jni_futimesat(dirfd,cpath, ptr);
    if(rc < 0)
    {
        perror("jni_futimesat error");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    jobject timeval_obj;
    if(fill_timeval(env, ptr, &timeval_obj) == 0)
    {
        JNI_FLUSH;
        return timeval_obj;
    }
    JNI_FLUSH
    return NULL_OBJ;  
}

/* fill_utimbuf */
int fill_utimbuf(JNIEnv *env, struct utimbuf *ptr, jobject *inst)
{
    int num_fields = 2;
    char *field_names[] = {
        "actime", "modtime"};
    char *field_types[] = {
        "J", "J"};
    jfieldID fids[num_fields];
    char *cls_name = "org/orangefs/usrint/Utimbuf";
    jclass cls = (*env)->FindClass(env, cls_name);
    if(!cls)
    {
        fprintf(stderr, "invalid class: %s\n", cls_name);
        fill_error((void *) ptr);
        return -1;
    }
    int fid_index = 0;
    for(; fid_index < num_fields; fid_index++)
    {
        fids[fid_index] = GET_FIELD_ID(env, cls, 
            field_names[fid_index], field_types[fid_index]);
        if(!fids[fid_index])
        {
            fprintf(stderr, "invalid field requested: %s\n", field_names[fid_index]);
            fill_error((void *) ptr);
            return -1;
        }
    }
    *inst = (*env)->AllocObject(env, cls);
    /* Load object with data from structure using
     * constructor or set methods.
     */
    SET_LONG_FIELD(env, *inst, fids[0],ptr->actime);
    SET_LONG_FIELD(env, *inst, fids[1],ptr->modtime);
    /* Free the space allocated for the stat struct and
     * return an instance of Stat.
     */
    JNI_FLUSH
    free(ptr);
    return 0;
}

/* jni_utime */
JNIEXPORT jobject JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_utime(JNIEnv *env, jobject obj, jstring path)
{
    PFI
    struct utimbuf *ptr = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    ptr = (struct utimbuf *) calloc(1, sizeof(struct utimbuf));
    if(!ptr)
    {
        fprintf(stderr, "couldn't allocate memory for struct utimbuf!\n");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    int rc = jni_utime(cpath, ptr);
    if(rc < 0)
    {
        perror("jni_utime error");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    jobject utimbuf_obj;
    if(fill_utimbuf(env, ptr, &utimbuf_obj) == 0)
    {
        JNI_FLUSH;
        return utimbuf_obj;
    }
    JNI_FLUSH
    return NULL_OBJ;
}

/* jni_listxattr */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_listxattr (JNIEnv *env, jobject obj, jstring path, jstring list, jlong size)
{
    PFI
    long rc = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    char clist[PVFS_MAX_XATTR_LISTLEN];
    int clist_len = (*env)->GetStringLength(env, list);
    (*env)->GetStringUTFRegion(env, list, 0, clist_len, clist);
    size_t csize = (size_t) size;
    rc = jni_listxattr(cpath, clist, csize);
    if(rc < 0)
    {
        perror("jni_listxattr error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_llistxattr */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_llistxattr (JNIEnv *env, jobject obj, jstring path, jstring list, jlong size)
{
    PFI
    long rc = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    char clist[PVFS_MAX_XATTR_LISTLEN];
    int clist_len = (*env)->GetStringLength(env, list);
    (*env)->GetStringUTFRegion(env, list, 0, clist_len, clist);
    size_t csize = (size_t) size;
    rc = jni_llistxattr(cpath, clist, csize);
    if(rc < 0)
    {
        perror("jni_llistxattr error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_flistxattr */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_flistxattr (JNIEnv *env, jobject obj, int fd, jstring list, jlong size)
{
    PFI
    long rc = 0;
    char clist[PVFS_MAX_XATTR_LISTLEN];
    int clist_len = (*env)->GetStringLength(env, list);
    (*env)->GetStringUTFRegion(env, list, 0, clist_len, clist);
    size_t csize = (size_t) size;
    rc = jni_flistxattr(fd, clist, csize);
    if(rc < 0)
    {
        perror("jni_flistxattr error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_removexattr */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_removexattr(JNIEnv *env, jobject obj, jstring path, jstring name)
{
    PFI
    int rc = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    char cname[PVFS_NAME_MAX];
    int cname_len = (*env)->GetStringLength(env, name);
    (*env)->GetStringUTFRegion(env, name, 0, cname_len, cname);
    rc = jni_removexattr(cpath, cname);
    if(rc < 0)
    {
        perror("jni_removexattr error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_lremovexattr */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_lremovexattr(JNIEnv *env, jobject obj, jstring path, jstring name)
{
    PFI
    int rc = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    char cname[PVFS_NAME_MAX];
    int cname_len = (*env)->GetStringLength(env, name);
    (*env)->GetStringUTFRegion(env, name, 0, cname_len, cname);
    rc = jni_lremovexattr(cpath, cname);
    if(rc < 0)
    {
        perror("jni_Lremovexattr error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_fremovexattr */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_fremovexattr(JNIEnv *env, jobject obj, int fd, jstring name)
{
    PFI
    int rc = 0;
    char cname[PVFS_NAME_MAX];
    int cname_len = (*env)->GetStringLength(env, name);
    (*env)->GetStringUTFRegion(env, name, 0, cname_len, cname);
    rc = jni_fremovexattr(fd, cname);
    if(rc < 0)
    {
        perror("jni_fremovexattr error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_getumask */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_getumask(JNIEnv *env, jobject obj)
{
    PFI
    mode_t rc = jni_getumask();
    long ret = (long) rc;
    JNI_FLUSH
    return ret;
}

/* jni_getdtablesize */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_getdtablesize(JNIEnv *env, jobject obj)
{
    PFI
    int rc = jni_getdtablesize();
    JNI_FLUSH
    return rc;
}

/* jni_sync */
JNIEXPORT void JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_sync(JNIEnv *env, jobject obj)
{
    PFI
    jni_sync();
    JNI_FLUSH
    return;
}

/* Convert allocated struct to an instance of our Statfs Class */
int fill_statfs(JNIEnv *env, struct statfs *ptr, jobject *inst)
{
    int num_fields = 12;
    char *field_names[] = {
        "f_type", "f_bsize", "f_blocks",
        "f_bfree", "f_bavail", "f_files",
        "f_ffree", "f_flags", "f_namelen",
        "f_frsize","f_spare","f_fsid"};
    char *field_types[] = {
        "J", "J", "J",
        "J", "J", "J",
        "J", "J", "J",
        "J","[J","[I"};
    jfieldID fids[num_fields];
    char *cls_name = "org/orangefs/usrint/Statfs";
    jclass cls = (*env)->FindClass(env, cls_name);
    if(!cls)
    {
        fprintf(stderr, "invalid class: %s\n", cls_name);
        fill_error((void *) ptr);
        return -1;
    }
    int fid_index = 0;
    for(; fid_index < num_fields; fid_index++)
    {
        fids[fid_index] = GET_FIELD_ID(env, cls, 
            field_names[fid_index], field_types[fid_index]);
        if(!fids[fid_index])
        {
            fprintf(stderr, "invalid field requested: %s\n", field_names[fid_index]);
            fill_error((void *) ptr);
            return -1;
        }
    }
    
    jmethodID mid = (*env)->GetMethodID(env,cls, "<init>", "()V");
    *inst = (*env)->NewObject(env,cls,mid);
    jlongArray ar;
    jlongArray ar1;
    int jval;
    jlong cbuf[5];
    jlong cbuf1[2];
    for(jval = 0; jval < 5; jval++)
    {
        cbuf[jval]=ptr->f_spare[jval];
        
    }
    for(jval = 0; jval < 2; jval++)
    {
        cbuf1[jval]=ptr->f_fsid.__val[jval];
        
    }
    /* Load object with data from structure using
     * constructor or set methods.
     */
    SET_LONG_FIELD(env, *inst, fids[0],ptr->f_type);
    SET_LONG_FIELD(env, *inst, fids[1],ptr->f_bsize);
    SET_LONG_FIELD(env, *inst, fids[2],ptr->f_blocks);
    SET_LONG_FIELD(env, *inst, fids[3],ptr->f_bfree);
    SET_LONG_FIELD(env, *inst, fids[4],ptr->f_bavail);
    SET_LONG_FIELD(env, *inst, fids[5],ptr->f_files);
    SET_LONG_FIELD(env, *inst, fids[6],ptr->f_ffree);
    SET_LONG_FIELD(env, *inst, fids[7],ptr->f_flags);
    SET_LONG_FIELD(env, *inst, fids[8],ptr->f_namelen);
    SET_LONG_FIELD(env, *inst, fids[9],ptr->f_frsize);

    ar = (*env)->GetObjectField(env, *inst , fids[10]);
    (*env)->SetLongArrayRegion(env, ar, 0, 5, cbuf);
    
    ar1 = (*env)->GetObjectField(env, *inst , fids[11]);
    (*env)->SetLongArrayRegion(env, ar1, 0, 2, cbuf1);

    /* Free the space allocated for the stat struct and
     return an instance of Statfs. */
    JNI_FLUSH
    free(ptr);
    return 0;
}

/* jni_statfs */
JNIEXPORT jobject JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_statfs(JNIEnv *env, jobject obj, jstring path)
{
    PFI
    struct statfs *ptr = 0;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    ptr = (struct statfs *) calloc(1, sizeof(struct statfs));
    if(!ptr)
    {
        fprintf(stderr, "couldn't allocate memory for struct statfs!\n");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    int rc = jni_statfs(cpath, ptr);
    
    if(rc < 0)
    {
        perror("jni_statfs error");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }

    jobject statfs_obj;
    if(fill_statfs(env, ptr, &statfs_obj) == 0)
    {
        JNI_FLUSH;
        return statfs_obj;
    }
    JNI_FLUSH
    return NULL_OBJ;
}

/* jni_fstatfs */
JNIEXPORT jobject JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_fstatfs(JNIEnv *env, jobject obj, int fd)
{
    PFI
    struct statfs *ptr = 0;
    ptr = (struct statfs *) calloc(1, sizeof(struct statfs));
    if(!ptr)
    {
        fprintf(stderr, "couldn't allocate memory for struct statfs!\n");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    int rc = jni_fstatfs(fd, ptr);
    if(rc < 0)
    {
        perror("jni_fstatfs error");
        fill_error((void *) ptr);
        return NULL_OBJ;
    }
    jobject statfs_obj;
    if(fill_statfs(env, ptr, &statfs_obj) == 0)
    {
        JNI_FLUSH;
        return statfs_obj;
    }
    JNI_FLUSH
    return NULL_OBJ;
}

/* TODO */
#if 0
/* jni_statfs64 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_statfs64  (JNIEnv *env, jobject obj, jlong jarg, jstring path)
{
    PFI
    int rc = 0;
    struct statfs64 *arg;
    arg = (struct statfs64 *)jarg;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    rc = jni_statfs64(cpath, arg);
    if(rc < 0)
    {
        perror("jni_statfs64 error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_fstatfs64 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_fstatfs64(JNIEnv *env, jobject obj, jlong jarg, int fd)
{
    PFI
    int rc = 0;
    struct statfs64 *arg;
    arg = (struct statfs64 *)jarg;
    rc = jni_fstatfs64(fd, arg);
    if(rc < 0)
    {
        perror("jni_fstatfs64 error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_statvfs */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_statvfs  (JNIEnv *env, jobject obj, jlong jarg, jstring path)
{
    PFI
    int rc = 0;
    struct statvfs *arg;
    arg = (struct statvfs *)jarg;
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    rc = jni_statvfs(cpath, arg);
    if(rc < 0)
    {
        perror("jni_statvfs error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}

/* jni_fstatvfs */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2POSIXJNI_fstatvfs(JNIEnv *env, jobject obj, jlong jarg, int fd)
{
    PFI
    int rc = 0;
    struct statvfs *arg;
    arg = (struct statvfs *)jarg;
    rc = jni_fstatvfs(fd, arg);
    if(rc < 0)
    {
        perror("jni_fstatvfs error");
        rc = -1;
    }
    JNI_FLUSH
    return rc;
}
#endif
