/* 
 * (C) 2011 Clemson University
 *
 * See COPYING in top-level directory.
 */

#define _GNU_SOURCE

/* Include our headers that wrap calls present in stdio.c */
#include <jni_stdio.h>

/* Include other headers */
#include <stdlib.h>
#include <sys/types.h>
#include <dirent.h>
#include <pvfs2-types.h>
#include <errno.h>
#include <malloc.h>
#include <string.h>
#include <pwd.h>
#include <grp.h>

/* Our header generated by "javah" */
#include "org_orangefs_usrint_PVFS2STDIOJNI.h"

/* Header file that includes definitions and macros used by both POSIX and
 * STDIO libs */
#include "libPVFS2JNI_common.h"

/* Forward declarations of non-native functions */
int get_username_by_uid(uid_t uid, char *username);
int get_groupname_by_gid(gid_t gid, char *groupname);
int get_comb_len(char* s1, char* s2);
char *combine(char* s1, char* s2, char* dest);
int remove_files_in_dir(char *dir, DIR* dirp);
int recursive_delete(char *dir);
void fill_error(void *ptr);
int fill_dirent(JNIEnv *env, struct dirent *ptr, jobject *inst);

/********** BEGIN code related to filling PVFS2STDIOJNIFlags class */
/* Fill PVFS2STDIOJNIFlags object */
JNIEXPORT jobject JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_fillPVFS2STDIOJNIFlags(
    JNIEnv *env, 
    jobject obj
)
{
    int num_fields = 14;
    jfieldID fids[num_fields];
    char *field_names[] = 
    {
        "SEEK_SET", "SEEK_CUR", "SEEK_END", 
        "O_EXCL", "O_APPEND", "O_SYNC", 
        "DT_BLK", "DT_CHR", "DT_DIR", 
        "DT_FIFO", "DT_LNK", "DT_REG", 
        "DT_SOCK", "DT_UNKNOWN"
    };
    char *field_types[] = 
    {
        "J", "J", "J",
        "J", "J", "J",
        "J", "J", "J",
        "J", "J", "J",
        "J", "J"
        
    };

    char *cls_name = "org/orangefs/usrint/PVFS2STDIOJNIFlags";
    jclass cls = (*env)->FindClass(env, cls_name);
    if(!cls)
    {
        fprintf(stderr, "invalid class: %s\n", cls_name);
        return;
    }
    /* Allocates Memory for the Object specified by cls w/o calling its 
     * constructor. 
     */
    jobject inst = (*env)->AllocObject(env, cls);
    /* Get the field ids */
    int fid_index = 0;
    for(; fid_index < num_fields; fid_index++)
    {
        fids[fid_index] = GET_FIELD_ID(env, cls, 
            field_names[fid_index], field_types[fid_index]);
        if(!fids[fid_index])
        {
            fprintf(stderr, "invalid field requested: %s\n", field_names[fid_index]);
            return;
        }
        
    }

    /* Load PVFS2STDIOJNIFlags object with data replaced by C-Preprocessor 
     * using set methods.
     */
    SET_LONG_FIELD(env, inst, fids[0], SEEK_SET);
    SET_LONG_FIELD(env, inst, fids[1], SEEK_CUR);
    SET_LONG_FIELD(env, inst, fids[2], SEEK_END);
    //SET_LONG_FIELD(env, inst, fids[3], O_EXCL);
    //SET_LONG_FIELD(env, inst, fids[4], O_APPEND);
    //SET_LONG_FIELD(env, inst, fids[5], O_SYNC);
    SET_LONG_FIELD(env, inst, fids[6], DT_BLK );
    SET_LONG_FIELD(env, inst, fids[7], DT_CHR);
    SET_LONG_FIELD(env, inst, fids[8], DT_DIR);
    SET_LONG_FIELD(env, inst, fids[9], DT_FIFO);

    SET_LONG_FIELD(env, inst, fids[10], DT_LNK);
    SET_LONG_FIELD(env, inst, fids[11], DT_REG);
    SET_LONG_FIELD(env, inst, fids[12], DT_SOCK);
    SET_LONG_FIELD(env, inst, fids[13], DT_UNKNOWN);
    
    JNI_FLUSH
    return inst;
}
/********** END code related to filling PVFS2STDIOJNIFlags class */

/********** BEGIN code related to getFileStatus **********/

/* Usernames are limited to 256 characters + 1 for null terminating char */
#define MAX_USERNAME_LENGTH 257 
/* Groupnames are limited to 1024 characters + 1 for null terminating char */
#define MAX_GROUPNAME_LENGTH 1025

int get_username_by_uid(uid_t uid, char *username)
{
    errno = 0;
    struct passwd *pwdp = getpwuid(uid);
    if(pwdp == NULL)
    {
        jni_perror("getpwuid");
        return -1;
    }
    strcpy(username, pwdp->pw_name);
    return 0;
}

int get_groupname_by_gid(gid_t gid, char *groupname)
{
    errno = 0;
    struct group* groupp = getgrgid(gid);
    if(groupp == NULL)
    {
        jni_perror("getgrid");
        return -1;
    }
    strcpy(groupname, groupp->gr_name);
    return 0;

}

JNIEXPORT jobjectArray JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_getUsernameGroupname(
    JNIEnv *env, 
    jobject obj,
    jint uid,
    jint gid
)
{
    PFI
    int rc = 0;
    jobjectArray ret = NULL;
    char username[MAX_USERNAME_LENGTH];
    char groupname[MAX_GROUPNAME_LENGTH];
    memset(username, 0, MAX_USERNAME_LENGTH);
    memset(groupname, 0, MAX_GROUPNAME_LENGTH);

    rc = get_username_by_uid(uid, username);
    if(rc != 0)
    {
        goto err;
    }
    //jni_printf("uid, username = <%u, %s>\n", uid, username);

    rc = get_groupname_by_gid(gid, groupname);
    if(rc != 0)
    {
        goto err;
    }
    //jni_printf("gid, groupname = <%u, %s>\n", gid, groupname);

    ret = (*env)->NewObjectArray(env, (jsize) 2, 
        (*env)->FindClass(env, "java/lang/String"), 
        (*env)->NewStringUTF(env, ""));

    (*env)->SetObjectArrayElement(env, ret, 0, (*env)->NewStringUTF(env, username));
    (*env)->SetObjectArrayElement(env, ret, 1, (*env)->NewStringUTF(env, groupname));

err:
    JNI_FLUSH
    return (jobjectArray) ret;
}

/********** END code related to getFileStatus **********/

/********** BEGIN functions related to listStatus **********/

/* Return the directory entries of this directory as an array of Java Strings */
JNIEXPORT jobjectArray JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_getFilesInDir(
    JNIEnv *env, 
    jobject obj, 
    jstring path
)
{
    PFI
    jobjectArray ret = (jobjectArray) NULL;

    char cpath[PVFS_NAME_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);

    DIR*dirp = NULL;
    struct dirent * direntp = NULL;

    /* Open the directory specified by cpath */
    errno = 0;
    dirp = jni_opendir(cpath);
    if(!dirp)
    {
        jni_perror("opendir");
        goto err;
    }

    /* Iterate over directory entries counting entries we're concerned with. */
    int cnt = 0;
    do
    {
        errno = 0;
        direntp = jni_readdir(dirp);
        if(direntp)
        {
            if(DOTDIR(direntp->d_name))
            {
                continue;
            }
            cnt++;
        }
    } while(direntp);

    if(JNI_DBG) jni_printf("dir entries = %d\n", cnt);

    /* Now that we know how many entry names we're storing, 
     * make space and copy strings. */
    if(cnt > 0)
    {
        char fileNames[cnt][PVFS_PATH_MAX];
        memset(fileNames, 0, cnt * PVFS_PATH_MAX);
        jni_rewinddir(dirp);
        int i = 0;
        do
        {
            errno = 0;
            direntp = jni_readdir(dirp);
            if(direntp)
            {
                if(DOTDIR(direntp->d_name))
                {
                    continue;
                }
                strcpy(fileNames[i], direntp->d_name);
                i++;
            }
        } while(direntp);

        ret = (*env)->NewObjectArray(env, (jsize) cnt, 
            (*env)->FindClass(env, "java/lang/String"), 
            (*env)->NewStringUTF(env, ""));
        /* Fill object array */
        for(i = 0; i < cnt; i++)
        {
            jobject fileName = (*env)->NewStringUTF(env, fileNames[i]);
            (*env)->SetObjectArrayElement(env, ret, i, fileName);
        }
    }

err:
    JNI_FLUSH
    return (jobjectArray) ret;
}

/********** END functions related to listStatus **********/


/********** BEGIN functions related to recursive delete operation **********/

/** Return the length of the resulting string assuming s1 and s2 will be 
 * combined with a seperating slash and null terminating byte.
 */
int get_comb_len(char* s1, char* s2)
{
    return (int) (strlen(s1) + strlen(s2) + 2);
}

/** Combine the two strings with a forward slash between. 
 * Don't forget to memset the string!!! The resulting string is stored in dest.
 * Ensure dest is large enough to contain the resulting string.
 */
char *combine(char* s1, char* s2, char* dest)
{
    strcat(dest, s1);
    strcat(dest, "/");
    return strcat(dest, s2);
}

/* Remove all files discovered in the open directory pointed to by dirp. */
int remove_files_in_dir(char *dir, DIR* dirp)
{
    int rc = 0;
    struct dirent* direntp = NULL;
    /* Rewind this directory stream back to the beginning. */
    jni_rewinddir(dirp);

    /* Loop over directory contents */
    do
    {
        errno = 0; /* reset errno for every readdir call */
        direntp = jni_readdir(dirp);
        if(direntp && (direntp->d_type != DT_DIR))
        {
            size_t abs_path_len = get_comb_len(dir, direntp->d_name);
            char abs_path[abs_path_len];
            memset((void *)abs_path, 0, abs_path_len);
            combine(dir, direntp->d_name, abs_path);
            errno = 0;
            if(pvfs_unlink(abs_path) == -1)
            {
                jni_perror("remove");
                rc = -1;
                goto err;
            }
        }
        else
        {
            /* Print errno only if it's set */
            if(errno)
            {
                jni_perror("readdir error");
                rc = -1;
                goto err;
            }
        }
    } while(direntp != NULL);
    rc = 0;

err:
    JNI_FLUSH
    return rc;
}

/* Recursively delete the path specified by dir. */
int recursive_delete(char *dir)
{
    int rc = 0;
    DIR*dirp = NULL;
    struct dirent * direntp = NULL;

    /* Open the directory specified by dir */
    errno = 0;
    dirp = jni_opendir(dir);
    if(!dirp)
    {
        jni_perror("opendir");
        rc = -1;
        goto err;
    }

    /* Remove all files in the current directory */
    if(remove_files_in_dir(dir, dirp) != 0)
    {
        jni_fprintf(stderr, "remove_files_in_dir failed on directory: %s\n", dir);
        rc = -1;
        goto err;
    }

    /* Rewind directory stream and call recursive delete on the directories 
     * in this directory.
     */
    jni_rewinddir(dirp);
    do
    {
        direntp = jni_readdir(dirp);
        if(direntp && (direntp->d_type == DT_DIR))
        {
            if(DOTDIR(direntp->d_name))
            {
                continue;
            }
            int dir_abs_len = get_comb_len(dir, direntp->d_name);
            char dir_abs[dir_abs_len];
            memset(dir_abs, 0, dir_abs_len);
            combine(dir, direntp->d_name, dir_abs);
            recursive_delete(dir_abs);
        }
    } while(direntp);

    /* Close current directory before we attempt removal */
    if(jni_closedir(dirp) != 0)
    {
        jni_perror("closedir");
        rc = -1;
        goto err;
    }

    if(pvfs_rmdir(dir) != 0)
    {
        jni_perror("remove");
        rc = -1;
    }
    rc = 0;

err:
    JNI_FLUSH
    return rc;
}

/* recursive_delete */
JNIEXPORT int JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_recursiveDelete(
    JNIEnv *env, 
    jobject obj, 
    jstring path
)
{
    PFI
    int rc = 0;
    char cpath[PVFS_NAME_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    rc = recursive_delete(cpath);
    if(rc == -1)
    {
        jni_fprintf(stderr, "recursiveDelete error\n");
    }
err:
    JNI_FLUSH
    return rc;
}

/********** END OF recursive delete related functions **********/

void fill_error(void *ptr)
{
    if(ptr)
    {
        free(ptr);
    }
    JNI_FLUSH;
}

/* Convert allocated struct DIR to an instance of our Dirent Class */
int fill_dirent(JNIEnv *env, struct dirent *ptr, jobject *inst)
{
    int rc = 0;
    int num_fields = 5;
    char *field_names[] = {
        "d_ino", "d_off", "d_reclen", "d_type", "d_name"};
    char *field_types[] = {
        "J", "J", "I", "Ljava/lang/String;", "Ljava/lang/String;"};
    jfieldID fids[num_fields];
    char *cls_name = "org/orangefs/usrint/Dirent";
    jclass cls = (*env)->FindClass(env, cls_name);
    if(!cls)
    {
        jni_fprintf(stderr, "invalid class: %s\n", cls_name);
        fill_error((void *) 0);
        rc = -1;
        goto err;
    }
    int fid_index = 0;
    for(; fid_index < num_fields; fid_index++)
    {
        fids[fid_index] = GET_FIELD_ID(env, cls, 
            field_names[fid_index], field_types[fid_index]);
        if(!fids[fid_index])
        {
            jni_fprintf(stderr, "invalid field requested: %s\n", field_names[fid_index]);
            fill_error((void *) 0);
            rc = -1;
            goto err;
        }
    }

    *inst = (*env)->AllocObject(env, cls);

    /* Load object with data from structure using
     * constructor or set methods.
     */
    SET_LONG_FIELD(env, *inst, fids[0], ptr->d_ino);
    SET_LONG_FIELD(env, *inst, fids[1], ptr->d_off);
    SET_INT_FIELD(env, *inst, fids[2], ptr->d_reclen);
    SET_CHAR_FIELD(env, *inst, fids[3], (char) ptr->d_type);
    jstring d_name_string = (*env)->NewStringUTF(env, ptr->d_name);
    SET_OBJECT_FIELD(env, *inst, fids[4], d_name_string);

err:
    free(ptr);
    JNI_FLUSH
    return 0;
}

/* malloc */
JNIEXPORT long JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_malloc(JNIEnv *env, jobject obj, jlong size)
{
    PFI
    void *ptr = malloc((size_t) size);
    if(!ptr)
    {
        jni_perror("malloc failed");
    }
    return (long unsigned int) ptr;
}

/* free */
JNIEXPORT void JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_free(JNIEnv *env, jobject obj, jlong ptr)
{
    PFI
    free((void *) ptr);
}

/* fopen */
JNIEXPORT long JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_fopen(JNIEnv *env, jobject obj, jstring path, jstring mode)
{
    PFI
    char cpath[256];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    char cmode[10];
    int cmode_len = (*env)->GetStringLength(env, mode);
    (*env)->GetStringUTFRegion(env, mode, 0, cmode_len, cmode);
    if(JNI_DBG) jni_printf("%s\n",cpath);
    if(JNI_DBG) jni_printf("%s\n",cmode);
    FILE *fp = jni_fopen(cpath, cmode);
    if(JNI_DBG) jni_printf("FILE *fp = %llu\n", (long long unsigned int) fp);
    if(fp == 0)
    {
        jni_perror("fopen failed");
    }
err:
    JNI_FLUSH
    return (long)fp;
}

/* fdopen */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_fdopen(JNIEnv *env, jobject obj, int fd, jstring mode)
{    
    PFI
    char cmode[10];
    int cmode_len = (*env)->GetStringLength(env, mode);
    (*env)->GetStringUTFRegion(env, mode, 0, cmode_len, cmode);
    FILE * fptr;
    fptr = jni_fdopen(fd, cmode);
    if(fptr == NULL)
    {
        jni_perror("fdopen failed!");
    }
    return (jlong) fptr;
}

/* fileno */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_fileno(JNIEnv *env, jobject obj, jlong stream)
{    
    PFI
    errno = 0;
    int fd = jni_fileno((FILE *) stream);
    if(fd == -1)
    {
        jni_perror("fileno failed!");
    }
err:
    JNI_FLUSH
    return (jint) fd;
}

/* remove */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_remove(JNIEnv *env, jobject obj, jstring path)
{    
    PFI
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    int val = jni_remove(cpath);
    if (val != 0)
    {
        jni_perror("remove failed!");
    }
    return (jint) val;
}

/* fread */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_fread(JNIEnv *env, jobject obj, jbyteArray ptr, jlong size, jlong nmemb, jlong stream)
{
    PFI
    ssize_t rc = 0;
    jboolean is_copy;
    jbyte * cptr = (*env)->GetByteArrayElements(env, ptr, &is_copy);
    if(!ptr)
    {
        jni_perror("GetByteArrayElements");
        errno = EFAULT;
        rc = -1;
        goto err;
    }
    rc = jni_fread((void *) cptr, (size_t) size, (size_t) nmemb, (FILE *) stream);
    if(rc < 0)
    {
        jni_perror("jni fread");
    }
    else
    {
        if(JNI_DBG) jni_printf("\tread %llu \n", ((long long unsigned int) rc * (long long unsigned int) size));
    }
err:
    /* copy back and free the ptr using 0 */
    (*env)->ReleaseByteArrayElements(env, ptr, cptr, 0);
    return (jlong) rc;
}

/* fwrite */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_fwrite(JNIEnv *env, 
    jobject obj, 
    jbyteArray ptr, 
    jlong size, 
    jlong nmemb, 
    jlong stream
)   
{
    //PFI
    ssize_t rc = 0;
    jboolean is_copy;
    jbyte * cptr = (*env)->GetByteArrayElements(env, ptr, &is_copy);
    if(!ptr)
    {
        jni_perror("GetByteArrayElements");
        errno = EFAULT;
        rc = -1;
        goto err;
    }
    rc = jni_fwrite((void *) cptr, (size_t) size, (size_t) nmemb, (FILE *) stream);
    if(rc < 0)
    {
        jni_perror("jni fwrite");
    }
    else
    {
        /*
        if(JNI_DBG) jni_printf("\twrote %llu bytes\n", 
            ((long long unsigned int) rc * (long long unsigned int) size));
        */
    }
err:
    /* copy back and free the ptr using 0 */
    (*env)->ReleaseByteArrayElements(env, ptr, cptr, 0);
    JNI_FLUSH
    return (jlong) rc;
}

/* fdopendir */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_fdopendir(JNIEnv *env, jobject obj, int fd)   
{
    PFI
    DIR *dstr;
    dstr = jni_fdopendir(fd);
    if(dstr == NULL)
    {
        jni_perror("jni fdopendir");
    }
    JNI_FLUSH
    return (jlong) dstr;
}

/* flockfile */
JNIEXPORT void JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_flockfile(JNIEnv *env, jobject obj, jlong stream)   
{
    PFI
    jni_flockfile((FILE *) stream);
    return;
}

/* ftrylockfile */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_ftrylockfile(JNIEnv *env, jobject obj, jlong stream)
{
    PFI
    int rc = jni_ftrylockfile((FILE *) stream);
    if(rc == 0)
    {
        jni_perror("jni ftrylockfile");
    }
    JNI_FLUSH
    return (jint) rc;
}

/* funlockfile */
JNIEXPORT void JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_funlockfile(JNIEnv *env, jobject obj, jlong stream)   
{
    PFI
    jni_funlockfile((FILE *) stream);
    return;
}

/* fopen64 */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_fopen64(JNIEnv *env, jobject obj, jstring path, jstring modes)
{    
    PFI
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    char cmodes[10];
    int cmodes_len = (*env)->GetStringLength(env, modes);
    (*env)->GetStringUTFRegion(env, modes, 0, cmodes_len, cmodes);
    FILE * fptr = jni_fopen64(cpath, cmodes);
    if(fptr == NULL)
    {
        jni_perror("fopen failed");
    }
    else
    {
        if(JNI_DBG) jni_printf("Fptr = %llu \n",(long long unsigned int) fptr);
    }
    JNI_FLUSH
    return (jlong) fptr;
}

/* freopen */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_freopen(JNIEnv *env, jobject obj, jstring path, jstring modes, jlong stream)
{    
    PFI
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    char cmodes[10];
    int cmodes_len = (*env)->GetStringLength(env, modes);
    (*env)->GetStringUTFRegion(env, modes, 0, cmodes_len, cmodes);
    FILE * fptr = jni_freopen(cpath, cmodes, (FILE *) stream);
    if (fptr == NULL)
    {
        jni_perror("freopen failed");
    }
    else
    {
        if(JNI_DBG) jni_printf("fptr = %llu \n", (long long unsigned int) fptr);
    }
    JNI_FLUSH
    return (jlong) fptr;
}

/* freopen64 */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_freopen64(JNIEnv *env, jobject obj, jstring path, jstring modes, jlong stream)
{    
    PFI
    char cpath[PVFS_PATH_MAX];
    int cpath_len = (*env)->GetStringLength(env, path);
    (*env)->GetStringUTFRegion(env, path, 0, cpath_len, cpath);
    char cmodes[10];
    int cmodes_len = (*env)->GetStringLength(env, modes);
    (*env)->GetStringUTFRegion(env, modes, 0, cmodes_len, cmodes);
    FILE * fptr = jni_freopen64(cpath, cmodes, (FILE *) stream);
    if(fptr == NULL)
    {
        jni_perror("freopen64 failed");
    }
    else
    {
        if(JNI_DBG) jni_printf("fptr = %llu \n", (long long unsigned int) fptr);
    }
    JNI_FLUSH
    return (jlong) fptr;
}   

/* fwrite_unlocked */

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_fwriteUnlocked(JNIEnv *env, jobject obj, jbyteArray ptr, jlong size, jlong nmemb, jlong stream)   
{
ssize_t rc = 0;
    PFI
    jboolean is_copy;
    jbyte * cptr = (*env)->GetByteArrayElements(env, ptr, &is_copy);
    if(!ptr)
    {
        jni_perror("GetByteArrayElements");
        errno = EFAULT;
        rc = -1;
        goto err;
    }
    rc = fwrite_unlocked((void *) cptr, (size_t) size, (size_t) nmemb, (FILE *) stream);
    if(rc < 0)
    {
        jni_fprintf(stderr, "jni fwrite_unlocked\n");
    }
    else
    {
        if(JNI_DBG) jni_printf("\twrote %llu bytes\n", (long long unsigned int) rc);
    }
err:
    /* copy back and free the ptr using 0 */
    (*env)->ReleaseByteArrayElements(env, ptr, cptr, 0);
    JNI_FLUSH
    return (jlong) rc;
}

/* fread_unlocked */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_freadUnlocked(JNIEnv *env, jobject obj, jbyteArray ptr, jlong size, jlong nmemb, jlong stream)
{
    PFI
    ssize_t rc = 0;
    jboolean is_copy;
    jbyte * cptr = (*env)->GetByteArrayElements(env, ptr, &is_copy);
    if(!ptr)
    {
        jni_perror("GetByteArrayElements");
        errno = EFAULT;
        rc = -1;
        goto err;
    }
    rc = fread_unlocked((void *) cptr, (size_t) size, (size_t) nmemb, (FILE *) stream);
    if(rc < 0)
    {
        fprintf(stderr, "jni fread_unlocked\n");
    }
    else
    {
        if(JNI_DBG) jni_printf("\tread %llu bytes\n", (long long unsigned int) rc);
    }
err:
    /* copy back and free the ptr using 0 */
    (*env)->ReleaseByteArrayElements(env, ptr, cptr, 0);
    JNI_FLUSH
    return (jlong) rc;
}

/* fclose */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_fclose(JNIEnv *env, jobject obj, long fp)
{
    PFI
    int rc = 0;
    if(JNI_DBG) jni_printf("fp = %llu\n", (long long unsigned int) fp);
    errno = 0;
    rc = jni_fclose((FILE *) fp);
    if(rc == EOF)
    {
        jni_perror("fclose");
    }
err:
    JNI_FLUSH
    return (jint) rc;
}

/* fcloseall */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_fcloseall(JNIEnv *env, jobject obj)   
{
    PFI
    int rc = jni_fcloseall();
    if(rc == EOF)
    {
        jni_fprintf(stderr, "fcloseall failed\n");
    }
    JNI_FLUSH
    return rc;
}

/* ftell */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_ftell(JNIEnv *env, jobject obj, jlong stream)
{
    PFI
    long rc = jni_ftell((FILE *) stream);
    if(rc < 0)
    {
        jni_perror("ftell failed!");
    }
    JNI_FLUSH
    return (jlong) rc;
}

/* fseek */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_fseek(JNIEnv *env, jobject obj, jlong stream, jlong offset, jlong whence)
{
    PFI

    int rc = jni_fseek((FILE *) stream, (long) offset, (int) whence);
    if(rc != 0)
    {
        jni_perror("fseek failed!");
    }
    JNI_FLUSH
    return (jint) rc;
}

/* fseeko */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_fseeko(JNIEnv *env, jobject obj, jlong stream, jlong offset, jlong whence)
{
    PFI

    off_t rc = jni_fseeko((FILE *) stream, (off_t) offset, (int) whence);
    if(rc != 0)
    {
        jni_perror("fseeko failed!");
    }
    JNI_FLUSH
    return (jlong) rc;
}

/* fseek64 */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_fseek64(JNIEnv *env, jobject obj, jlong stream, jlong offset, jlong whence)
{
    PFI

    int rc = jni_fseek64((FILE *) stream, (off64_t) offset, (int) whence);
    if(rc != 0)
    {
        jni_perror("Fseek64 failed!");
    }
    JNI_FLUSH
    return (jint) rc;
}

/* fseeko64 */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_fseeko64(JNIEnv *env, jobject obj, jlong stream, jlong offset, jlong whence)
{
    PFI

    off_t rc = jni_fseeko64((FILE *) stream, (off_t) offset, (int) whence);
    if(rc != 0)
    {
        jni_perror("fseeko failed!");
    }
    JNI_FLUSH
    return (jlong) rc;
}

/* setvbuf*/
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_setvbuf(JNIEnv *env, jobject obj, jlong stream, jlong buf, jlong mode, jlong size)
{
    PFI

    int rc = jni_setvbuf((FILE *) stream, (char *) buf, (int) mode, (size_t) size);
    if(rc != 0)
    {
        jni_perror("setvbuf");
    }
    JNI_FLUSH
    return (jint) rc;
}

#if 0
/*
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_FillFpost(JNIEnv *env, jobject obj, jobject x)
{
    jni_printf("FillStatvfs\n");
    
    jfieldID fid1;
    jfieldID fid2;
    
    
    jlong pos;
    jlong state;
    
    jclass cls1 = (*env)->FindClass(env, "PVFS2STDIOJNI$Fpost");
    
    fid1 = (*env)->GetFieldID(env, cls1, "__pos", "J");
    if (fid1 == NULL)
    {
        return;
    }
    fid2 = (*env)->GetFieldID(env, cls1, "__state", "J");
    if (fid2 == NULL)
    {
        return;
    }
    
    fpos_t *cfpos_t = (fpos_t *)malloc(sizeof(fpos_t));
    
    pos = (*env)->GetLongField(env, x, fid1);
    __off_t cpos = (__off_t) pos;
    cfpos_t->__pos = cpos;
    
    state = (*env)->GetLongField(env, x, fid2);
    __mbstate_t cstate = (__mbstate_t) state;
    cfpos_t->__state = cstate;
    
    
    long lp = (long)cfpos_t;
    return lp;
}

void dispfpost(fpos_t *abc)
{
    jni_printf("=======DISPLAY========\n");
    jni_printf("The pos is: %lu\n", abc->__pos);
    jni_printf("The state is: %lu\n", abc->__state);
    free(abc);
}

JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_useFpost(JNIEnv *env, jobject obj, jlong jarg)
{
    fpos_t *arg;
    arg = (fpos_t *)jarg;
    dispfpost(arg);
}*/
#endif

/* fflush */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_fflush(JNIEnv *env, jobject obj, jlong stream)
{
    PFI
    int rc = jni_fflush((FILE *) stream);
    if(rc < 0)
    {
        jni_perror("fflush failed");
    }
    JNI_FLUSH
    return (jint) rc;
}

/*fflush_unlocked*/

JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_fflush_unlocked(JNIEnv *env, jobject obj, jlong stream)
{
    PFI
    int rc = jni_fflush_unlocked((FILE *) stream);
    if(rc < 0)
    {
        jni_perror("fflush_unlocked failed");
    }
    JNI_FLUSH
    return (jint) rc;
}

#if 0
/*fputc*/
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_fputc(JNIEnv *env, jobject obj, int c, jlong stream)
{
    if(JNI_DBG) jni_printf("Fputc\n");
    int rc = 0;
    rc = fputc(c, (FILE *) stream);
    if(rc == -1)
    {
        jni_perror("Fputc failed!");
        
    }
    else
    {
        jni_printf("Fputc successful.\n");
    }
    return (jint) rc;
}

/*fputc_unlocked*/
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_fputcUnlocked(JNIEnv *env, jobject obj, int c, jlong stream)
{
    jni_printf("FputcUnlocked\n");
    int rc;
    rc = fputc_unlocked(c, (FILE *) stream);
    if(rc == -1)
    {
        jni_perror("FputcUnlocked failed!");
    }
    else
    {
        jni_printf("FputcUnlocked successful.\n");
    }
    return (jint) rc;
}

/* fputs */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_fputs(JNIEnv *env, jobject obj, jstring s, jlong stream)
{
    jni_printf("Fputs\n");
    int rc = 0;
    char cs[1024];
    int cs_len = (*env)->GetStringLength(env, s);
    (*env)->GetStringUTFRegion(env, s, 0, cs_len, cs);
    rc = fputs(cs, (FILE *) stream);
    if(rc == -1)
    {
        jni_perror("Fputs failed!");
        
    }
    else
    {
        jni_printf("Fputs successful.\n");
    }
    return (jint) rc;
}

/* fputs_unlocked */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_fputsUnlocked(JNIEnv *env, jobject obj, jstring s, jlong stream)
{
    jni_printf("FputsUnlocked\n");
    int rc ;
    char cs[1024];
    int cs_len = (*env)->GetStringLength(env, s);
    (*env)->GetStringUTFRegion(env, s, 0, cs_len, cs);
    rc = fputs_unlocked(cs, (FILE *) stream);
    if(rc == -1)
    {
        jni_perror("FputsUnlocked failed!");
        
    }
    else
    {
        jni_printf("FputsUnlocked successful.\n");
    }
    return (jint) rc;
} 

/* putc */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_putc(JNIEnv *env, jobject obj, int c, jlong stream)
{
    jni_printf("Putc\n");
    int rc = 0;
    rc = putc(c, (FILE *) stream);
    if(rc == -1)
    {
        jni_perror("Putc failed!");
        
    }
    else
    {
        jni_printf("Putc successful.\n");
    }
    return (jint) rc;
}

/* putc_unlocked */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_putcUnlocked(JNIEnv *env, jobject obj, int c, jlong stream)
{
    jni_printf("PutcUnlocked\n");
    int rc;
    rc = putc_unlocked(c, (FILE *) stream);
    if(rc == -1)
    {
        jni_perror("PutcUnlocked failed!");
        
    }
    else
    {
        jni_printf("PutcUnlocked successful.\n");
    }
    return (jint) rc;
}


/* putchar */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_putchar(JNIEnv *env, jobject obj, int c)
{
    jni_printf("Putchar\n");
    int rc = 0;
    rc = putchar(c);
    if(rc == -1)
    {
        jni_perror("Putchar failed!");
        
    }
    else
    {
        jni_printf("Putchar successful.\n");
    }
    return (jint) rc;
}

/*putchar_unlocked*/
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_putcharUnlocked(JNIEnv *env, jobject obj, int c)
{
    jni_printf("PutcharUnlocked\n");
    int rc;
    rc = putchar_unlocked(c);
    if(rc == -1)
    {
        jni_perror("PutcharUnlocked failed!");
        
    }
    else
    {
        jni_printf("PutcharUnlocked successful.\n");
    }
    return (jint) rc;
}

/* puts */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_puts(JNIEnv *env, jobject obj, jstring s)
{
    jni_printf("Puts\n");
    int rc = 0;
    char cs[1024];
    int cs_len = (*env)->GetStringLength(env, s);
    (*env)->GetStringUTFRegion(env, s, 0, cs_len, cs);
    rc = puts(cs);
    if(rc == -1)
    {
        jni_perror("Puts failed!");
        
    }
    else
    {
        jni_printf("Puts successful.\n");
    }

/*fputc*/
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_fputc(JNIEnv *env, jobject obj, int c, jlong stream)
{
    jni_printf("Fputc\n");
    int rc = 0;
    rc = fputc(c, (FILE *) stream);
    if(rc == -1)
    {
        jni_perror("Fputc failed!");
        
    }
    else
    {
        jni_printf("Fputc successful.\n");
    }
    return (jint) rc;
}

/* putw */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_putw(JNIEnv *env, jobject obj, int wd, jlong stream)
{
    jni_printf("Putw\n");
    int rc;
    char cs[1024];
    rc = putw(wd, (FILE *) stream);
    if(rc <= 0)
    {
        jni_perror("Putw failed!");
        
    }
    else
    {
        jni_printf("Putw successful.\n");
    }
    return (jint) rc;
}

/* fgets */
JNIEXPORT jstring JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_fgets(JNIEnv *env, jobject obj, jstring s, int size, jlong stream)
{
    jni_printf("Fgets\n");
    char *rc = NULL;
    char cs[size];
    int cs_len = (*env)->GetStringLength(env, s);
    (*env)->GetStringUTFRegion(env, s, 0, cs_len, cs);
    rc = fgets(cs, size, (FILE *) stream);
    if(rc == NULL)
    {
        jni_perror("Fgets failed!");
        
    }
    else
    {
        jni_printf("Fgets successful.\n");
    }
    return (*env)->NewStringUTF(env, rc);
}

/* fgets_unlocked 
JNIEXPORT jstring JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_fgetsUnlocked(JNIEnv *env, jobject obj, jstring s, int size, jlong stream)
{
    jni_printf("FgetsUnlocked\n");
    char *rc = NULL;
    char cs[size];
    int cs_len = (*env)->GetStringLength(env, s);
    (*env)->GetStringUTFRegion(env, s, 0, cs_len, cs);
    rc = fgets_unlocked(cs, size, (FILE *) stream);
    if(rc == NULL)
    {
        jni_perror("FgetsUnlocked failed!");
    }
    else
    {
        jni_printf("FgetsUnlocked successful.\n");
    }
    return (*env)->NewStringUTF(env, rc);
    
}
*/
/* fgetc */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_fgetc(JNIEnv *env, jobject obj, jlong stream)
{
    jni_printf("Fgetc\n");
    int rc;
    rc = fgetc((FILE *) stream);
    if(rc == -1)
    {
        jni_perror("Fgetc failed!");
        
    }
    else
    {
        jni_printf("Fgetc successful.\n");
    }
    return (jint) rc;
}

/* fgetc_unlocked */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_fgetcUnlocked(JNIEnv *env, jobject obj, jlong stream)
{
    jni_printf("FgetcUnlocked\n");
    int rc;
    rc = fgetc_unlocked((FILE *) stream);
    if(rc == -1)
    {
        jni_perror("FgetcUnlocked failed!");
        
    }
    else
    {
        jni_printf("FgetcUnlocked successful.\n");
    }
    return (jint) rc;
}


/* getc */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_getc(JNIEnv *env, jobject obj, jlong stream)
{
    jni_printf("Getc\n");
    int rc;
    rc = getc((FILE *) stream);
    if(rc == -1)
    {
        jni_perror("Getc failed!");
        
    }
    else
    {
        jni_printf("Getc successful.\n");
    }
    return (jint) rc;
}

/* getc_unlocked */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_getcUnlocked(JNIEnv *env, jobject obj, jlong stream)
{
    jni_printf("GetcUnlocked\n");
    int rc;
    rc = getc_unlocked((FILE *) stream);
    if(rc == -1)
    {
        jni_perror("GetcUnlocked failed!");
        
    }
    else
    {
        jni_printf("GetcUnlocked successful.\n");
    }
    return (jint) rc;
}

/* getchar */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_getchar(JNIEnv *env, jobject obj)
{
    jni_printf("Getchar\n");
    int rc;
    rc = jni_getchar();
    if(rc == -1)
    {
        jni_perror("Getchar failed!");
        
    }
    else
    {
        jni_printf("Getchar successful.\n");
    }
    return (jint) rc;
}

/* getchar_unlocked */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_getcharUnlocked(JNIEnv *env, jobject obj)
{
    jni_printf("GetcharUnlocked\n");
    int rc;
    rc = jni_getchar_unlocked();
    if(rc == -1)
    {
        jni_perror("GetcharUnlocked failed!");
        
    }
    else
    {
        jni_printf("GetcharUnlocked successful.\n");
    }
    return (jint) rc;
}

/* getw */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_getw(JNIEnv *env, jobject obj, jlong stream)
{
    jni_printf("Getw\n");
    int rc;
    rc = getw((FILE *) stream);
    if(rc == -1)
    {
        jni_perror("Getw failed!");
        
    }
    else
    {
        jni_printf("Getw successful.\n");
    }
    return (jint) rc;
}

/* gets */
JNIEXPORT jstring JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_gets(JNIEnv *env, jobject obj, jstring s)
{
    jni_printf("Gets\n");
    char *rc = NULL;
    char cs[1024];
    int cs_len = (*env)->GetStringLength(env, s);
    (*env)->GetStringUTFRegion(env, s, 0, cs_len, cs);
    rc = gets(cs);
    if(rc == NULL)
    {
        jni_perror("Gets failed!");
        
    }
    else
    {
        jni_printf("Gets successful.\n");
    }
    return (*env)->NewStringUTF(env, rc);
    
}

/* ungetc */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_ungetc(JNIEnv *env, jobject obj, int c, jlong stream)
{
    jni_printf("Ungetc\n");
    int rc;
    rc = ungetc(c, (FILE *) stream);
    if(rc < 0)
    {
        jni_perror("Ungetc failed!");
        
    }
    else
    {
        jni_printf("Ungetc successful.\n");
    }
    return (jint) rc;
}

/* jni_perror */

JNIEXPORT void JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_perror(JNIEnv *env, jobject obj, jstring s)
{
    jni_printf("Perror\n");
    
    char cs[1024];
    int cs_len = (*env)->GetStringLength(env, s);
    (*env)->GetStringUTFRegion(env, s, 0, cs_len, cs);
    jni_perror(cs);
}
#endif

/* clearerr */

JNIEXPORT void JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_clearerr(JNIEnv *env, jobject obj, jlong stream)
{
    PFI
    clearerr((FILE *) stream);
    JNI_FLUSH
}

/* clearerr_unlocked */

JNIEXPORT void JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_clearerrUnlocked(JNIEnv *env, jobject obj, jlong stream)
{
    PFI
    clearerr_unlocked((FILE *) stream);
    JNI_FLUSH
}

/* feof */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_feof(JNIEnv *env, jobject obj, jlong stream)
{
    PFI
    int rc = feof((FILE *) stream);
    if(rc != 0)
    {
       if(JNI_DBG) jni_printf("EOF reached!\n");
    }
    JNI_FLUSH
    return (jint) rc;
}

/* feof_unlocked  */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_feofUnlocked(JNIEnv *env, jobject obj, jlong stream)
{
    PFI
    int rc = feof_unlocked((FILE *) stream);
    if(rc != 0)
    {
        if(JNI_DBG) jni_printf("EOF reached!\n");
    }
    JNI_FLUSH
    return (jint) rc;
}

/* ferror */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_ferror(JNIEnv *env, jobject obj, jlong stream)
{
    PFI
    int rc = ferror((FILE *) stream);
    if(rc != 0)
    {
        if(JNI_DBG) jni_perror("ferror detected error");        
    }
    JNI_FLUSH
    return (jint) rc;
}

/* ferror_unlocked */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_ferrorUnlocked(JNIEnv *env, jobject obj, jlong stream)
{
    PFI
    int rc = ferror_unlocked((FILE *) stream);
    if(rc != 0)
    {
        if(JNI_DBG) jni_perror("ferror detected error");        
    }
    JNI_FLUSH
    return (jint) rc;
}

#if 0
/* fileno_unlocked */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_filenoUnlocked(JNIEnv *env, jobject obj, jlong stream)
{
    jni_printf("FilenoUnlocked\n");
    int rc = 0;
    rc = fileno_unlocked((FILE *) stream);
    if(rc == -1)
    {
        jni_perror("FilenoUnlocked failed!");
        
    }
    else
    {
        jni_printf("FilenoUnlocked successful.\n");
        
    }
    return (jint) rc;
}

/* setbuf */
JNIEXPORT void JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_setbuf(JNIEnv *env, jobject obj, jlong stream, jstring buf)
{    
    jni_printf("Setbuf\n");
    
    char cbuf[1024];
    int cbuf_len = (*env)->GetStringLength(env, buf);
    (*env)->GetStringUTFRegion(env, buf, 0, cbuf_len, cbuf);
    setbuf((FILE *) stream, cbuf);
    
}

/* setbuffer */
JNIEXPORT void JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_setbuffer(JNIEnv *env, jobject obj, jlong stream, jstring buf, jlong size)
{    
    jni_printf("Setbuffer\n");
    
    char cbuf[size];
    int cbuf_len = (*env)->GetStringLength(env, buf);
    (*env)->GetStringUTFRegion(env, buf, 0, cbuf_len, cbuf);
    
    setbuffer((FILE *) stream, cbuf, (size_t) size);
}

/* setlinebuf */
JNIEXPORT void JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_setlinebuf(JNIEnv *env, jobject obj, jlong stream)
{    
    jni_printf("Setlinebuf\n");
    setlinebuf((FILE *) stream);
}

/* setvbuf*/
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_setvbuf(JNIEnv *env, jobject obj)
/*
Java_org_orangefs_usrint_PVFS2STDIOJNI_setvbuf(JNIEnv *env, jobject obj, jlong stream, jlong buf, jint mode, jlong size)
*/
{
    /*
    if(JNI_DBG) jni_printf("setvbuf\n");
    int rc = jni_setvbuf((FILE *) stream, (char *) buf, (int) mode, (size_t) size);
    if(rc != 0)
    {
        jni_perror("setvbuf failed!");
    }
    return (jint) rc;
    */
    return 1;
}

/* mkdtemp */
JNIEXPORT jstring JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_mkdtemp(JNIEnv *env, jobject obj, jstring tmplate)
{    
    jni_printf("Mkdtemp\n");
    char * rc;
    char ctmplate[1024];
    int ctmplate_len = (*env)->GetStringLength(env, tmplate);
    (*env)->GetStringUTFRegion(env, tmplate, 0, ctmplate_len, ctmplate);
    rc = mkdtemp(ctmplate);
    if(rc == NULL)
    {
        jni_perror("Mkdtemp failed!");
        
    }
    else
    {
        jni_printf("Mkdtemp successful.\n");
    }
    return (*env)->NewStringUTF(env, rc);
}

/* mkstemp */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_mkstemp(JNIEnv *env, jobject obj, jstring tmplate)
{    
    jni_printf("Mkstemp\n");
    int rc;
    char ctmplate[1024];
    int ctmplate_len = (*env)->GetStringLength(env, tmplate);
    (*env)->GetStringUTFRegion(env, tmplate, 0, ctmplate_len, ctmplate);
    rc = mkstemp(ctmplate);
    if(rc == -1)
    {
        jni_perror("Mkstemp failed!");
        
    }
    else
    {
        jni_printf("Mkstemp successful.\n");
        
    }
    return (jint) rc;
}

/* tmpfile */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_tmpfile(JNIEnv *env, jobject obj)
{    
    jni_printf("Tmpfile\n");
    FILE * fd;
    
    fd = tmpfile();
    if(fd == NULL)
    {
        jni_perror("Tmpfile failed!");
        
    }
    else
    {
        jni_printf("Tmpfile successful.\n");
        
    }
    return (jlong) fd;
}
#endif 

/* opendir */
JNIEXPORT jobject JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_opendir(JNIEnv *env, jobject obj, jstring name)
{    
    PFI
    struct dirent *dir;
    jobject ret = (jobject) 0;
    char cname[PVFS_NAME_MAX];
    int cname_len = (*env)->GetStringLength(env, name);
    (*env)->GetStringUTFRegion(env, name, 0, cname_len, cname);
    dir = (struct dirent *) opendir(cname);
    if(dir == NULL)
    {
        jni_perror("opendir");
        goto err;
    }
    else
    {
        if(JNI_DBG) jni_printf("Opendir successful.\n");
    }

    jobject dir_obj;
    if(fill_dirent(env, dir, &dir_obj) == 0)
    {
        JNI_FLUSH
        return dir_obj;
    }
err:
    JNI_FLUSH
    return ret;
}

/* dirfd */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_dirfd(JNIEnv *env, jobject obj, jlong dir)
{
    PFI
    int rc;
    rc = dirfd((DIR *) dir);
    if(rc == -1)
    {
        jni_perror("Dirfd");
        
    }
    JNI_FLUSH
    return (jint) rc;
}

/* rewinddir */
JNIEXPORT void JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_rewinddir(JNIEnv *env, jobject obj, jlong dir)
{
    PFI
    rewinddir((DIR *) dir);
    JNI_FLUSH
}

/* seekdir */
JNIEXPORT void JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_seekdir(JNIEnv *env, jobject obj, jlong dir, jlong offset)
{
    PFI
    seekdir((DIR *) dir, (off_t) offset);
    JNI_FLUSH
}

/* telldir */
JNIEXPORT jlong JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_telldir(JNIEnv *env, jobject obj, jlong dir)
{
    PFI
    off_t rc;
    rc = telldir((DIR *) dir);
    if(rc == -1)
    {
        jni_perror("telldir");
        
    }
    JNI_FLUSH
    return (jlong) rc;
}

/* closedir */
JNIEXPORT jint JNICALL
Java_org_orangefs_usrint_PVFS2STDIOJNI_closedir(JNIEnv *env, jobject obj, jlong dir)
{
    PFI
    int rc;
    rc = closedir((DIR *) dir);
    if(rc == 0)
    {
        jni_printf("Closedir successful.\n");
    }
    JNI_FLUSH
    return (jint) rc;
}

