#!/bin/sh

# run through a bunch of possible command line arguments for pvfs2-cp:

${PVFS2_DEST}/INSTALL-pvfs2/bin/pvfs2-cp \
                ${PVFS2_DEST}/pvfs2/configure ${PVFS2_MOUNTPOINT}/configure1

${PVFS2_DEST}/INSTALL-pvfs2/bin/pvfs2-cp -s 128 \
                ${PVFS2_DEST}/pvfs2/configure ${PVFS2_MOUNTPOINT}/configure2

${PVFS2_DEST}/INSTALL-pvfs2/bin/pvfs2-cp -s $((1024*1024)) \
                ${PVFS2_DEST}/pvfs2/configure ${PVFS2_MOUNTPOINT}/configure3

${PVFS2_DEST}/INSTALL-pvfs2/bin/pvfs2-cp -n 1 \
                ${PVFS2_DEST}/pvfs2/configure ${PVFS2_MOUNTPOINT}/configure4

${PVFS2_DEST}/INSTALL-pvfs2/bin/pvfs2-cp -n 10 \
                ${PVFS2_DEST}/pvfs2/configure ${PVFS2_MOUNTPOINT}/configure5

${PVFS2_DEST}/INSTALL-pvfs2/bin/pvfs2-cp -b 128 \
                ${PVFS2_DEST}/pvfs2/configure ${PVFS2_MOUNTPOINT}/configure6

${PVFS2_DEST}/INSTALL-pvfs2/bin/pvfs2-cp -b $((1024*1024)) \
                ${PVFS2_DEST}/pvfs2/configure ${PVFS2_MOUNTPOINT}/configure7
