#!/bin/sh

# can't really be common since tests might want more/less time or nodes

# i'm terribly sorry for how confusing this is... I want to generate a pbs
# script that itself uses some environment variables.  Thus we escape some
# dollar signs before things like $PATH, but not others like $PAV_CONFIG.  

make_pbs_script() {

	echo "#!/bin/sh
#PBS -l walltime=0:30:0
#PBS -l nodes=16
#PBS -j oe

nprocs=8

$CLUSTER_DIR/pav/pav_start -c $PAV_CONFIG -n \$nprocs >/dev/null

eval \$( $CLUSTER_DIR/pav/pav_info -c $PAV_CONFIG)
export PVFS2TAB_FILE

PATH=${CLUSTER_DIR}/mpich2/bin:\${PATH}
mpdboot --file=\${WORKINGDIR}/compnodes --totalnum=\$nprocs

mpiexec -np \$nprocs ${MPI_IO_TEST} -f pvfs2:\${MOUNTPOINT}/file1 -b $((1024*1024*32)) -y 
mpdallexit
$CLUSTER_DIR/pav/pav_stop -c $PAV_CONFIG >/dev/null" 
}

# this could be common among tests...

block_until_done() {
	while true ; do 
		qstat -i $job_id >/dev/null 2>&1 
		if [ $? -eq 0 ] ; then
			sleep 60
			continue
		else
			break
		fi	
	done
}


##
## entry point for script
##

MPI_IO_TEST=${CLUSTER_DIR}/mpi-io-test

${CLUSTER_DIR}/mpich2/bin/mpicc ${PVFS2_DEST}/pvfs2/test/client/mpi-io/mpi-io-test.c -o $MPI_IO_TEST

if [ $? -eq 1 ] ; then
	exit 1
fi

# like the other mpiio tests we can only do multi processor tests if there's a
# pav config file we can use
# If we have to we can fall back to single processor, and still do something
# reasonable. 

if [ -f $PAV_CONFIG ] ; then 
	# write out a pbs script
	pbs_script=${CLUSTER_DIR}/mpiiotest.sh
	make_pbs_script > $pbs_script

	# submit it
	job_id=$(qsub -N mpiiotest $pbs_script | cut -d . -f1)

	# wait patently for it to complete
	block_until_done $job_id

	# need to get results into per-test log files
	cat mpiiotest.o$job_id

	# need to know if we failed or not
	grep -q 'bandwidth' mpiiotest.o$job_id
fi
