.\" Process this file with
.\" groff -man -Tascii foo.1
.TH "PVFS2-PERROR" "1" "SEPTEMBER 2011" "PVFS2" "PVFS2 MANUALS"
.SH "NAME"
pvfs2\-perror \- show information about an error code
.SH "SYNOPSIS"
pvfs2\-perror [OPTIONS] <error_code>
.SH "DESCRIPTION"
Display human readable information about the supplied error code.
.SH "OPTIONS"
.IP \-v
Print the PVFS2 version and exit.
.IP \-h
Print a usage message and exit.
.SH "ENVIRONMENT"
Please report all bugs to the pvfs2 bugzilla (http://bugzilla.mcs.anl.gov/pvfs/)
.SH "BUGS"
Please report all bugs to the pvfs2 bugzilla (http://bugzilla.mcs.anl.gov/pvfs/)
.SH "AUTHOR"
The PVFS2 development team (pvfs2\-developers@beowulf\-underground.org)
