.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH PVFS2-LS 1 "SEPTEMBER 2003"  PVFS2 "PVFS2 Manuals"
.SH NAME
pvfs2-ls \- List files in a PVFS2 directory
.SH SYNOPSIS
.B pvfs2-ls 
.I [-a|--all] [-A|--almost-all] [-d|--directory] [-g] [-G|--no-group]
.I [ -h|--human-readable] [-i|--inode] [-l] [-n|--numeric-uid-gid] [-o] [--help]
.I [--version]  [FILE]

.SH DESCRIPTION
List information about the FILEs (the current directory by default). 

.SH OPTIONS
.IP -a,--all
do not hide entries starting with .
.IP -A,--almost-all          
do not list implied . and ..
.IP -d,--directory
list directory entries instead of contents
.IP -g
like -l, but do not list owner
.IP -G,--no-group
inhibit display of group information
.IP -h,--human-readable
print sizes in human readable format (e.g., 1K 234M 2G)
.IP -i,--inode
print index number of each file
.IP -l
use a long listing format
.IP -n,--numeric-uid-gid
like -l, but list numeric UIDs and GIDs
.IP -o
like -l, but do not list group information
.IP --help     
display this help and exit
.IP --version  
output version information and exit

.SH ENVIRONMENT
.IP PVFS2TAB_FILE
If set, the full pathname for an alternate 
.IR pvfs2tab
file

.SH BUGS
Please report all bugs to the pvfs2 bugzilla (http://bugzilla.mcs.anl.gov/pvfs/)
.SH AUTHOR
The PVFS2 development team (pvfs2-developers@beowulf-underground.org)
.SH "SEE ALSO"
.BR pvfs2-server (1),
.BR pvfs2-statfs (1)
.BR pvfs2-ping (1)
.BR pvfs2-import (1)
.BR pvfs2-export (1)
.BR pvfs2-genconfig (1)
