.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH PVFS2-SERVER 1 "SEPTEMBER 2003"  PVFS2 "PVFS2 Manuals"
.SH NAME
pvfs2-server \- The PVFS2 file serving, request processing, dancing  daemon
.SH SYNOPSIS
.B pvfs2-server [-d] [-f] [-h]
.I <global_config_file> <local_config_file>

.SH DESCRIPTION
.B pvfs2-server
runs on every node that is part of a PVFS2 volume.  A single 
.B pvfs2-server 
can serve as a
.I metadata
server or a 
.I datafile
server, or both.  
.SH OPTIONS
.IP -h 
print a helpful usage message
.IP -d
Keeps the server in the foreground.  Useful for debugging.
.IP -f
Server will create the file system storage space and exit.
.IP global_config_file
Contains defaults applied to all servers.
.IP local_config_file
Contains settings applied to the local instance of the server.

.SH BUGS
Please report all bugs to the pvfs2 bugzilla (http://bugzilla.mcs.anl.gov/pvfs/)
.SH AUTHOR
The PVFS2 development team (pvfs2-developers@beowulf-underground.org)
.SH "SEE ALSO"
.BR pvfs2-server (1),
.BR pvfs2-ls (1),
.BR pvfs2-statfs (1)
.BR pvfs2-ping (1)
.BR pvfs2-cp (1)
.BR pvfs2-genconfig (1)
