.TH PVFS2-START-ALL 1 2025-07-04
.SH NAME
\fBpvfs2-start-all\fR \(en Start all orangefs servers in config file.
.SH SYNOPSIS
.B pvfs2-start-all --help

.SH DESCRIPTION
This script can parse an orangefs server config file and start all
of the servers.

.SH BUGS
Please submit bug reports to devel@lists.orangefs.org
