.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH PVFS2-SET-SYNC 1 "July 2005"  PVFS2 "PVFS2 Manuals"
.SH NAME
pvfs2-set-sync \- Change meta and data sync flags of a pvfs2-server
.SH SYNOPSIS
.B pvfs2-set-sync
.I -m mount_point -M [0|1] -D [0|1]

.SH DESCRIPTION
Changes the behavior of all  
.B pvfs2-servers
within a given file system with respect to when they synchronize metadata and
file data

.SH OPTIONS
.IP -m
Modify settings for the servers associated with 
.I mount_point

.IP -M
can be  
.I 1 
(indicates that metadata should be synchronized after every operation), or
.I 0 
(indicates that metadata should be synchronized only when requested)

.IP -D
can be  
.I 1 
(indicates that file data should be synchronized after every operation), or 
.I 0 
(indicates that file data should be synchronized only when requested)

.SH ENVIRONMENT
.IP PVFS2TAB_FILE
If set, the full pathname for an alternate 
.IR pvfs2tab
file

.SH BUGS
Please report all bugs to the pvfs2 bugzilla (http://bugzilla.mcs.anl.gov/pvfs/)
.SH AUTHOR
The PVFS2 development team (pvfs2-developers@beowulf-underground.org)
.SH "SEE ALSO"
.BR pvfs2-server (1),
.BR pvfs2-genconfig (1)

