.TH PVFS2-STAT 1 2017-08-09
.SH NAME
\fBpvfs2-stat\fR \(en display file attributes
.SH SYNOPSIS
\fBpvfs2-stat\fR [\fB\-LV\fR] \fIFILE\fR
.SH DESCRIPTION
The
.B pvfs2-stat
utility displays the attributes of the specified files.
.PP
The options are as follows:
.IP -L
Follow symbolic links.
.IP -V
Print version number and exit.
.SH ENVIRONMENT
.IP PVFS2_DEBUGFILE
If set to the path of a local file, redirect debug output to it.
.IP PVFS2_DEBUGMASK
Set the OrangeFS debug mask.  Possible masks are documented in
.BR pvfs2-set-debugmask ( 1 ) \& .
.IP PVFS2TAB_FILE
If set, the full pathname for an alternate
.IR pvfs2tab
file
.SH FILES
.I /etc/passwd
.PP
.I /etc/pvfs2tab
.SH EXAMPLES
Display attributes for the file
.IR /mnt/foo .
.PP
.RS 6n
pvfs2-stat /mnt/foo
.RE
.SH BUGS
Please submit bug reports to pvfs2-developers@beowulf-underground.org
.SH SEE ALSO
.BR stat ( 1 ),
.BR pvfs2tab ( 5 )
