.TH PVFS2-SETMATTR 1 2017-07-13
.SH NAME
\fBpvfs2-setmattr\fR \(en set file mirroring properties
volumes
.SH SYNOPSIS
\fBpvfs2-setmattr\fR [\fB\-c\fI copies\fR] [\fB\-m\fI mode\fR]
[\fB\-h\fR] \fB-f\fR \fIfile\fR
.br
\fBsetmattr\fR [\fB\-c\fI copies\fR] [\fB\-m\fI mode\fR]
[\fB\-h\fR] \fB-f\fR \fIfile\fR
.SH DESCRIPTION
The
.B pvfs2-setmattr
utility changes information about file mirroring for a given file.
.PP
The options are as follows:
.IP -c
Set the number of mirror copies.
.IP -m
Set the mirroring mode.  The mode
.I 100
means no mirroring and
.I 200
means create mirror when immutable is set.
.IP -h
Display synopsis.
.SH ENVIRONMENT
.IP PVFS2_DEBUGFILE
If set to the path of a local file, redirect debug output to it.
.IP PVFS2_DEBUGMASK
Set the OrangeFS debug mask.  Possible masks are documented in
.BR pvfs2-set-debugmask ( 1 ) \& .
.IP PVFS2TAB_FILE
If set, the full pathname for an alternate
.IR pvfs2tab
file
.SH FILES
.I /etc/passwd
.PP
.I /etc/pvfs2tab
.SH EXAMPLES
Set mirroring for the file
.IR /mnt/foo .
.PP
.RS 6n
pvfs2-setmattr -c 2 -m 200 -f /mnt/foo
.RE
.SH BUGS
Please submit bug reports to pvfs2-developers@beowulf-underground.org
.SH SEE ALSO
.BR pvfs2-getmattr ( 1 ),
.BR pvfs2tab ( 5 )
