.TH PVFS2-PERROR 1 2017-07-03
.SH NAME
\fBpvfs2-perror\fR \(en interpret numerical error code
.SH SYNOPSIS
\fBpvfs2-perror\fR \fIerror_code\fR
.SH DESCRIPTION
The
.B pvfs2-perror
utility prints the human language definition associated with
.IR error_code .
.SH BUGS
Please submit bug reports to pvfs2-developers@beowulf-underground.org
