.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH PVFS2-STATFS 1 "SEPTEMBER 2003"  PVFS2 "PVFS2 Manuals"
.SH NAME
pvfs2-statfs \- Display statistics about a pvfs2 volume
.SH SYNOPSIS
.B pvfs2-statfs
.I -m mount_point

.SH DESCRIPTION
Displays aggregate PVFS2 file system information as well as individual server
statistics.

Aggregate Statistics
.RS
Displays the filesystem id number (
.I fs_id
), the total number of servers, the total and avaliable handles, and the total
and avalaible bytes.
.RE

Meta Server Statistics
.RS
Displays the 
.I bmi address
of the server, the total and available handles, the total and avalable bytes, and the mode of the server.
.RE

I/O Server Statistics
.RS
same as the meta server statistics above
.RE

.SH OPTIONS
.IP -m
Display information about the volume and servers at 
.I mount_point

.SH ENVIRONMENT
.IP PVFS2TAB_FILE
If set, the full pathname for an alternate 
.IR pvfs2tab
file

.SH BUGS
Please report all bugs to the pvfs2 bugzilla (http://bugzilla.mcs.anl.gov/pvfs/)
.SH AUTHOR
The PVFS2 development team (pvfs2-developers@beowulf-underground.org)
.SH "SEE ALSO"
.BR pvfs2-server (1),
.BR pvfs2-statfs (1)
.BR pvfs2-ping (1)
.BR pvfs2-import (1)
.BR pvfs2-export (1)
.BR pvfs2-genconfig (1)
