.TH PVFS2-CONFIG 1 2025-07-04
.SH NAME
\fBpvfs2-config\fR \(en pkgconf helper for orangefs
.SH SYNOPSIS
.B pvfs2-config
[\fB--prefix\fR[=\fIDIR\fR]] [\fB--exec-prefix\fR[=\fIDIR\fR]] [\fB--version\fR]
[\fB--cflags\fR] [\fB--libs\fR] [\fB--static-libs\fR] [\fB--serverlibs\fR]
[\fB--static-serverlibs\fR]

.SH DESCRIPTION
Helps to configure compiler and linker flags for development libraries.

.SH BUGS
Please submit bug reports to devel@lists.orangefs.org

