.TH PVFS2-SET-SYNC 1 2017-07-13
.SH NAME
\fBpvfs2-set-sync\fR \(en set server synchronization parameters
.SH SYNOPSIS
\fBpvfs2-set-sync\fR \fB\-m \fImount_point\fR [\fB\-D \fIdata\fR]
[\fB\-M \fImetadata\fR]
.SH DESCRIPTION
The
.I pvfs2-set-sync
utility is used to set whether data or metadata is implicity
synchronized to permanent storage on the server.
.PP
The options are as follows:
.IP -m
Specify the file system to operate on.
.IP -D
Specify whether file data is implicitly synchronized.  A setting of
.I 0
means off an
.I 1
means on.
.IP -M
Specify whether metadata is implicitly synchronized.  A setting of
.I 0
means off an
.I 1
means on.
.SH ENVIRONMENT
.IP PVFS2_DEBUGFILE
If set to the path of a local file, redirect debug output to it.
.IP PVFS2_DEBUGMASK
Set the OrangeFS debug mask.  Possible masks are documented in
.BR pvfs2-set-debugmask ( 1 ) \& .
.IP PVFS2TAB_FILE
If set, the full pathname for an alternate
.IR pvfs2tab
file
.SH FILES
.I /etc/pvfs2tab
.SH EXAMPLES
Synchronize metadata but not data.
.PP
.RS 6n
pvfs2-set-sync -m /mnt -D 0 -M 1
.RE
.SH BUGS
Please submit bug reports to pvfs2-developers@beowulf-underground.org
.SH SEE ALSO
.BR pvfs2-set-mode ( 1 ),
.BR pvfs2tab ( 5 )
