.TH PVFS2-CLIENT-CORE 1 2017-08-18
.SH NAME
\fBpvfs2-client-core\fR \(en internal kernel module userspace client
.SH SYNOPSIS
\fBpvfs2-client-core\fR
.SH DESCRIPTION
The
.B pvfs2-client-core
is used by the kernel module to communicate with the file system server.
It should not be run by users.
.SH BUGS
Please submit bug reports to pvfs2-developers@beowulf-underground.org
.SH SEE ALSO
.BR pvfs2-client ( 1 )
