.\" Process this file with
.\" groff -man -Tascii foo.1
.\" 
.TH "PVFS2-TOUCH" "1" "OCTOBER 2011" "PVFS2" "PVFS2 MANUALS"
.SH "NAME"
pvfs2\-touch \- Change the time stamp on a PVFS2 file
.SH "SYNOPSIS"
.B pvfs2\-touch
.I filename(s)
.SH "DESCRIPTION"
Change the timestamp for a PVFS2 file. If the file does not exist then a blank file will be created.
.SH "OPTIONS"
.IP \-l
Use list layout.
.IP \-r
Use random layout.
.SH "ENVIRONMENT"
.IP PVFS2TAB_FILE
If set, the full pathname for an alternate 
.I R pvfs2tab
file

.SH "BUGS"
Please report all bugs to the pvfs2 bugzilla (http://bugzilla.mcs.anl.gov/pvfs/)
.SH "AUTHOR"
The PVFS2 development team (pvfs2\-developers@beowulf\-underground.org)
