.TH PVFS2-STOP-ALL 1 2025-07-04
.SH NAME
\fBpvfs2-stop-all\fR \(en Stop all orangefs servers in config file.
.SH SYNOPSIS
.B pvfs2-stop-all --help

.SH DESCRIPTION
This script can parse an orangefs server config file and stop all
of the servers.

.SH BUGS
Please submit bug reports to devel@lists.orangefs.org
