.\" Process this file with
.\" groff -man -Tascii foo.1
.\" 
.TH "PVFS2-SET-EVENTMASK" "1" "SEPTEMBER 2011" "PVFS2" "PVFS2 MANUAL"
.SH "NAME"
pvfs2\-set\-eventmask \- Change the type of events that are logged for a given filesystem
.SH "SYNOPSIS"
.B pvfs2\-set\-eventmask
.I [\-v] [\-m mount_point] [\-e event(s)]
.SH "DESCRIPTION"
Set or change the event types that are logged for the filesystem located at
.I mount_point.
.SH "OPTIONS"
.IP \-v
Print the PVFS2 version and exit
.IP \-m
Change the logging events for this 
.I mount_point
.IP \-e
Comma seperated list of events to log
.SH "ENVIRONMENT"
.IP PVFS2TAB_FILE
If set, the full pathname for an alternate 
.I R pvfs2tab
file

.SH "BUGS"
Please report all bugs to the pvfs2 bugzilla (http://bugzilla.mcs.anl.gov/pvfs/)
.SH "AUTHOR"
The PVFS2 development team (pvfs2\-developers@beowulf\-underground.org)
.SH "SEE ALSO"
pvfs2\-set\-debugmask(1)
