.\" Process this file with
.\" groff -man -Tascii foo.1
.TH "PVFS2-DROP-CACHES" "1" "SEPTEMBER 2011" "PVFS2" "PVFS2 MANUALS"
.SH "NAME"
pvfs2\-drop\-caches \- Request that the OS flush and drop all I/O caches on all servers.
.SH "SYNOPSIS"
.B pvfs2\-drop\-caches
.I [OPTIONS]
.SH "DESCRIPTION"
Request that the OS drop and flush all I/O caches associated with the supplied mount point.
.SH "OPTIONS"
.IP \-m\ mount_point
Request that the operation be carried out on the filesystem located at the supplied mount
point.
.SH "ENVIRONMENT"
.IP PVFS2TAB_FILE
If set, the full pathname for an alternate 
.I R pvfs2tab
file

.SH "BUGS"
Please report all bugs to the pvfs2 bugzilla (http://bugzilla.mcs.anl.gov/pvfs/)
.SH "AUTHOR"
The PVFS2 development team (pvfs2\-developers@beowulf\-underground.org)
