.\" Process this file with
.\" groff -man -Tascii foo.1
.\" 
.TH "PVFS2-CONFIG-CONVERT" "1" "OCTOBER 2011" "PVFS2" "PVFS2 MANUALS"
.SH "NAME"
pvfs2\-config\-convert \- convert old fs.conf and server.conf to the new format.
.SH "SYNOPSIS"
.B pvfs2\-config\-convert
.I [OPTIONS] <old\-fs.conf> <old\-server.conf> <new\-fs.conf>
.SH "DESCRIPTIONS"
This utility script will convert an old fs.conf and old server.conf to the new format
which uses only a single fs.conf. Each of the options in the server.conf will be
added to the new fs.conf. This script does not have support for server.conf files
where multiple servers are running on a single node.
.SH "OPTIONS"
.IP \-\-servers
Required list of hostnames of all servers. Can be <prefix>{#\-#,#,#\-#,...}.
.SH "BUGS"
Please report all bugs to the pvfs2 bugzilla (http://bugzilla.mcs.anl.gov/pvfs/)
.SH "AUTHOR"
The PVFS2 development team (pvfs2\-developers@beowulf\-underground.org)
.SH "SEE ALSO"
.BR pvfs2\-genconfig(1)
