#!/usr/bin/perl -w

use Getopt::Long;
use POSIX "sys_wait_h";

#globals
my $session_file;
my %config;
my $rc = 0;
my $pid;

if (init()) {
    exit 1;
}

$rc = start_servers(\%config);
if ($rc) {
    print STDERR "WARNING: failed to start iod on remote node $rc, trying to recover\n";
    
    $rc = recover_from_bad(\%config, $rc);
    exit($rc);
}

exit(0);

sub start_servers{
    my $href = shift;

    my @nodes = ();
    my $rc = 0;

    if ($href->{'UNIQEMETA'} ) {
    	@nodes = (@{$href->{'IONODES'}}, @{$href->{'MGR'}});
    } else  {  
        # some subset of the io nodes will also be our meta servers
    	@nodes = (@{$href->{'IONODES'}} )
    }


    my $binary = $href->{'BINDIR'} . "/pvfs2-server";
    my $serverconf = $href->{'WORKINGDIR'} . "/pav.conf";
    my $localconf = $href->{'WORKINGDIR'} . "/server.conf";

    # once to make the storage space, then a second time to run the servers
    my $cmd = "%node $binary  -f $serverconf $localconf-%node";

    $rc = do_remote_command($href->{'RCMDPROG'}, 8, 30, $cmd, undef, undef, @nodes);

    $cmd = "%node $binary $serverconf $localconf-%node";
    $rc = do_remote_command($href->{'RCMDPROG'}, 8, 30, $cmd, undef, undef, @nodes);
    return($rc);
}

sub usage {

    print<<EOF;
Usage: $prog_name [option]
-s -session       session file for PAV to use
-sd -sessiondir   directory containing session file 'pvfs_autosession'
-rsh              remote shell command to use (default 'ssh')
-rcp              remote copy command to use (default 'scp')
-h -help          display this message
EOF
}

sub init {
    GetOptions(\%args,
	       's|session:s',
	       'sd|sessiondir:s',
	       'rsh:s',
	       'rcp:s',
	       'r|root:s',
	       'h|help'
	       );

    if ($args{'h'}) {
	usage();
	return(1);
    }

    if ($args{'s'}) {
	$session_file = $args{'s'};
    } elsif ($args{'sd'}) {
	$session_file = $args{'sd'} . "/pvfs_autosession";
    } else {
	usage();
	return(1);
    }

    if (!-f $session_file) {
	print STDERR "ERROR: cannot find session file: $session_file\n";
	return(1);
    }

    %config = ('RCMDPROG' => "ssh",
	       'RCPPROG' => "scp",
	       'PROGROOT' => "./"
	       );

    $config{'PROGROOT'} = $args{'r'} || $config{'PROGROOT'};
    my $prog_root = $config{'PROGROOT'};
    require "$prog_root/pav_lib.pl";

    $rc = read_sessionfile($session_file, \%config);
    if ($rc) {
	print STDERR "ERROR: cannot read session file\n";
	return(1);
    }

    $config{'RCMDPROG'} = $args{'rsh'} || $config{'RCMDPROG'};
    $config{'RCPPROG'} = $args{'rcp'} || $config{'RCPPROG'};

    $prog_name = $0;
    $pid = $$;

    return(0);
}
