#!/bin/sh
#
# description: mgr is the PVFS manager daemon
#
# chkconfig: 345 35 55

# Source function library.
. /etc/rc.d/init.d/functions

#PVFS_PREFIX=`cat /home/software/webwulf-config/pvfs_path`
#[ -f $PVFS_PREFIX/sbin/mgr ] || exit 0

# See how we were called.
case "$1" in
  start)
   echo -n "Starting PVFS V2 Server: "
  	../../../src/server/pvfs2-server ../../../src/server/simple.conf ../../../src/server/server.conf &
   echo
   touch pvfs2-server
   ;;
  stop)
   echo -n "Stopping PVFS V2 Server: "
   killproc pvfs2-server
   #echo
   #rm -f pvfs2-server
   ;;
  status)
        status pvfs2-server
   ;;
  restart)
   $0 stop
   $0 start
   ;;
  *)
   echo "Usage: $0 {start|stop|status|restart}"
   exit 1
esac

exit 0

