#ifndef FCACHED_H
#define FCACHED_H

#include <sys/stat.h>

#define FCACHE_LOGFILE_ENV_VAR "FCACHED_LOGFILE"
#define FCACHE_LOGFILE_DEFAULT "/var/log/pvfs2-fcached.log"

#define FCACHE_PIDFILE_ENV_VAR "FCACHED_PIDFILE"
#define FCACHE_PIDFILE_DEFAULT NULL
#define FCACHE_PIDFILE_MODE (S_IRUSR | S_IRUSR | S_IRUSR | S_IRUSR)
#define FCACHE_PID_BUFF_LEN 16

#endif /* FCACHED_H */
