OFSTest: OFSTest.OFSTestMain.OFSTestMain Class Reference
OFSTest.OFSTestMain.OFSTestMain Class Reference
This class drives the OrangeFS testing.
Public Member Functions
def setConfig
Sets self.config based on info from the command line, config file, etc.
def printConfig
Prints the dictionary of self.config.
def writeOutput
Writes the output of a test to the output file.
def initNetwork
Builds the OFSTestNetwork virtual cluster based on the config values.
def checkOFS
checks to see if OrangeFS is setup on the cluster.
def setupOFS
Builds the OFSTestNetwork as specified by the config.
def writeOutputHeader
Writes the output header to the file.
def runTest
Runs the tests for OrangeFS as specified by the config.
def runFunctionGroup
Run a function group.
Public Attributes
config
OFSTestConfig Testing configuration.
ofs_network
Detailed Description
This class drives the OrangeFS testing.
This sets up OrangeFS on the OFSTestNetwork based on the OFSTestConfig.
Definition at line 39 of file OFSTestMain.py.
Member Function Documentation
OFSTest.OFSTestMain.OFSTestMain.checkOFS (self)
checks to see if OrangeFS is setup on the cluster.
Parameters
self The object pointer
Returns
0 OrangeFS setup
Not 0 OrangeFS not setup
Definition at line 174 of file OFSTestMain.py.
References OFSTest.OFSTestMain.OFSTestMain.initNetwork().
OFSTest.OFSTestMain.OFSTestMain.initNetwork (self)
Builds the OFSTestNetwork virtual cluster based on the config values.
Parameters
self The object pointer
Definition at line 118 of file OFSTestMain.py.
Referenced by OFSTest.OFSTestMain.OFSTestMain.checkOFS(), and OFSTest.OFSTestMain.OFSTestMain.setupOFS().
def OFSTest.OFSTestMain.OFSTestMain.printConfig (self)
Prints the dictionary of self.config.
For debugging.
Parameters
self The object pointer
Definition at line 89 of file OFSTestMain.py.
def OFSTest.OFSTestMain.OFSTestMain.runFunctionGroup (self, function_group_name)
Run a function group.
Function groups are in separate files with appropriate test functions in them. For example, OFSSysintTest.py contains the OFSSysintTest function group that tests the system integration functions.
Parameters
self The object pointer
function_group_name The name of the python namespace that contains the function. This should be the same as the python file that contains the functions without the .py extension.
Definition at line 718 of file OFSTestMain.py.
References OFSTest.OFSTestMain.OFSTestMain.writeOutput(), and OFSTest.OFSTestMain.OFSTestMain.writeOutputHeader().
def OFSTest.OFSTestMain.OFSTestMain.runTest (self)
Runs the tests for OrangeFS as specified by the config.
Parameters
self The object pointer
Definition at line 443 of file OFSTestMain.py.
References OFSTest.OFSTestMain.OFSTestMain.writeOutput(), and OFSTest.OFSTestMain.OFSTestMain.writeOutputHeader().
def OFSTest.OFSTestMain.OFSTestMain.setConfig (self, kwargs)
Sets self.config based on info from the command line, config file, etc.
Parameters
self The object pointer
kwargs Dictionary with configuration variable,value pairs. See OFSTestConfig for possible values.
Definition at line 78 of file OFSTestMain.py.
def OFSTest.OFSTestMain.OFSTestMain.setupOFS (self)
Builds the OFSTestNetwork as specified by the config.
Parameters
self The object pointer
Definition at line 231 of file OFSTestMain.py.
References OFSTest.OFSTestMain.OFSTestMain.initNetwork().
def OFSTest.OFSTestMain.OFSTestMain.writeOutput (self, filename, function, rc)
Writes the output of a test to the output file.
If test function returns 0, assume success, otherwise, failure.
Parameters
self The object pointer
filename Name of output file
function Function that was tested.
rc Return code of the tested function
Definition at line 103 of file OFSTestMain.py.
Referenced by OFSTest.OFSTestMain.OFSTestMain.runFunctionGroup(), and OFSTest.OFSTestMain.OFSTestMain.runTest().
def OFSTest.OFSTestMain.OFSTestMain.writeOutputHeader (self, filename, header, mode = 'a+')
Writes the output header to the file.
Parameters
self The object pointer
filename The file to write the message
header The message to write in the header
mode Mode to open the file. Default is append (a+).
Definition at line 428 of file OFSTestMain.py.
Referenced by OFSTest.OFSTestMain.OFSTestMain.runFunctionGroup(), and OFSTest.OFSTestMain.OFSTestMain.runTest().
Member Data Documentation
OFSTest.OFSTestMain.OFSTestMain.config
OFSTestConfig Testing configuration.
Definition at line 51 of file OFSTestMain.py.
OFSTest.OFSTestMain.OFSTestMain.ofs_network
Definition at line 3 of file OFSTestMain.py.
The documentation for this class was generated from the following files:
OFSTest/OFSTestMain.py