OFSTest: OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager Class Reference
OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager Class Reference
This class manages the cloud connection using the OpenStack Nova API.
Public Member Functions
def readCloudConfigFile
Reads relevant values from openrc.sh file.
def readCloudPasswordFile
Reads relevant values from password file.
def connect
Gets region info and connects to Cloud.
def terminateCloudInstance
Terminates a running Cloud instance.
def createNewCloudInstances
Creates new EC2 instances and returns list of them.
def associateIPAddresses
Creates an new external IP address and associates with the instances in the array.
def checkCloudConnection
Checks to see if the Cloud connection is available.
def getAllCloudImages
Gets all images from Cloud connection.
def printAllInstanceStatus
Prints the status of all instances.
def instanceIsDaysOld
Tests whether an instance is so many days old.
def refreshCloudInstanceList
def deleteOldInstances
deleteOldInstances(days_old,name_filter,key_filter)
def getCloudConfigFromEnvironment
def manageExistingCloudInstance
def getCloudInstanceInformation
def deleteCloudInstance
def hardRebootCloudInstance
def deleteAllCloudInstances
def createNewCloudNodes
Creates new cloud nodes and adds them to network_nodes list.
Public Member Functions inherited from OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager
def readCloudConfigFile
Reads relevant values from configuration file.
def readCloudPasswordFile
Reads relevant values from password file.
def connect
Gets region info and connects to Cloud.
def setCloudKey
Sets key name (Cloud) and key location (file) used to create and access Cloud instances.
def getAllCloudImages
def terminateCloudInstance
Terminates a running Cloud instance.
def createNewCloudInstances
Creates new Cloud instances and returns list of them.
def associateIPAddresses
Creates an new external IP address and associates with the instances in the array.
def checkCloudConnection
Checks to see if the Cloud connection is available.
def getAllCloudInstances
Gets all instances from Cloud connection.
def printAllInstanceStatus
Prints the status of all instances.
def instanceIsDaysOld
Tests whether an instance is so many days old.
def deleteOldInstances
deleteOldInstances(days_old,name_filter,key_filter)
def getCloudConfigFromEnvironment
def manageExistingCloudInstance
def getCloudInstanceInformation
def deleteCloudInstance
def hardRebootCloudInstance
def deleteAllCloudInstances
def createNewCloudNodes
Creates new cloud nodes and adds them to network_nodes list.
Public Attributes
cloud_instance_key
cloud_instance_key_location
nova_auth_url
nova_default_role_name
nova_username
nova_tenant_name
nova_passwdfile
nova_password
nova_network_id
keystoneapi
novaapi
glance_endpoint
glanceapi
nova_network_name
cloud_image_list
cloud_instances
Public Attributes inherited from OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager
cloud_instance_names
Dictionary of Cloud instance names.
cloud_instance_list
cloud_image_list
cloud_key_list
cloud_is_secure
cloud_instance_key
cloud_instance_key_location
Detailed Description
This class manages the cloud connection using the OpenStack Nova API.
It has no awareness of OFSTestNodes or the OFSTestNetwork.
Definition at line 34 of file OFSNovaConnectionManager.py.
Member Function Documentation
def OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.associateIPAddresses (self, instances = [], domain = None)
Creates an new external IP address and associates with the instances in the array.
Parameters
self The object pointer
instances List of instances to associate
domain Domain on which to allocate addresses
Returns
A list of the external addresses
Definition at line 247 of file OFSNovaConnectionManager.py.
def OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.checkCloudConnection (self)
Checks to see if the Cloud connection is available.
Connects if it isn't.
Parameters
self The object pointer
Definition at line 277 of file OFSNovaConnectionManager.py.
References OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.checkCloudConnection(), OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.cloud_instances, OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.connect(), OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.getAllCloudInstances(), and OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.novaapi.
def OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.connect (self, debug = 0)
Gets region info and connects to Cloud.
Cloud.connection.CloudConnection object should be stored in self.cloud_connection.
Parameters
self The object pointer
debug Debug level.
Definition at line 153 of file OFSNovaConnectionManager.py.
References OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.glance_endpoint, OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.glanceapi, OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.keystoneapi, OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.nova_auth_url, OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.nova_password, OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.nova_tenant_name, OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.nova_username, and OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.novaapi.
def OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.createNewCloudInstances (self, number_nodes, image_name, flavor_name, subnet_id = None)
Creates new EC2 instances and returns list of them.
Parameters
self The object pointer
number_nodes Number of nodes to create
image_name Image to run. (e.g. "cloud-ubuntu-12.04")
flavor_name Image "flavor" (e.g. "m1.medium")
subnet_id Id of subnet instance should run on
Returns
A list of new instances.
Definition at line 205 of file OFSNovaConnectionManager.py.
References OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.checkCloudConnection().
def OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.createNewCloudNodes (self, number_nodes, image_name, flavor_name, local_master, associateip = False, domain = None, cloud_subnet = None)
Creates new cloud nodes and adds them to network_nodes list.
Parameters
self The object pointer
number_nodes number of nodes to be created
image_name Name of Cloud image to launch
flavor_name Cloud "flavor" of virtual node
associateip Associate to external ip?
domain Domain to associate with external ip
cloud_subnet cloud subnet id for primary network interface.
Returns
list of new nodes.
Definition at line 426 of file OFSNovaConnectionManager.py.
References OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.associateIPAddresses(), OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.cloud_instance_key_location, OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.createNewCloudInstances(), OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.nova_network_name, and OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.refreshCloudInstanceList().
def OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.deleteAllCloudInstances (self)
Definition at line 405 of file OFSNovaConnectionManager.py.
def OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.deleteCloudInstance (self, Cloud_node)
Definition at line 399 of file OFSNovaConnectionManager.py.
def OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.deleteOldInstances (self, days_old = 7, name_filter = "", key_filter = "")
deleteOldInstances(days_old,name_filter,key_filter)
Delete instances over a certain number of days old.
Parameters
self The object pointer
days_old Age to check
name_filter Filter to only delete instances matching name
key_filter Filter to only delete instance associated with this Cloud key
Definition at line 365 of file OFSNovaConnectionManager.py.
References OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.checkCloudConnection(), OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.cloud_instance_list, OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.getAllCloudInstances(), and OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.instanceIsDaysOld().
def OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.getAllCloudImages (self)
Gets all images from Cloud connection.
Returns a list of images.
Parameters
self The object pointer
Definition at line 301 of file OFSNovaConnectionManager.py.
References OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.checkCloudConnection(), and OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.cloud_image_list.
def OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.getCloudConfigFromEnvironment (self)
Definition at line 389 of file OFSNovaConnectionManager.py.
def OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.getCloudInstanceInformation (self, Cloud_node)
Definition at line 395 of file OFSNovaConnectionManager.py.
def OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.hardRebootCloudInstance (self, Cloud_node)
Definition at line 402 of file OFSNovaConnectionManager.py.
def OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.instanceIsDaysOld (self, instance, days_old = 7)
Tests whether an instance is so many days old.
Parameters
self The object pointer
instance Instance to check
days_old Age to check
Returns
True if instance is at least days_old days old
Fals if instance is not days_old
Definition at line 331 of file OFSNovaConnectionManager.py.
def OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.manageExistingCloudInstance (self, Cloud_node)
Definition at line 392 of file OFSNovaConnectionManager.py.
def OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.printAllInstanceStatus (self)
Prints the status of all instances.
For debugging.
Parameters
self The object pointer
Definition at line 314 of file OFSNovaConnectionManager.py.
References OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.cloud_instance_list, and OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.getAllCloudInstances().
def OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.readCloudConfigFile (self, filename)
Reads relevant values from openrc.sh file.
Parameters
self The object pointer
filename Path to openrc.sh file
Definition at line 103 of file OFSNovaConnectionManager.py.
References OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.nova_auth_url, OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.nova_tenant_name, and OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.nova_username.
def OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.readCloudPasswordFile (self, filename)
Reads relevant values from password file.
This file contains the password for nova that is used for the OS_PASSWORD value
Parameters
self The object pointer
filename Path to file
Definition at line 140 of file OFSNovaConnectionManager.py.
References OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.nova_password.
def OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.refreshCloudInstanceList (self, instances = [])
Definition at line 346 of file OFSNovaConnectionManager.py.
Referenced by OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.createNewCloudNodes().
OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.terminateCloudInstance (self, ip_address)
Terminates a running Cloud instance.
Parameters
self The object pointer
ip_address IP address (internal) of the node.
Returns
1 Instance not found for that ip address
0 Instance terminated.
Definition at line 178 of file OFSNovaConnectionManager.py.
References OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.checkCloudConnection(), and OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.nova_network_name.
Member Data Documentation
OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.cloud_image_list
Definition at line 211 of file OFSNovaConnectionManager.py.
OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.cloud_instance_key
OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.cloud_instance_key_location
Definition at line 3 of file OFSNovaConnectionManager.py.
OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.cloud_instances
Definition at line 301 of file OFSNovaConnectionManager.py.
Referenced by OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.checkCloudConnection().
OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.glance_endpoint
Definition at line 14 of file OFSNovaConnectionManager.py.
Referenced by OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.connect().
OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.glanceapi
Definition at line 16 of file OFSNovaConnectionManager.py.
Referenced by OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.connect().
OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.keystoneapi
Definition at line 12 of file OFSNovaConnectionManager.py.
Referenced by OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.connect().
OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.nova_auth_url
Definition at line 5 of file OFSNovaConnectionManager.py.
Referenced by OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.connect(), and OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.readCloudConfigFile().
OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.nova_default_role_name
Definition at line 6 of file OFSNovaConnectionManager.py.
OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.nova_network_id
Definition at line 11 of file OFSNovaConnectionManager.py.
OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.nova_network_name
Definition at line 22 of file OFSNovaConnectionManager.py.
Referenced by OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.createNewCloudNodes(), and OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.terminateCloudInstance().
OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.nova_passwdfile
Definition at line 9 of file OFSNovaConnectionManager.py.
OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.nova_password
Definition at line 10 of file OFSNovaConnectionManager.py.
Referenced by OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.connect(), and OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.readCloudPasswordFile().
OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.nova_tenant_name
Definition at line 8 of file OFSNovaConnectionManager.py.
Referenced by OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.connect(), and OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.readCloudConfigFile().
OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.nova_username
Definition at line 7 of file OFSNovaConnectionManager.py.
Referenced by OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.connect(), and OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.readCloudConfigFile().
OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.novaapi
Definition at line 13 of file OFSNovaConnectionManager.py.
Referenced by OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.checkCloudConnection(), and OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.connect().
The documentation for this class was generated from the following files:
OFSTest/OFSNovaConnectionManager.py