OFSTest: OFSTest.OFSTestLocalNode.OFSTestLocalNode Class Reference
OFSTest.OFSTestLocalNode.OFSTestLocalNode Class Reference
This class is for the local machine.
Public Member Functions
def __init__
def currentNodeInformation
Gets the current node information, including external ip address.
def runAllBatchCommands
Writes stored batch commands to a file, then runs them.
def prepareCommandLine
Formats the command line to run on this specific type of node with appropriate environment.
def copyToRemoteNode
This copies files from this node to the remote node via rsync.
def copyFromRemoteNode
This copies files from the remote node to this node via rsync.
def getAliasesFromConfigFile
Reads the OrangeFS alias from the configuration file.
Public Member Functions inherited from OFSTest.OFSTestNode.OFSTestNode
def __init__
Initialize node.
def currentNodeInformation
Logs into the node to gain information about the system.
def changeDirectory
Change the current directory on the node to run scripts.
def restoreDirectory
Restore directory - This restores the previous directory.
def setEnvironmentVariable
set an environment variable to a value
def unsetEnvironmentVariable
Erase an environment variable.
def setEnvironment
This function sets the environment based on the output of setenv.
def clearEnvironment
Clear all environment variables.
def printWorkingDirectory
def addBatchCommand
Add a command to the list of batch commands to be run.
def runSingleCommand
This runs a single command and returns the return code of that command.
def runSingleCommandBacktick
This runs a single command and returns the stdout of that command.
def runOFSTest
This method runs an OrangeFS test on the given node.
def prepareCommandLine
This method prepares the command line for run single command.
def runAllBatchCommands
This method runs all the batch commands in the list.
def runSingleCommandAsBatch
Run a single command as a batchfile.
def runBatchFile
Run a batch file through the system.
def copyToRemoteNode
copy files from the current node to a destination node.
def copyFromRemoteNode
This copies files from the remote node to this node via rsync.
def writeToOutputFile
writeToOutputFile()
def getRemoteKeyFile
ssh utility functions
def addRemoteKey
This method adds the location of the key for machine at address to the keytable.
def copyLocal
This runs the copy command locally.
def updateNode
This function updates the software on the node via the package management system.
def installTorqueServer
This function installs and configures the torque server from the package management system on the node.
def installTorqueClient
This function installs and configures the torque client from the package management system on the node.
def restartTorqueServer
When installed from the package manager, torque doesn't start with correct options.
def restartTorqueMom
When installed from the package manager, torque doesn't start with correct options.
def installRequiredSoftware
This installs all the prerequisites for building and testing OrangeFS from the package management system.
def installMpich2
This function installs mpich2 software TODO: Must be reimplemented to match OpenMPI installation.
def installOpenMPI
This function installs OpenMPI software.
def copyOFSSourceFromSVN
This copies the source from an SVN branch.
def installBenchmarks
This downloads and untars the thirdparty benchmarks.
def makeFromTarFile
This is a generic function to .
def copyOFSSourceFromRemoteTarball
This downloads the source from a remote tarball.
def copyOFSSourceFromDirectory
This copies the source from a local directory.
def copyOFSSourceFromRemoteNode
This copies the source from a remote directory.
def copyOFSSource
This copies the source from wherever it is.
def configureOFSSource
This prepares the OrangeFS source and runs the configure command.
def checkMount
This looks to see if a given mount_point is mounted.
def getAliasesFromConfigFile
Reads the OrangeFS alias from the configuration file.
def makeOFSSource
This makes the OrangeFS source.
def getKernelVersion
wrapper for uname -r
def installOFSSource
This looks to see if a given mount_point is mounted.
def installOFSTests
This installs the OrangeFS test programs in the OFS source tree.
def exportNFSDirectory
this exports directory directory_name via NFS.
def mountNFSDirectory
this mounts nfs_share at mount_point with options.
def clearSHM
This clears out all SHM objects for OrangeFS.
def copyOFSInstallationToNode
This copies an entire OrangeFS installation from the current node to destination_node.
def configureOFSServer
This function runs the configuration programs and puts the result in self.ofs_installation_location/etc/orangefs.conf.
def startOFSServer
This function starts the orangefs server.
def stopOFSServer
This function stops the OrangeFS servers.
def installKernelModule
This function inserts the kernel module into the kernel.
def startOFSClient
This function starts the orangefs client.
def mountOFSFilesystem
This function mounts OrangeFS via kernel module or fuse.
def unmountOFSFilesystem
This function unmounts OrangeFS.
def stopOFSClient
This function stops the orangefs client and unmounts the filesystem.
def findExistingOFSInstallation
This function finds an existing OrangeFS installation on the node.
Public Attributes
is_remote
Local nodes are neither remote nor Cloud.
is_cloud
Is this node an cloud node? Always false, even if it's true.
ip_address
set to local host
current_user
Current logged in user.
ext_ip_address
batch_commands
Public Attributes inherited from OFSTest.OFSTestNode.OFSTestNode
alias_list
list of OrangeFS Aliases
ip_address
ip address on internal network
ext_ip_address
ip address on external network
hostname
current hostname
distro
operating system
package_system
package system (rpm/dpkg)
kernel_source_location
location of the linux kernel source
kernel_version
Output of (uname -r)
is_remote
is this a remote machine?
is_cloud
is this an cloud/openstack instance?
processor_type
type of processor (i386/x86_64)
current_user
main user login.
current_directory
current working directory
previous_directory
previous directory
current_environment
current environment variables
batch_commands
commands written to a batch file
sshLocalKeyFile
The local key file is the location of the key on the local host.
sshNodeKeyFile
The node key file is the file on the node that contains the key to access this machine.
keytable
The keytable is a dictionary of locations of keys to remote machines on the current node.
ofs_source_location
This is the location of the OrangeFS source.
ofs_storage_location
This is the location of the OrangeFS storage.
ofs_installation_location
This is where OrangeFS is installed.
ofs_extra_tests_location
This is the location of the third party benchmarks.
ofs_mount_point
This is the mount_point for OrangeFS.
ofs_fs_name
This is the OrangeFS service name.
ofs_branch
svn branch (or ofs source directory name)
ofs_conf_file
Location of orangefs.conf file.
build_kmod
Do we need to build the kernel module?
ofs_tcp_port
default tcp port
db4_dir
berkeley db4 location
db4_lib_dir
berkeley db4 library location
mpich2_installation_location
mpich2_source_location
mpich2_version
created_mpichhosts
openmpi_installation_location
openmpi_source_location
openmpi_version
created_openmpihosts
Created openmpihosts file.
mpi_nfs_directory
Where is the common mpi nfs directory?
romio_runtests_pvfs2
Where is the romio test script?
hadoop_version
Version of hadoop software.
hadoop_location
Location of hadoop installation.
jdk6_location
Location of Oracle JDK 6.
node_number
current_group
Additional Inherited Members
Static Public Attributes inherited from OFSTest.OFSTestNode.OFSTestNode
int node_number = 0
variable for number of node in the cluster.
Detailed Description
This class is for the local machine.
Since there is always one and only one local machine, there should always be one and only one instance of OFSTestLocalNode.
The OFSTestLocalNode is the "master" of the OFSTest system. It controls access to all the other nodes. This is because you access remote nodes through your local machine.
This programs assumes that the OFSTestNode is a *nix machine operating a bash shell. MacOSX functionality may be limited. Windows local nodes are not currently supported.
Definition at line 28 of file OFSTestLocalNode.py.
Constructor & Destructor Documentation
def OFSTest.OFSTestLocalNode.OFSTestLocalNode.__init__ (self)
Definition at line 32 of file OFSTestLocalNode.py.
Member Function Documentation
def OFSTest.OFSTestLocalNode.OFSTestLocalNode.copyFromRemoteNode (self, source_node, source, destination, recursive = False)
This copies files from the remote node to this node via rsync.
Parameters
self The object pointer
source_node Node from which files should be copied
source Source file or directory on remote node.
destination Destination file or directory
recursive Copy recursively?
Returns
Return code of copy command.
Definition at line 248 of file OFSTestLocalNode.py.
References OFSTest.OFSTestNode.OFSTestNode.getRemoteKeyFile(), and OFSTest.OFSTestNode.OFSTestNode.runSingleCommand().
def OFSTest.OFSTestLocalNode.OFSTestLocalNode.copyToRemoteNode (self, source, destination_node, destination, recursive = False)
This copies files from this node to the remote node via rsync.
Parameters
self The object pointer
source Source file or directory
destination_node Node to which files should be copied
destination Destination file or directory on remote node.
recursive Copy recursively?
Returns
Return code of copy command.
Definition at line 215 of file OFSTestLocalNode.py.
References OFSTest.OFSTestNode.OFSTestNode.getRemoteKeyFile(), and OFSTest.OFSTestNode.OFSTestNode.runSingleCommand().
Referenced by OFSTest.OFSTestNode.OFSTestNode.copyOFSInstallationToNode().
def OFSTest.OFSTestLocalNode.OFSTestLocalNode.currentNodeInformation (self)
Gets the current node information, including external ip address.
Parameters
self The object pointer
Definition at line 60 of file OFSTestLocalNode.py.
def OFSTest.OFSTestLocalNode.OFSTestLocalNode.getAliasesFromConfigFile (self, config_file_name)
Reads the OrangeFS alias from the configuration file.
Parameters
self The object pointer
config_file_name Full path to the configuration file. (Usually orangefs.conf)
Returns
list of alias names
Definition at line 275 of file OFSTestLocalNode.py.
References OFSTest.OFSTestNode.OFSTestNode.runSingleCommandBacktick().
Referenced by OFSTest.OFSTestNode.OFSTestNode.startOFSServer().
def OFSTest.OFSTestLocalNode.OFSTestLocalNode.prepareCommandLine (self, command, outfile = "", append_out = False, errfile = "", append_err = False, remote_user = None)
Formats the command line to run on this specific type of node with appropriate environment.
Parameters
self The object pointer
command Shell command to be run.
outfile File to redirect stdout to.
append_out Append outfile or overwrite?
errfile File to redirect stderr to.
append_err Append errfile or overwrite?
remote_user Run command as this user
Returns
String Formatted command line.
Definition at line 155 of file OFSTestLocalNode.py.
References OFSTest.OFSTestNode.OFSTestNode.current_directory, OFSTest.OFSTestNode.OFSTestNode.current_environment, and OFSTest.OFSTestLocalNode.OFSTestLocalNode.current_user.
Referenced by OFSTest.OFSTestNode.OFSTestNode.runSingleCommand().
def OFSTest.OFSTestLocalNode.OFSTestLocalNode.runAllBatchCommands (self, output = [])
Writes stored batch commands to a file, then runs them.
Parameters
self The object pointer
output Output of command
Definition at line 87 of file OFSTestLocalNode.py.
References OFSTest.OFSTestLocalNode.OFSTestLocalNode.batch_commands, OFSTest.OFSTestNode.OFSTestNode.current_directory, and OFSTest.OFSTestNode.OFSTestNode.current_environment.
Referenced by OFSTest.OFSTestNode.OFSTestNode.installKernelModule(), OFSTest.OFSTestNode.OFSTestNode.installRequiredSoftware(), OFSTest.OFSTestNode.OFSTestNode.installTorqueClient(), OFSTest.OFSTestNode.OFSTestNode.installTorqueServer(), OFSTest.OFSTestNode.OFSTestNode.mountOFSFilesystem(), OFSTest.OFSTestNode.OFSTestNode.restartTorqueServer(), OFSTest.OFSTestNode.OFSTestNode.runBatchFile(), OFSTest.OFSTestNode.OFSTestNode.runSingleCommandAsBatch(), OFSTest.OFSTestNode.OFSTestNode.startOFSClient(), OFSTest.OFSTestNode.OFSTestNode.stopOFSClient(), and OFSTest.OFSTestNode.OFSTestNode.updateNode().
Member Data Documentation
OFSTest.OFSTestLocalNode.OFSTestLocalNode.batch_commands
Definition at line 133 of file OFSTestLocalNode.py.
Referenced by OFSTest.OFSTestLocalNode.OFSTestLocalNode.runAllBatchCommands(), OFSTest.OFSTestRemoteNode.OFSTestRemoteNode.runAllBatchCommands(), and OFSTest.OFSTestNode.OFSTestNode.runBatchFile().
OFSTest.OFSTestLocalNode.OFSTestLocalNode.current_user
Current logged in user.
Definition at line 47 of file OFSTestLocalNode.py.
Referenced by OFSTest.OFSTestNode.OFSTestNode.configureOFSSource(), OFSTest.OFSTestNode.OFSTestNode.currentNodeInformation(), OFSTest.OFSTestNode.OFSTestNode.installBenchmarks(), OFSTest.OFSTestNode.OFSTestNode.installMpich2(), OFSTest.OFSTestNode.OFSTestNode.installTorqueServer(), OFSTest.OFSTestNode.OFSTestNode.mountNFSDirectory(), OFSTest.OFSTestLocalNode.OFSTestLocalNode.prepareCommandLine(), OFSTest.OFSTestRemoteNode.OFSTestRemoteNode.prepareCommandLine(), OFSTest.OFSTestRemoteNode.OFSTestRemoteNode.runAllBatchCommands(), OFSTest.OFSTestNode.OFSTestNode.runSingleCommand(), OFSTest.OFSTestNode.OFSTestNode.runSingleCommandBacktick(), and OFSTest.OFSTestRemoteNode.OFSTestRemoteNode.uploadRemoteKeyFromLocal().
OFSTest.OFSTestLocalNode.OFSTestLocalNode.ext_ip_address
Definition at line 63 of file OFSTestLocalNode.py.
Referenced by OFSTest.OFSTestRemoteNode.OFSTestRemoteNode.getKeyFileFromLocal(), OFSTest.OFSTestRemoteNode.OFSTestRemoteNode.prepareCommandLine(), OFSTest.OFSTestRemoteNode.OFSTestRemoteNode.runAllBatchCommands(), OFSTest.OFSTestRemoteNode.OFSTestRemoteNode.uploadNodeKeyFromLocal(), and OFSTest.OFSTestRemoteNode.OFSTestRemoteNode.uploadRemoteKeyFromLocal().
OFSTest.OFSTestLocalNode.OFSTestLocalNode.ip_address
set to local host
Definition at line 44 of file OFSTestLocalNode.py.
Referenced by OFSTest.OFSTestNode.OFSTestNode.exportNFSDirectory(), and OFSTest.OFSTestNode.OFSTestNode.updateNode().
OFSTest.OFSTestLocalNode.OFSTestLocalNode.is_cloud
Is this node an cloud node? Always false, even if it's true.
Definition at line 41 of file OFSTestLocalNode.py.
OFSTest.OFSTestLocalNode.OFSTestLocalNode.is_remote
Local nodes are neither remote nor Cloud.
Definition at line 38 of file OFSTestLocalNode.py.
The documentation for this class was generated from the following file:
OFSTest/OFSTestLocalNode.py