OFSTest: OFSTest.OFSTestConfigMenu.OFSTestConfigMenu Class Reference
OFSTest.OFSTestConfigMenu.OFSTestConfigMenu Class Reference
Public Member Functions
def __init__
def yes_no_prompt
def menu_selection
def filepath_prompt
def directory_prompt
def ip_prompt
def hostname_prompt
def string_prompt
def int_prompt
def add_remote_nodes
def setConfig
Public Member Functions inherited from OFSTest.OFSTestConfig.OFSTestConfig
def __init__
def setConfig
A universal method for setting the initial configuration.
def addConfig
This method can "override" existing values as specified in str_args.
def printDict
This prints all the setup variables.
def setConfigFromDict
This method takes a formatted dictionary d and converts the values into the variables of this class.
Public Attributes
node_ip_address
node_usernames
using_cloud
cloud_config
ssh_key_filepath
cloud_key_name
number_new_cloud_nodes
cloud_image
cloud_machine
cloud_delete_after_test
ofs_resource_location
ofs_resource_type
run_sysint_tests
run_vfs_tests
configure_opts
pvfs2genconfig_opts
Public Attributes inherited from OFSTest.OFSTestConfig.OFSTestConfig
log_file
name of output logfile
using_cloud
Are we using OpenStack/Cloud?
cloud_config
Location of the ec2rc.sh/openstack.sh file.
ssh_key_filepath
Path of ssh key used to access all nodes.
ssh_key_filepaths
List of differing keypaths, if applicable.
cloud_key_name
Internal cloud key name.
number_new_cloud_nodes
Number of new cloud nodes to be created.
cloud_image
Image name to be launched for cloud instance.
cloud_machine
cloud machine type (e.g.
cloud_delete_after_test
Should the nodes be deleted after testing?
cloud_domain
Cloud domain.
cloud_associate_ip
Associate external ip address with Cloud nodes?
node_ip_addresses
List of node ip addresses.
node_ext_ip_addresses
List of addresses accessible from the local machine.
node_username
Single username to access all nodes.
node_usernames
usernames for login of individual nodes, if necessary
ofs_fs_name
Name of OrangeFS filesystem service in URL.
ofs_resource_location
location of OrangeFS source
ofs_resource_type
What package is the OrangeFS source? SVN, TAR, Local Dir, Node?
pvfs2genconfig_opts
Additional options for pvfs2genconfig to generate Orangefs.conf file.
install_fuse
Build Fuse module.
install_prefix
Where to install OrangeFS.
db4_prefix
Location of DB4.
install_OFS_client
Install the OrangeFS client and add –with-kernel option.
install_shared
–enable-shared flag
enable_strict
–enable-strict flag
ofs_security_mode
Security Mode.
ofs_build_kmod
Build the kernel module?
ofs_compile_debug
Compile with -g debugging option?
ofs_patch_files
List of patches to patch OrangeFS source.
svn_username
Username of svn user.
svn_password
Password of svn user.
svn_options
Additional options for SVN.
install_hadoop
Enable OrangeFS hadoop support.
configure_opts
Additional options for configure.
mount_OFS_after_setup
Mount the filesystem after setup.
ofs_mount_as_fuse
Mount filesystem using the fuse module instead of kernel module.
install_tests
Install OrangeFS tests.
install_OFS_server
Install and start the OrangeFS server software.
install_MPI
Install MPI software, including Torque.
install_opts
Additional installation options.
ofs_extra_tests_location
location of suite of testing benchmarks
ofs_pvfs2tab_file
location of PVFS2TAB_FILE.
ofs_source_location
location of orangefs on the main node
ofs_config_file
Location of OrangeFS.conf file.
delete_existing_data
Delete data on OrangeFS partition.
ofs_mount_point
OrangeFS mount point.
ofs_host_name_override
Override the hostname given by hostname command.
start_client_on_all_nodes
Start the OrangeFS client on all nodes after installation?
run_sysint_tests
Run the system integration tests?
run_usrint_tests
Run the user integration library tests?
run_vfs_tests
Run the kernel module vfs tests?
run_fuse_tests
Run the fuse vfs tests?
run_mpi_tests
Run OrangeFS ROM-IO tests.
run_hadoop_tests
Run OrangeFS Hadoop tests.
cloud_subnet
cloud subnet ID for primary network interface self.cloud_subnet=None TODO: Remove hardcoded definition.
cloud_type
nova_password_file
Detailed Description
Definition at line 15 of file OFSTestConfigMenu.py.
Constructor & Destructor Documentation
def OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.__init__ (self)
Definition at line 18 of file OFSTestConfigMenu.py.
Member Function Documentation
def OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.add_remote_nodes (self, keyfile, is_cloud = False)
Definition at line 157 of file OFSTestConfigMenu.py.
References OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.ip_prompt(), OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.node_ip_address, OFSTest.OFSTestConfig.OFSTestConfig.node_usernames, OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.string_prompt(), and OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.yes_no_prompt().
def OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.directory_prompt (self, prompt, default = "", validate = True)
Definition at line 82 of file OFSTestConfigMenu.py.
References OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.string_prompt().
def OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.filepath_prompt (self, prompt, default = "", validate = True)
Definition at line 57 of file OFSTestConfigMenu.py.
References OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.string_prompt().
def OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.hostname_prompt (self, prompt, default = "", validate = False)
Definition at line 120 of file OFSTestConfigMenu.py.
References OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.string_prompt().
def OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.int_prompt (self, prompt, default = "")
Definition at line 148 of file OFSTestConfigMenu.py.
References OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.string_prompt().
def OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.ip_prompt (self, prompt, default = "", validate = False)
Definition at line 105 of file OFSTestConfigMenu.py.
References OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.string_prompt().
Referenced by OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.add_remote_nodes().
def OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.menu_selection (self, prompt, options = [], default = 0)
Definition at line 42 of file OFSTestConfigMenu.py.
def OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.setConfig (self, kwargs = {})
Definition at line 192 of file OFSTestConfigMenu.py.
def OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.string_prompt (self, prompt, default = "")
Definition at line 134 of file OFSTestConfigMenu.py.
Referenced by OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.add_remote_nodes(), OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.directory_prompt(), OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.filepath_prompt(), OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.hostname_prompt(), OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.int_prompt(), OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.ip_prompt(), and OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.yes_no_prompt().
def OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.yes_no_prompt (self, prompt)
Definition at line 31 of file OFSTestConfigMenu.py.
References OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.string_prompt().
Referenced by OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.add_remote_nodes().
Member Data Documentation
OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.cloud_config
Definition at line 201 of file OFSTestConfigMenu.py.
OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.cloud_delete_after_test
Definition at line 227 of file OFSTestConfigMenu.py.
OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.cloud_image
Definition at line 216 of file OFSTestConfigMenu.py.
OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.cloud_key_name
Definition at line 205 of file OFSTestConfigMenu.py.
OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.cloud_machine
Definition at line 217 of file OFSTestConfigMenu.py.
OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.configure_opts
Definition at line 240 of file OFSTestConfigMenu.py.
OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.node_ip_address
Definition at line 188 of file OFSTestConfigMenu.py.
Referenced by OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.add_remote_nodes().
OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.node_usernames
Definition at line 189 of file OFSTestConfigMenu.py.
OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.number_new_cloud_nodes
Definition at line 215 of file OFSTestConfigMenu.py.
OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.ofs_resource_location
Definition at line 234 of file OFSTestConfigMenu.py.
OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.ofs_resource_type
Definition at line 235 of file OFSTestConfigMenu.py.
OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.pvfs2genconfig_opts
Definition at line 241 of file OFSTestConfigMenu.py.
OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.run_sysint_tests
Definition at line 237 of file OFSTestConfigMenu.py.
OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.run_vfs_tests
Definition at line 238 of file OFSTestConfigMenu.py.
OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.ssh_key_filepath
Definition at line 203 of file OFSTestConfigMenu.py.
OFSTest.OFSTestConfigMenu.OFSTestConfigMenu.using_cloud
Definition at line 194 of file OFSTestConfigMenu.py.
The documentation for this class was generated from the following file:
OFSTest/OFSTestConfigMenu.py