OFSTest: OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager Class Reference
OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager Class Reference
This class manages the EC2 connection.
Public Member Functions
def readCloudConfigFile
def connect
Gets region info and connects to EC2.
def getAllCloudImages
Get a list of all the EC2 images.
def terminateCloudInstance
Terminates a running EC2 instance.
def createNewCloudInstances
Creates new EC2 instances and returns list of them.
def associateIPAddresses
Creates an new external IP address and associates with the instances in the array.
def checkCloudConnection
Checks to see if the EC2 connection is available.
def getAllCloudInstances
def printAllInstanceStatus
Prints the status of all instances.
def instanceIsDaysOld
Tests whether an instance is so many days old.
def deleteOldInstances
deleteOldInstances(days_old,name_filter,key_filter)
def getCloudConfigFromEnvironment
def createNewCloudNodes
Creates new cloud nodes and adds them to network_nodes list.
Public Member Functions inherited from OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager
def readCloudConfigFile
Reads relevant values from configuration file.
def readCloudPasswordFile
Reads relevant values from password file.
def connect
Gets region info and connects to Cloud.
def setCloudKey
Sets key name (Cloud) and key location (file) used to create and access Cloud instances.
def getAllCloudImages
def terminateCloudInstance
Terminates a running Cloud instance.
def createNewCloudInstances
Creates new Cloud instances and returns list of them.
def associateIPAddresses
Creates an new external IP address and associates with the instances in the array.
def checkCloudConnection
Checks to see if the Cloud connection is available.
def getAllCloudInstances
Gets all instances from Cloud connection.
def printAllInstanceStatus
Prints the status of all instances.
def instanceIsDaysOld
Tests whether an instance is so many days old.
def deleteOldInstances
deleteOldInstances(days_old,name_filter,key_filter)
def getCloudConfigFromEnvironment
def manageExistingCloudInstance
def getCloudInstanceInformation
def deleteCloudInstance
def hardRebootCloudInstance
def deleteAllCloudInstances
def createNewCloudNodes
Creates new cloud nodes and adds them to network_nodes list.
Public Attributes
ec2_access_key
EC2 Access key.
ec2_endpoint
ec2_path
ec2_port
ec2_secret_key
ec2_region
ec2_connection
ec2_is_secure
cloud_instance_key
cloud_instance_key_location
ec2_region_name
cloud_image_list
cloud_instance_list
Public Attributes inherited from OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager
cloud_instance_names
Dictionary of Cloud instance names.
cloud_instance_list
cloud_image_list
cloud_key_list
cloud_is_secure
cloud_instance_key
cloud_instance_key_location
Detailed Description
This class manages the EC2 connection.
It has no awareness of OFSTestNodes or the OFSTestNetwork.
Definition at line 19 of file OFSEC2ConnectionManager.py.
Member Function Documentation
def OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.associateIPAddresses (self, instances = [], domain = None)
Creates an new external IP address and associates with the instances in the array.
Parameters
self The object pointer
instances List of instances to associate
domain Domain on which to allocate addresses
Returns
A list of the external addresses
Definition at line 289 of file OFSEC2ConnectionManager.py.
def OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.checkCloudConnection (self)
Checks to see if the EC2 connection is available.
Connects if it isn't.
Parameters
self The object pointer
Definition at line 317 of file OFSEC2ConnectionManager.py.
References OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.connect(), and OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.ec2_connection.
def OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.connect (self, debug = 0)
Gets region info and connects to EC2.
ec2.connection.EC2Connection object should be stored in self.ec2_connection.
Parameters
self The object pointer
debug Debug level.
Definition at line 155 of file OFSEC2ConnectionManager.py.
References OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.ec2_access_key, OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.ec2_connection, OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.ec2_endpoint, OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.ec2_is_secure, OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.ec2_path, OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.ec2_port, OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.ec2_region, OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.ec2_region_name, and OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.ec2_secret_key.
def OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.createNewCloudInstances (self, number_nodes, image_name, flavor_name, subnet_id = None)
Creates new EC2 instances and returns list of them.
Parameters
self The object pointer
number_nodes Number of nodes to create
image_name Image to run. (e.g. "cloud-ubuntu-12.04")
flavor_name Image "flavor" (e.g. "m1.medium")
subnet_id Id of subnet instance should run on
Returns
A list of new instances.
Definition at line 238 of file OFSEC2ConnectionManager.py.
References OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.cloud_image_list, OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.cloud_instance_key, and OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.getAllCloudImages().
def OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.createNewCloudNodes (self, number_nodes, image_name, flavor_name, local_master, associateip = False, domain = None, cloud_subnet = None)
Creates new cloud nodes and adds them to network_nodes list.
Parameters
self The object pointer
number_nodes number of nodes to be created
image_name Name of Cloud image to launch
flavor_name Cloud "flavor" of virtual node
associateip Associate to external ip?
domain Domain to associate with external ip
cloud_subnet cloud subnet id for primary network interface.
Returns
list of new nodes.
Definition at line 430 of file OFSEC2ConnectionManager.py.
References OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.associateIPAddresses(), OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.cloud_instance_key_location, and OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.createNewCloudInstances().
def OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.deleteOldInstances (self, days_old = 7, name_filter = "", key_filter = "")
deleteOldInstances(days_old,name_filter,key_filter)
Delete instances over a certain number of days old.
Parameters
self The object pointer
days_old Age to check
name_filter Filter to only delete instances matching name
key_filter Filter to only delete instance associated with this EC2 key
Definition at line 385 of file OFSEC2ConnectionManager.py.
References OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.checkCloudConnection(), OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.cloud_instance_list, OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.getAllCloudInstances(), and OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.instanceIsDaysOld().
def OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.getAllCloudImages (self)
Get a list of all the EC2 images.
Parameters
self The object pointer
Returns
A list of available EC2 Images
Definition at line 179 of file OFSEC2ConnectionManager.py.
def OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.getAllCloudInstances (self)
Definition at line 328 of file OFSEC2ConnectionManager.py.
References OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.checkCloudConnection().
def OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.getCloudConfigFromEnvironment (self)
Definition at line 409 of file OFSEC2ConnectionManager.py.
def OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.instanceIsDaysOld (self, instance, days_old = 7)
Tests whether an instance is so many days old.
Parameters
self The object pointer
instance Instance to check
days_old Age to check
Returns
True if instance is at least days_old days old
Fals if instance is not days_old
Definition at line 360 of file OFSEC2ConnectionManager.py.
def OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.printAllInstanceStatus (self)
Prints the status of all instances.
For debugging.
Parameters
self The object pointer
Definition at line 343 of file OFSEC2ConnectionManager.py.
References OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.cloud_instance_list, and OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.getAllCloudInstances().
def OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.readCloudConfigFile (self, filename)
Definition at line 107 of file OFSEC2ConnectionManager.py.
References OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.ec2_access_key, OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.ec2_endpoint, OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.ec2_is_secure, OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.ec2_path, OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.ec2_port, and OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.ec2_secret_key.
OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.terminateCloudInstance (self, ip_address)
Terminates a running EC2 instance.
Parameters
self The object pointer
ip_address IP address (internal) of the node.
Returns
1 Instance not found for that ip address
0 Instance terminated.
Definition at line 197 of file OFSEC2ConnectionManager.py.
References OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.checkCloudConnection(), OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.cloud_instance_list, and OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.getAllCloudInstances().
Member Data Documentation
OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.cloud_image_list
Definition at line 181 of file OFSEC2ConnectionManager.py.
OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.cloud_instance_key
Definition at line 31 of file OFSEC2ConnectionManager.py.
OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.cloud_instance_key_location
Definition at line 35 of file OFSEC2ConnectionManager.py.
OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.cloud_instance_list
Definition at line 333 of file OFSEC2ConnectionManager.py.
OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.ec2_access_key
EC2 Access key.
In ec2rc.sh file.
Definition at line 33 of file OFSEC2ConnectionManager.py.
Referenced by OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.connect(), and OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.readCloudConfigFile().
OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.ec2_connection
Definition at line 23 of file OFSEC2ConnectionManager.py.
Referenced by OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.checkCloudConnection(), and OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.connect().
OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.ec2_endpoint
Definition at line 3 of file OFSEC2ConnectionManager.py.
Referenced by OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.connect(), and OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.readCloudConfigFile().
OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.ec2_is_secure
Definition at line 27 of file OFSEC2ConnectionManager.py.
Referenced by OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.connect(), and OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.readCloudConfigFile().
OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.ec2_path
Definition at line 7 of file OFSEC2ConnectionManager.py.
Referenced by OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.connect(), and OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.readCloudConfigFile().
OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.ec2_port
Definition at line 11 of file OFSEC2ConnectionManager.py.
Referenced by OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.connect(), and OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.readCloudConfigFile().
OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.ec2_region
Definition at line 19 of file OFSEC2ConnectionManager.py.
Referenced by OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.connect().
OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.ec2_region_name
Definition at line 39 of file OFSEC2ConnectionManager.py.
Referenced by OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.connect().
OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.ec2_secret_key
Definition at line 15 of file OFSEC2ConnectionManager.py.
Referenced by OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.connect(), and OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.readCloudConfigFile().
The documentation for this class was generated from the following files:
OFSTest/OFSEC2ConnectionManager.py