OFSTest: OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager Class Reference
OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager Class Reference
This class manages the Cloud connection.
Public Member Functions
def readCloudConfigFile
Reads relevant values from configuration file.
def readCloudPasswordFile
Reads relevant values from password file.
def connect
Gets region info and connects to Cloud.
def setCloudKey
Sets key name (Cloud) and key location (file) used to create and access Cloud instances.
def getAllCloudImages
def terminateCloudInstance
Terminates a running Cloud instance.
def createNewCloudInstances
Creates new Cloud instances and returns list of them.
def associateIPAddresses
Creates an new external IP address and associates with the instances in the array.
def checkCloudConnection
Checks to see if the Cloud connection is available.
def getAllCloudInstances
Gets all instances from Cloud connection.
def printAllInstanceStatus
Prints the status of all instances.
def instanceIsDaysOld
Tests whether an instance is so many days old.
def deleteOldInstances
deleteOldInstances(days_old,name_filter,key_filter)
def getCloudConfigFromEnvironment
def manageExistingCloudInstance
def getCloudInstanceInformation
def deleteCloudInstance
def hardRebootCloudInstance
def deleteAllCloudInstances
def createNewCloudNodes
Creates new cloud nodes and adds them to network_nodes list.
Public Attributes
cloud_instance_names
Dictionary of Cloud instance names.
cloud_instance_list
cloud_image_list
cloud_key_list
cloud_is_secure
cloud_instance_key
cloud_instance_key_location
Detailed Description
This class manages the Cloud connection.
It has no awareness of OFSTestNodes or the OFSTestNetwork.
Definition at line 16 of file OFSCloudConnectionManager.py.
Member Function Documentation
def OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.associateIPAddresses (self, instances = [], domain = None)
Creates an new external IP address and associates with the instances in the array.
Parameters
self The object pointer
instances List of instances to associate
domain Domain on which to allocate addresses
Returns
A list of the external addresses
Definition at line 167 of file OFSCloudConnectionManager.py.
Referenced by OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.createNewCloudNodes(), and OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.createNewCloudNodes().
def OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.checkCloudConnection (self)
Checks to see if the Cloud connection is available.
Connects if it isn't.
Parameters
self The object pointer
Definition at line 176 of file OFSCloudConnectionManager.py.
Referenced by OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.checkCloudConnection(), OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.createNewCloudInstances(), OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.deleteOldInstances(), OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.deleteOldInstances(), OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.deleteOldInstances(), OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.getAllCloudImages(), OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.getAllCloudInstances(), OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.terminateCloudInstance(), and OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.terminateCloudInstance().
def OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.connect (self, debug = 0)
Gets region info and connects to Cloud.
cloud.connection.CloudConnection object should be stored in self.cloud_connection.
Parameters
self The object pointer
debug Debug level.
Definition at line 99 of file OFSCloudConnectionManager.py.
Referenced by OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.checkCloudConnection(), and OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.checkCloudConnection().
def OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.createNewCloudInstances (self, number_nodes, image_system, instance_type, subnet_id = None)
Creates new Cloud instances and returns list of them.
Parameters
self The object pointer
number_nodes Number of nodes to create
image_system Image to run. (e.g. "cloud-ubuntu-12.04")
instance_type Image "flavor" (e.g. "m1.medium")
subnet_id Id of subnet instance should run on
Returns
A list of new instances.
Definition at line 155 of file OFSCloudConnectionManager.py.
Referenced by OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.createNewCloudNodes(), and OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.createNewCloudNodes().
def OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.createNewCloudNodes (self, number_nodes, image_name, flavor_name, local_master, associateip = False, domain = None, cloud_subnet = None)
Creates new cloud nodes and adds them to network_nodes list.
Parameters
self The object pointer
number_nodes number of nodes to be created
image_name Name of Cloud image to launch
flavor_name Cloud "flavor" of virtual node
associateip Associate to external ip?
domain Domain to associate with external ip
cloud_subnet cloud subnet id for primary network interface.
Returns
list of new nodes.
Definition at line 295 of file OFSCloudConnectionManager.py.
def OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.deleteAllCloudInstances (self)
Definition at line 274 of file OFSCloudConnectionManager.py.
def OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.deleteCloudInstance (self, cloud_node)
Definition at line 268 of file OFSCloudConnectionManager.py.
def OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.deleteOldInstances (self, days_old = 7, name_filter = "", key_filter = "")
deleteOldInstances(days_old,name_filter,key_filter)
Delete instances over a certain number of days old.
Parameters
self The object pointer
days_old Age to check
name_filter Filter to only delete instances matching name
key_filter Filter to only delete instance associated with this Cloud key
Definition at line 234 of file OFSCloudConnectionManager.py.
References OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.checkCloudConnection(), OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.cloud_instance_list, OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.getAllCloudInstances(), and OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.instanceIsDaysOld().
def OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.getAllCloudImages (self)
Definition at line 124 of file OFSCloudConnectionManager.py.
Referenced by OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.createNewCloudInstances().
def OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.getAllCloudInstances (self)
Gets all instances from Cloud connection.
Returns a list of instances.
Parameters
self The object pointer
Definition at line 185 of file OFSCloudConnectionManager.py.
Referenced by OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.checkCloudConnection(), OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.deleteOldInstances(), OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.deleteOldInstances(), OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.deleteOldInstances(), OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.printAllInstanceStatus(), OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.printAllInstanceStatus(), and OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.terminateCloudInstance().
def OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.getCloudConfigFromEnvironment (self)
Definition at line 258 of file OFSCloudConnectionManager.py.
def OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.getCloudInstanceInformation (self, cloud_node)
Definition at line 264 of file OFSCloudConnectionManager.py.
def OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.hardRebootCloudInstance (self, cloud_node)
Definition at line 271 of file OFSCloudConnectionManager.py.
def OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.instanceIsDaysOld (self, instance, days_old = 7)
Tests whether an instance is so many days old.
Parameters
self The object pointer
instance Instance to check
days_old Age to check
Returns
True if instance is at least days_old days old
Fals if instance is not days_old
Definition at line 209 of file OFSCloudConnectionManager.py.
Referenced by OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.deleteOldInstances(), OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.deleteOldInstances(), and OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.deleteOldInstances().
def OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.manageExistingCloudInstance (self, cloud_node)
Definition at line 261 of file OFSCloudConnectionManager.py.
def OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.printAllInstanceStatus (self)
Prints the status of all instances.
For debugging.
Parameters
self The object pointer
Definition at line 194 of file OFSCloudConnectionManager.py.
def OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.readCloudConfigFile (self, filename)
Reads relevant values from configuration file.
Parameters
self The object pointer
filename Path to configuration file
Definition at line 73 of file OFSCloudConnectionManager.py.
def OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.readCloudPasswordFile (self, filename)
Reads relevant values from password file.
This file contains the password for nova that is used for the OS_PASSWORD value
Parameters
self The object pointer
filename Path to file
Definition at line 88 of file OFSCloudConnectionManager.py.
def OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.setCloudKey (self, keyname, keylocation)
Sets key name (Cloud) and key location (file) used to create and access Cloud instances.
Parameters
self The object pointer
keyname Name of key in Cloud
keylocation Location of .pem file in filesystem.
Definition at line 113 of file OFSCloudConnectionManager.py.
References OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.cloud_instance_key, and OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.cloud_instance_key_location.
OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.terminateCloudInstance (self, ip_address)
Terminates a running Cloud instance.
Parameters
self The object pointer
ip_address IP address (internal) of the node.
Returns
1 Instance not found for that ip address
0 Instance terminated.
Definition at line 138 of file OFSCloudConnectionManager.py.
Member Data Documentation
OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.cloud_image_list
Definition at line 7 of file OFSCloudConnectionManager.py.
Referenced by OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.createNewCloudInstances(), and OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.getAllCloudImages().
OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.cloud_instance_key
Definition at line 19 of file OFSCloudConnectionManager.py.
Referenced by OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.createNewCloudInstances(), and OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.setCloudKey().
OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.cloud_instance_key_location
Definition at line 23 of file OFSCloudConnectionManager.py.
Referenced by OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.createNewCloudNodes(), OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.createNewCloudNodes(), and OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.setCloudKey().
OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.cloud_instance_list
Definition at line 3 of file OFSCloudConnectionManager.py.
Referenced by OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.deleteOldInstances(), OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.deleteOldInstances(), OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.deleteOldInstances(), OFSTest.OFSNovaConnectionManager.OFSNovaConnectionManager.printAllInstanceStatus(), OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.printAllInstanceStatus(), and OFSTest.OFSEC2ConnectionManager.OFSEC2ConnectionManager.terminateCloudInstance().
OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.cloud_instance_names
Dictionary of Cloud instance names.
Definition at line 30 of file OFSCloudConnectionManager.py.
OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.cloud_is_secure
Definition at line 15 of file OFSCloudConnectionManager.py.
OFSTest.OFSCloudConnectionManager.OFSCloudConnectionManager.cloud_key_list
Definition at line 11 of file OFSCloudConnectionManager.py.
The documentation for this class was generated from the following files:
OFSTest/OFSCloudConnectionManager.py