OFSTest: OFSTest.OFSTestNetwork Namespace Reference
OFSTest.OFSTestNetwork Namespace Reference
Classes
class OFSTestNetwork
Functions
def uploadKeys
def enablePasswordlessSSH
Enable passwordless SSH for the node for the current user.
def terminateCloudNode
Terminate the remote node and remove it from the created node list.
def updateCloudNodes
Update only the Cloud Nodes
def updateEtcHosts
This function updates the etc hosts file on each node with the hostname and ip address.
def updateNodes
This updates the system software on the list of nodes.
def installRequiredSoftware
This installs the required software on all the nodes.
def buildOFSFromSource
def installOFSBuild
Install the OrangeFS build on a given node
def installOFSTests
def installBenchmarks
Install the 3rd party benchmarks on the given node.
def configureOFSServer
def copyOFSToNodeList
Copy OFS from build node to rest of cluster.
def copyResourceToNodeList
This is a multi-threaded recursive copy routine.
def stopOFSServers
Stops the OrangeFS servers on the nodes
def startOFSServers
Starts the OrangeFS servers on the nodes
def startOFSClientAllNodes
Starts the OrangeFS servers on all created nodes
def startOFSClient
def mountOFSFilesystem
Mount OrangeFS on a given client node.
def mountOFSFilesystemAllNodes
Mount OrangeFS on all nodes
def stopOFSClient
Stop the OrangeFS client on a given node
def stopOFSClientAllNodes
Stop the OrangeFS client on all nodes in list
def unmountOFSFilesystemAllNodes
Unmount the OrangeFS directory on all nodes in list
def terminateAllCloudNodes
Terminate all the cloud nodes in a list
def installTorque
installTorque(self,node_list=None, head_node=None):
def checkTorque
Check to see if Torque is running properly.
def installMpich2
Install Mpich on the virtual cluster
def generateOFSKeys
Generate SSH keys for OrangeFS security
def generateOFSServerKeys
Generate server SSH keys for OrangeFS security
def generateOFSClientKeys
Generate client SSH keys for OrangeFS security
def generateOFSKeystoreFile
Generate OrangeFS keystore file for security
def findExistingOFSInstallation
find an existing OrangeFS installation for each node in the list.
def networkOFSSettings
Manually set OrangeFS settings for each node in the list.
def exportNFSDirectory
def mountNFSDirectory
Mount an NFS share at mount_point for each client in the client list.
def installOpenMPI
This function installs OpenMPI software at the mpi_nfs_directory.
def setupHadoop
Hadoop should be installed with required software.
Variables
network_nodes
queue
manager
mpi_nfs_directory
openmpi_version
Function Documentation
def OFSTest.OFSTestNetwork.buildOFSFromSource (self, resource_type, resource_location, download_location = None, build_node = None, build_kmod = True, enable_strict = False, enable_fuse = False, enable_shared = False, enable_hadoop = False, ofs_prefix = "/opt/orangefs", db4_prefix = "/opt/db4", security_mode = None, ofs_patch_files = [], configure_opts = "", make_opts = "", debug = False, svn_options = None, node_list = None)
Definition at line 468 of file OFSTestNetwork.py.
Referenced by OFSTest.OFSTestNetwork.installRequiredSoftware().
def OFSTest.OFSTestNetwork.checkTorque (self, node_list = None, head_node = None)
Check to see if Torque is running properly.
Parameters
self The object pointer
node_list List of nodes in network.
head_node Head node of Torque setup
Definition at line 946 of file OFSTestNetwork.py.
def OFSTest.OFSTestNetwork.configureOFSServer (self, ofs_fs_name, master_node = None, node_list = None, pvfs2genconfig_opts = "", security = None)
Parameters
self The object pointer
ofs_fs_name Default name of OrangeFS service: version < 2.9 = "pvfs2-fs"; version >= 2.9 = "orangefs"
master_node Master node in the cluster.
node_list List of nodes in OrangeFS cluster
pvfs2genconfig_opts = Additional options for pvfs2genconfig utility
security None, "Key", "Cert"
Definition at line 597 of file OFSTestNetwork.py.
def OFSTest.OFSTestNetwork.copyOFSToNodeList (self, destination_list = None)
Copy OFS from build node to rest of cluster.
Parameters
self The object pointer
destination_list List of nodes to copy OrangeFS to. OFS should already be at destination_list[0].
Definition at line 613 of file OFSTestNetwork.py.
def OFSTest.OFSTestNetwork.copyResourceToNodeList (self, node_function, destination_list = None)
This is a multi-threaded recursive copy routine.
Function copies OrangeFS from list[0] to list[len/2] Then it partitions the list into two parts and copies again. This copies at O(log n) time.
For an eight node setup [0:7], copy is as follows: 1: 0->4 2: 0->2 4->6 3: 0->1 2->3 4->5 6->7
Parameters
self The object pointer
node_function Python function/method that does copying
destination_list list of nodes. Assumption is source is at node[0].
Definition at line 637 of file OFSTestNetwork.py.
References OFSTest.OFSSetup.__init__().
def OFSTest.OFSTestNetwork.enablePasswordlessSSH (self, node_list = None)
Enable passwordless SSH for the node for the current user.
Parameters
self The object pointer
node_list List of nodes to enable passwordless ssh
Definition at line 266 of file OFSTestNetwork.py.
def OFSTest.OFSTestNetwork.exportNFSDirectory (self, directory, nfs_server_list = None, options = None, network = None, netmask = None)
Definition at line 1345 of file OFSTestNetwork.py.
def OFSTest.OFSTestNetwork.findExistingOFSInstallation (self, node_list = None)
find an existing OrangeFS installation for each node in the list.
Parameters
self The object pointer
node_list List of nodes in network.
Definition at line 1224 of file OFSTestNetwork.py.
References OFSTest.OFSTestNetwork.networkOFSSettings().
OFSTest.OFSTestNetwork.generateOFSClientKeys (self, node_list = None, security_node = None)
Generate client SSH keys for OrangeFS security
Parameters
self The object pointer
node_list List of nodes in network.
security_node Node that generates server keys
Definition at line 1106 of file OFSTestNetwork.py.
def OFSTest.OFSTestNetwork.generateOFSKeys (self, node_list = None, head_node = None)
Generate SSH keys for OrangeFS security
Parameters
self The object pointer
node_list List of nodes in network.
head_node Head node of ssh setup
Definition at line 1034 of file OFSTestNetwork.py.
def OFSTest.OFSTestNetwork.generateOFSKeystoreFile (self, node_list = None, security_node = None)
Generate OrangeFS keystore file for security
Parameters
self The object pointer
node_list List of nodes in network.
security_node Node that generates server keys
Definition at line 1152 of file OFSTestNetwork.py.
OFSTest.OFSTestNetwork.generateOFSServerKeys (self, node_list = None, security_node = None)
Generate server SSH keys for OrangeFS security
Parameters
self The object pointer
node_list List of nodes in network.
security_node Node that generates server keys
Definition at line 1061 of file OFSTestNetwork.py.
def OFSTest.OFSTestNetwork.installBenchmarks (self, build_node = None, node_list = None)
Install the 3rd party benchmarks on the given node.
Parameters
self The object pointer
build_node Node on which to install benchmark tests
node_list List of nodes in network.
Definition at line 577 of file OFSTestNetwork.py.
def OFSTest.OFSTestNetwork.installMpich2 (self, node_list = None, head_node = None)
Install Mpich on the virtual cluster
Parameters
self The object pointer
node_list List of nodes in network.
head_node Head node of Torque setup
Definition at line 1013 of file OFSTestNetwork.py.
def OFSTest.OFSTestNetwork.installOFSBuild (self, build_node = None, install_opts = "", node_list = None)
Install the OrangeFS build on a given node
Parameters
self The object pointer
build_node Node on which to build OrangeFS
install_opts Other install options
node_list List of nodes in network
Definition at line 541 of file OFSTestNetwork.py.
def OFSTest.OFSTestNetwork.installOFSTests (self, client_node = None, configure_options = "", node_list = None)
Definition at line 560 of file OFSTestNetwork.py.
def OFSTest.OFSTestNetwork.installOpenMPI (self, mpi_nfs_directory = None, build_node = None, mpi_local_directory = None, node_list = None)
This function installs OpenMPI software at the mpi_nfs_directory.
Parameters
self The object pointer
build_node Node used to build OpenMPI
mpi_nfs_directory Location to install OpenMPI. This should be an nfs directory accessible from all nodes
mpi_local_directory Location to build OpenMPI. This should be a local directory on the build node
node_list List of nodes in OpenMPI network.
Definition at line 1399 of file OFSTestNetwork.py.
def OFSTest.OFSTestNetwork.installRequiredSoftware (self, node_list = None)
This installs the required software on all the nodes.
Parameters
self The object pointer
node_list List of nodes to update
Definition at line 400 of file OFSTestNetwork.py.
References OFSTest.OFSTestNetwork.buildOFSFromSource().
def OFSTest.OFSTestNetwork.installTorque (self, node_list = None, head_node = None)
installTorque(self,node_list=None, head_node=None):
Install Torque on the virtual cluster
Parameters
self The object pointer
node_list List of nodes in network.
head_node Head node of Torque setup
Definition at line 887 of file OFSTestNetwork.py.
def OFSTest.OFSTestNetwork.mountNFSDirectory (self, nfs_share, mount_point, options = "", nfs_client_list = None)
Mount an NFS share at mount_point for each client in the client list.
Parameters
self The object pointer
nfs_share NFS share to mount
mount_point NFS mount_point on machine
options NFS mount options
nfs_client_list List of NFS client nodes
Definition at line 1368 of file OFSTestNetwork.py.
def OFSTest.OFSTestNetwork.mountOFSFilesystem (self, mount_fuse = False, client_node = None, node_list = None)
Mount OrangeFS on a given client node.
Parameters
self The object pointer
mount_fuse Mount using fuse module?
client_node Node on which to run OrangeFS client
node_list List of nodes in network.
Definition at line 776 of file OFSTestNetwork.py.
def OFSTest.OFSTestNetwork.mountOFSFilesystemAllNodes (self, mount_fuse = False, node_list = None)
Mount OrangeFS on all nodes
Parameters
self The object pointer
mount_fuse Mount using fuse module?
node_list List of nodes in network.
Definition at line 799 of file OFSTestNetwork.py.
def OFSTest.OFSTestNetwork.networkOFSSettings (self, ofs_installation_location, db4_prefix, ofs_extra_tests_location, pvfs2tab_file, resource_location, resource_type, ofs_config_file, ofs_fs_name, ofs_hostname_override = None, ofs_mount_point = None, node_list = None)
Manually set OrangeFS settings for each node in the list.
Used for retesting.
Parameters
self The object pointer
ofs_installation_location Directory where OrangeFS is installed. Should be the same on all nodes.
db4_prefix Location of Berkeley DB4
ofs_extra_tests_location Location of 3rd party benchmarks
pvfs2tab_file Location of pvfs2tab file
resource_location Location of OrangeFS source
resource_type Form of source: TAR,SVN,LOCAL,BUILDNODE
ofs_config_file Location of orangefs.conf file
ofs_fs_name Name of OrangeFS in filesystem url
ofs_hostname_override Change hostname to this. Needed to work around an openstack issue
ofs_mount_point Location of OrangeFS mount_point
node_list List of nodes in network
Definition at line 1277 of file OFSTestNetwork.py.
Referenced by OFSTest.OFSTestNetwork.findExistingOFSInstallation().
def OFSTest.OFSTestNetwork.setupHadoop (self, hadoop_nodes = None, master_node = None)
Hadoop should be installed with required software.
This configures hadoop for OrangeFS testing on the virtual cluster.
Parameters
self The object pointer
hadoop_nodes Nodes on which to setup hadoop
master_node Hadoop master node
Definition at line 1487 of file OFSTestNetwork.py.
def OFSTest.OFSTestNetwork.startOFSClient (self, client_node = None, security = None, node_list = None)
Definition at line 754 of file OFSTestNetwork.py.
def OFSTest.OFSTestNetwork.startOFSClientAllNodes (self, security = None, node_list = None)
Starts the OrangeFS servers on all created nodes
Parameters
self The object pointer
security OFS security mode: None,"Key","Cert"
node_list List of nodes in network.
Definition at line 737 of file OFSTestNetwork.py.
def OFSTest.OFSTestNetwork.startOFSServers (self, node_list = None)
Starts the OrangeFS servers on the nodes
Parameters
self The object pointer
node_list List of nodes in network.
Definition at line 721 of file OFSTestNetwork.py.
def OFSTest.OFSTestNetwork.stopOFSClient (self, client_node = None, node_list = None)
Stop the OrangeFS client on a given node
Parameters
self The object pointer
client_node Node on which to run OrangeFS client
node_list List of nodes in network.
Definition at line 815 of file OFSTestNetwork.py.
def OFSTest.OFSTestNetwork.stopOFSClientAllNodes (self, node_list = None)
Stop the OrangeFS client on all nodes in list
Parameters
self The object pointer
node_list List of nodes in network.
Definition at line 832 of file OFSTestNetwork.py.
def OFSTest.OFSTestNetwork.stopOFSServers (self, node_list = None)
Stops the OrangeFS servers on the nodes
Parameters
self The object pointer
node_list List of nodes in network.
Definition at line 705 of file OFSTestNetwork.py.
def OFSTest.OFSTestNetwork.terminateAllCloudNodes (self, node_list = None)
Terminate all the cloud nodes in a list
Parameters
self The object pointer
node_list List of nodes in network.
Definition at line 867 of file OFSTestNetwork.py.
OFSTest.OFSTestNetwork.terminateCloudNode (self, remote_node)
Terminate the remote node and remove it from the created node list.
Parameters
self The object pointer
remote_node Node to be terminated.
Definition at line 293 of file OFSTestNetwork.py.
def OFSTest.OFSTestNetwork.unmountOFSFilesystemAllNodes (self, node_list = None)
Unmount the OrangeFS directory on all nodes in list
Parameters
self The object pointer
node_list List of nodes in network.
Definition at line 850 of file OFSTestNetwork.py.
def OFSTest.OFSTestNetwork.updateCloudNodes (self, node_list = None)
Update only the Cloud Nodes
Parameters
self The object pointer
node_list List of nodes to update.
Definition at line 320 of file OFSTestNetwork.py.
def OFSTest.OFSTestNetwork.updateEtcHosts (self, node_list = None)
This function updates the etc hosts file on each node with the hostname and ip address.
Also creates the necessary mpihosts config files.
Parameters
self The object pointer
node_list List of nodes in network
Definition at line 340 of file OFSTestNetwork.py.
OFSTest.OFSTestNetwork.updateNodes (self, node_list = None)
This updates the system software on the list of nodes.
Parameters
self The object pointer
node_list List of nodes to update
Definition at line 374 of file OFSTestNetwork.py.
def OFSTest.OFSTestNetwork.uploadKeys (self, node_list = None)
Definition at line 248 of file OFSTestNetwork.py.
Variable Documentation
OFSTest.OFSTestNetwork.manager
Definition at line 664 of file OFSTestNetwork.py.
OFSTest.OFSTestNetwork.mpi_nfs_directory
Definition at line 1408 of file OFSTestNetwork.py.
OFSTest.OFSTestNetwork.network_nodes
Definition at line 303 of file OFSTestNetwork.py.
OFSTest.OFSTestNetwork.openmpi_version
Definition at line 1442 of file OFSTestNetwork.py.
OFSTest.OFSTestNetwork.queue
Definition at line 663 of file OFSTestNetwork.py.