#!/bin/sh

WEB_HOST=parlweb.parl.clemson.edu
WEB_DIR=/web/pvfs.org/pvfs2

FILE_LIST="pvfs2-guide pvfs2-faq pvfs2-quickstart"

DOCS_DIR=$1

if [ -z $DOCS_DIR ] ; then
	echo "usage: $0 <document_directory>"
	exit 1
fi

if [ ! -d $DOCS_DIR ] ; then
	echo "usage: $0 <document_directory>"
	exit 1
fi

files=""
for f in $FILE_LIST; do
	page="$DOCS_DIR/$f/$f.html"
	[ -r $page ] && files="$page $files"
done

scp $files ${WEB_HOST}:${WEB_DIR}
