#ifndef JNI_POSIX_H
#define JNI_POSIX_H

#define open jni_open
#define open64 jni_open64
#define openat jni_openat
#define openat64 jni_openat64
#define creat jni_creat
#define creat64 jni_creat64
#define unlink jni_unlink
#define unlinkat jni_unlinkat
#define rename jni_rename
#define renameat jni_renameat
#define read jni_read
#define pread jni_pread
#define readv jni_readv
#define pread64 jni_pread64
#define write jni_write
#define pwrite jni_pwrite
#define writev jni_writev
#define pwrite64 jni_pwrite64
#define lseek jni_lseek
#define lseek64 jni_lseek64
#define truncate jni_truncate
#define truncate64 jni_truncate64
#define ftruncate jni_ftruncate
#define ftruncate64 jni_ftruncate64
#define posix_fallocate jni_posix_fallocate
#define close jni_close
#define stat jni_stat
#define __xstat jni___xstat
#define stat64 jni_stat64
#define __xstat64 jni___xstat64
#define fstat jni_fstat
#define __fxstat jni___fxstat
#define fstat64 jni_fstat64
#define __fxstat64 jni___fxstat64
#define fstatat jni_fstatat
#define __fxstatat jni___fxstatat
#define fstatat64 jni_fstatat64
#define __fxstatat64 jni___fxstatat64
#define lstat jni_lstat
#define __lxstat jni___lxstat
#define lstat64 jni_lstat64
#define __lxstat64 jni___lxstat64
#define futimesat jni_futimesat
#define utimes jni_utimes
#define utime jni_utime
#define futimes jni_futimes
#define dup jni_dup
#define dup2 jni_dup2
#define chown jni_chown
#define fchown jni_fchown
#define fchownat jni_fchownat
#define lchown jni_lchown
#define chmod jni_chmod
#define fchmod jni_fchmod
#define fchmodat jni_fchmodat
#define mkdir jni_mkdir
#define mkdirat jni_mkdirat
#define rmdir jni_rmdir
#define readlink jni_readlink
#define readlinkat jni_readlinkat
#define symlink jni_symlink
#define symlinkat jni_symlinkat
#define link jni_link
#define linkat jni_linkat
#define posix_readdir jni_posix_readdir
#define getdents jni_getdents
#define getdents64 jni_getdents64
#define access jni_access
#define faccessat jni_faccessat
#define flock jni_flock
#define fcntl jni_fcntl
#define sync jni_sync
#define fsync jni_fsync
#define fdatasync jni_fdatasync
#define posix_fadvise jni_posix_fadvise
#define fadvise64 jni_fadvise64
#define statfs jni_statfs
#define statfs64 jni_statfs64
#define fstatfs jni_fstatfs
#define fstatfs64 jni_fstatfs64
#define statvfs jni_statvfs
#define fstatvfs jni_fstatvfs
#define mknod jni_mknod
#define mknodat jni_mknodat
#define sendfile jni_sendfile
#define sendfile64 jni_sendfile64
#define setxattr jni_setxattr
#define lsetxattr jni_lsetxattr
#define fsetxattr jni_fsetxattr
#define getxattr jni_getxattr
#define lgetxattr jni_lgetxattr
#define fgetxattr jni_fgetxattr
#define listxattr jni_listxattr
#define llistxattr jni_llistxattr
#define flistxattr jni_flistxattr
#define removexattr jni_removexattr
#define lremovexattr jni_lremovexattr
#define fremovexattr jni_fremovexattr
#define chdir jni_chdir
#define fchdir jni_fchdir
#define getcwd jni_getcwd
#define get_current_dir_name jni_get_current_dir_name
#define getwd jni_getwd
#define umask jni_umask
#define getumask jni_getumask
#define getdtablesize jni_getdtablesize

#endif /* JNI_POSIX_H */
