#ifndef JNI_STDIO_H
#define JNI_STDIO_H

#define flockfile jni_flockfile
#define ftrylockfile jni_ftrylockfile
#define funlockfile jni_funlockfile
#define fopen jni_fopen
#define fopen64 jni_fopen64
#define fdopen jni_fdopen
#define freopen jni_freopen
#define freopen64 jni_freopen64
#define fwrite jni_fwrite
#define fwrite_unlocked jni_fwrite_unlocked
#define fread jni_fread
#define fread_unlocked jni_fread_unlocked
#define fcloseall jni_fcloseall
#define fclose jni_fclose
#define fseek jni_fseek
#define fseeko jni_fseeko
#define fseeko64 jni_fseeko64
#define fseek64 jni_fseek64
#define fsetpos jni_fsetpos
#define fsetpos64 jni_fsetpos64
#define rewind jni_rewind
#define ftell jni_ftell
#define ftello jni_ftello
#define ftello64 jni_ftello64
#define ftell64 jni_ftell64
#define ftell64 jni_ftell64
#define fgetpos jni_fgetpos
#define fgetpos64 jni_fgetpos64
#define fflush jni_fflush
#define fflush_unlocked jni_fflush_unlocked
#define fputc jni_fputc
#define fputc_unlocked jni_fputc_unlocked
#define fputs jni_fputs
#define fputs_unlocked jni_fputs_unlocked
#define putc jni_putc
#define _IO_putc jni__IO_putc
#define putc_unlocked jni_putc_unlocked
#define putchar jni_putchar
#define putchar_unlocked jni_putchar_unlocked
#define puts jni_puts
#define putw jni_putw
#define fgets jni_fgets
#define fgets_unlocked jni_fgets_unlocked
#define fgetc jni_fgetc
#define fgetc_unlocked jni_fgetc_unlocked
#define getc jni_getc
#define _IO_getc jni__IO_getc
#define getc_unlocked jni_getc_unlocked
#define getchar jni_getchar
#define getchar_unlocked jni_getchar_unlocked
#define getw jni_getw
#define gets jni_gets
#define getline jni_getline
#define getdelim jni_getdelim
#define __getdelim jni___getdelim
#define ungetc jni_ungetc
#define dprintf jni_dprintf
#define vdprintf jni_vdprintf
#define vfprintf jni_vfprintf
#define vprintf jni_vprintf
#define fprintf jni_fprintf
#define printf jni_printf
#define perror jni_perror
#define clearerr jni_clearerr
#define clearerr_unlocked jni_clearerr_unlocked
#define feof jni_feof
#define feof_unlocked jni_feof_unlocked
#define ferror jni_ferror
#define ferror_unlocked jni_ferror_unlocked
#define fileno jni_fileno
#define fileno_unlocked jni_fileno_unlocked
#define remove jni_remove
#define setbuf jni_setbuf
#define setbuffer jni_setbuffer
#define setlinebuf jni_setlinebuf
#define setvbuf jni_setvbuf
#define mkdtemp jni_mkdtemp
#define mkstemp jni_mkstemp
#define tmpfile jni_tmpfile
#define opendir jni_opendir
#define fdopendir jni_fdopendir
#define dirfd jni_dirfd
#define readdir jni_readdir
#define readdir64 jni_readdir64
#define rewinddir jni_rewinddir
#define seekdir jni_seekdir
#define telldir jni_telldir
#define closedir jni_closedir
#define scandir jni_scandir
#define scandir64 jni_scandir64

#endif /* JNI_STDIO_H */
